bcgov/tno

tools/scripts/gen-env-files.sh
Fixing bug with script that generates `.env` files.
=> Fix script

.vscode/settings.json, api/editor/README.md, api/editor/api-editor/bin/api-editor/src/main/resources/application.yml, api/editor/api-editor/src/main/resources/application.yml, app/editor/public/keycloak.json, app/subscriber/public/keycloak.json, docs/DEVELOPMENT.md, libs/java/core/README.md, libs/java/dal/db/README.md, libs/java/dal/elastic/README.md, libs/java/service/README.md, openshift/templates/backup/README.md, openshift/templates/backup/build.yaml, openshift/templates/backup/deploy.yaml, services/elastic/src/main/resources/application.yml, services/syndication/src/main/resources/application.yml, test/README.md, tools/scripts/gen-maven-files.sh
We now have nightly backups of the database running in DEV!
- Fixed port number configuration
- Add build and deploy templates for the database backup pod
- Ability to schedule backups based on configuration
- Ability to create backups, or restores ad-hoc through scripts
=> TNO-141 Add database backup

.github/CODEOWNERS, docs/DEVELOPMENT.md, libs/java/dal/db/.devcontainer/Dockerfile, libs/java/dal/db/dal-db/pom.xml, libs/java/dal/db/scripts/close-staging-repo.sh, libs/java/dal/db/scripts/deploy-release.sh, libs/java/dal/db/scripts/deploy-staging.sh, libs/java/dal/db/scripts/drop-staging-repo.sh, libs/java/dal/db/scripts/release-staging-repo.sh, libs/java/dal/db/scripts/setup.sh, tools/scripts/gen-maven-files.sh, tools/scripts/os.sh, tools/scripts/variables.sh
Fixed issues with Macos scripts.  They should now work.
Resolved gpg signing issues and Maven Nexus authentication issues for some Docker containers that demand having `sudo` instead of the default `vscode` user.  I would like to solve why this is, but it's far too complex for my understanding.
=> Fixed maven package gpg issue

Makefile, app/editor/.devcontainer/devcontainer.json, db/kafka-enterprise/docker-compose.yml, db/kafka/docker-compose.yml, docker-compose.yml, libs/java/dal/db/dal-db-migration/pom.xml, libs/java/dal/db/dal-db-migration/src/main/resources/db/migration/U1__Init.sql, libs/java/dal/db/dal-db-migration/src/main/resources/db/migration/V1__Init.sql, network/nginx/config/default.conf, tools/scripts/db-update.sh
The database migration was not longer working within a separate docker container.  Another mystery with maven, as it did work originally.  Must have been dependency upgrades that broke it.  I've resolved the issues and it works again.
Also note I've changed the docker-compose profiles.  I've removed `app` and replaced it with `editor` and `subscriber`.  This will reduce the number of containers running at one time.
`make up p=editor` to get the frontend running for Editors.
=> Fix DB Migration

api/editor/api-editor/src/main/java/ca/bc/gov/tno/core/excel/CBRAReport.java
Completed CBRA Report API endpoint.
=> TNO-223 Add CBRA report

api/editor/api-editor/src/main/java/ca/bc/gov/tno/areas/editor/models/ContentModel.java, libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/services/ContentService.java
Fixed issue related to saving time tracking.
> Will require `make refresh n=api-editor`
=> TNO-208 Fix content time tracking

api/editor/api-editor/src/main/java/ca/bc/gov/tno/areas/editor/controllers/ContentController.java, libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Action.java, libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Category.java, libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Claim.java, libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Content.java, libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentAction.java
PUT was using the `contentService.add(...)` but it should have been `contentService.update(...)`
=> TNO-208 Fix update content

openshift/templates/services/audio/capture/build.yaml, openshift/templates/services/audio/capture/deploy.yaml
Adding Build/Deploy Infrastructure as Code templates for the Audio Capture Service.
Presently the service still has the bootstrap issue so it can't start,  That issue is outside of this PR's scope.
=> TNO-245 Add Audio Capture

openshift/templates/services/audio/clip/build.yaml, openshift/templates/services/audio/clip/deploy.yaml, services/capture/pom.xml
Adding Build/Deploy Infrastructure as Code templates for the Audio Clip Service.
Fix audio capture service log4j issue with Kafka log appender.
=> TNO-246 Add audio clip service

api/editor/api-editor/src/main/java/ca/bc/gov/tno/areas/editor/controllers/ContentController.java, api/editor/api-editor/src/main/java/ca/bc/gov/tno/areas/editor/models/ContentModel.java, libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Action.java, libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Category.java, libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Claim.java, libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Content.java, libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentAction.java, libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentCategory.java, libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentLink.java, libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentReference.java, libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentTag.java, libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentTone.java, libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentType.java, libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentTypeAction.java, libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/DataLocation.java, libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/DataSource.java, libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/DataSourceSchedule.java, libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/FileReference.java, libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/License.java, libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/MediaType.java, libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/PrintContent.java, libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Role.java, libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/RoleClaim.java, libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Schedule.java, libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Series.java, libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Tag.java, libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/TimeTracking.java, libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/TonePool.java, libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/User.java, libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/UserRole.java
Fixing delete content endpoint and DAL.
=> Fixed delete content

app/editor/src/features/admin/sources/DataSource.tsx, app/editor/src/features/login/UserInfo.tsx, app/editor/src/store/hooks/app/useToastError.ts
Updated error toast style.  Also added success toast to Data Source management form.
I believe I have also resolved a warning that shows up when state changes incorrectly within <UserInfo/>.
=> TNO-197 Update error handling

app/editor/src/components/form/area/styled/Area.tsx, app/editor/src/components/form/formpage/FormPage.tsx, app/editor/src/components/form/formpage/index.ts, app/editor/src/components/form/formpage/styled/FormPage.tsx, app/editor/src/components/form/formpage/styled/index.ts, app/editor/src/features/content/form/ContentForm.tsx, app/editor/src/features/content/list-view/ContentListView.tsx, app/editor/src/features/content/list-view/styled/ContentListView.tsx
All that was added to `ContentListView` and `ContentForm` was the addition of wrapping it in the new `<FormPage>`. Indentation is the explanation for all the additions.
=> TNO-267: Page size consistency

api/net/Areas/Services/Models/DataSource/DataSourceModel.cs
The API wasn't returning the parent with the requested data source.
=> Fix api data source with parent

services/audio/pom.xml, services/capture/pom.xml, services/elastic/pom.xml, services/nlp/pom.xml, services/syndication/pom.xml
Mistakenly introduced a run-time bug in the configuration by setting the active profile.
=> Fix service run config error

app/editor/src/components/formik/select/styled/FormikSelect.tsx, app/editor/src/features/content/form/ContentForm.tsx, app/editor/src/features/content/form/PropertiesContentForm.tsx, app/editor/src/features/content/form/styled/ContentForm.tsx
A few minor UI fixes for the Content Form.
=> TNO-277 Fix content form ui

app/editor/src/features/content/form/PropertiesContentForm.tsx, app/editor/src/features/content/form/styled/ContentForm.tsx
Should probably put these one liners in a single PR. Will start doing that now :P
=> TNO-300, 310, 311: Turn off auto complete on publishedOn, Extend tags field, Reduce summary height

app/editor/src/features/content/list-view/ContentListView.tsx
=> TNO-316: Hide time from date range filter

openshift/kustomize/api/base/config-map.yaml, openshift/kustomize/api/base/deploy.yaml, openshift/kustomize/api/overlays/dev/deploy.yaml, openshift/templates/api/deploy.yaml, openshift/templates/tekton/pipelines/complete.yaml, openshift/templates/tekton/pipelines/db-migration.yaml, openshift/templates/tekton/pipelines/deploy.yaml, openshift/templates/tekton/tasks/db-migration.yaml
Fixing database connection configuration in templates.
=> Fix devops templates

app/editor/src/components/form/formpage/styled/FormPage.tsx, app/editor/src/features/admin/sources/DataSource.tsx, app/editor/src/features/content/form/ContentForm.tsx
_Styling obviously not yet completed._
=> TNO-270: Add ability to delete data source

app/editor/src/features/content/form/ContentForm.tsx, app/editor/src/features/content/form/ContentSummaryForm.tsx, app/editor/src/features/content/form/utils/toForm.ts
A number of bugs introduced over the past few PRs are now resolved on the Content Form.
- Default values
- Selecting a series
- Redirect after creating
=> Fixing content form bugs

openshift/kustomize/services/build/base/syndication.yaml, openshift/kustomize/services/config-map.yaml, openshift/kustomize/services/syndication/base/config-map.yaml, openshift/kustomize/services/syndication/base/deploy.yaml, services/net/syndication/Program.cs, services/net/syndication/appsettings.Staging.json, services/net/syndication/appsettings.json
Updating devops for syndication service, so that it runs the new version.
=> TNO-336 Update syndication devops

libs/net/services/Controllers/HealthController.cs, libs/net/services/Controllers/StatusController.cs, openshift/kustomize/services/content/base/deploy.yaml, openshift/kustomize/services/syndication/base/deploy.yaml, services/net/content/ContentService.cs, services/net/syndication/SyndicationService.cs
=> TNO-336 Fix service api

libs/net/services/ServiceState.cs
I introduced a silly build bug in my rush.
=> Fix Service Build Bug

libs/net/core/Http/OpenIdConnectRequestClient.cs, openshift/kustomize/services/syndication/base/deploy.yaml, openshift/kustomize/services/syndication/overlays/dev/kustomization.yaml, openshift/kustomize/services/syndication/overlays/prod/kustomization.yaml, openshift/kustomize/services/syndication/overlays/test/kustomization.yaml
The services were not updating the access token reliably.  I have updated the code to handle a scenario where the refresh token was not provided.
=> TNO-44 Fix token refresh

app/editor/__mocks__/styleMock.ts, app/editor/package.json, app/editor/src/features/content/list-view/ContentListView.test.tsx, app/editor/src/features/content/list-view/__snapshots__/ContentListView.test.tsx.snap, app/editor/src/test/utils/TestWrapper.tsx, app/editor/src/test/utils/index.ts, app/editor/src/test/utils/testData.ts
Having some errors on ContentForm.test.tsx at the moment. Also tried cleaning up the test data to have it in a constant file; however, it would throw errors for some reason. Investigating that.
Also debugging further filter tests for the list view.
=> Content List View Tests

libs/java/service/src/main/java/ca/bc/gov/tno/services/data/TnoApi.java, libs/java/service/src/main/java/ca/bc/gov/tno/services/models/DataSource.java, services/java/capture/.devcontainer/devcontainer.json, services/java/capture/src/main/resources/application.yml, services/java/clip/src/main/resources/application.yml
A few changes to the Java capture service that were required to get it running following changes @Fosol made during my vacation.
=> Getting java based capture service working with latest changes

app/editor/src/features/admin/AdminRouter.tsx, app/editor/src/features/admin/sources/ContentReferenceList.tsx, app/editor/src/features/admin/sources/DataSource.tsx, app/editor/src/features/admin/sources/ReachEarnedMedia.tsx, app/editor/src/features/admin/sources/services/ServiceIngestSettings.tsx, app/editor/src/features/admin/sources/services/ServiceSchedule.tsx, app/editor/src/features/admin/sources/services/index.ts, app/editor/src/features/admin/sources/services/styled/ServiceIngestSettings.tsx, app/editor/src/features/admin/sources/services/styled/index.ts, app/editor/src/hooks/api-editor/validation/AdvancedScheduleSchema.ts, libs/net/services/Managers/DataSourceManager`.cs, openshift/kustomize/services/build/base/capture.yaml, openshift/kustomize/services/build/base/clip.yaml, openshift/kustomize/services/capture/base/config-map.yaml, openshift/kustomize/services/capture/base/deploy.yaml, openshift/kustomize/services/capture/overlays/dev/kustomization.yaml, openshift/kustomize/services/capture/overlays/prod/kustomization.yaml, openshift/kustomize/services/capture/overlays/test/kustomization.yaml, openshift/kustomize/services/clip/base/config-map.yaml, openshift/kustomize/services/clip/base/deploy.yaml, openshift/kustomize/services/clip/overlays/dev/kustomization.yaml, openshift/kustomize/services/clip/overlays/prod/kustomization.yaml, openshift/kustomize/services/clip/overlays/test/kustomization.yaml, openshift/kustomize/services/syndication/base/deploy.yaml, openshift/kustomize/services/syndication/overlays/dev/kustomization.yaml, openshift/kustomize/services/syndication/overlays/prod/kustomization.yaml, openshift/kustomize/services/syndication/overlays/test/kustomization.yaml, services/net/capture/CaptureDataSourceManager.cs, services/net/clip/ClipAction.cs
The Clip Service is erroring out quickly if the Capture Service doesn't contain the stream.  I've modified the Clip Service to hopefully keep it running even when this occurs.
Also updated the Data Source Admin to be more consistent in naming conventions.
=> TNO-302 Fix Clip Service

libs/net/services/Managers/DataSourceManager`.cs, openshift/kustomize/api/base/config-map.yaml
Presently the shared code for services will never pause or sleep due to a bug.
Also fixed DevOps config issue for API.
=> NTO-213 Fixing bugs

services/net/capture/appsettings.Development.json, services/net/capture/appsettings.Staging.json, services/net/capture/appsettings.json, services/net/clip/appsettings.Development.json, services/net/clip/appsettings.Staging.json, services/net/clip/appsettings.json, services/net/command/appsettings.Development.json, services/net/command/appsettings.Staging.json, services/net/command/appsettings.json, services/net/content/appsettings.Development.json, services/net/content/appsettings.Staging.json, services/net/content/appsettings.json, services/net/nlp/appsettings.Development.json, services/net/nlp/appsettings.Staging.json, services/net/nlp/appsettings.json, services/net/syndication/appsettings.Development.json, services/net/syndication/appsettings.Staging.json, services/net/syndication/appsettings.json
The logs for the services are too chatty.  This should reduce that.
=> Reduce log chatter

api/net/Areas/Editor/Models/Storage/FolderModel.cs, app/editor/src/features/storage/StorageListView.tsx, libs/net/core/Extensions/StringExtensions.cs
While testing in DEV found a few issues with the new Storage controller and video viewer.
=> TNO-342 Fix storage bug

api/net/Areas/Editor/Controllers/StorageController.cs, app/editor/src/features/admin/sources/DataSourceDetails.tsx, app/editor/src/features/admin/sources/services/ServiceIngestSettings.tsx, app/editor/src/features/storage/StorageListView.tsx
Streaming was hard-coded to localhost and needed to be updated to be relative.
Also updated Data Source admin UI by moving **Capture Source** and **Data Location** to the **Ingest Settings** tab, as it makes more sense there.  However, the validation doesn't currently inform the user to go to that tab, so this will need to be updated at some point.
@jdtoombs Note the changes to the Data Source admin page.  Not sure if it'll impact you when demoing.
=> TNO-342 Fix stream bug

app/editor/src/features/admin/sources/DataSourceLists.tsx
Previously was sorting on abbreviation, requested to be sorted on name
=> TNO-345: Default sort on name not abbreviation 

api/net/Areas/Editor/Controllers/ContentController.cs
Add streaming endpoint so that audio/video can be previewed in the Snippets page of the editor.
=> Added contents/stream endpoint

app/editor/src/components/upload/Upload.tsx, app/editor/src/features/content/form/ContentSummaryForm.tsx, app/editor/src/features/content/form/styled/ContentForm.tsx, app/editor/src/features/content/form/styled/ContentSummaryForm.tsx, app/editor/src/features/content/form/styled/index.ts, app/editor/src/serviceWorker.ts
Added the ability to view streaming audio/video in the snippets form.
=> First implementation of audio/video preview for snippet form

network/nginx/html/index.html
Made all file references absolute.
=> Fixed the issue where maintenance page doesn't handle paths

libs/net/tests/dal/Models/ContentFileReferenceTest.cs, libs/net/tests/dal/TNO.Test.DAL.csproj
Adding first unit test for DAL.
=> TNO-155 Add Unit Tests

.github/workflows/net-libs.yml, libs/net/TNO.sln, libs/net/tests/core/MoqHelper.cs, libs/net/tests/dal/Services/ActionServiceTest.cs, libs/net/tests/services/Controllers/HealthControllerTest.cs, libs/net/tests/services/ServiceStateTest.cs, libs/net/tests/services/TNO.Test.Services.csproj, libs/net/tests/services/Usings.cs, libs/net/tests/services/coverlet.runsettings
Adding unit tests for Services library.
=> TNO-154 Add Unit Tests

app/editor/src/features/content/combined-view/ListViewPanel.tsx, app/editor/src/features/content/form/CondensedContentForm.tsx, app/editor/src/features/content/form/ContentSummaryForm.tsx, app/editor/src/features/content/form/TimeLogTable.tsx, app/editor/src/features/content/list-view/ContentFilter.tsx, app/editor/src/features/content/list-view/ContentListView.tsx
Minor tweaks to a few bugs found with combined view
=> TNO-390: Combined View Bugs

libs/net/services/Actions/Managers/DataSourceIngestManager`.cs
I only made two changes to this so that VerifyDelay is comparing two times in the same time zone (UTC) and VerifyRunOn is doing the same.
Apart from these two issues, I found no problems with time zones or the scheduler.
=> TNO-381 Ingest Service Timezone Bugs

Makefile, docker-compose.yml, services/docker-compose.yml, tools/scripts/gen-env-files-java.sh, tools/scripts/gen-env-files.sh
Removed java dependencies from setup scripts.  While we still have a few PoC written in Java, the solution no longer relies on Java.  To improve the setup experience for new developers I have removed the extra steps.
=> Remove java setup files

app/editor/src/features/admin/sources/connections/Syndication.tsx
As per request, increase length of URL field for readability of longer URLs
=> TNO-404: Increase width of URL field

services/net/syndication/SyndicationAction.cs
When fetching content the prior process expected to find a date in the body, but it doesn't always exist.  The new process defaults to `DateTime.UtcNow` instead.
=> TNO-407 Fixing Syndication Ingest Service

app/editor/src/components/form/formpage/styled/FormPage.tsx
Eventually I think we will need to add media queries and make our forms more dynamic, but I am assuming this 1 point ticket was not for that rework
=> TNO-321: Consistent Form Page

app/editor/src/features/content/form/CondensedContentForm.tsx, app/editor/src/features/content/form/ContentForm.tsx
Previously tone values were only being saved correctly on create
=> TNO-416: Tone values saving on create not update

app/editor/src/features/admin/sources/connections/Image.tsx, services/net/syndication/SyndicationAction.cs
Syndication service was broken when a bug was introduced with the CP Feed enhancements.
=> TNO-434 Fix Syndication Service

api/net/Areas/Editor/Controllers/ContentController.cs, api/net/Dockerfile, api/net/TNO.API.csproj, libs/net/services/Helpers/ApiService.cs, libs/net/services/Interfaces/IApiService.cs, services/docker-compose.yml, services/net/.devcontainer/Dockerfile, services/net/.vscode/launch.json, services/net/.vscode/tasks.json, services/net/content/Config/ContentOptions.cs, services/net/content/ContentManager.cs, services/net/content/ContentService.cs, services/net/transcription/.dockerignore, services/net/transcription/Config/TranscriptionOptions.cs, services/net/transcription/Dockerfile, services/net/transcription/Program.cs, services/net/transcription/TNO.Services.Transcription.csproj, services/net/transcription/TranscriptionManager.cs, services/net/transcription/TranscriptionService.cs, services/net/transcription/appsettings.Development.json, services/net/transcription/appsettings.Staging.json, services/net/transcription/appsettings.json, tools/scripts/gen-env-files-java.sh, tools/scripts/gen-env-files.sh, tools/scripts/variables.sh
I was using the topic news-ghi to save time. This code worked in a regular service container.
=> Tno 413 - Create Transcription Service

app/editor/src/features/content/form/CondensedContentForm.tsx, app/editor/src/features/content/form/ContentForm.tsx
Fixing the Content form Source URL input value.
=> TNO-431 Fix content source URL

app/editor/src/features/admin/users/UserFilter.tsx, app/editor/src/features/admin/users/styled/UserFilter.tsx, app/editor/src/features/admin/users/styled/index.ts
Docker issues solved :) 
Can now hit enter on the user list to trigger the search, saving the user a click.
=> TNO-433: Click enter to search user filter

app/editor/src/features/content/form/CondensedContentForm.tsx, app/editor/src/features/content/form/ContentForm.tsx
State was out of line with tone pools
=> Tone pools bug fix

services/net/.gitignore, services/net/image/Config/ImageOptions.cs, services/net/image/ImageAction.cs, services/net/image/ImageManager.cs, services/net/image/appsettings.json
Updating Image Service logic to only work with data sources with the configured media type (i.e. "Image").
Also adding logic to handle fetching files with private keys.
=> Update Image Service

app/editor/src/features/admin/tags/constants/columns.tsx
=> TNO-438: Adjust tags column width

services/net/transcription/TranscriptionManager.cs
Hope my somewhat parrot-style implementation of the pause functionality in the transcription service was done correctly.
=> Adding pause and optimistic concurrency on content update code

app/editor/src/features/content/combined-view/CombinedView.tsx, app/editor/src/features/content/combined-view/ListViewPanel.tsx, app/editor/src/features/content/combined-view/styled/CombinedView.tsx, app/editor/src/features/content/combined-view/styled/ListViewPanel.tsx, app/editor/src/features/content/list-view/ContentFilter.tsx, app/editor/src/features/content/list-view/styled/ContentFilter.tsx
Re-arrange of combined view to save some screen real-estate while we figure out the final form.
=> TNO-458: Combined view layout update

app/editor/src/features/admin/users/UserFilter.tsx, app/editor/src/features/admin/users/UserList.tsx, app/editor/src/features/admin/users/interfaces/IUserListFilter.ts, app/editor/src/features/content/list-view/utils/makeUserFilter.ts, app/editor/src/hooks/api-editor/interfaces/IUserFilter.ts, app/editor/src/store/slices/admin/adminSlice.ts
Paging on the user list is now functional
=> TNO-447: User List Paging Bug Fix

app/editor/src/features/content/list-view/ContentFilter.tsx
Very small PR, but tooltips added to the remaining checkboxes on the content filter
=> TNO-421: Add tooltips to filter checkboxes

.vscode/launch.json, .vscode/tasks.json, Makefile, db/kafka/docker-compose.yml, openshift/kustomize/elastic/base/config-map.yaml, openshift/kustomize/elastic/base/route.yaml, openshift/kustomize/elastic/base/statefulset.yaml, openshift/kustomize/elastic/dejavu/base/deploy.yaml, openshift/kustomize/elastic/dejavu/base/kustomization.yaml, openshift/kustomize/elastic/dejavu/base/route.yaml, openshift/kustomize/elastic/dejavu/base/services.yaml, openshift/kustomize/elastic/dejavu/overlays/tools/kustomization.yaml, openshift/kustomize/services/build/base/kustomization.yaml, openshift/kustomize/services/build/base/transcription.yaml, openshift/kustomize/services/build/overlays/dev/kustomization.yaml, openshift/kustomize/services/build/overlays/jmf/kustomization.yaml, openshift/kustomize/services/content/base/config-map.yaml, openshift/kustomize/services/content/base/deploy.yaml, openshift/kustomize/services/indexing/base/config-map.yaml, openshift/kustomize/services/indexing/base/deploy.yaml, services/net/TNO.Services.sln, services/net/indexing/Dockerfile, services/net/indexing/TNO.Services.Indexing.csproj, services/net/transcription/TNO.Services.Transcription.csproj, services/net/transcription/TranscriptionManager.cs, tools/import/etl/TNO.Tools.Import.ETL.csproj, tools/import/source/TNO.Tools.Import.Source.csproj
Providing Infrastructure as Code objects to build/deploy the Indexing Service and Transcription Service.
Fixed build issue with Transcription Service.  Also fixed a number of implementation issues in the Transcription Service that were not caught in previous PR.
=> TNO-187/451 DevOps Indexing/Transcription Service

app/editor/src/features/admin/sources/services/ServiceIngestSettings.tsx, libs/net/dal/Extensions/DataSourceExtensions.cs, libs/net/dal/Services/DataSourceService.cs
When adding a new data source if a schedule was included it would fail.  This update resolves this issue.
=> TNO-529 Fix add data source

api/net/appsettings.json, libs/net/dal/Services/ContentService.cs, services/net/syndication/Config/SyndicationOptions.cs, services/net/syndication/SyndicationAction.cs, services/net/syndication/appsettings.json
Fixed an invalid text encoding issue
=> Fixed an invalid text encoding issue

libs/net/ches/ChesService.cs, libs/net/ches/Configuration/ChesOptions.cs, libs/net/ches/Exceptions/ChesException.cs, libs/net/ches/Extensions/ServiceCollectionExtensions.cs, libs/net/ches/IChesService.cs, libs/net/ches/Models/AttachmentModel.cs, libs/net/ches/Models/EmailBodyTypes.cs, libs/net/ches/Models/EmailContextModel.cs, libs/net/ches/Models/EmailEncodings.cs, libs/net/ches/Models/EmailMergeModel.cs, libs/net/ches/Models/EmailModel.cs, libs/net/ches/Models/EmailPriorities.cs, libs/net/ches/Models/EmailResponseModel.cs, libs/net/ches/Models/ErrorModel.cs, libs/net/ches/Models/ErrorResponseModel.cs, libs/net/ches/Models/IAttachment.cs, libs/net/ches/Models/IEmail.cs, libs/net/ches/Models/IEmailContext.cs, libs/net/ches/Models/IEmailMerge.cs, libs/net/ches/Models/MessageResponseModel.cs, libs/net/ches/Models/StatusHistoryResponseModel.cs, libs/net/ches/Models/StatusModel.cs, libs/net/ches/Models/StatusResponseModel.cs, libs/net/ches/TNO.Ches.csproj, libs/net/core/Converters/EnumValueJsonConverter.cs, libs/net/core/Converters/MicrosecondEpochJsonConverter.cs, libs/net/core/Extensions/EnumExtensions.cs, libs/net/core/Json/EnumValueAttribute.cs
Putting this up as draft to get some eyes on existing code. Working through some issues now with the notification queue.
=> TNO-377: CHES Integration

api/net/Areas/Admin/Controllers/UserController.cs
Fixed the issue - User Admin should not display system accounts
=> Fixed the TNO-444 issue

app/editor/src/features/content/form/ContentClipForm.tsx
TNO-521: [enhance] Create Snippet Clip Editor Start and End Display
=> Fixed the TNO-521 issue

app/editor/src/features/admin/sources/DataSourceDetails.tsx, libs/net/dal/Migrations/Initial/Up/PostUp/01-DataSource.sql, libs/net/dal/Migrations/Initial/Up/PostUp/01-Schedule.sql, libs/net/dal/Migrations/Initial/Up/PostUp/02-DataSourceSchedule.sql
Configure Source - CBC Talk Radio
=> configure data source for clip and capture services

app/editor/src/features/content/form/ContentClipForm.tsx
Fixed TNO-522 - [enhance] Create Snippet Clip Editor Prefix Label
=> Fixed TNO-522

libs/net/dal/Migrations/Initial/Up/PostUp/01-DataSource.sql, libs/net/dal/Migrations/Initial/Up/PostUp/01-Schedule.sql, libs/net/dal/Migrations/Initial/Up/PostUp/02-DataSourceSchedule.sql
Fixed TNO-586: Configure Source - CP News
=> Fixed TNO-586

app/editor/src/features/admin/sources/services/ServiceIngestSettings.tsx, libs/net/dal/Migrations/Initial/Up/PostUp/01-DataSource.sql
=> TNO-531. 530

app/editor/src/features/content/form/ContentClipForm.tsx
Fixed TNO-521 (#2): [enhance] Create Snippet Clip Editor Start and End Display
=> Fixed TNO-521 (#2)

app/editor/src/features/content/form/ContentForm.tsx, app/editor/src/features/content/form/FormPicker.tsx
- Fix previous and next content navigation buttons
- Default form to Snippet while the other content forms are undeveloped 
- These fixes also address the popout button not expanding to the correct page
=> TNO-581, 602

app/editor/src/features/content/form/ContentTranscriptForm.tsx, app/editor/src/features/content/form/styled/ContentForm.tsx
Fixed TNO-598: Expand Transcription Textarea to fill vertical space
=> Fixed TNO-598

app/editor/src/features/content/list-view/constants/columns.tsx, app/editor/src/features/content/list-view/constants/condensedColumns.tsx, app/editor/src/hooks/api-editor/validation/DataSourceSchema.ts, libs/net/core/Exceptions/HttpClientRequestException.cs, libs/net/core/Http/HttpRequestClient.cs, libs/net/kafka/ConsumerAction.cs, libs/net/kafka/Interfaces/IKafkaListener`.cs, libs/net/kafka/KafkaListener`.cs, openshift/kustomize/services/content/base/deploy.yaml, openshift/kustomize/services/content/overlays/dev/kustomization.yaml, openshift/kustomize/services/content/overlays/prod/kustomization.yaml, openshift/kustomize/services/content/overlays/test/kustomization.yaml, services/net/content/Config/ContentOptions.cs, services/net/content/ContentManager.cs, services/net/content/appsettings.json, services/net/indexing/Config/IndexingOptions.cs, services/net/indexing/IndexingManager.cs, services/net/indexing/appsettings.json, services/net/nlp/Config/NLPOptions.cs, services/net/nlp/NLPManager.cs, services/net/nlp/appsettings.json, services/net/transcription/Config/TranscriptionOptions.cs, services/net/transcription/TranscriptionManager.cs, services/net/transcription/appsettings.json
Made a number of changes to resolve issues related to Kafka consumer error handling.
Fixed an issue with data source validation.
=> Fix Kafka Consumer Services

app/editor/src/components/form/checkbox/Checkbox.tsx, app/editor/src/components/form/datepicker/SelectDate.tsx, app/editor/src/components/form/error/Error.tsx, app/editor/src/components/form/error/index.ts, app/editor/src/components/form/index.ts, app/editor/src/components/form/radio/RadioGroup.tsx, app/editor/src/components/form/select/Select.tsx, app/editor/src/components/form/textarea/TextArea.tsx, app/editor/src/components/form/timeinput/TimeInput.tsx, app/editor/src/features/content/form/ContentClipForm.tsx, app/editor/src/features/content/form/styled/ContentClipForm.tsx
Updated the error validation on the clips "form", did not use Yup as this is not technically behaving like a Formik form but follows the same conditional error message display format.
Also created a small component used elsewhere in the application to display errors.
=> TNO-418: Change error validation

app/editor/src/components/layout/DefaultLayout.tsx
Fixed TNO-420: [bug] User is not redirect to login after session expires
=> Fixed TNO-420

app/editor/src/components/layout/DefaultLayout.tsx
Fixed TNO-420 (#2): [bug] User is not redirect to login after session expires
=> Fixed TNO-420 #2

app/editor/src/features/content/form/styled/ContentForm.tsx
Fixed a code merge issue for TNO-598.
=> Fixed a code merge issue for TNO-598

app/editor/src/features/content/form/ContentForm.tsx
Small change based on a comment from Carolynn
=> Move byline

app/editor/src/features/admin/tags/TagList.tsx, app/editor/src/features/admin/tags/TagsForm.tsx, app/editor/src/features/admin/tags/constants/columns.tsx
The Tag admin forms were invalid.  They didn't correctly handle the `id` property.
=> Fix Tag Admin

libs/net/kafka/Models/ContentBase.cs, libs/net/kafka/Models/SourceContent.cs, services/net/capture/CaptureAction.cs, services/net/clip/ClipAction.cs, services/net/content/ContentManager.cs, services/net/image/ImageAction.cs, services/net/syndication/SyndicationAction.cs
Any ingest service that involved files was incorrectly mapping the file path for the Kafka message.
=> Fix ingest services

app/editor/src/features/admin/ingests/configurations/AudioClip.tsx, app/editor/src/features/admin/ingests/configurations/AudioStream.tsx, app/editor/src/features/admin/ingests/configurations/VideoClip.tsx, app/editor/src/features/admin/ingests/configurations/VideoStream.tsx, app/editor/src/hooks/api-editor/constants/WorkflowStatus.ts, app/editor/src/hooks/api-editor/constants/WorkflowStatusName.ts, libs/net/dal/Migrations/Initial/Up/PostUp/02-Ingest.sql, libs/net/entities/WorkflowStatus.cs, services/net/content/ContentManager.cs
Fixed a configuration bug with the Capture Services.  Also added a status update to the content reference after it has been imported.
=> TNO-610 Fix Capture Services

app/editor/src/features/content/form/ContentForm.tsx
Fixed TNO-578: Snippet Form - Headline Input Size
=> Fixed TNO-578

api/net/Areas/Editor/Controllers/StorageController.cs, api/net/Dockerfile, app/editor/src/features/content/form/ContentClipForm.tsx, libs/net/dal/Helpers/FfmpegHelper.cs
Fixing a number of issues related to creating clips.
- File names with spaces
- Container volume permissions
- Error messages
=> TNO-445 Fixing clip bugs

app/editor/src/features/content/list-view/styled/ContentListView.tsx
=> Slight tweak for TNO-611

services/net/capture/CaptureAction.cs, services/net/clip/ClipAction.cs, services/net/command/CommandAction`.cs
Adding logging to our Capture and Clip services.
FFMPEG logs all messages to error output.  Which apparently is a common practice.  Which essentially means there isn't an easy way to know what is an error or just information.  We'll have to learn as we go.
=> Log ffmpeg

app/editor/src/components/form/radio/RadioGroup.tsx, app/editor/src/components/form/select/Select.tsx, app/editor/src/components/form/textarea/TextArea.tsx, app/editor/src/index.scss, libs/npm/core/package.json, libs/npm/core/src/components/form/text/Text.tsx
Fixed TNO-613: Change Tooltip Behaviour
=> Fixed TNO-613

app/editor/src/features/admin/products/ProductForm.tsx, app/editor/src/features/content/list-view/ContentFilter.tsx, app/editor/src/features/content/list-view/ContentListView.tsx, app/editor/src/hooks/index.ts, app/editor/src/hooks/useLookupSync.ts, app/editor/src/store/hooks/content/useContent.ts, app/editor/src/store/hooks/lookup/utils/filterEnabled.ts, app/editor/src/store/hooks/lookup/utils/index.ts, app/editor/src/utils/getSortableOptions.ts
**TNO-607**
**TNO-457 - List View Now Updates**
=> TNO-607, 457: Product store not updating correctly & Combined view not updating list 

openshift/kustomize/services/capture/base/config-map.yaml, openshift/kustomize/services/clip/base/config-map.yaml, openshift/kustomize/services/image/base/config-map.yaml, openshift/kustomize/services/image/base/deploy.yaml
A number of minor changes to Infrastructure as Code to resolve bad configs, or outdated values.
=> Fix DevOps configs

app/editor/src/features/admin/ingests/schedules/ScheduleDaily.tsx, libs/net/dal/Migrations/Initial/Up/PostUp/02-Ingest.sql, services/net/capture/CaptureAction.cs, services/net/clip/ClipAction.cs, services/net/command/CommandAction`.cs, services/net/content/ContentManager.cs, services/net/transcription/TranscriptionManager.cs
I introduced a couple bugs latest into the Capture and Clip Service.
- Fix DB migration Ingest configuration
- Capture/Clip stop process
=> Fix Capture/Clip Service

services/net/filemonitor/FilemonitorAction.cs
The File Service was sending incorrect messages to Kafka.
=> TNO-139 Fix File Service

app/editor/src/features/content/form/ContentActions.tsx, app/editor/src/features/content/form/utils/toModel.ts, openshift/kustomize/tekton/base/deploy.yaml, openshift/kustomize/tekton/base/pvc.yaml, openshift/kustomize/tekton/build/base/Dockerfile, openshift/kustomize/tekton/build/base/build.yaml, openshift/kustomize/tekton/build/overlays/dev/kustomization.yaml, openshift/kustomize/tekton/build/overlays/master/kustomization.yaml, openshift/kustomize/tekton/overlays/tools/kustomization.yaml
Print Content has been fixed so that the actions work again.
=> TNO-680 Fix Print Content Actions

app/editor/src/hooks/api-editor/validation/SourceSchema.ts
Seems to be working already after a number of PRs have gone in. Thought my changes had fixed it, but then I went on DEV and noticed it seems to be working as expected. Validation is fired every time a submission is submitted.
=> TNO-533: Data source validation

app/editor/src/features/admin/sources/constants/columns.tsx
Fixed TNO-634: Remove Description column from Admin Sources page; source + description = same data
=> Fixed TNO-634

app/editor/src/components/form/formpage/styled/FormPage.tsx, app/editor/src/features/admin/connections/ConnectionList.tsx, app/editor/src/features/admin/connections/styled/ConnectionList.tsx, app/editor/src/features/admin/ingest-types/IngestTypeList.tsx, app/editor/src/features/admin/ingest-types/styled/IngestTypeList.tsx, app/editor/src/features/admin/ingests/IngestList.tsx, app/editor/src/features/admin/sources/SourceList.tsx, app/editor/src/features/admin/users/UserList.tsx, app/editor/src/features/admin/users/styled/UserList.tsx, app/editor/src/hooks/useCombinedView.ts
Removed some redundant `FormPages`, or applied `FormPage` to Styled Component where applicable.
=> TNO-642: Admin Page Consistency

app/editor/src/components/form/formpage/styled/FormPage.tsx
=> TNO-630: Form page expand to children

app/editor/src/features/content/form/styled/ContentForm.tsx
=> TNO-645: Fix button overlap on full content form

app/editor/src/features/admin/users/utils/makeUserFilter.ts, app/editor/src/features/content/form/utils/formatTime.ts, app/editor/src/features/content/form/utils/getTotalTime.ts, app/editor/src/features/content/list-view/utils/setTimeFrame.ts, app/editor/src/utils/formatIdir.ts, app/editor/src/utils/formatUserRoles.ts, app/editor/src/utils/hasErrors.ts
Just needed a breather from this Redux bug. Added a few docs in the meantime.
=> Add some docs

app/editor/src/components/form/radio/RadioGroup.tsx, app/editor/src/components/form/select/Select.tsx, app/editor/src/components/form/textarea/TextArea.tsx, libs/npm/core/src/components/form/text/Text.tsx
Fixed TNO-652: [bug] Tooltips no longer have standard styling
=> Fixed TNO-652

app/editor/src/features/content/form/ContentSummaryForm.tsx
Fixed TNO-641: [bug] A/V player stays visible when content changes
=> Fixed TNO-641

libs/net/kafka/Interfaces/IKafkaListener`.cs, libs/net/kafka/KafkaListener`.cs, services/net/transcription/Config/TranscriptionOptions.cs, services/net/transcription/TranscriptionManager.cs, services/net/transcription/appsettings.json
Fixed TNO-355: Multi-Thread Transcription Service
=> TNO-355 Add Multithreading to Transcription Service

api/net/Areas/Admin/Models/User/UserModel.cs, api/net/Keycloak/KeycloakHelper.cs, api/net/Models/Auth/PrincipalModel.cs, openshift/kustomize/api/base/config-map.yaml, openshift/kustomize/api/base/deploy.yaml, openshift/kustomize/api/overlays/dev/kustomization.yaml, openshift/kustomize/api/overlays/prod/kustomization.yaml, openshift/kustomize/api/overlays/test/kustomization.yaml
I introduced a couple bugs with the last release.  This PR should resolve the following.
- DevOps API deployment configuration
- API endpoint user roles model
I've also added a more advanced Keycloak Sync endpoint so that we can import all users after a refresh.
=> TNO-715 Fix keycloak changes

api/net/Areas/Admin/Models/Action/ActionModel.cs
Can now properly enable/disable the actions checkbox in the administrative section
=> TNO-704: Action isEnabled checkbox

app/editor/src/features/content/list-view/ContentFilter.tsx, app/editor/src/features/content/list-view/utils/makeFilter.ts
This works for me. Hopefully I took the right approach.
=> Filter the content list by published date instead of created date

app/editor/src/features/admin/ingests/configurations/Newspaper.tsx, services/net/filemonitor/FilemonitorAction.cs
git rebase -i still not working. I'll troubleshoot in the morning.
=> TNO-712 - Ingest content with unknown source name

api/net/Areas/Admin/Controllers/UserController.cs, libs/net/dal/Services/UserService.cs
Moved the logic so the query excludes system accounts unless specified otherwise. Desired behaviour is now achieved.
=> TNO-673: Users missing from list

libs/net/core/Extensions/StringExtensions.cs, services/net/content/ContentManager.cs
The Content Service will extract <p> from all content.
=> TNO-699: replace p tag with new line in content service

app/editor/src/features/content/form/ContentActions.tsx, app/editor/src/features/content/form/ContentForm.tsx, app/editor/src/features/content/form/ContentSummaryForm.tsx, app/editor/src/features/content/form/utils/index.ts, app/editor/src/features/content/form/utils/isImageForm.ts, app/editor/src/features/content/form/utils/isSnippetForm.ts, app/editor/src/features/content/list-view/ContentListView.tsx, app/editor/src/features/content/validation/ContentFormSchema.ts, app/editor/src/features/router/AppRouter.tsx
Fixed TNO-696: [UX/QA] create version 1 of a form editors can use to upload front pages (editor app)
=> Fixed TNO-696

services/net/syndication/SyndicationAction.cs, services/net/syndication/SyndicationIngestActionManager.cs
Introduced a bug in the Syndication Service when updates were made to support Raspberry Pi.  This should resolve the dependency injection.
=> Fix syndication service

.vscode/launch.json, .vscode/tasks.json, libs/net/core/Extensions/StringExtensions.cs, libs/net/dal/Extensions/IngestExtensions.cs, libs/net/dal/Services/IngestService.cs, libs/net/services/Helpers/ApiService.cs, openshift/kustomize/tekton/base/tasks/build-component.yaml, openshift/kustomize/tekton/base/tasks/buildah.yaml, openshift/kustomize/tekton/base/tasks/db-migration-conditional.yaml, openshift/kustomize/tekton/base/tasks/db-migration.yaml, openshift/kustomize/tekton/base/tasks/git-conditions.yaml, openshift/kustomize/tekton/base/tasks/git-pull.yaml, openshift/kustomize/tekton/base/tasks/oc-backup.yaml, openshift/kustomize/tekton/base/tasks/oc-deploy-with-tag.yaml, openshift/kustomize/tekton/base/tasks/oc-patch-route.yaml, openshift/kustomize/tekton/base/tasks/owasp-scanner.yaml, openshift/kustomize/tekton/base/tasks/pipeline-wait.yaml, services/net/Makefile, services/net/filemonitor/FilemonitorAction.cs, services/net/image/ImageAction.cs, services/net/image/ImageManager.cs
Fix add ingest
Fix image/file ingest paths
=> TNO-710 Update Tekton tasks

api/net/Middleware/LogRequestMiddleware.cs, libs/net/core/Http/HttpRequestClient.cs, openshift/kustomize/services/capture/base/config-map.yaml, openshift/kustomize/services/capture/base/deploy.yaml, openshift/kustomize/services/clip/base/config-map.yaml, openshift/kustomize/services/clip/base/deploy.yaml, openshift/kustomize/services/filemonitor/base/config-map.yaml, openshift/kustomize/services/filemonitor/base/deploy.yaml, openshift/kustomize/services/image/base/config-map.yaml, openshift/kustomize/services/image/base/deploy.yaml, openshift/kustomize/services/syndication/base/config-map.yaml, openshift/kustomize/services/syndication/base/deploy.yaml, services/net/capture/appsettings.Development.json, services/net/capture/appsettings.Staging.json, services/net/capture/appsettings.json, services/net/clip/appsettings.Development.json, services/net/clip/appsettings.Staging.json, services/net/clip/appsettings.json, services/net/filemonitor/appsettings.Development.json, services/net/filemonitor/appsettings.Staging.json, services/net/filemonitor/appsettings.json, services/net/image/appsettings.Development.json, services/net/image/appsettings.Staging.json, services/net/image/appsettings.json, services/net/syndication/appsettings.Development.json, services/net/syndication/appsettings.Staging.json, services/net/syndication/appsettings.json
Removed Kafka configuration from ingest services that no longer need it.
=> Reduce logs

openshift/kustomize/services/capture/base/deploy.yaml, openshift/kustomize/services/clip/base/deploy.yaml, openshift/kustomize/services/filemonitor/base/deploy.yaml, openshift/kustomize/services/image/base/deploy.yaml, services/net/capture/CaptureAction.cs, services/net/capture/appsettings.json, services/net/clip/ClipAction.cs, services/net/clip/appsettings.json, services/net/content/ContentManager.cs, services/net/content/appsettings.json, services/net/filemonitor/appsettings.json, services/net/image/ImageAction.cs, services/net/image/appsettings.json, services/net/indexing/appsettings.json, services/net/nlp/appsettings.json, services/net/syndication/appsettings.json, services/net/transcription/appsettings.json
Resolving issue with the Content Service unable to copy image when importing content.
Resolving DevOps templates with incorrect environment variables.
=> Fix content service file copy

app/editor/src/features/admin/users/UserForm.tsx
Had some issues with my other branch, new PR for same issue.
=> TNO-679: Allow user editing

app/editor/src/features/content/form/ContentForm.tsx
Fixed TNO-535: [QA feedback] Hyperlink source URL
=> Fixed TNO-535

libs/net/dal/Migrations/Initial/Up/PostUp/00-Connection.sql
Fixed TNO-665: Remove any sensitive information from DB Migration configuration
=> Fixed TNO-665

libs/net/dal/Migrations/Initial/Up/PostUp/00-License.sql, libs/net/dal/Migrations/Initial/Up/PostUp/01-Source.sql
Fixed TNO-635: [QA] verify all media sources licences are correct (x-reference against Wiki on GitHub)
=> Fixed TNO-635

api/net/Areas/Admin/Models/Action/ActionModel.cs, api/net/Areas/Admin/Models/Product/ProductModel.cs
Fixed TNO-717: [bug] 'sort order' on Products and Actions not saving
=> Fixed TNO-717

app/editor/src/features/admin/ingests/configurations/VideoRPi.tsx, app/editor/src/features/admin/ingests/configurations/VideoStream.tsx, services/net/capture/CaptureAction.cs
Resolving a few capture service configuration issues.
=> TNO-734 Update capture

app/editor/src/features/content/list-view/ContentFilter.tsx
Fixed TNO-719: [UX] as an TNO editor, I want to be able to search a source without knowing its org code
=> Fixed TNO-719

api/net/Program.cs, api/net/appsettings.json, app/editor/nginx/local.conf, app/editor/src/hooks/api-editor/editor/useApiHubConnection.ts, network/nginx/config/default.conf
This is just a temporary update for testing the SignalR issue on the dev environment.
=> TNO-697 updates just for testing on dev only

services/net/content/ContentManager.cs
Fixed TNO-675: [bug] Import issue when file is not found
=> Fixed TNO-675

services/net/filemonitor/FilemonitorAction.cs
One thing of note: I reverted the switch statement in PerformActionAsync() to classic syntax to resolve compilation errors.
=> Modify to process only one file at a time and create a single SourceContent object at a time

app/editor/src/features/admin/ingests/configurations/AudioClip.tsx, app/editor/src/features/admin/ingests/configurations/VideoClip.tsx, app/editor/src/features/admin/ingests/configurations/VideoRPi.tsx, libs/net/ches/TNO.Ches.csproj, libs/net/core/Extensions/StringExtensions.cs, libs/net/core/TNO.Core.csproj, services/net/capture/CaptureManager.cs, services/net/clip/ClipAction.cs, services/net/clip/ClipManager.cs, services/net/content/ContentManager.cs, services/net/content/TNO.Services.Content.csproj, tools/scripts/purge-folders.sh
A few bug fixes, tweaks, and small enhancements to support the Clip Service running in the server room.
- Add Clip service filename filter
- Add Capture service ingest filter by data location
- Add Clip service ingest filter by data location
- Add cron job to server room to purge files over configured period
=> TNO-643 Fix content service ssh

app/editor/src/components/form/formpage/styled/FormPage.tsx, app/editor/src/components/layout/DefaultLayout.tsx, app/editor/src/components/layout/LayoutAnonymous.tsx, app/editor/src/features/content/form/ContentForm.tsx, app/editor/src/features/content/form/styled/ContentForm.tsx
=> TNO-728: Scrolling styling and removing footer

app/editor/src/features/admin/licenses/LicenseForm.tsx, app/editor/src/features/admin/licenses/LicenseList.tsx, app/editor/src/features/admin/sources/SourceDetails.tsx, app/editor/src/features/admin/sources/constants/columns.tsx, app/editor/src/features/content/form/ContentSummaryForm.tsx, app/editor/src/features/navbar/NavBar.tsx, app/editor/src/hooks/api-editor/validation/SourceSchema.ts
Fixed TNO-753: [QA] Pls correct spelling of licence
=> Fixed TNO-753

app/editor/src/features/content/form/ContentForm.tsx, app/editor/src/store/hooks/editor/useContent.ts, app/editor/src/store/hooks/editor/useWorkOrders.ts, network/nginx/config/default.conf
The redux state in the list view wasn't being updated reliably when content was updated.  The issue was the implementation of the `useContent` hook that contained a state controller.
=> TNO-670 Fix content redux hook

app/editor/src/features/content/form/ContentSummaryForm.tsx
Fixed TNO-703: [enhance] when creating new snippet or new print item, date/time should be pre-populated to current date/time
=> Fixed TNO-703

libs/npm/core/src/components/button/styled/Button.tsx
Fixed TNO-760: [bug] Button Text Overflow
=> Fixed TNO-760

app/editor/src/components/form/wysiwyg/CustomToolbar.tsx, app/editor/src/components/form/wysiwyg/Wysiwyg.tsx, app/editor/src/components/form/wysiwyg/styled/Wysiwyg.tsx
- Fix tag invalid tags bug, now only checks last set of []
- Add a clear button to get rid of all text/html
- iOS compatible
=> WYSIWYG Bugs - Part 1/2

app/editor/src/features/content/form/ContentForm.tsx, app/editor/src/features/content/form/ContentSummaryForm.tsx, app/editor/src/features/content/list-view/ContentFilter.tsx
- slight change to text field on content form
- able to clear some previously un clearable fields (via x button)
=> TNO-764, TNO-765: Select Field Tweaks

app/editor/src/components/form/select/Select.tsx, app/editor/src/components/form/select/styled/Select.tsx
Same look and feel, just less bugs 🤦‍♂️
=> Clearable dropdown bugs

app/editor/src/features/content/form/ContentSummaryForm.tsx, app/editor/src/features/navbar/NavBar.tsx
Fixing bug introduced in recent PR related to the Event of Day Category dropdown.
Also adding small enhancement to navbar.
=> TNO-764 Fix dropdown Event of Day Category

openshift/kustomize/api/base/config-map.yaml, openshift/kustomize/api/base/deploy.yaml, openshift/kustomize/api/base/kustomization.yaml, openshift/kustomize/api/overlays/dev/kustomization.yaml, openshift/kustomize/api/overlays/prod/kustomization.yaml, openshift/kustomize/api/overlays/test/kustomization.yaml, openshift/kustomize/app/editor/base/config-map.yaml, openshift/kustomize/app/editor/overlays/dev/kustomization.yaml, openshift/kustomize/app/editor/overlays/prod/kustomization.yaml, openshift/kustomize/app/editor/overlays/test/kustomization.yaml
I've updated Infrastructure as Code for the latest changes to support Keycloak Gold Realm integration.
=> TNO-8 Update DevOps for Keycloak Gold

api/net/Areas/Admin/Controllers/WorkOrderController.cs
Fixing bug introduced with Keycloak Gold realm integration.
=> TNO-8 Fix work orders controller

api/net/Keycloak/CssHelper.cs, app/editor/src/components/toggle-group/ToggleGroup.tsx, app/editor/src/features/admin/users/UserForm.tsx, libs/net/css/CssService.cs, libs/net/css/Extensions/HttpResponseMessageExtensions.cs, openshift/kustomize/api/base/config-map.yaml
Resolving a few issues with user management related to Keycloak Gold realm.
- Edit user name
- Update/Delete a user that doesn't exist in Keycloak Gold realm
- First time a user logs in to app they will not see an 403 error anymore
Fixed a couple bugs introduced with the new UI elements.
=> TNO-8 Fix approve user

libs/net/core/Http/HttpRequestClient.cs, libs/net/core/Http/OpenIdConnectRequestClient.cs, libs/net/services/Helpers/ApiService.cs
Adding the additional error handling regrettably introduced a thread issue.  Fixed this, and also a logic error.
=> TNO-792 Fix ingest services

app/editor/src/features/content/tool-bar/sections/CreateNewSection.tsx
TNO-808: [enhance] Toolbar Hover Text
=> Fixed TNO-808

app/editor/src/features/content/form/ContentForm.tsx
Fixed TNO-337: (re-opened) QA feedback: as a TNO editor, when I create a snippet, I want some fields to auto-populate, saving me input time.
=> Fixed TNO-337

app/editor/src/components/form/wysiwyg/CustomToolbar.tsx, app/editor/src/components/form/wysiwyg/Wysiwyg.tsx, app/editor/src/components/form/wysiwyg/styled/Wysiwyg.tsx, app/editor/src/components/modal/styled/Modal.tsx, app/editor/src/features/content/form/ContentSummaryForm.tsx
Fixed TNO-761: [enhance] Expand WYSIWYG Editor to Full Page
=> Fixed TNO-761

libs/net/core/Http/HttpRequestClient.cs
=> TNO-815 (a minor update)

app/editor/src/features/content/list-view/styled/ContentListView.tsx
Scroll bar was causing some misalignment issues.
=> TNO-809: Column alignments

app/editor/src/components/form/wysiwyg/Wysiwyg.tsx, app/editor/src/components/form/wysiwyg/styled/Wysiwyg.tsx, app/editor/src/components/modal/Modal.tsx, app/editor/src/components/modal/styled/Modal.tsx, app/editor/src/features/content/form/ContentSummaryForm.tsx
TNO-761: [enhance] Expand WYSIWYG Editor to Full Page
=> Fixed TNO-761 #2

app/editor/src/components/form/wysiwyg/CustomToolbar.tsx
TNO-873: [QA] remove function for last widget in the WYSIWYG toolbar
=> Fixed TNO-873

app/editor/src/features/content/form/ContentForm.tsx
TNO-878: [QA] toggling between combined view and split screen view - uncomment this code
=> Fixed TNO-878

app/editor/src/features/content/form/ContentForm.tsx
TNO-837: Content Form Return to List View Button
=> Fixed TNO-837

app/editor/src/features/content/form/ContentSummaryForm.tsx
TNO-864: Tags aren't deleting when pressing "clear"
=> Fixed TNO-864

app/editor/src/features/content/form/constants/defaultFormValues.ts
TNO-826: [bug] New Content Status
=> Fixed TNO-826

app/editor/src/components/tool-bar/ToolBarSection.tsx, app/editor/src/components/tool-bar/styled/ToolBarSection.tsx, app/editor/src/features/content/form/ContentForm.tsx, app/editor/src/features/content/tool-bar/ContentFormToolBar.tsx, app/editor/src/features/content/tool-bar/sections/form/StatusSection.tsx, app/editor/src/features/content/tool-bar/sections/form/index.ts
=> TNO-784: Status section

app/editor/src/components/form/datepicker/styled/SelectDate.tsx, app/editor/src/components/tool-bar/styled/ToolBar.tsx, app/editor/src/components/tool-bar/styled/ToolBarSection.tsx, app/editor/src/features/content/tool-bar/ContentToolBar.tsx, app/editor/src/features/content/tool-bar/sections/filter/FilterContentSection.tsx
Mockup has an animation; however, I am wondering if that is necessary since there is space for it?
=> TNO-775: Date range

app/editor/src/features/content/list-view/ContentListView.tsx, app/editor/src/features/content/tool-bar/sections/filter/FilterContentSection.tsx
Ensure the filter is applied based on the query parameters, also updated the toggle options to show correct values when this is this case
=> TNO-726: Persist filter from query params

libs/npm/core/src/components/grid-table/styled/GridTable.tsx, libs/npm/core/src/components/loading/LoadingStyled.tsx
TNO-825: [bug] Fix loading overlay within table
=> Fixed TNO-825

libs/npm/core/src/components/grid-table/GridTable.tsx
TNO-828: [bug] Content Form Combined View Next/Previous Buttons
=> Fixed TNO-828

app/editor/src/features/content/tool-bar/sections/filter/FilterContentSection.tsx
Fixed issue introduced in list content query filter.  Prior submitted code was not handling undefined.
Still need to figure out how to handle secondary issue resulting from 'intermediate value'...
=> TNO-276 Fix list content search

api/net/Program.cs, app/subscriber/src/features/admin/users/interfaces/IUserListFilter.ts, app/subscriber/src/features/admin/users/interfaces/index.ts, app/subscriber/src/features/admin/work-orders/interfaces/IWorkOrderListFilter.ts, app/subscriber/src/features/admin/work-orders/interfaces/index.ts, libs/net/Makefile, openshift/kustomize/api/base/deploy.yaml, openshift/kustomize/app/subscriber/base/config-map.yaml, openshift/kustomize/app/subscriber/base/deploy.yaml, openshift/kustomize/app/subscriber/base/kustomization.yaml, openshift/kustomize/app/subscriber/base/network-policy.yaml, openshift/kustomize/app/subscriber/base/route.yaml, openshift/kustomize/app/subscriber/base/service.yaml, openshift/kustomize/app/subscriber/build/base/build.yaml, openshift/kustomize/app/subscriber/build/base/kustomization.yaml, openshift/kustomize/app/subscriber/build/overlays/dev/kustomization.yaml, openshift/kustomize/app/subscriber/build/overlays/jmf/kustomization.yaml, openshift/kustomize/app/subscriber/overlays/dev/kustomization.yaml, openshift/kustomize/app/subscriber/overlays/prod/kustomization.yaml, openshift/kustomize/app/subscriber/overlays/test/kustomization.yaml, openshift/kustomize/services/capture/base/deploy.yaml, openshift/kustomize/services/config-map.yaml, openshift/kustomize/services/content/base/deploy.yaml, openshift/kustomize/services/filemonitor/base/deploy.yaml, openshift/kustomize/services/image/base/deploy.yaml, openshift/kustomize/services/indexing/base/deploy.yaml, openshift/kustomize/services/nlp/base/deploy.yaml, openshift/kustomize/services/syndication/base/deploy.yaml, openshift/kustomize/services/transcription/base/deploy.yaml
Add missing subscriber interfaces.
Updated DevOps templates to fix TEST environment.
Resolve build issues with subscriber app.
=> TNO-859 Fix templates

openshift/kustomize/api/base/route.yaml, openshift/kustomize/api/overlays/dev/kustomization.yaml, openshift/kustomize/api/overlays/prod/kustomization.yaml, openshift/kustomize/api/overlays/test/kustomization.yaml, openshift/kustomize/app/subscriber/base/route.yaml, openshift/kustomize/app/subscriber/overlays/dev/kustomization.yaml, openshift/kustomize/app/subscriber/overlays/prod/kustomization.yaml, openshift/kustomize/app/subscriber/overlays/test/kustomization.yaml, openshift/kustomize/tekton/base/pipelines/buildah-main.yaml, openshift/kustomize/tekton/base/pipelines/buildah-subscriber.yaml, openshift/kustomize/tekton/base/tasks/git-conditions.yaml
Adding DevOps templates for the subscriber app.
=> TNO-850 Subscriber DevOps

app/editor/src/features/content/morning-report/MorningReportFilter.tsx
Updating morning report filters to have the following "quick filter checkboxes"
- Front Page
- Commentary
- Top Story
- Hidden
=> TNO-835: Morning report filters

services/net/clip/ClipAction.cs
Also addressed the issue where the default ffprobe command returns a float in string format but the mkv command returns an integer. Effectively divided the mkv duration string value by 1000 by inserting a decimal point, making the duration represent seconds rather than milliseconds. I couldn't find a way to control the output format of the duration in ffprobe. This also ensures that the duration for all formats can be converted using float.TryParse().
=> Adding ffprobe command for in-progress mkv capture duration

app/editor/src/features/content/form/ContentForm.tsx
Moving edition to same row as other print content values
=> TNO-883: Move edition to same row

app/editor/src/features/content/morning-report/MorningReportFilter.tsx
- remove duplicate commentary filter
- get rid of state variable and use the state of the checkbox for filter value
=> Clean up report filters

api/net/Config/Swagger/SwaggerDocumentFilter.cs, api/net/Program.cs, services/net/filemonitor/FilemonitorAction.cs
Applying Stuart's timezone fix in separate PR to avoid DB changes for now.
Resolved a number of build warnings.
=> TNO-906 Fix timezone

app/editor/src/features/content/tool-bar/sections/filter/FilterContentSection.tsx, app/editor/src/store/slices/content/contentSlice.ts
- On initial load content filter will now default to All Content
- Note that this is a separate story from persisting the filter and that work will be in a different PR
=> TNO-907: Default to all content

libs/npm/core/package.json, libs/npm/core/webpack.config.js
Resolving issue with missing assets in the `tno-core` package.
=> Fix tno-core build/pack

app/editor/src/features/content/form/ContentSummaryForm.tsx
Now able to correctly expand WYSIWYG for Print Content and label adjusted accordingly.
=> TNO-882: Expand WYSIWYG for Print Content

app/editor/src/features/content/tool-bar/sections/filter/DateRangeSection.tsx, app/editor/src/features/content/tool-bar/sections/filter/styled/DateRangeSection.tsx
Align date range component styling with mockup and add tooltip
=> TNO-910: Styling date range

api/net/Areas/Editor/Controllers/StorageController.cs, app/editor/src/features/admin/ingests/configurations/AudioClip.tsx, app/editor/src/features/admin/ingests/configurations/AudioStream.tsx, app/editor/src/features/admin/ingests/configurations/AudioTuner.tsx, libs/net/dal/Migrations/Initial/Up/PostUp/02-Ingest.sql
Fixing API endpoints that access storage/files/streams.  There was an issue where an invalid connection would result in attempting to access files in the wrong location.
Adding FFmpeg loglevel to more ingest configurations.
Fixing a few default radio station URLs.  FFmpeg doesn't support playlists.
=> TNO-874 Fix streams

api/net/Areas/Editor/Controllers/StorageController.cs
The Openshift mapped volume was not working correctly.  The storage controller should now handle locations without a connection.
=> TNO-874 Fix storage locations

app/editor/src/features/content/form/ContentSummaryForm.tsx, app/editor/src/features/content/list-view/constants/columns.tsx
=> Fix content list columns

app/editor/src/features/content/tool-bar/sections/filter/DateRangeSection.tsx
- was constantly trying to force the page index to 0 when the pager was changed
=> Pagination bug

openshift/kustomize/cron/Dockerfile, openshift/kustomize/cron/base/config-map.yaml, openshift/kustomize/cron/base/cron-job.yaml, openshift/kustomize/cron/build/base/build.yaml, openshift/kustomize/cron/build/base/kustomization.yaml, openshift/kustomize/cron/build/overlays/dev/kustomization.yaml, openshift/kustomize/cron/build/overlays/jmf/kustomization.yaml, tools/scripts/purge-folders.sh
Updated `purge-service` CronJob so that it works and doesn't spam logs with invalid info.
=> TNO-939 Fix cron job

libs/net/services/Managers/IngestManager`.cs
TNO-1003: [bug] Capture doesn't stop when disabled
=> Fixed TNO-1003

app/editor/src/components/tool-bar/styled/ToolBarSection.tsx
=> Fix toolbar z-index

api/net/Areas/Admin/Models/Connection/ConnectionModel.cs, api/net/Areas/Admin/Models/DataLocation/ConnectionModel.cs, api/net/Areas/Admin/Models/Ingest/ConnectionModel.cs, api/net/Areas/Admin/Models/Ingest/IngestModel.cs, api/net/Areas/Admin/Models/Source/SourceModel.cs
I somehow missed a build issue with the API after I updated the DB migration.
=> TNO-736 Fix API build

api/net/Dockerfile.openshift, openshift/kustomize/tekton/base/pipeline-runs/buildah-service.yaml, openshift/kustomize/tekton/base/tasks/build-component.yaml, openshift/kustomize/tekton/base/tasks/buildah.yaml
Fixing bug in API Dockerfile used by Openshift
=> Fixing API Dockerfile

libs/net/services/Managers/IngestManager`.cs
TNO-921: [bug] Changes to Ingest Configuration is not being detected by service
=> Fixed TNO-921

app/editor/src/components/form/time-log/TimeLogSection.tsx, app/editor/src/components/form/time-log/styled/TimeLogSection.tsx, app/editor/src/components/form/time-log/styled/index.ts, app/editor/src/features/content/form/ContentForm.tsx, app/editor/src/features/content/form/ContentSummaryForm.tsx, app/editor/src/index.scss
- ensure required asterisks does not disappear on source
- update time log styling
=> TNO-995, 1023: Source required bug, and time style

app/editor/src/features/content/form/ContentSummaryForm.tsx
Rename to Show/Program for snippets.
=> TNO-1036: Rename series for snippets

openshift/kustomize/services/build/base/capture.yaml, openshift/kustomize/services/build/base/clip.yaml, openshift/kustomize/services/build/base/content.yaml, openshift/kustomize/services/build/base/filecopy.yaml, openshift/kustomize/services/build/base/filemonitor.yaml, openshift/kustomize/services/build/base/image.yaml, openshift/kustomize/services/build/base/indexing.yaml, openshift/kustomize/services/build/base/nlp.yaml, openshift/kustomize/services/build/base/syndication.yaml, openshift/kustomize/services/build/base/transcription.yaml, openshift/kustomize/tekton/base/pipelines/buildah-service.yaml, openshift/kustomize/tekton/base/pipelines/buildah-services.yaml, services/net/capture/Dockerfile.openshift, services/net/clip/Dockerfile.openshift, services/net/command/Dockerfile.openshift, services/net/content/Dockerfile.openshift, services/net/filecopy/Dockerfile.openshift, services/net/filemonitor/Dockerfile.openshift, services/net/image/Dockerfile.openshift, services/net/indexing/Dockerfile.openshift, services/net/nlp/Dockerfile.openshift, services/net/syndication/Dockerfile.openshift, services/net/transcription/Dockerfile.openshift
Trying to debug build issues with Tekton pipelines again...
=> Fix DevOps builds

api/net/Middleware/ErrorHandlingMiddleware.cs, app/editor/src/store/hooks/app/useToastError.tsx, app/editor/src/store/hooks/useAjaxWrapper.ts, app/editor/src/store/slices/app/interfaces/IErrorModel.ts, app/subscriber/src/store/hooks/app/useToastError.tsx, app/subscriber/src/store/hooks/useAjaxWrapper.ts, app/subscriber/src/store/slices/app/interfaces/IErrorModel.ts, libs/net/Dockerfile
When creating a new record with a primary key value that already exists, a friendly error will be returned.
Also fixed the DB migration DevOps pipeline.
=> TNO-927 Improve error message

app/editor/src/features/content/form/ContentForm.tsx, app/editor/src/features/content/form/ContentSummaryForm.tsx
- rename buttons on content form
- remove EoD from image form 
- add other source to image form
Introduced a different bug after finally figuring out the persistence of the productids putting this up in the meantime.
=> TNO-1067: Rename buttons

app/editor/src/features/content/form/ContentSummaryForm.tsx
- just a change in the conditional rendering so wysiwyg and tags will now appear for image form
=> Rest of tno-893: Add tags and wysiwyg for image

app/editor/src/features/admin/series/SeriesList.tsx, app/editor/src/features/content/form/ContentSummaryForm.tsx
Correct admin area of application as well.
=> TNO-1036 changes

app/editor/__mocks__/styleMock.ts, app/editor/src/features/admin/ingests/configurations/Video.tsx, app/editor/src/features/admin/ingests/configurations/VideoClip.tsx, app/editor/src/features/admin/ingests/configurations/VideoHDMI.tsx, app/editor/src/features/admin/ingests/configurations/VideoStream.tsx, app/editor/src/features/admin/ingests/configurations/constants/ServiceTypes.ts, app/editor/src/features/admin/ingests/configurations/index.ts, libs/net/services/Config/IngestServiceOptions.cs, openshift/kustomize/tekton/base/tasks/db-migration-conditional.yaml, openshift/kustomize/tekton/base/tasks/db-migration.yaml, services/net/capture/CaptureManager.cs, services/net/capture/appsettings.json
Provide a way to configure HDMI ingest configurations for capturing audio and video.
=> Add HDMI ingest config

app/editor/src/features/admin/AdminRouter.tsx, app/editor/src/features/admin/actions/ActionForm.tsx, app/editor/src/features/admin/series/SeriesForm.tsx, app/editor/src/features/admin/series/SeriesList.tsx, app/editor/src/features/navbar/NavBar.tsx
Few more areas that had to be updated
=> series -> programs

app/editor/src/features/content/tool-bar/sections/filter/FilterContentSection.tsx
Was testing TNO-899 and ran into this bug in DEV.
=> Fix for persisting user filter selected

api/net/appsettings.Development.json, api/net/appsettings.json
TNO-928: a minor fix for deployment
=> TNO-928 (a minor fix for deployment)

libs/net/entities/ContentAction.cs, libs/net/entities/ContentCategory.cs, libs/net/entities/ContentLabel.cs, libs/net/entities/ContentLink.cs, libs/net/entities/ContentTag.cs, libs/net/entities/ContentTonePool.cs, libs/net/entities/ContentTypeAction.cs, libs/net/entities/FileReference.cs, libs/net/entities/Ingest.cs, libs/net/entities/IngestDataLocation.cs, libs/net/entities/IngestSchedule.cs, libs/net/entities/IngestState.cs, libs/net/entities/Source.cs, libs/net/entities/SourceMetric.cs, libs/net/entities/SourceSourceAction.cs, libs/net/entities/TimeTracking.cs
TNO-928: a few more constructor order related updates
=> TNO-928 (a few more deployment related updates)

app/editor/src/features/content/form/ContentActions.tsx, app/editor/src/features/content/form/ContentForm.tsx
TNO-1063: Disabled Actions should NOT be displayed
=> Fixed TNO-1063

openshift/README.md, openshift/kustomize/api/base/statefulset.yaml, openshift/kustomize/tekton/base/pipelines/buildah-api.yaml, openshift/kustomize/tekton/base/pipelines/buildah-main.yaml, openshift/kustomize/tekton/base/tasks/oc-deploy-with-tag.yaml, openshift/templates/tekton/service-account/role.yaml
Updated our DevOps pipeline so that it can automate deployments for Statefulsets.
Also improved deployment for other objects as it will now wait until all pods are ready.
=> TNO-1041 Update DevOps for Statefulsets

api/net/Areas/Editor/Controllers/ContentController.cs, openshift/kustomize/elastic/base/config-map.yaml, services/net/indexing/IndexingManager.cs
When publishing the indexing service should also index.
Fixed logging issue to help with debugging.
=> Fix Indexing Service

api/net/Areas/Services/Controllers/ContentController.cs
Content send to the API via ingestion services should also automatically index.
=> Fix indexing content from service

api/net/Areas/Services/Controllers/ContentController.cs
Added a new endpoint to reindex the whole database.  It'll probably timeout, but for testing it can help us.
=> Add reindex endpoint

libs/net/dal/Services/ContentService.cs
928: Search Content: Elastic Search
=> 928 deployment updates for paging

libs/net/dal/Services/ContentService.cs
TNO-928: Search Content: Elastic Search
=> TNO-928 (a few more updates for dev)

app/editor/src/features/content/form/ContentSummaryForm.tsx, app/editor/src/features/content/form/styled/ContentSummaryForm.tsx
=> TNO-897: Rearrange media

app/editor/src/features/content/form/ContentForm.tsx
When a piece of content is published the user now has a button to unpublish.
=> Add unpublish button

libs/net/dal/Services/ContentService.cs
TNO-982: Search Content: Elastic Search
=> TNO-982 (Fixed the IncludedInEod issue)

app/editor/src/features/content/form/ContentTranscriptForm.tsx
In the meantime before the new tags are implemented. Currently a disabled field
=> Decouple tags

app/editor/src/features/content/tool-bar/sections/filter/AdvancedSearchSection.tsx
Remove clear option from fieldType select in the content list tool bar
=> TNO-1056: Remove clear button from fieldType

app/editor/src/features/content/form/ContentForm.tsx
Users need option to Unpublish regardless of status.
=> Remove conditional rendering

app/editor/src/features/content/form/ContentSummaryForm.tsx
One more spot to rename to topics
=> EoD -> Topics

app/editor/src/features/content/form/ContentSummaryForm.tsx
=> Topics -> Topic

app/editor/src/components/form/wysiwyg/Wysiwyg.tsx, app/editor/src/components/layout/DefaultLayout.tsx, app/editor/src/components/layout/LayoutErrorBoundary.tsx, app/editor/src/components/layout/styled/Layout.tsx, app/editor/src/features/content/form/ContentForm.tsx, app/editor/src/features/content/list-view/ContentListView.tsx, app/editor/src/hooks/api-editor/editor/useApiContents.ts, app/editor/src/store/hooks/editor/useContent.ts
When attempting to load content that does not exist the API returns a 204 to acknowledge the endpoint request is valid, but the content doesn't exist.
A toast will now be displayed with an error message.
In addition to this fix, the ErrorBoundary component now includes the menu and displays a little more information.
=> TNO-1115 Fix 204 no content

app/editor/src/features/content/form/ContentForm.tsx
TNO-1082: Content Form - Reverse order of Publish/Save without publish buttons
=> Fixed TNO-1082

app/editor/src/components/form/wysiwyg/styled/Wysiwyg.tsx, app/editor/src/features/admin/ingests/configurations/Newspaper.tsx, libs/net/core/Extensions/StringExtensions.cs, libs/net/dal/Migrations/Initial/Up/PostUp/02-Ingest.sql, services/net/filemonitor/FilemonitorAction.cs, services/net/filemonitor/models/Fields.cs
The File Monitor Service now handles FMS formatting better and wraps the story boy parts in paragraph tags.
=> TNO-902 Fix paper ingest

api/net/Areas/Admin/Controllers/WorkOrderController.cs, api/net/Areas/Editor/Controllers/ContentController.cs, api/net/Areas/Editor/Controllers/WorkOrderController.cs, api/net/Areas/Services/Controllers/ContentController.cs, api/net/Areas/Services/Controllers/WorkOrderController.cs, api/net/Program.cs, api/net/SignalR/MessageHub.cs
Not certain why this wasn't working in DEV as it does work locally.  I've made a best guess in hopes it will resolve the DEV issue.
=> TNO-1128 Fix signalR

libs/net/entities/Product.cs, libs/net/models/Areas/Services/Models/Content/ContentModel.cs, libs/net/models/Areas/Services/Models/Content/ProductModel.cs
TNO-1123: Product Designation missing on home page table (elastic search)
=> Fix TNO-1123

app/editor/src/components/form/tags/Tags.tsx
Menu was a little long, and would cause scroll issues (add additional scrolling) for some content types
=> Styling tweak for tags

app/editor/src/components/form/tags/Tags.tsx
One more little tweak after doing some resizing - sorry was zoomed out on my monitor.
=> Adjust height for print content

app/editor/src/features/content/form/ContentForm.tsx, app/editor/src/features/content/form/styled/ContentForm.tsx, app/editor/src/index.scss
TNO-847: Snippet Content Form - Publish requires A/V file
=> Fix TNO-847

libs/net/services/Managers/IngestManager`.cs
TNO-1079: Capture Service won't stop capturing after it has started
=> Fix TNO-1079

app/editor/src/features/content/form/ContentForm.tsx, app/editor/src/features/content/form/MediaSummary.tsx
TNO-664: [QA] image form: remove the following fields: byline, topic, tone & tag
=> Fix TNO-664

app/editor/src/features/admin/topic-score-rules/TopicScoreRuleList.tsx, app/editor/src/features/admin/topic-score-rules/validation/TopicScoreRuleSchema.ts, app/editor/src/features/admin/topic-score-rules/validation/TopicScoreRulesSchema.ts, app/editor/src/features/admin/topic-score-rules/validation/index.ts, app/editor/src/features/admin/topics/TopicForm.tsx, app/editor/src/features/admin/topics/TopicList.tsx, app/editor/src/features/admin/topics/validation/TopicSchema.ts, app/editor/src/features/admin/topics/validation/index.ts
Added validation and fixed bugs on the Topic Score Rules page.
=> TNO-843 Fix topic admin

libs/net/models/Areas/Services/Models/Content/ContentTagModel.cs
Resolving issue when requesting a transcript for a story that has tag values.
=> TNO-1162 Fix transcription service

app/editor/src/features/content/form/ContentTranscriptForm.tsx, app/editor/src/features/content/form/styled/ContentTranscriptForm.tsx
Tags now work on the transcript tab.
=> TNO-1162 Fix Transcript Tab and Tags

services/net/filemonitor/FilemonitorAction.cs
TNO-1154: Globe & Mail Source Failure
=> Fix TNO-1154

services/net/clip/ClipAction.cs
TNO-1152: Clip Service is failing
=> Fix TNO-1152

app/editor/src/features/content/form/ContentStoryForm.tsx, app/editor/src/features/content/morning-report/MorningReportFilter.tsx, app/editor/src/features/content/morning-report/constants/defaultReportFilter.ts, app/editor/src/features/content/morning-report/filter-sections/FilteredContentSection.tsx
- default selected now appears when loading the morning report
- removed show/program from both print content and stories (internet)
=> TNO-931, TNO-1158: Default selected for a.m report

libs/net/services/Helpers/ApiService.cs, libs/net/services/Interfaces/IApiService.cs
Fixing coding errors introduced in the services.
=> Fix services

tools/scripts/cc.sh
Basic script to capture Closed Caption and place it into a file with timestamps.
=> TNO-1117 Add CC script

libs/net/dal/TNOContext.cs, services/net/capture/CaptureAction.cs, services/net/clip/ClipAction.cs, services/net/image/ImageAction.cs, services/net/syndication/SyndicationAction.cs
TNO-1048: DB Concurrency Errors
=> Fix TNO-1048 #3

app/editor/src/features/content/form/ContentForm.tsx
TNO-849: Content Form - Delete Button
=> Fix TNO-849

app/editor/src/features/content/form/ContentStoryForm.tsx, app/editor/src/features/content/form/ContentTranscriptForm.tsx
TNO-1075: WYSIWYG expand button doesn't work
=> Fix TNO-1075

libs/npm/core/Makefile, libs/npm/core/scripts/package.sh
Putting this up just incase it is useful for anyone else.
Can now do:
`make pack n=editor` OR `make pack n=subscriber`
=> Update make pack script

app/editor/src/features/content/form/ContentForm.tsx
TNO-849: Content Form - Delete Button
=> Fix TNO-849 #2

app/editor/src/features/content/tool-bar/ContentToolBar.tsx
TNO-394: Secure HTML 5 Audio/Video Stream
=> TNO-394 (fix an url related issue)

libs/npm/core/src/components/header/Header.tsx
TNO-892: [QA] hyperlink MM logo in banner
=> Fix TNO-892

app/subscriber/src/features/content/view-content/ViewContent.tsx
Small bug while testing in DEV
=> Bug for undefined tone

app/editor/src/features/content/morning-reports/styled/MorningReports.tsx
Making the table have a max height on the Morning Papers page.
=> TNO-1193 Fix morning paper table

libs/net/core/Extensions/StringExtensions.cs
TNO-1191: Pls add paragraph spacing to ingested content from Globe & Mail
=> Fix TNO-1191

libs/net/dal/Services/ContentReferenceService.cs, libs/net/dal/Services/ContentService.cs
TNO-1048: DB Concurrency Errors
=> TNO-1048 updates

app/editor/src/features/content/list-view/utils/makeFilter.ts, app/editor/src/features/content/morning-reports/utils/makeFilter.ts
Fixing filter issues related to sources.  This may also fix the product id bug.
=> Fix filter bugs

services/net/transcription/Dockerfile
I broke the transcription service when editing a mass of Dockerfile.
=> TNO-1251 Fix transcription service

app/editor/src/features/admin/ingests/configurations/FrontPage.tsx, libs/net/kafka/Models/ContentBase.cs, libs/net/kafka/Models/SourceContent.cs, services/net/content/ContentManager.cs, services/net/image/ImageAction.cs
TNO-1071: Auto-publish Frontpages
=> Fix TNO-1071

app/subscriber/src/features/commentary/Commentary.tsx, app/subscriber/src/features/commentary/index.ts, app/subscriber/src/features/commentary/styled/Commentary.tsx, app/subscriber/src/features/commentary/styled/index.ts, app/subscriber/src/features/commentary/utils/DetermineContentIcon.tsx, app/subscriber/src/features/commentary/utils/index.ts, app/subscriber/src/features/commentary/utils/isWeekday.ts, app/subscriber/src/features/commentary/utils/styled/DetermineContentIcon.tsx, app/subscriber/src/features/commentary/utils/styled/index.ts, app/subscriber/src/features/home/Home.tsx, app/subscriber/src/features/home/utils/DetermineToneIcon.tsx, app/subscriber/src/features/landing/Landing.tsx, app/subscriber/src/features/landing/styled/Landing.tsx
In this PR:
- Commentary box will populate with commentary items
- If it is a weekday it will show commentary from the last 3 hours
- If it is a weekend it will show commentary from the last 5 hours
- Display content type indicator depending on type of content
- Navigate to view on click of a headline
=> Commentary box

api/net/Areas/Editor/Controllers/ContentController.cs
TNO-1048: DB Concurrency Errors
=> TNO-1048 (content related updates)

libs/net/core/Extensions/StringExtensions.cs
TNO-1191: Pls add paragraph spacing to ingested content from Globe & Mail
=> TNO-1191 updates

libs/net/core/Extensions/StringExtensions.cs
TNO-1191: Pls add paragraph spacing to ingested content from Globe & Mail
=> TNO-1191 updates #2

app/editor/src/features/content/morning-reports/MorningReports.tsx, app/editor/src/features/content/morning-reports/MorningReportsFilter.tsx, app/editor/src/features/content/morning-reports/components/AdvancedFilter.tsx, app/editor/src/features/content/morning-reports/utils/makeFilter.ts, app/editor/src/store/hooks/editor/useContent.ts, app/editor/src/store/slices/content/contentSlice.ts, app/editor/src/store/slices/content/interfaces/IContentState.ts, app/editor/src/store/slices/content/useContentStore.ts
Extracted the shared advanced filter so that the Morning Papers works correctly.
=> Fix morning papers filter

app/editor/src/components/layout/DefaultLayout.tsx, app/editor/src/components/layout/styled/Layout.tsx, app/editor/src/css/_colors.scss, app/editor/src/css/_variables.module.scss
TNO-1172: Colour Code Each Environment
=> Fix TNO-1172

api/net/Areas/Editor/Controllers/LookupController.cs, libs/net/dal/Services/Interfaces/IUserService.cs, libs/net/dal/Services/UserService.cs, libs/net/dal/TNO.DAL.csproj
TNO-1234: [QA] remove subscribers from Other drop-down list
=> Fix TNO-1234

openshift/kustomize/tekton/base/triggers/listener.yaml
Having trouble testing this.. this is the only difference b/w the subscriber and editor I could find..
=> Add subscriber pipeline

app/subscriber/src/features/content/view-content/ViewContent.tsx, app/subscriber/src/features/home/Home.tsx
Putting up some little fixes, while figuring out file references for frontpages on the list view.
=> TNO-1238: Fix byline

services/net/reporting/Dockerfile
=> Fix reporting service image

services/net/indexing/IndexingManager.cs
This resolves the issue where published content is not correctly updated in the editor Elasticsearch index.
=> TNO-1252 Fix indexing published content

app/editor/src/features/router/AppRouter.tsx
Fixing editor permission to view content.
=> Fix editor permission

app/editor/src/features/content/form/ImageSection.tsx
TNO-1267: exclude front page types from the scoring rules
=> Fix TNO-1267

app/editor/src/features/content/tool-bar/sections/filter/DateRangeSection.tsx, app/editor/src/features/content/tool-bar/sections/filter/styled/DateRangeSection.tsx
=> TNO-1161 Fix date filter icon

app/editor/src/features/content/morning-papers/components/ReportActions.tsx
TNO-1265: Morning Papers Default Commentary Expiry Value
=> Fix TNO-1265

app/editor/src/features/content/morning-papers/MorningReports.tsx, app/editor/src/features/content/morning-papers/constants/columns.tsx
TNO-1264: Add Open in New Tab on the Morning Papers
=> Fix TNO-1264

libs/npm/core/src/components/toggle-group/ToggleGroup.tsx
TNO-1080: [QA] when selecting My Content, I don't want the 'Other' List of Other Users Drop Down to display
=> Fix TNO-1080

app/subscriber/src/App.tsx, app/subscriber/src/features/content/view-content/ViewContentToolbar.tsx, app/subscriber/src/features/content/view-content/constants/ActionNames.ts, app/subscriber/src/features/content/view-content/constants/index.ts, app/subscriber/src/features/content/view-content/styled/ViewContentToolbar.tsx, app/subscriber/src/features/home/Home.tsx
Add new hover states, tooltips, and active sate to the action toolbar.
=> Update action buttons

app/subscriber/src/features/home/Home.tsx, libs/net/models/Areas/Services/Models/Content/ContentModel.cs
Source now included in Elastic Search return, and as such the full name is shown for the grouped headers.
=> TNO-1237: Source name not code

app/editor/src/features/admin/topic-score-rules/validation/TopicScoreRuleSchema.ts, app/editor/src/features/content/validation/ContentFormSchema.ts, libs/npm/core/src/hooks/api-editor/editor/index.ts, libs/npm/core/src/hooks/api-editor/editor/useApiAnonAlerts.ts, libs/npm/core/src/hooks/api-editor/validation/AdvancedScheduleSchema.ts, libs/npm/core/src/hooks/api-editor/validation/AuditColumnsSchema.ts, libs/npm/core/src/hooks/api-editor/validation/ScheduleSchema.ts, libs/npm/core/src/hooks/api-subscriber/index.ts, libs/npm/core/src/hooks/api-subscriber/useApiAlerts.ts, libs/npm/core/src/hooks/index.ts
TNO-1175: Upgrade Yup Package Version
=> TNO-1175 updates

api/net/Areas/Services/Controllers/ContentController.cs, api/net/Program.cs, libs/net/services/Helpers/ApiService.cs
Adding additional error log information to debug Content Service errors.
=> TNO-474 Debug Content Service Issue

libs/net/entities/Models/NotificationFilter.cs, libs/net/entities/Validation/NotificationValidator.cs
TNO-1201: Convert Notification Filter from JSON to Code
=> Fix TNO-1201

api/net/Areas/Editor/Controllers/ContentController.cs, api/net/Areas/Subscriber/Controllers/ContentController.cs, libs/net/dal/Services/ContentService.cs, libs/net/dal/Services/Interfaces/IContentService.cs
Let me know if this makes sense @Fosol, can also make a separate service for the Subscriber App that only hits the published index if that is preferred
=> Published Index

app/editor/src/features/content/morning-papers/components/ContentFilter.tsx
TNO-1287: [QA] Morning Papers screen: fix punctuation. Add apostrophe in Today's
=> Fix TNO-1287

app/editor/src/features/admin/actions/ActionFilter.tsx, app/editor/src/features/admin/actions/ActionList.tsx, app/editor/src/features/admin/connections/ConnectionFilter.tsx, app/editor/src/features/admin/connections/ConnectionList.tsx, app/editor/src/features/admin/contributors/ContributorFilter.tsx, app/editor/src/features/admin/contributors/ContributorList.tsx, app/editor/src/features/admin/data-locations/DataLocationFilter.tsx, app/editor/src/features/admin/data-locations/DataLocationList.tsx, app/editor/src/features/admin/ingest-types/IngestTypeFilter.tsx, app/editor/src/features/admin/ingest-types/IngestTypeList.tsx, app/editor/src/features/admin/ingests/IngestFilter.tsx, app/editor/src/features/admin/ingests/IngestList.tsx, app/editor/src/features/admin/licenses/LicenseFilter.tsx, app/editor/src/features/admin/licenses/LicenseList.tsx, app/editor/src/features/admin/products/ProductFilter.tsx, app/editor/src/features/admin/products/ProductList.tsx, app/editor/src/features/admin/reports/ReportFilter.tsx, app/editor/src/features/admin/reports/ReportList.tsx, app/editor/src/features/admin/series/SeriesFilter.tsx, app/editor/src/features/admin/series/SeriesList.tsx, app/editor/src/features/admin/sources/SourceFilter.tsx, app/editor/src/features/admin/sources/SourceList.tsx, app/editor/src/features/admin/tags/TagFilter.tsx, app/editor/src/features/admin/tags/TagList.tsx, app/editor/src/features/admin/topics/TopicFilter.tsx, app/editor/src/features/admin/topics/TopicList.tsx
Adding filters to all the admin pages.
=> TNO-1318 Add admin filters

openshift/kustomize/postgres/crunchy/README.md, openshift/kustomize/postgres/crunchy/base/deploy.yaml, openshift/kustomize/tekton/base/tasks/buildah.yaml, openshift/kustomize/tekton/base/tasks/db-migration-conditional.yaml, openshift/kustomize/tekton/base/tasks/db-migration.yaml, openshift/kustomize/tekton/base/tasks/elastic-migration.yaml, openshift/kustomize/tekton/base/tasks/pipeline-wait.yaml
1) Crunchy DB Image fix
2) Reduce quotas as we are not utilizing limits or request capacity even at db migration stage.
3) Removed bash tracing from various DB & elastic pipelines.
=> Tno crunchy fix

app/editor/src/features/content/list-view/components/tool-bar/filter/ShowOnlySection.tsx
TNO-1306: Clearing "Show Only" filter in Select Box Doesn't work
=> Fix TNO-1306

app/editor/src/features/content/list-view/styled/ContentListView.tsx
TNO-1298: [QA] display more content on home page (more rows)
=> Fix TNO-1298

app/subscriber/src/features/home/constants/columns.tsx
From QA, add space between `section: page`
=> TNO-1320: Add space between column and page

api/net/Areas/Admin/Controllers/ReportController.cs, app/editor/src/components/formik/form/FormikForm.tsx, app/editor/src/features/admin/reports/ReportFilter.tsx, app/editor/src/features/admin/reports/ReportForm.tsx, app/editor/src/features/admin/reports/constants/index.ts, app/editor/src/features/admin/reports/constants/subscriberColumns.tsx, app/editor/src/features/admin/reports/styled/ReportForm.tsx, libs/net/dal/Services/ReportService.cs, libs/net/entities/UserReport.cs, libs/net/models/Areas/Admin/Report/ReportModel.cs
Providing a way for administrators to add/remove which users are subscribing to a report.
=> TNO-1217 - Add admin report subscribers

app/subscriber/src/features/home/styled/Home.tsx
As per spec provided by Bobbi.
=> TNO-1293: Adjust font size for table header

app/subscriber/src/features/home/styled/Home.tsx
Request size was smaller than appears on Adobe XD. Adjustment made.
=> Adjustment to TNO-1293

app/subscriber/src/features/home/Home.tsx, app/subscriber/src/features/home/constants/columns.tsx
- Section/page will now only show on print content as intended
=> TNO-1289: Page/section should only show on print

app/subscriber/src/features/my-minister/MyMinister.tsx, libs/net/dal/Services/ContentService.cs
- grab from local storage rather than making another request
- adjustment to the elastic search query
=> My Minister adjustment

app/subscriber/src/components/form/tags/Tags.tsx, app/subscriber/src/features/content/view-content/ViewContent.tsx, app/subscriber/src/features/content/view-content/ViewContentToolbar.tsx
Adds the selected tags to the given piece of content on the subscriber site,
=> TNO-1290: Display tags on subscriber site

services/net/notification/NotificationManager.cs
TNO-1291: Templating Errors Breaks Service
=> Fix TNO-1291

libs/net/models/Areas/Subscriber/Models/Content/ContentModel.cs, libs/net/models/Areas/Subscriber/Models/Content/FileReferenceModel.cs
Must have stopped working when I switched from the editor endpoints and created subscriber endpoints
=> TNO-1279: A/V Content not displaying

app/editor/src/components/wysiwyg/Wysiwyg.tsx, app/editor/src/features/content/form/components/wysiwyg/Wysiwyg.tsx, app/subscriber/src/components/form/wysiwyg/Wysiwyg.tsx, services/net/syndication/SyndicationAction.cs, services/net/transcription/TranscriptionManager.cs
TNO-1313: Ingest Content Invalid Story Text
=> Fix TNO-1313

app/editor/src/features/content/form/ContentForm.tsx, app/editor/src/features/content/form/components/time-log/TimeLogSection.tsx, app/editor/src/features/content/validation/ContentFormSchema.ts
TNO-1277: [QA] make Prep time mandatory on Radio TV input form
=> Fix TNO-1277

app/editor/src/features/home/Home.tsx, app/editor/src/features/home/index.ts, app/subscriber/src/features/landing/Landing.tsx, app/subscriber/src/features/todays-commentary/TodaysCommentary.tsx, app/subscriber/src/features/todays-commentary/index.ts, app/subscriber/src/features/todays-commentary/styled/TodaysCommentary.tsx, app/subscriber/src/features/todays-commentary/styled/index.ts
This PR includes the Today's Commentary functionality. 
- Today's commentary now functional by selecting it from the left hand navigation menu
- Defaults to today's date
- Date for commentary is adjustable via the date filter located at the top of the table
=> TNO-1383: Today's Commentary View

app/editor/src/features/admin/topics/styled/TopicList.tsx
TNO-1368: [QA] Pls increase height of Type dropdown on Topic/Event of the Day management page
=> TNO-1368: [QA] Pls increase height of Type dropdown on Topic/Event of the Day management page

libs/net/services/Actions/Managers/IngestActionManager`.cs, libs/net/services/Actions/Managers/ServiceActionManager`.cs, libs/net/services/Interfaces/IServiceActionManager.cs, services/net/contentmigration/ContentMigrationAction.cs
- service can push back creationDate  of Last NewsItem migrated in run
=> feat: #tno-1324 - added ability to store config

services/net/syndication/SyndicationAction.cs
TNO-1366: [QA] CP News content does not display in Pacific Standard Time
=> Fix TNO-1366

api/net/Areas/Admin/Controllers/ReportController.cs, app/editor/src/features/admin/reports/ReportForm.tsx, app/editor/src/features/admin/reports/ReportSections.tsx, libs/net/dal/Migrations/1.0.27/Down/PreDown/00-Notification.sql, libs/net/dal/Migrations/20230612222140_1.0.28.Designer.cs, libs/net/dal/Migrations/20230612222140_1.0.28.cs, libs/net/entities/ReportInstanceContent.cs, libs/net/template/Extensions/ReportModelExtensions.cs, libs/net/template/Models/Reports/TemplateModel.cs
Resolving bugs within the new preview report functionality.
- Fixed bugs related to report sections
- Add new DB migration `1.0.28`
=> TNO-937 Fix Preview Report

app/subscriber/src/components/search-with-logout/SearchWithLogout.tsx, app/subscriber/src/components/search-with-logout/styled/SearchWithLogout.tsx, app/subscriber/src/features/router/AppRouter.tsx, app/subscriber/src/features/search-page/SearchPage.tsx, app/subscriber/src/features/search-page/styled/SearchPage.tsx, app/subscriber/src/features/search-page/styled/index.ts, app/subscriber/src/features/search-page/utils/index.ts, app/subscriber/src/features/search-page/utils/trimWords.ts
TNO-1386 is to add a View Media button to watch videos "in line" on the search results page. This search results page has not been made yet so this PR is capturing that work. 
Will release part (2/2) in a subsequent PR. Splitting of functionality to keep things easier.
In this PR:
- users can now search with a keyword
- after searching the user will be redirected to a new page
- the user may see a quick summary and overview of the content and click the headline to navigate to the view screen
=> TNO-1386: (1/2) Create search result page

app/subscriber/src/components/search-with-logout/SearchWithLogout.tsx, app/subscriber/src/features/search-page/SearchPage.tsx, app/subscriber/src/features/search-page/player/Player.tsx, app/subscriber/src/features/search-page/player/styled/Player.tsx, app/subscriber/src/features/search-page/player/styled/index.ts, app/subscriber/src/features/search-page/styled/SearchPage.tsx
This PR includes the ability to click "PLAY MEDIA" in the search view when a piece of content has the appropriate file references. Doing so will open a media player on the right hand side of the screen, while also indicating that it is playing on the button that previously said PLAY MEDIA.
Bugs fixed 🐛 : 
- can now scroll on search results when contents expand pass screen view
=> TNO-1386: (2/2 )Add media player to view

app/subscriber/src/components/sidebar/SelectableMenuItems.tsx
Sidebar now functioning as it did prior to the bug, and secondary menu button works as intended.
=> TNO-1382: Bug fix for side bar

app/subscriber/src/features/search-page/SearchPage.tsx, app/subscriber/src/features/search-page/styled/SearchPage.tsx
Fixing minor issues with layout on adjusted screen sizes
=> Fix layout of media and search

app/subscriber/src/features/front-pages/styled/FrontPages.tsx, app/subscriber/src/features/landing/styled/Landing.tsx, app/subscriber/src/features/search-page/player/Player.tsx, app/subscriber/src/features/search-page/utils/index.ts, app/subscriber/src/features/search-page/utils/stripHtml.ts
This PR addresses some styling issues for the landing page, as well as the media preview.
=> Styling fixes

app/subscriber/src/components/search-with-logout/SearchWithLogout.tsx, app/subscriber/src/features/landing/Landing.tsx, app/subscriber/src/features/search-page/SearchPage.tsx, app/subscriber/src/features/search-page/player/Player.tsx, app/subscriber/src/features/search-page/player/styled/Player.tsx, app/subscriber/src/features/search-page/styled/SearchPage.tsx
This PR includes the following bug fixes 🐛:
- back button on view content now goes back to the user's last page rather than the home view
- exit button added to search media player
- clicking play media will no longer close the media player if it is already open, it will pop the new content into it
- you can now hit enter in the search bar to trigger the search
=> Handful of bugs

app/subscriber/src/components/layout/constants/SidebarMenuItems.tsx, app/subscriber/src/features/landing/Landing.tsx, app/subscriber/src/features/landing/styled/Landing.tsx, app/subscriber/src/features/search-page/SearchPage.tsx, app/subscriber/src/features/search-page/styled/SearchPage.tsx, app/subscriber/src/features/settings/MyMinisterSettings.tsx
In this PR:
- users have the ability to save their search and later view them
Please note this is based off ticket TNO-1385, not the new things Bobbi was showing today. There will be a further iteration soon.
=> TNO-1385: Iteration 1 of saving searches

services/net/syndication/SyndicationAction.cs
TNO-1366: [QA] CP News content does not display in Pacific Standard Time
=> TNO-1366 updates

api/net/Areas/Services/Controllers/ContentController.cs, services/net/content/Config/ContentMigrationOptions.cs, services/net/content/Config/ContentOptions.cs, services/net/content/ContentManager.cs, services/net/contentmigration/ContentMigrationAction.cs, services/net/contentmigration/sources/oracle/Entities/NewsItem.cs
* feat: tno-1329 - Tone and Topic mappping
- add new Topics at the ContentController
- changes as per PR feedback
=> feat: tno-1329 - Tone and Topic mappping (#833)

api/net/Areas/Admin/Controllers/TopicController.cs, app/editor/src/features/admin/topics/TopicList.tsx
TNO-1407: Event of the Day/Topics - confirmation to delete prompt
=> Fix TNO-1407

app/subscriber/src/features/content/view-content/ViewContent.tsx, app/subscriber/src/features/content/view-content/styled/ViewContent.tsx, app/subscriber/src/features/content/view-content/utils/WorkOrderStatus.tsx, app/subscriber/src/features/content/view-content/utils/findWorkOrder.ts, app/subscriber/src/features/content/view-content/utils/index.ts, app/subscriber/src/features/content/view-content/utils/isWorkOrderStatus.ts
This PR includes the functionality that allows subscribers to transcribe a video if it has not been transcribed already. Clearly my own instance of Azure is having some issues as seen by the text it has generated..
However, you can see that after the transcription is appended to the body the application will add a new section for the transcription as was discussed with Bobbi on Friday.
=> TNO-1388: Add ability for subscriber to transcribe

api/net/Areas/Services/Controllers/ContentController.cs, services/net/content/Config/ContentMigrationOptions.cs, services/net/content/ContentManager.cs, services/net/contentmigration/ContentMigrationAction.cs, services/net/contentmigration/migrators/ClipMigrator.cs, services/net/contentmigration/migrators/ContentMigrator.cs, services/net/contentmigration/migrators/ImageMigrator.cs, services/net/contentmigration/migrators/PaperMigrator.cs
- existing tags will be mapped
- new tags will be added with a dummy name to prompt editors to fix them
=> feat: tno-1330 - Import Tags found in Summary

api/net/Areas/Services/Controllers/ContentController.cs, libs/net/kafka/Models/Action.cs, libs/net/kafka/Models/ContentBase.cs, services/net/content/Config/ContentMigrationOptions.cs, services/net/content/ContentManager.cs, services/net/contentmigration/Config/ActionType.cs, services/net/contentmigration/Config/ContentMigrationOptions.cs, services/net/contentmigration/ContentMigrationAction.cs, services/net/contentmigration/appsettings.json, services/net/contentmigration/migrators/ClipMigrator.cs, services/net/contentmigration/migrators/ContentMigrator.cs, services/net/contentmigration/migrators/ImageMigrator.cs, services/net/contentmigration/migrators/PaperMigrator.cs
- only map tags which are present in MMIA
- use configuration+enum to map Tag names
=> feat: #tno-1327 - capture migrated content Actions

app/subscriber/src/features/content/view-content/ViewContent.tsx
No changes visible to users if you are looking Carolynn :)
Just clearing up some console warnings!
=> TNO-1427: Cleanup console warnings

app/subscriber/src/features/landing/Landing.tsx, app/subscriber/src/features/top-stories/TopStories.tsx, app/subscriber/src/features/top-stories/index.ts, app/subscriber/src/features/top-stories/styled/TopStories.tsx, app/subscriber/src/features/top-stories/styled/index.ts
This PR adds the ability for users to browse "Top Stories" by date. Similar to Today's Commentary. Getting this in before my styling tweaks to make sure everything is behaving.
=> TNO-1415: Top stories

app/subscriber/src/features/my-minister/MyMinister.tsx, app/subscriber/src/features/search-page/SearchPage.tsx
Bug fix for:
- navigating to my minister view before selecting minister would cause an undefined error
=> Little bug tweaks for multi minister

app/subscriber/src/components/search-with-logout/SearchWithLogout.tsx, app/subscriber/src/components/search-with-logout/styled/SearchWithLogout.tsx, app/subscriber/src/features/commentary/styled/Commentary.tsx, app/subscriber/src/features/front-pages/FrontPages.tsx, app/subscriber/src/features/front-pages/styled/FrontPages.tsx, app/subscriber/src/features/home/Home.tsx, app/subscriber/src/features/home/constants/columns.tsx, app/subscriber/src/features/landing/styled/Landing.tsx
In this PR:
- table columns (namely headline) now adjust based on window width 
- search bar looks better in mobile view
- content can be on full display on mobile device as small as the iPhone SE
- better responsiveness when adjusting the screen size 
<hr />
See mobile view below:
=> TNO-1426: App responsiveness

app/subscriber/src/features/my-minister/MyMinister.tsx
Quick little bug fix for an issue when selecting `myMinisters`
=> Undefined myMinisters bug

api/net/Areas/Services/Controllers/IngestController.cs, app/editor/src/features/admin/ingests/configurations/DbMigration.tsx, libs/net/services/Actions/Managers/IngestActionManager`.cs, libs/net/services/Actions/Managers/ServiceActionManager`.cs, libs/net/services/Helpers/ApiService.cs, libs/net/services/Interfaces/IApiService.cs, libs/net/services/Interfaces/IServiceActionManager.cs, services/net/contentmigration/ContentMigrationAction.cs
- created new endpoint for updating ingest configuration
- refactored existing endpoint to match name
- tweaked date format for storing ingest filter dates
=> fix: #tno-1473 - fixed config update

app/subscriber/src/features/home/constants/columns.tsx
Few little fixes for screen space on mobile
=> Minor css tweaks

app/subscriber/src/components/sidebar/SelectableMenuItems.tsx
Bug fix, sidebar was rendering blank div causing a misalignment with the icon and labels.
=> TNO-1435: Adjust alignment of side menu

libs/net/kafka/Models/ContentBase.cs, libs/net/kafka/Models/LabelModel.cs, libs/net/models/Areas/Services/Models/Content/ContentLabelModel.cs, services/net/content/ContentManager.cs, services/net/syndication/SyndicationAction.cs
- Syndicated content has Categories
- They should be assigned to Labels instead of Tags
=> fix: tno-1497 - re-mapped Categories to Labels

api/net/Areas/Services/Controllers/ContentController.cs
TNO-1209: Create Razor Template for Morning Report
=> TNO-1209 updates for missing images

app/editor/src/features/content/form/components/upload/Upload.tsx
TNO-1471: [QA] Thumbnails are missing from front page images editors screen
=> TNO-1471: [QA] Thumbnails are missing from front page images editors screen 

libs/net/kafka/Models/ContentBase.cs, libs/net/kafka/Models/TimeTrackingModel.cs, libs/net/models/Areas/Admin/TimeTracking/TimeTrackingModel.cs, libs/net/models/Areas/Services/Models/Content/ContentModel.cs, libs/net/models/Areas/Services/Models/Content/ContentTimeTrackingModel.cs, services/net/content/ContentManager.cs, services/net/contentmigration/Config/ContentMigrationOptions.cs, services/net/contentmigration/ContentMigrationAction.cs, services/net/contentmigration/Extensions/NewsItemExtensions.cs, services/net/contentmigration/migrators/ClipMigrator.cs, services/net/contentmigration/migrators/ContentMigrator.cs, services/net/contentmigration/migrators/ImageMigrator.cs, services/net/contentmigration/migrators/PaperMigrator.cs
- created new models
- mapped value from TNO db "NUMBER2"
- fixed creation date time mapping
=> feat: #tno-1404 - time and effort now migrated

libs/net/dal/Migrations/1.0.37/Up/PostUp/00-Report.sql
TNO-1476: [QA] Pls check timestamp for report preview: needs to display in Pacific Standard time
=> TNO-1476 (Fix a compile issue)

services/net/filemonitor/FilemonitorAction.cs
- filemonitor service update similar to syndication
=> fix: #tno-1404 - fixed label-tag mismatch

libs/net/core/Extensions/LinqExtensions.cs, libs/net/dal/Configuration/ContentConfiguration.cs, libs/net/dal/Migrations/20230707202614_1.0.42.Designer.cs, libs/net/dal/Migrations/20230707202614_1.0.42.cs, libs/net/entities/Content.cs, libs/net/kafka/Models/SourceContent.cs, libs/net/models/Areas/Editor/Models/Content/ContentModel.cs, libs/net/models/Areas/Services/Models/Content/ContentModel.cs, libs/net/services/Actions/IngestAction.cs, services/net/capture/CaptureAction.cs, services/net/clip/ClipAction.cs, services/net/contentmigration/ContentMigrationAction.cs, services/net/contentmigration/Extensions/NewsItemExtensions.cs, services/net/contentmigration/migrators/ClipMigrator.cs, services/net/contentmigration/migrators/ContentMigrator.cs, services/net/contentmigration/migrators/IContentMigrator.cs, services/net/contentmigration/migrators/ImageMigrator.cs, services/net/contentmigration/migrators/PaperMigrator.cs, services/net/filemonitor/FilemonitorAction.cs, services/net/image/ImageAction.cs, services/net/syndication/SyndicationAction.cs
- changed from using various different things in different ingests
- ingests will use some variation of a has on Source+Title+PublishDate
- tweaked filters on when to update contentreference if it is found
- if a contentreference is found it may be a duplicate based on the has as opposed to reimporting the same content
=> feat: #tno-1530 - change UID on content

api/net/Areas/Admin/Controllers/ReportController.cs, libs/net/template/Models/Reports/ReportSectionModel.cs, libs/net/template/Models/Reports/TemplateModel.cs, services/net/reporting/ReportingManager.cs
TNO-1534: Missing image in Morning Report & Frontpage Report
=> TNO-1534: Missing image in Reports

app/subscriber/src/features/my-minister/MyMinister.tsx
Unable to recreate issue locally, but I think this should do the trick.
=> Bug fix - My Minister

app/subscriber/src/features/my-minister/MyMinister.tsx
Frustrating one as it is not occurring locally still... will have to see how this behaves in dev
=> My Minister bug

libs/net/dal/Migrations/1.0.45/Up/PostUp/00-Report.sql
TNO-1476: [QA] Pls check timestamp for report preview: needs to display in Pacific Standard time
=> TNO-1476 updates

openshift/kustomize/services/build/base/contentmigration.yaml, openshift/kustomize/services/build/base/kustomization.yaml, openshift/kustomize/services/contentmigration/base/config-map.yaml, openshift/kustomize/services/contentmigration/base/deploy.yaml, openshift/kustomize/services/contentmigration/base/kustomization.yaml, openshift/kustomize/services/contentmigration/base/service.yaml, openshift/kustomize/services/contentmigration/overlays/dev/kustomization.yaml, openshift/kustomize/services/contentmigration/overlays/prod/kustomization.yaml, openshift/kustomize/services/contentmigration/overlays/test/kustomization.yaml, services/net/contentmigration/Config/ContentMigrationOptions.cs, services/net/contentmigration/Config/OracleConnectionSettings.cs, services/net/contentmigration/ContentMigrationAction.cs, services/net/contentmigration/appsettings.json, services/net/contentmigration/migrators/ContentMigrator.cs, services/net/contentmigration/sources/oracle/MigrationSourceContext.cs, services/net/contentmigration/sources/oracle/Services/OracleConnectionStringHelper.cs, services/net/contentmigration/sources/oracle/Services/ServiceCollectionExtensions.cs
- added method for utilizing the db config from the ingest
=> feat: #tno-1490 - first pass at openshift config

app/subscriber/src/components/sidebar/CustomSidebar.tsx, app/subscriber/src/components/sidebar/advanced-search/AdvancedSearch.tsx, app/subscriber/src/components/sidebar/advanced-search/constants/SubMediaGroups.ts, app/subscriber/src/components/sidebar/advanced-search/constants/index.ts, app/subscriber/src/components/sidebar/advanced-search/index.ts, app/subscriber/src/components/sidebar/advanced-search/styled/AdvancedSearch.tsx, app/subscriber/src/components/sidebar/advanced-search/styled/index.ts, app/subscriber/src/features/landing/styled/Landing.tsx
Finally dug this out of my stash, was a bit of a nightmare.
This is the *intro* PR for the UI components before made functional with a new ticket this sprint. Leaving the old search bar in the meantime as well. A few questions for Bobbi as well based off the mockup and what happens when clicking certain elements.
Would also like to add some smoother animations; however, that can be down the road when the barebones is complete.
=> TNO-1507: UI for advanced search

app/editor/src/features/content/form/ContentStoryForm.tsx, app/editor/src/features/content/form/MediaSummary.tsx
TNO-1543: Content Image Does Not Display Correctly
=> TNO-1543: Content Image Does Not Display Correctly

app/subscriber/src/components/layout/constants/SidebarMenuItems.tsx
Very small PR:
- adds navigation item to sidebar that allows users to select "Folders"
- just UI for this ticket, functionality contained in upcoming tickets
=> TNO-1551: Add folders navigation

libs/net/dal/Configuration/ContentConfiguration.cs, libs/net/dal/Migrations/20230724165029_1.0.50.Designer.cs, libs/net/dal/Migrations/20230724165029_1.0.50.cs
=> fix: #tno-1492 - increased column size for Page

app/editor/src/features/content/form/components/upload/Upload.tsx, app/editor/src/features/content/form/components/upload/styled/Upload.tsx
- switched usage of video tag to audio tag
=> fix: #tno-1130 - fix audo clip layout in Editor

app/subscriber/src/features/settings/MyMinisterSettings.tsx, app/subscriber/src/features/settings/styled/MyMinisterSettings.tsx
- also make minister name bold
=> fix: #tno-1576 - hide aliases on my ministers page

app/subscriber/src/features/content/view-content/ViewContent.tsx
- was only search for the value stored in preferences.myMinisters
- retrieve the minister record and then search for name AND aliases
=> fix: #tno-1582 - aliases not showing up

app/editor/src/features/admin/topics/TopicFilter.tsx, app/editor/src/features/admin/topics/TopicList.tsx, app/editor/src/features/admin/topics/styled/TopicList.tsx, app/editor/src/features/admin/topics/useColumns.tsx, libs/npm/core/src/components/table/FlexboxTable.tsx
TNO-1472: [QA] saving new Topics/Event of the Day is much too slow
=> TNO-1472 updates based on the latest prototype

app/editor/src/features/admin/evening-overview/overview-section/OverviewSection.tsx, app/subscriber/src/components/sidebar/advanced-search/AdvancedSearch.tsx, app/subscriber/src/components/sidebar/advanced-search/components/MediaSection.tsx, app/subscriber/src/components/sidebar/advanced-search/components/SentimentSection.tsx, app/subscriber/src/components/sidebar/advanced-search/constants/ToggleOptions.ts, app/subscriber/src/components/sidebar/advanced-search/constants/index.ts, app/subscriber/src/components/sidebar/advanced-search/utils/queryToState.ts
In this PR:
- av overview will re-fetch on save to account for sort order changes that were previously causing errors
- the advanced search bar is now in sync with the url
- a user can send a url to another user and get their search in the same state
- can save advanced search
=> TNO-1587, 1508: Bugs

docker-compose.yml, services/net/contentmigration/Config/OracleConnectionSettings.cs, services/net/contentmigration/appsettings.Development.json, services/net/contentmigration/appsettings.json, services/net/contentmigration/sources/oracle/Configuration/NewsItemConfiguration.cs, services/net/contentmigration/sources/oracle/MigrationSourceContext.cs, tools/oracle-instantclient/Dockerfile
- needed to introduce schema as an attribute for oracle
- allso added setup for running an oracle client for testing
=> feat: #tno-1558 - connect to PROD oracle instance

app/editor/src/features/content/form/ContentForm.tsx
TNO-1451: [UX/QA] Fine Tuning workflow for adding multiple TV/audio files
=> TNO-1451 updates

app/editor/src/features/admin/ingests/configurations/DbMigration.tsx, services/net/contentmigration/ContentMigrationAction.cs
- reduced size of minimum ingest window
=> fix: #tno-1655 - fixed path on migrated file

app/editor/src/features/admin/topics/TopicList.tsx, app/editor/src/features/admin/topics/styled/TopicList.tsx, app/editor/src/features/admin/topics/useColumns.tsx
TNO-1472: [QA] saving new Topics/Event of the Day is much too slow
=> TNO-1472 (a few more updates)

api/net/appsettings.json, app/editor/nginx/default.conf, network/nginx/config/default.conf
TNO-1496: File Upload and Streaming Out of Memory Exception
=> TNO-1496 (updates for larger files)

app/editor/src/features/admin/charts/ChartTemplateFormOptions.tsx, app/editor/src/features/admin/ingests/IngestSettings.tsx, app/editor/src/features/admin/ingests/configurations/FrontPage.tsx, docker-compose.yml, libs/net/dal/Migrations/Initial/Up/PostUp/00-Connection.sql, libs/net/dal/Migrations/Initial/Up/PostUp/02-Ingest.sql, libs/net/template/ReportEngine.cs, openshift/kustomize/api/base/route-editor.yaml, openshift/kustomize/api/base/route-subscriber.yaml, openshift/kustomize/api/overlays/dev/kustomization.yaml, openshift/kustomize/api/overlays/prod/kustomization.yaml, openshift/kustomize/api/overlays/test/kustomization.yaml, openshift/kustomize/app/editor/base/route.yaml, openshift/kustomize/app/editor/overlays/dev/kustomization.yaml, openshift/kustomize/app/editor/overlays/prod/kustomization.yaml, openshift/kustomize/app/editor/overlays/test/kustomization.yaml, openshift/kustomize/app/subscriber/base/route.yaml, openshift/kustomize/app/subscriber/overlays/dev/kustomization.yaml, openshift/kustomize/app/subscriber/overlays/prod/kustomization.yaml, openshift/kustomize/app/subscriber/overlays/test/kustomization.yaml, services/net/image/ImageAction.cs
Updated Image Service to be able to connect to SFTP with username and password.  Also updated configuration options to handle more complex file name patterns.
Updated Infrastructure as Code related to HTTP routes to fix the TEST environment.
- https://test.mmia.gov.bc.ca
- https://test.editor.mmia.gov.bc.ca
Fixed bug in Chart Template configuration.
=> TNO-1315 Fix test env domain

services/net/contentmigration/migrators/PaperMigrator.cs
did a stupid thing and changed it and didnt rebuild.  introduced a syntax error
=> fix: #tno-1662 - fixed code touched at last second

libs/net/kafka/Models/ContentBase.cs, services/net/content/ContentManager.cs, services/net/contentmigration/ContentMigrationAction.cs, services/net/contentmigration/Extensions/NewsItemExtensions.cs, services/net/contentmigration/migrators/ClipMigrator.cs, services/net/contentmigration/sources/oracle/Entities/NewsItem.cs
- Tone to be fixed seperately
- Fixed issue with confusing date & properties on NewsItem object
- Series had never been used before by the ingestion service so it had to be plumbed in
=> fix: #TNO-1657 - fixed timestamp and program/show

services/net/contentmigration/ContentMigrationAction.cs, services/net/contentmigration/migrators/ClipMigrator.cs, services/net/contentmigration/migrators/ContentMigrator.cs, services/net/contentmigration/migrators/IContentMigrator.cs, services/net/contentmigration/migrators/ImageMigrator.cs, services/net/contentmigration/migrators/PaperMigrator.cs
timezone was not being set on date before converting to UTC
=> fix: #tno-1657 - fixed incorrect timezone issue

app/subscriber/src/features/my-folders/MyFolders.tsx
TNO-1630: Create New Error/Validation
=> TNO-1630: Create New Error/Validation

services/net/contentmigration/migrators/ClipMigrator.cs, services/net/contentmigration/migrators/ImageMigrator.cs, services/net/contentmigration/migrators/PaperMigrator.cs
odd behavior in dev environment needs more logging
=> fix: #tno-1657 - added logging for time conversion

services/net/contentmigration/ContentMigrationAction.cs, services/net/contentmigration/migrators/ClipMigrator.cs, services/net/contentmigration/migrators/ContentMigrator.cs, services/net/contentmigration/migrators/IContentMigrator.cs, services/net/contentmigration/migrators/ImageMigrator.cs, services/net/contentmigration/migrators/PaperMigrator.cs
- split out the filter for Print vs Online
- PrintContent now limited to records with any of these Types - { "Newspaper", "Regional" }
- Story now limited to records with any of these Types - { "CP News", "Internet" }
=> fix: #tno-1682 - updated filters

services/net/contentmigration/appsettings.json
- "Global News Okanagon RSS" mapped to "BC 1"
- "Global News RSS" mapped to "BC 1"
=> feat: #tno-1684 - added additional mappings

app/editor/src/features/admin/av-overviews/EditBroadcastDetails.tsx, app/editor/src/features/admin/series/SeriesForm.tsx, app/editor/src/features/reports/av-overview/EditBroadcastDetails.tsx
- all labels using "Series" now set to "Show/Program"
=> feat: #tno-1590 - updated Series labels

openshift/kustomize/services/contentmigration/base/deploy.yaml
=> feat: #tno-1625 - created new kustomize config

app/subscriber/src/features/search-page/SearchPage.tsx
One bug found in advanced search - more to come
=> Advanced search

app/subscriber/src/components/layout/DefaultLayout.tsx
TNO-1599: Unauthorized Users should be sent to a separate welcome page
=> TNO-1599 updates

openshift/kustomize/tekton/base/tasks/db-migration-conditional.yaml, openshift/kustomize/tekton/base/tasks/db-migration.yaml
- updated oc run command to use --overrides
- added memory config to override
- switched from passing env variables to configmap
=> fix: #tno-1697 - updated db migration tasks

services/net/contentmigration/ContentMigrationAction.cs
-  set `creationDateOfLastImport` when there are no more records to import prior to filter end date. log this
- log when the ingest finishes "early" because it hit the `maxmaxIngestedRecords`
- log how many records were ingested by a "normal" ingest completion
=> fix: #tno-1709 - fixed issues in content migration

openshift/kustomize/services/contentmigration-historic/base/config-map.yaml, openshift/kustomize/services/contentmigration-historic/base/deploy.yaml, openshift/kustomize/services/contentmigration-historic/base/service.yaml, openshift/kustomize/services/contentmigration-historic/overlays/dev/kustomization.yaml, openshift/kustomize/services/contentmigration-historic/overlays/prod/kustomization.yaml, openshift/kustomize/services/contentmigration-historic/overlays/test/kustomization.yaml
=> fix: #tno-1711 - renamed service in yaml

services/net/contentmigration/ContentMigrationAction.cs
created a quick lookup for contenttype based on file extension.  Based on the source data this should fix the error being seen in the logs
=> fix: #tno-1712 - added lookup for contenttype

api/net/Areas/Services/Controllers/ContentController.cs
- taken from the UploadFile method
=> fix: #tno-1714 - applied filter logic

services/net/contentmigration/ContentMigrationAction.cs
=> fix: #tno-1715 - exclude data with NULL Source

libs/net/elastic/Models/HitModel.cs, libs/net/elastic/TNOElasticClient.cs
A regression issue was introduced when sorting was added to Elasticsearch queries.  This PR resolves that issue.
=> Fixing Elasticsearch sort bug

libs/net/core/Extensions/JsonElementExtensions.cs, libs/net/dal/Migrations/1.0.54/Up/PostUp/02-Ingest.sql, libs/npm/core/src/components/table/interfaces/TableInternal.ts, services/net/contentmigration/ContentMigrationAction.cs, services/net/contentmigration/migrators/ContentMigrator.cs, services/net/contentmigration/migrators/IContentMigrator.cs
Resolved serialization issue with subscriber report endpoints.
=> Fix subscriber report model

openshift/kustomize/cron/base/config-map.yaml
seemingly the user context was being lost inside the call to rm which is odd
=> fix: #tno-1734 - tweaked bash script portion

openshift/kustomize/tekton/base/pipelines/buildah-all.yaml, openshift/kustomize/tekton/base/tasks/git-conditions.yaml, openshift/kustomize/tekton/base/triggers/dev/binding.yaml, openshift/kustomize/tekton/base/triggers/dev/ingress.yaml, openshift/kustomize/tekton/base/triggers/dev/listener.yaml, openshift/kustomize/tekton/base/triggers/template.yaml, openshift/kustomize/tekton/base/triggers/test/binding.yaml, openshift/kustomize/tekton/base/triggers/test/ingress.yaml, openshift/kustomize/tekton/base/triggers/test/listener.yaml
Added a pipeline and trigger for the `master` branch to build and deploy to the TEST environment.
Still need to do more testing on this to ensure I haven't broken the `dev` branch pipeline to the DEV environment.
=> TNO-1615 Add master pipeline

openshift/kustomize/services/content/base/kustomization.yaml, openshift/kustomize/services/content/overlays/dev-tno/kustomization.yaml, openshift/kustomize/services/content/overlays/dev/kustomization.yaml, openshift/kustomize/services/content/overlays/prod/kustomization.yaml, openshift/kustomize/services/content/overlays/test-tno/kustomization.yaml
- also updated some values in kustomization which were out of sync
- values in openshift hadnt been set back in the original yaml
=> feat: #tno-1763 - add TNO specific content service

app/subscriber/src/components/layout/constants/SidebarMenuItems.tsx
TNO-1722: Remove My Collections Menu
=> TNO-1722: Remove My Collections Menu

libs/net/dal/Migrations/1.0.64/Up/PostUp/00-EventSchedule.sql, openshift/kustomize/services/scheduler/base/config-map.yaml, openshift/kustomize/services/scheduler/base/deploy.yaml, openshift/kustomize/services/scheduler/base/kustomization.yaml, openshift/kustomize/services/scheduler/base/service.yaml, openshift/kustomize/services/scheduler/overlays/dev/kustomization.yaml, openshift/kustomize/services/scheduler/overlays/prod/kustomization.yaml, openshift/kustomize/services/scheduler/overlays/test/kustomization.yaml, openshift/kustomize/tekton/base/tasks/deploy-all.yaml, openshift/kustomize/tekton/base/triggers/dev/binding.yaml, openshift/kustomize/tekton/base/triggers/template.yaml, openshift/kustomize/tekton/base/triggers/test/binding.yaml
Updating Infrastructure as Code to include the Scheduler Service.
> Our TEST pipeline has a design issue.  It uses the same git script as the DEV pipeline.  The DEV pipeline only looks at the most recent commit to determine what has changed.  However, this of course isn't what we want when we run the TEST pipeline since there will always be more than a single commit merged into the `master` branch.  To work around this for now I've updated the pipeline trigger to build/deploy all components in TEST.
=> TNO-1723 Deploy scheduler

app/editor/src/features/admin/filters/FilterFormQuery.tsx, app/editor/src/features/admin/filters/utils/generateQuery.ts, app/editor/src/features/admin/filters/utils/generateSimpleQueryString.ts, app/editor/src/features/admin/filters/utils/index.ts
- now uses simple_query_string instead of multi_match
- made textbox much larger
- added some basic help
=> feat: #tno-1737 - changed keywords search

app/subscriber/src/features/commentary/Commentary.tsx, app/subscriber/src/features/commentary/styled/Commentary.tsx, app/subscriber/src/features/search-page/SearchPage.tsx
In this PR:
- max commentary size increased to max size
- scroll bar added if content list longer than 20em
- minor css adjustments for the spacing of the images and headline in the commentary box
=> TNO-1716: Change max commentary returned

app/subscriber/src/features/my-folders/MyFolders.tsx
TNO-1727: Create new Folder Validation
=> TNO-1727: Create new Folder Validation

libs/net/services/Actions/IngestAction.cs, libs/net/services/Actions/Managers/ServiceActionManager`.cs, libs/net/services/Actions/ServiceAction.cs, libs/net/services/Actions/ServiceActionResult.cs, libs/net/services/Interfaces/IIngestAction`.cs, libs/net/services/Interfaces/IServiceAction`.cs, services/net/capture/CaptureAction.cs, services/net/clip/ClipAction.cs, services/net/clip/ClipIngestActionManager.cs, services/net/command/CommandAction`.cs, services/net/command/CommandIngestActionManager`.cs, services/net/contentmigration/ContentMigrationAction.cs, services/net/filemonitor/FilemonitorAction.cs, services/net/image/ImageAction.cs, services/net/syndication/SyndicationAction.cs
- now returns an enum to signify a more specific result
=> feat: #tno-1773 - modified PerformActionAsync

app/subscriber/src/features/my-folders/MyFolders.tsx
TNO-1726: Confirm Deleting Folder
=> TNO-1726: Confirm Deleting Folder

app/editor/src/features/content/list-view/ContentListView.tsx, app/editor/src/features/content/list-view/constants/columns.tsx, app/editor/src/features/content/list-view/constants/defaultPage.ts, app/editor/src/features/content/papers/Papers.tsx, app/editor/src/features/content/papers/components/ReportActions.tsx, app/editor/src/features/content/papers/constants/columns.tsx, app/editor/src/store/slices/content/contentSlice.ts, app/editor/src/store/slices/content/interfaces/IContentSearchResult.ts, app/editor/src/store/slices/content/interfaces/IContentState.ts, app/editor/src/store/slices/content/interfaces/index.ts, app/editor/src/store/slices/content/utils/castContentToSearchResult.ts, app/editor/src/store/slices/content/utils/index.ts
I've reduce the amount of data we're storing in redux memory on our Content List View and Papers View pages.
=> Reduce memory usage - redux

app/subscriber/src/features/content/view-content/FolderMenu.tsx, libs/net/dal/Services/FolderService.cs
Resolved infinite loop when opening up add to folders.  
Fixed issue where content was not being added to a folder.
=> TNO-1135 Fix my folders

app/subscriber/src/components/date-filter/DateFilter.tsx, app/subscriber/src/features/content/view-content/FolderMenu.tsx, app/subscriber/src/features/content/view-content/ViewContent.tsx, app/subscriber/src/features/content/view-content/ViewContentToolbar.tsx, app/subscriber/src/features/home/Home.tsx, app/subscriber/src/features/home/constants/columns.tsx, app/subscriber/src/features/home/styled/Home.tsx, app/subscriber/src/features/my-minister/MyMinister.tsx, app/subscriber/src/features/todays-commentary/TodaysCommentary.tsx, app/subscriber/src/features/top-stories/TopStories.tsx
In this PR:
- users may now add content from the list view
- same sub menu as adding from view content page
- modified the `FolderMenu` component to take in an array to make it universal for singleton or many pieces of content
=> TNO-1743: Add content from list view

app/subscriber/src/components/folder-sub-menu/FolderSubMenu.tsx, app/subscriber/src/features/home/utils/DetermineToneIcon.tsx, app/subscriber/src/features/search-page/SearchPage.tsx, app/subscriber/src/features/search-page/styled/SearchPage.tsx
In this PR:
- add checkbox to search page results to allow users to select/deselect content
- add folder button to toolbar that will allow user to add selected content to folder
UI may change as Bobbi reviews.
=> TNO-1748: Add content to folder from search

services/net/contentmigration/Config/ContentMigrationOptions.cs, services/net/contentmigration/migrators/ContentMigrator.cs
- also added option flag to disable this feature in the future
=> feat: #tno-1825 - uncommented code to fix

services/net/contentmigration/appsettings.json
- Kelowna Capital News and CBC online
- waiting on source code for West Kelowna News
=> feat: #tno-1780 - added missing mappings

app/subscriber/src/features/content/view-content/styled/ViewContent.tsx
TNO-1793: Transcript Request button - client side
=> TNO-1793: Transcript Request button - client side

libs/net/template/Config/ReportingOptions.cs, openshift/kustomize/services/notification/base/deploy.yaml, openshift/kustomize/services/reporting/base/deploy.yaml, openshift/kustomize/services/reporting/overlays/dev/config-map.yaml, openshift/kustomize/services/reporting/overlays/prod/config-map.yaml, openshift/kustomize/services/reporting/overlays/test/config-map.yaml, services/net/notification/Config/NotificationOptions.cs, services/net/notification/NotificationManager.cs, services/net/notification/NotificationService.cs, services/net/notification/appsettings.Development.json, services/net/notification/appsettings.Staging.json
- re-used the ReportingOptions Config model in Notiofications
- TODO - configure shared ConfigMap for Reporting and Notification svc
=> fix: #tno-1550 - moved options for easier control

app/editor/src/components/tab-control/TabControl.tsx, app/editor/src/features/content/form/ContentForm.tsx
Fixed an issue where the toggle button was not showing up.
=> Fix multi-tab

services/net/content/ContentManager.cs
=> fix: #tno-1828 - fixed logic issue

services/net/content/ContentManager.cs
- force a re-index when content is updated.
=> feat: #tno-1828 - updated ContentManager

api/net/.devcontainer/devcontainer.json, app/editor/.devcontainer/devcontainer.json, app/editor/src/components/status/Status.tsx, app/editor/src/components/status/index.ts, app/editor/src/css/_colors.scss, app/editor/src/features/content/form/ContentForm.tsx, app/editor/src/features/content/form/components/tool-bar/form/StatusSection.tsx, app/editor/src/features/content/list-view/hooks/useColumns.tsx, app/editor/src/features/content/papers/Papers.tsx, app/editor/src/features/content/papers/hooks/useColumns.tsx, app/editor/src/index.scss, app/subscriber/.devcontainer/devcontainer.json, libs/net/.devcontainer/devcontainer.json, services/net/.devcontainer/Dockerfile, services/net/.devcontainer/devcontainer.json, services/net/transcription/Config/TranscriptionOptions.cs, services/net/transcription/TranscriptionManager.cs, services/net/transcription/appsettings.json, tools/import/.devcontainer/devcontainer.json
Video files for MOV will now be automatically converted to mp3 before being sent to Azure Cognitive Services.
- Fixed MOV transcription bug
- Updated Content List View status column
- Updated Papers status column
=> TNO-1739 Fix MOV Format

services/net/content/ContentManager.cs
- when updating content, some previously set properties where being lost
=> fix: #tno-1828 - fix missing properties

services/net/contentmigration/migrators/ClipMigrator.cs, services/net/contentmigration/migrators/ContentMigrator.cs, services/net/contentmigration/migrators/PaperMigrator.cs
- swapped out string sanitize method for something better
=> feat: #tno-1733 - fixed transcript

app/subscriber/src/features/home/Home.tsx, app/subscriber/src/features/top-stories/TopStories.tsx
The filter for the Home component was fixed to the required format.
The same filter was added to the Top Stories component.
=> TNO-1505 Filters fixed on Home and Top Stories

app/editor/src/features/admin/av-overviews/AVOverview.tsx, app/editor/src/features/admin/av-overviews/ListFilter.tsx, app/editor/src/features/admin/av-overviews/OverviewSubscribers.tsx, app/editor/src/features/admin/av-overviews/constants/index.ts, app/editor/src/features/admin/av-overviews/constants/subscriberColumns.tsx, libs/net/dal/Services/AVOverviewTemplateService.cs
TNO-1694: Admin Evening Overview Subscribers
=> TNO-1694: Admin Evening Overview Subscribers

app/subscriber/src/components/layout/constants/SidebarMenuItems.tsx, app/subscriber/src/components/sidebar/CustomSidebar.tsx, app/subscriber/src/components/sidebar/styled/CustomSidebar.tsx, app/subscriber/src/features/daily-overview/AVOverviewPreview.tsx, app/subscriber/src/features/daily-overview/hooks/useAVOverviewInstances.ts, app/subscriber/src/features/daily-overview/styled/AVOverviewPreview.tsx, app/subscriber/src/features/daily-overview/styled/index.ts, app/subscriber/src/features/landing/Landing.tsx
In this PR:
- new sidebar item to view evening overview
- click to view today's overview
- click logo in top left to navigate home
=> TNO-1501: View evening overview on MMI Subscriber

app/subscriber/src/features/search-page/SearchPage.tsx
TNO-1872: Search Spinner to show Progress
=> TNO-1872: Search Spinner to show Progress

app/subscriber/src/features/content/view-content/ViewContentToolbar.tsx
TNO-1859: remove the tags icon/selection box
=> TNO-1859: remove the tags icon/selection box

app/editor/src/features/admin/filters/FilterFormQuery.tsx, app/editor/src/features/admin/filters/utils/parseExportedFilter.ts
- also fix markup for filter checkboxes
=> feat: #tno-1730 - add isEnabled to filter import

app/editor/src/features/admin/filters/FilterForm.tsx, app/editor/src/features/admin/filters/FilterFormImportExport.tsx, app/editor/src/features/admin/filters/styled/FilterForm.tsx
=> feat: #tno-1730 - add button for new filter

app/editor/src/features/content/form/ContentForm.tsx
Show the image upload component when the content type is an image.
=> TNO-1876 Display image upload

libs/net/dal/Services/ContentService.cs
TNO-1833: Editor app headline search should work when using multiple words
=> TNO-1833: Editor app headline search should work when using multiple words

services/net/contentmigration/ContentMigrationAction.cs
needed to check that creationDateOfLastImport was set
=> fix: #tno-1886 - fixed null reference error

app/subscriber/src/features/home/Home.tsx, app/subscriber/src/features/home/constants/columns.tsx, app/subscriber/src/features/home/styled/Home.tsx
Had quick meeting with Bobbi and the press gallery needs a few tweaks before I include that. Splitting this off in the meantime.
In this PR:
- add view options that allow user to control columns shown 
- sort by media source or time
=> TNO-1856: Content list view options

app/editor/src/features/admin/reports/constants/defaultReportSchedule.ts, libs/net/dal/Configuration/ScheduleConfiguration.cs, libs/net/dal/Migrations/1.0.74/Down/PreDown/00-Schedule.sql, libs/net/dal/Migrations/1.0.74/Up/PreUp/00-Schedule.sql, libs/net/dal/Migrations/20231013183923_1.0.74.Designer.cs, libs/net/dal/Migrations/20231013183923_1.0.74.cs
- updated helper method to truncate excessively long names
=> fix: #tno-1877 - fixed name field length

app/editor/src/features/content/form/ContentForm.tsx
Align the image upload component with the text editor like it was before.
Screenshot:
=> TNO-1876 Align upload component

app/editor/src/features/admin/ingests/IngestDetails.tsx, openshift/kustomize/tekton/base/tasks/build-all.yaml, openshift/kustomize/tekton/base/tasks/deploy-all.yaml
Fixed pipeline so that it can build/deploy all components.  This should also fix the DB migration task.
Using bash arrays so that it's easier to debug and maintain the scripts.
=> TNO-1799 Fix DevOps Pipelines

openshift/kustomize/tekton/base/tasks/build-all.yaml, openshift/kustomize/tekton/base/tasks/deploy-all.yaml, services/net/content/ContentManager.cs, services/net/folder-collection/FolderCollectionManager.cs, services/net/nlp/NLPManager.cs, services/net/transcription/TranscriptionManager.cs
The Folder Collection Service will now ignore empty Elasticsearch queries.
Also added the service to the pipeline.
=> TNO-1531 Ignore empty queries

app/editor/src/css/_colors.scss, app/subscriber/src/css/_colors.scss
TNO-1865: Provide Colour Blind Colours for Environments
=> TNO-1865: Provide Colour Blind Colours for Environments

app/subscriber/src/features/home/Home.tsx, app/subscriber/src/features/home/styled/Home.tsx
- some minor styling changes
- disabled buttons that will require future work
=> Fix styling - View Options (list view)

app/editor/src/features/admin/ingests/configurations/FrontPage.tsx, libs/net/dal/Migrations/Initial/Up/PostUp/02-Ingest.sql, services/net/image/ImageAction.cs
The Image Service can now handle ZIP files, and will also delete the original files based on configuration.
=> TNO-1826 Add unzip to Image Service

app/editor/src/features/content/form/components/upload/Upload.tsx, app/subscriber/src/features/content/view-content/ViewContent.tsx
Fixing A/V player so that it works in Safari.
=> TNO-1873 Fix A/V player

services/net/contentmigration/migrators/PaperMigrator.cs
skip historic values which dont match the enforced enum
=> fix: #tno-1901 - added TryParse to ignore unknowns

api/net/Areas/Admin/Controllers/UserController.cs, libs/net/dal/Services/Interfaces/INotificationService.cs, libs/net/dal/Services/Interfaces/IReportService.cs, libs/net/dal/Services/NotificationService.cs, libs/net/dal/Services/ReportService.cs
TNO-1644: When user is disabled they should unsubscribe from reports/notifications
=> TNO-1644: When user is disabled they should unsubscribe from reports/notifications

openshift/kustomize/services/build/base/folder-collection.yaml, openshift/kustomize/services/build/base/kustomization.yaml, services/net/filemonitor/FilemonitorAction.cs, services/net/folder-collection/FolderCollectionManager.cs
=> TNO-1531 Fix Folder Collection Service

openshift/kustomize/services/build/base/kustomization.yaml, openshift/kustomize/services/build/base/scheduler.yaml, services/net/scheduler/SchedulerManager.cs
Updated the Scheduler Service to use the correct timezone.
=> TNO-1845 Fix Scheduler Service

services/net/contentmigration/migrators/ContentMigrator.cs
- this method was not neccesary
=> fix: #tno-1918 - removing Regex.Unescape

app/editor/src/features/admin/filters/FilterFormQuery.tsx, app/editor/src/features/admin/filters/constants/defaultFilter.ts, app/subscriber/src/features/my-searches/FilterFormDetails.tsx, app/subscriber/src/features/my-searches/constants/defaultFilter.ts
Setting the default filter values to size 100.
New value on a new filter creation.
=> TNO-1906 Set default filter size to 100

app/editor/src/features/admin/filters/FilterFormQuery.tsx, app/editor/src/features/admin/filters/constants/defaultFilter.ts, app/subscriber/src/features/my-searches/FilterFormDetails.tsx, app/subscriber/src/features/my-searches/constants/defaultFilter.ts, app/subscriber/src/features/search-page/utils/filterFormat.ts
There was a missing part while saving the search I found while testing on DEV.
I believe this is the last fix.
=> Tno 1906 default filter size

libs/npm/core/src/hooks/api-editor/interfaces/IFilterSettingsModel.ts, libs/npm/core/src/utils/elastic/generateQuery.ts, libs/npm/core/src/utils/elastic/generateTerm.ts
TNO-1908: Elasticsearch regression issues
=> TNO-1908: Elasticsearch regression issues

api/net/Areas/Editor/Controllers/ContentController.cs, api/net/Areas/Editor/Controllers/SystemMessageController.cs, api/net/Areas/Services/Controllers/ContentController.cs, api/net/Areas/Subscriber/Controllers/SystemMessageController.cs, app/editor/src/components/wysiwyg/Wysiwyg.tsx, app/editor/src/features/admin/folders/FolderFormCollect.tsx, app/editor/src/features/content/form/ContentForm.tsx, app/editor/src/features/content/form/components/toning/ToningGroup.tsx, app/editor/src/features/content/list-view/ContentListView.tsx, app/editor/src/features/content/papers/Papers.tsx, app/editor/src/features/content/papers/components/ReportActions.tsx, app/editor/src/features/content/validation/ContentFormSchema.ts, app/editor/src/store/slices/content/contentSlice.ts, app/editor/src/store/slices/content/interfaces/IContentSearchResult.ts, app/editor/src/store/slices/content/interfaces/IContentState.ts
The Content List View will immediately display any content added by the current user.  Note that this will occur before the content has been indexed in most cases.  This means if the user attempts to search for that content, it won't show up until it has been indexed.  The reason for this is because when we add content it first is placed in the database.  The API then informs client apps of new content added.  However, the Content List View uses Elasticsearch to find content.
- Updated Content List View when content is added
- Updated Papers when content is added
- Fixed Content Form validation
- Fixed Content Form button click issue
- Fixed user session timeout bug
=> TNO-1902 Improve Content List View

app/subscriber/src/features/my-reports/utils/calcNextSend.ts, app/subscriber/src/features/my-reports/utils/isAutoSend.ts, app/subscriber/src/features/my-reports/utils/isAutoSendDisabled.ts
Preview next report send based on the schedule.
=> TNO-1802 Function to calculate next report send

.github/CODEOWNERS, libs/net/entities/ScheduleWeekDay.cs, openshift/kustomize/services/indexing/base/deploy.yaml, openshift/kustomize/services/indexing/overlays/dev/kustomization.yaml, openshift/kustomize/services/indexing/overlays/prod/kustomization.yaml, openshift/kustomize/services/indexing/overlays/test/kustomization.yaml, services/net/event-handler/EventHandlerManager.cs, services/net/scheduler/SchedulerManager.cs
Fixed issue where Event Handler Service would throw concurrency error due to the race condition.
Added other team members to contributors so they receive PR emails.
Updated resources for Index Service to improve performance.
=> TNO-1650 Fix Event Handler Service

app/editor/src/features/content/list-view/ContentListView.tsx, app/editor/src/features/content/list-view/hooks/useColumns.tsx, app/editor/src/features/content/list-view/utils/getFilter.ts, app/editor/src/features/content/list-view/utils/getSortBy.ts, app/editor/src/features/content/list-view/utils/index.ts, libs/net/elastic/ITNOElasticClient.cs, libs/net/elastic/TNOElasticClient.cs, libs/npm/core/src/utils/elastic/generateQuery.ts, libs/npm/core/src/utils/elastic/generateRangeForDateOffset.ts
TNO-1751: Convert Advanced Search to use the Raw Elasticsearch Query endpoint
=> TNO-1751: Convert Advanced Search to use the Raw Elasticsearch Query endpoint

api/net/Dockerfile, app/editor/Dockerfile, app/subscriber/Dockerfile, services/net/capture/Dockerfile, services/net/clip/Dockerfile, services/net/command/Dockerfile, services/net/content/Dockerfile, services/net/contentmigration/Dockerfile, services/net/event-handler/Dockerfile, services/net/ffmpeg/Dockerfile, services/net/filecopy/Dockerfile, services/net/filemonitor/Dockerfile, services/net/folder-collection/Dockerfile, services/net/image/Dockerfile, services/net/indexing/Dockerfile, services/net/nlp/Dockerfile, services/net/notification/Dockerfile, services/net/reporting/Dockerfile, services/net/scheduler/Dockerfile, services/net/syndication/Dockerfile, services/net/transcription/Dockerfile
- switched from use of sdk image to aspnet
- commented out unneccessary stuff from api Dockerfile
=> feat: #tno-1940 - tweaks to Dockerfiles

libs/npm/core/src/utils/elastic/generateQueryForAction.ts
TNO-1751: Convert Advanced Search to use the Raw Elasticsearch Query endpoint
=> TNO-1751 updates for Top Story & Commentary

app/subscriber/src/features/my-reports/hooks/useColumns.tsx, app/subscriber/src/features/my-reports/utils/isAutoSend.ts, app/subscriber/src/features/my-reports/utils/isAutoSendDisabled.ts, app/subscriber/src/features/press-gallery/PressGallery.tsx
Was previously trying to fetch instance with `reportId` instead of `instanceId`.
One question down below:
=> TNO-1612: Bug fix

api/net/Areas/Admin/Controllers/ReportController.cs, api/net/Areas/Editor/Controllers/ReportController.cs, api/net/Areas/Editor/Controllers/ReportInstanceController.cs, api/net/Areas/Helpers/IReportHelper.cs, api/net/Areas/Helpers/ReportHelper.cs, api/net/Areas/Subscriber/Controllers/ReportController.cs, api/net/Areas/Subscriber/Controllers/ReportInstanceController.cs, app/editor/src/features/admin/reports/ReportForm.tsx, app/editor/src/features/admin/reports/ReportFormTemplate.tsx, libs/net/template/IReportEngine.cs, libs/net/template/ReportEngine.cs, libs/net/template/TemplateEngine.cs, services/net/reporting/ReportingManager.cs
- changed mechanism for determining when to get from or add to cache.
- now based on the hash of the template plus key
- key is now based on the caller saying isPreview
- preview and final reports are considered different
- changed report preview UI so that it calls a "warm up" preview
- TODO - make calls to elastic in parallel
=> feat: #tno-1864 - changed caching

app/editor/src/features/content/form/ContentForm.tsx, app/editor/src/features/content/form/ContentStoryForm.tsx
TNO-1888: Modify Radio/TV Form Layout: Move Row above Tabs
=> TNO-1888: Modify Radio/TV Form Layout: Move Row above Tabs

api/net/Areas/Services/Controllers/ContentController.cs
- indexing service was never being notified of the new content
=> fix: #tno-1953 - added kafka message for upload

services/net/image/ImageAction.cs
- directory wont exist if no files are extracted
=> fix: #tno-1955 - check if directory exists

app/subscriber/src/components/layout/DefaultLayout.tsx, app/subscriber/src/components/sidebar/CustomSidebar.tsx, app/subscriber/src/components/sidebar/advanced-search/AdvancedSearch.tsx, app/subscriber/src/components/sidebar/advanced-search/components/SearchInGroup.tsx, app/subscriber/src/components/sidebar/advanced-search/styled/AdvancedSearch.tsx, app/subscriber/src/css/_colors.scss, app/subscriber/src/css/_variables.module.scss, app/subscriber/src/features/landing/Landing.tsx, app/subscriber/src/features/landing/styled/Landing.tsx
- move adv search from sidebar
- add text area when in adv search
- missing functionality pieces will be coming in the next PR
- dynamically adjust height if expanded
=> TNO-1855: Move advanced search

libs/net/core/Extensions/StringExtensions.cs, services/net/content/ContentManager.cs, services/net/contentmigration/migrators/ClipMigrator.cs, services/net/contentmigration/migrators/ContentMigrator.cs, services/net/contentmigration/migrators/PaperMigrator.cs, services/net/filemonitor/FilemonitorAction.cs, services/net/image/ImageAction.cs, services/net/syndication/SyndicationAction.cs
- tweaked paragraph sanitizing in filemonitor and syndication
=> fix: #tno-1956 - stopped content service from stripping

api/net/Areas/Admin/Controllers/NotificationController.cs, app/editor/src/features/admin/filters/FilterSettingsForm.tsx, app/editor/src/features/admin/notifications/NotificationForm.tsx, app/editor/src/features/admin/notifications/constants/defaultNotification.ts, libs/net/dal/Services/NotificationService.cs
Fixed bugs with filter dates and creating new notification templates.
=> Fix notification bugs

app/subscriber/src/features/my-reports/view/ReportSnapshotEdit.tsx, app/subscriber/src/features/my-reports/view/components/ReportSectionContent.tsx
Enables drag and drop boxes between sections.
=> TNO-1810 Drag and drop between different sections

services/net/image/ImageAction.cs
- since we cant delete in non-PROD, we have to do it the long way
=> fix: #tno-1590 - made duplicate detection more robust

app/subscriber/src/features/press-gallery/PressGallery.tsx, app/subscriber/src/features/press-gallery/utils/createFilterSettings.ts
Noticed that only 10 items were being returned max, and that when it searches by name (not aliases) it was doing a partial match which we don't want. This PR should fix both those items
=> Remainder of press gallery bugs

app/subscriber/src/features/press-gallery/PressGallery.tsx
Quick PR to add loading status to press gallery and remove problematic code, ' OR ' not needed with default operator.
=> Add loading indicator to Press Gallery table

app/editor/src/features/reports/av-overview/OverviewGrid.tsx
TNO-1893: Evening Overview Summary Lines
=> TNO-1893: Evening Overview Summary Lines

app/editor/src/features/reports/av-overview/AVOverview.tsx, app/editor/src/features/reports/av-overview/OverviewSection.tsx, app/editor/src/features/reports/av-overview/styled/AVOverview.tsx, libs/net/dal/Services/AVOverviewInstanceService.cs
TNO-1954: Evening Overview feedback
=> TNO-1954: Evening Overview feedback

api/net/Areas/Subscriber/Controllers/ReportController.cs, app/subscriber/src/features/my-reports/constants/reportProductColumns.tsx, app/subscriber/src/features/my-reports/view/ViewReport.tsx, app/subscriber/src/features/my-reports/view/styled/ViewReport.tsx, app/subscriber/src/features/my-reports/view/styled/index.ts, app/subscriber/src/features/router/AppRouter.tsx, libs/net/dal/Services/ReportService.cs
- new page to view generated reports on the subscriber site
- a user may view a report if it is their own, or it is made public
=> View Report Page

libs/net/kafka/KafkaListener`.cs, libs/net/kafka/TNO.Kafka.csproj, libs/net/services/TNO.Services.csproj, openshift/kustomize/services/content/base/deploy.yaml, openshift/kustomize/services/folder-collection/base/deploy.yaml, openshift/kustomize/services/indexing/base/deploy.yaml, services/net/content/ContentManager.cs, services/net/content/ContentService.cs, services/net/folder-collection/FolderCollectionService.cs, services/net/indexing/IndexingManager.cs, services/net/indexing/IndexingService.cs
- update confluent.kafka libraya to 2.3.0
- switched KafkaAdmin to singleton in all usages
=> tno-2026 - fix memory issue service

app/subscriber/src/features/filter-media/FilterMedia.tsx, app/subscriber/src/features/filter-media/index.ts, app/subscriber/src/features/filter-media/styled/FilterMedia.tsx, app/subscriber/src/features/filter-media/styled/index.ts, app/subscriber/src/features/landing/Landing.tsx
=> TNO-1892: Filter media type, add page, all but source filtering

app/editor/src/features/reports/av-overview/OverviewGrid.tsx
TNO-1929: Evening Overview summaries field: character limit of 80
=> TNO-1929: Evening Overview summaries field: character limit of 80

app/editor/src/features/reports/av-overview/OverviewGrid.tsx
TNO-1951: MMI Evening Overview - snippet options
=> TNO-1951: MMI Evening Overview - snippet options

openshift/kustomize/services/build/base/notification.yaml, services/net/content/appsettings.json, services/net/ffmpeg/appsettings.json, services/net/indexing/appsettings.json, services/net/nlp/appsettings.json, services/net/notification/Validation/NotificationValidator.cs, services/net/transcription/appsettings.json
The notification filter logic was incorrect and stopped sending notifications.
Also updated the Kafka Consumer configuration where applicable.
=> Fix Notification Service
