services/net/contentmigration/Config/ContentMigrationOptions.cs, services/net/contentmigration/ContentMigrationAction.cs, services/net/contentmigration/appsettings.json
- added a string setting for TagForMigratedContent
- if set, it will be added to all content that is migrated from TNO
- if empty, nothing will be added
=> feat: #tno-1984 - tag content migrated from TNO

app/editor/src/features/reports/av-overview/AVOverview.tsx, app/subscriber/src/features/daily-overview/AVOverviewPreview.tsx
TNO-1883: Link to Evening Overview in Left Hand menu not working on Subscriber site
=> TNO-1883: Link to Evening Overview in Left Hand menu not working on Subscriber site

app/editor/src/features/reports/av-overview/OverviewGrid.tsx
TNO-2016: autopopulate timestamp for evening report
=> TNO-2016: autopopulate timestamp for evening report

app/subscriber/src/features/daily-overview/AVOverviewPreview.tsx
TNO-1883: Link to Evening Overview in Left Hand menu not working on Subscriber site
=> TNO-1883 updates based on the QA feedback

app/subscriber/src/features/press-gallery/PressGallery.tsx, app/subscriber/src/store/hooks/subscriber/useContent.ts, app/subscriber/src/store/slices/content/contentSlice.ts, app/subscriber/src/store/slices/content/interfaces/IContentState.ts, app/subscriber/src/store/slices/content/useContentStore.ts
- Persist press gallery filters
- Adapt the initial query to use the persisted filters
=> TNO-1938 Persist press gallery filters

app/subscriber/src/components/sidebar/advanced-search/AdvancedSearch.tsx, app/subscriber/src/components/sidebar/advanced-search/styled/AdvancedSearch.tsx, app/subscriber/src/css/_colors.scss, app/subscriber/src/features/commentary/styled/Commentary.tsx, app/subscriber/src/features/landing/Landing.tsx, app/subscriber/src/features/landing/styled/Landing.tsx, app/subscriber/src/features/my-searches/MySearches.tsx, app/subscriber/src/features/my-searches/constants/columns.tsx, app/subscriber/src/features/my-searches/styled/MySearches.tsx, app/subscriber/src/features/router/AppRouter.tsx, app/subscriber/src/features/search-page/SearchPage.tsx, app/subscriber/src/features/search-page/hooks/index.ts, app/subscriber/src/features/search-page/hooks/useParamsToFilter.tsx, app/subscriber/src/features/search-page/styled/SearchPage.tsx
Please note that the app is in a bit of styling limbo as some components have been updated with the new MMI style, while others have not.
Also one more thing to note, I have to talk to Bobbi about something in regards to updating a search. Going to add that in once I gather that information. **_Leaving in draft; however, will include these changes in a separate smaller commit to keep the review easy,._** 
- user can now navigate from my searches to search results
- styling updated
- a few other styling and scrollbar fixes
=> TNO-1652: Show Results of Searches

app/subscriber/src/components/sidebar/advanced-search/components/MediaSection.tsx, app/subscriber/src/components/sidebar/advanced-search/styled/AdvancedSearch.tsx
Small PR that allows the user to click the row of sub media types rather than just being able to click the tiny dropdown icon
=> TNO-1966: Be able to click row of sub options

libs/npm/core/src/components/form/textarea/TextArea.tsx
TNO-1941: Perfomance: Slow Input when working with Evening Report form
=> TNO-1941: Perfomance: Slow Input when working with Evening Report form

openshift/kustomize/kafka/kowl/base/deploy.yaml, openshift/kustomize/kafka/kowl/overlays/dev/kustomization.yaml, openshift/kustomize/kafka/kowl/overlays/prod/kustomization.yaml, openshift/kustomize/kafka/kowl/overlays/test/kustomization.yaml
=> fix: #tno-2041 - moved image inhouse

services/net/content/ContentManager.cs, services/net/contentmigration/ContentMigrationAction.cs, services/net/contentmigration/appsettings.json
- only happens with bad data
- also fixed mapping for products from TNO
=> fix: #tno-2042 - skip records with no title

services/net/filemonitor/FilemonitorAction.cs
Minor change to remove invalid `try+catch` and extra update of the ingest status.
=> TNO-1965 Fix File Monitor Service

app/subscriber/src/components/sidebar/advanced-search/components/sections/MediaSection.tsx, app/subscriber/src/components/sidebar/advanced-search/styled/AdvancedSearch.tsx
small styling fix to center some items that look misaligned
=> Small style fix

app/subscriber/src/components/layout/DefaultLayout.tsx, app/subscriber/src/store/hooks/signalr/index.ts, app/subscriber/src/store/hooks/signalr/interfaces/IWorkOrderToast.ts, app/subscriber/src/store/hooks/signalr/interfaces/index.ts, app/subscriber/src/store/hooks/signalr/useApiHub.ts, app/subscriber/src/store/slices/app/appSlice.ts, app/subscriber/src/store/slices/app/interfaces/IAppState.ts, app/subscriber/src/store/slices/app/useAppStore.ts
Adding SignalR to the Subscriber app.
=> TNO-2058 Add SignalR

app/editor/src/features/reports/av-overview/OverviewGrid.tsx
=> TNO-2016: Autopopulate timestamp for evening report using publishedOn media date

app/subscriber/src/features/my-reports/admin/ReportAdmin.tsx
Allow update if there's a same name report.
=> TNO-1818 Allow update with same name report

api/net/Areas/Admin/Controllers/ReportController.cs, api/net/Areas/Services/Controllers/ReportInstanceController.cs, api/net/Areas/Subscriber/Controllers/ReportController.cs, app/subscriber/src/features/my-reports/MyReports.tsx, app/subscriber/src/features/my-reports/ReportCard.tsx, app/subscriber/src/features/my-reports/styled/MyReports.tsx, app/subscriber/src/features/my-reports/utils/calcNextSend.ts, app/subscriber/src/store/hooks/subscriber/useReports.ts, libs/net/dal/Services/Interfaces/IReportInstanceService.cs, libs/net/dal/Services/ReportInstanceService.cs, libs/net/dal/Services/ReportService.cs
A few minor UI improvements to show loading components and a fix for the performance issue on the My Reports page.
There are still significant issues related to performance on the report generation and viewing pages that need to be addressed.
=> TNO-2017 Fix my reports

app/editor/src/features/admin/products/ProductDetailsForm.tsx
- quick performance fix
- switched out call for retrieving Reports to Headers only
=> feat: #tno-2054 - new page for MMI Products

app/subscriber/src/components/info/InfoShield.tsx, app/subscriber/src/components/sidebar/advanced-search/AdvancedSearch.tsx, app/subscriber/src/components/sidebar/advanced-search/styled/AdvancedSearch.tsx, app/subscriber/src/components/tooltip-menu/TooltipMenu.tsx, app/subscriber/src/components/tooltip-menu/index.ts, app/subscriber/src/components/tooltip-menu/styled/TooltipMenu.tsx, app/subscriber/src/components/tooltip-menu/styled/index.ts, app/subscriber/src/css/_variables.module.scss, app/subscriber/src/css/_variables.scss, app/subscriber/src/features/my-searches/MySearches.tsx, app/subscriber/src/features/my-searches/constants/columns.tsx, app/subscriber/src/features/my-searches/styled/MySearches.tsx, app/subscriber/src/features/search-page/SearchPage.tsx, app/subscriber/src/features/search-page/styled/SearchPage.tsx
- users may now select the gear icon and click modify search to modify viewed search
- common tooltip component added called TooltipMenu to be used when a menu is to be displayed with clickable options
- few UI adjustments
- cut out a number of requests being triggered erroneously
=> TNO-2023, TNO-2024: Modify / view searches

app/subscriber/src/components/basic-search/BasicSearch.tsx, app/subscriber/src/components/basic-search/index.ts, app/subscriber/src/components/basic-search/styled/BasicSearch.tsx, app/subscriber/src/components/basic-search/styled/index.ts, app/subscriber/src/components/search-with-logout/SearchWithLogout.tsx, app/subscriber/src/components/section/PageSection.tsx, app/subscriber/src/components/section/styled/PageSection.tsx, app/subscriber/src/components/sidebar/advanced-search/AdvancedSearch.tsx, app/subscriber/src/components/sidebar/advanced-search/components/sections/SearchInGroup.tsx, app/subscriber/src/components/sidebar/advanced-search/styled/AdvancedSearch.tsx, app/subscriber/src/components/user-profile/styled/UserProfile.tsx, app/subscriber/src/css/_variables.module.scss, app/subscriber/src/css/_variables.scss, app/subscriber/src/features/landing/Landing.tsx, app/subscriber/src/features/landing/styled/Landing.tsx, app/subscriber/src/features/my-searches/MySearches.tsx, app/subscriber/src/features/my-searches/constants/columns.tsx, app/subscriber/src/features/my-searches/styled/MySearches.tsx, app/subscriber/src/features/search-page/MySearchesSection.tsx, app/subscriber/src/features/search-page/SearchPage.tsx, app/subscriber/src/features/search-page/styled/SearchPage.tsx
- separate basic search from advanced to simplify component logic
- responsive basic search
- remove double search on mobile
- add page section to search page components 
- see available searches on left hand side while viewing a search from my search
VIEW SEARCH:
RESPONSIVE BASIC SEARCH //  REMOVE DOUBLE SEARCH:
NEW BASIC SEARCH COMPONENT:
=> Search Enhancements 

app/subscriber/src/components/sidebar/advanced-search/AdvancedSearch.tsx, app/subscriber/src/components/sidebar/advanced-search/components/ElasticInfo.tsx, app/subscriber/src/components/sidebar/advanced-search/components/index.ts, app/subscriber/src/components/sidebar/advanced-search/components/styled/ElasticInfo.tsx, app/subscriber/src/components/sidebar/advanced-search/components/styled/index.ts, app/subscriber/src/components/sidebar/advanced-search/constants/DefaultAdvancedSearch.ts, app/subscriber/src/components/sidebar/advanced-search/styled/AdvancedSearch.tsx, app/subscriber/src/components/tooltip-menu/TooltipMenu.tsx, app/subscriber/src/components/tooltip-menu/styled/TooltipMenu.tsx, app/subscriber/src/css/_variables.module.scss, app/subscriber/src/css/_variables.scss, app/subscriber/src/features/my-searches/utils/settingsToFilter.ts
Simple tooltip to help users perform elastic queries
=> TNO-1971: Elastic search help text / fix store filter bug

app/editor/src/features/admin/products/constants/subscriberColumns.tsx
- fix for null reference error if no record exists for report subscriber
=> fix: #tno-1937 - fix null reference error

app/editor/src/features/reports/av-overview/OverviewGrid.tsx, app/editor/src/features/reports/av-overview/styled/AutoComplete.tsx, app/editor/src/features/reports/av-overview/styled/index.ts
=> TNO-2061: Autofill Evening Overview summary

app/subscriber/src/components/sidebar/advanced-search/styled/AdvancedSearch.tsx, app/subscriber/src/features/search-page/styled/SearchPage.tsx
- search bottom bar now stays in place, same with header
- scroll body contents 
- form input more responsive
=> Fix scrolling advanced search

api/net/Areas/Subscriber/Controllers/ProductController.cs, app/editor/src/features/admin/products/constants/subscriberColumns.tsx, app/subscriber/src/components/section/Section.tsx, app/subscriber/src/features/my-products/MyProducts.tsx, libs/net/dal/Services/ProductService.cs
- subscriber who had never been subscribed before couldn't request subscription
- unapproved requests for subscription were not showing up
- fixed cursor issue on the shared section component
=> fix: #TNO-937 - fixes for subscriber site

app/editor/src/features/home/InfoText.tsx, openshift/scripts/deploy.sh
Not certain how this hasn't broken then application in the past, but this should fix the issue.
=> Fix editor app

libs/net/ches/ChesService.cs, libs/net/ches/Models/IEmail.cs, libs/net/ches/Models/IEmailBase.cs, libs/net/ches/Models/IEmailMerge.cs
- convert any inline base64 encoded images to attachments
- happens at the final stage just before sending email
- works with single email and mail merge
=> feat: #tno-1708 - fix issue with base64 images

api/net/Areas/Editor/Models/Storage/ItemModel.cs, api/net/Areas/Subscriber/Models/Storage/ItemModel.cs, api/net/TNO.API.csproj, libs/net/models/Filters/ContentFileReference.cs, libs/net/models/TNO.Models.csproj, libs/net/services/Helpers/ApiService.cs, libs/net/services/TNO.Services.csproj
- apparently the new library is also wrong
- implemented use of a new library
- all file types tested and returning the "correct" mime type
=> fix: #tno-2090 - radio content content type broken

docs/DEVELOPMENT.md
Found this fix for my local environment running Linux, on Windows Docker Desktop will automatically add this for you (with different addresses though)
Just documenting before it disappears into the void of my brain.
=> Small documentation update 

libs/net/dal/Configuration/ContentConfiguration.cs, libs/net/dal/Configuration/SourceConfiguration.cs, libs/net/dal/Migrations/20231206001803_1.0.96.Designer.cs, libs/net/dal/Migrations/20231206001803_1.0.96.cs
- changed Content and Source table relationships to User table
- need to allow owner_id to be setNull on delete User
=> fix: #tno-2049 - fixed relationships

app/editor/src/features/admin/event-of-the-day/EventOfTheDayList.tsx, app/editor/src/features/admin/event-of-the-day/hooks/useColumns.tsx, app/editor/src/features/admin/event-of-the-day/styled/EventOfTheDayList.tsx, libs/net/dal/Services/ContentService.cs
- fix bug when Event of the Day folder is empty
- removed unneccesary logic from Service call
=> feat: #tno-1980 - Event of the Day Admin page

app/subscriber/src/components/tabs/FormikTabs.tsx, app/subscriber/src/components/tabs/Tabs.tsx, app/subscriber/src/components/tabs/index.ts, app/subscriber/src/components/tabs/interfaces/IFormikTab.ts, app/subscriber/src/components/tabs/interfaces/index.ts, app/subscriber/src/components/tabs/styled/Tabs.tsx, app/subscriber/src/css/_variables.module.scss, app/subscriber/src/css/_variables.scss, app/subscriber/src/features/my-reports/admin/ReportAdmin.tsx, app/subscriber/src/features/my-reports/admin/styled/ReportAdmin.tsx, app/subscriber/src/features/my-reports/admin/validation/ReportFormSchema.ts, app/subscriber/src/features/my-reports/admin/validation/ReportFormSettingsSchema.ts, app/subscriber/src/features/my-reports/admin/validation/ReportFormTemplateSchema.ts
We have a new component FormikTab that supports validation of each tab.  It also identifies which tab has issues.
=> TNO-2045 Add tab validation

libs/net/models/Areas/Subscriber/Models/Folder/FolderModel.cs, libs/net/models/Areas/Subscriber/Models/Folder/FolderScheduleModel.cs
Somehow managed to forget to push these, noticed when testing on DEV.
=> Update models for FolderSchedule

app/editor/src/features/admin/event-of-the-day/hooks/useColumns.tsx, app/editor/src/features/admin/event-of-the-day/styled/EventOfTheDayList.tsx, app/editor/src/features/admin/topics/TopicList.tsx, app/editor/src/features/content/form/components/topic/Topic.tsx, app/editor/src/features/content/form/styled/ContentForm.tsx
- fixed a bug with adding/enabling topics.  Name search was not case insensitive which could result in duplicate topics
- added styling for diabled topics in drop down
- disabled topics could come in from TNO *or* through a particular real world order of actions
- renamed variable in TopicList component for readability
=> fix: #tno-1980 - bug fix and change from Scott

app/subscriber/src/features/search-page/styled/SearchPage.tsx
Fix text size on Share button
to
=> Fix styling

app/subscriber/src/features/landing/Landing.tsx
made a rookie mistake with a hard coded string
=> fix bug with home filter buttons

app/subscriber/src/components/section/Section.tsx, app/subscriber/src/components/section/styled/Section.tsx, app/subscriber/src/features/my-reports/admin/ReportTemplate.tsx, app/subscriber/src/features/my-reports/admin/old/components/ReportSection.tsx, app/subscriber/src/features/my-reports/admin/styled/ReportAdmin.tsx, app/subscriber/src/features/my-reports/constants/defaultReportSection.ts, app/subscriber/src/features/my-reports/interfaces/IReportSectionForm.ts, app/subscriber/src/features/my-reports/utils/getBlockName.ts, app/subscriber/src/index.scss
Editing report configuration has been improved.
- Can close/open all sections
- Can change order with number text box
=> TNO-2045 Update Reports

app/editor/src/features/admin/event-of-the-day/hooks/useColumns.tsx
- content coming in somehow with no topic breaks the UI
=> fix: #tno-1980 - bug fix

services/net/folder-collection/FolderCollectionManager.cs
- trying to catch which condition is causing the content to be rejected
=> fix: #tno-2147 - added more logging

services/net/folder-collection/FolderCollectionManager.cs
- dateoffset filter logic was flipped
=> fix: #tno-2147 - fixed dateOffset filter logic

api/net/Areas/Editor/Controllers/ContentController.cs, app/editor/src/features/admin/reports/ReportForm.tsx, app/editor/src/features/admin/reports/constants/defaultRazorTemplate.ts, libs/net/dal/Services/AVOverviewInstanceService.cs, libs/net/dal/Services/ReportService.cs
Fixed the issue when saving a new report with a new template.
=> Fix add new report

app/subscriber/src/features/content/view-content/styled/ViewContent.tsx
Scale image content according to div.
=> TNO-2069 Fit image to div in view content

app/editor/src/features/admin/filters/FilterForm.tsx, app/editor/src/features/admin/filters/styled/FilterForm.tsx, app/editor/src/features/admin/reports/ReportForm.tsx, app/editor/src/features/admin/reports/ReportSection.tsx, app/editor/src/features/admin/reports/styled/ReportForm.tsx, app/subscriber/src/features/my-reports/admin/old/components/ReportSectionContent.tsx
Added a way to copy filters and reports from the Editor administration.
Added a way to quickly open up a filter/folder from a report section in a new tab.
=> Add copy filter/report

app/subscriber/src/components/layout/DefaultLayout.tsx, app/subscriber/src/components/layout/styled/Layout.tsx, app/subscriber/src/components/navbar/Navbar.tsx, app/subscriber/src/components/navbar/NavbarItems.tsx, app/subscriber/src/components/navbar/constants/INavbarItem.ts, app/subscriber/src/components/navbar/index.ts, app/subscriber/src/components/navbar/styled/Navbar.tsx, app/subscriber/src/components/navbar/styled/index.ts, app/subscriber/src/components/navbar/utils/determineGroupIcon.tsx, app/subscriber/src/components/search-with-logout/SearchWithLogout.tsx, app/subscriber/src/components/search-with-logout/styled/SearchWithLogout.tsx, app/subscriber/src/css/_variables.module.scss, app/subscriber/src/css/_variables.scss, app/subscriber/src/features/landing/Landing.tsx, app/subscriber/src/features/manage-folder/ManageFolder.tsx, app/subscriber/src/features/my-reports/admin/old/ReportAdmin.tsx, app/subscriber/src/features/my-searches/SearchForm.tsx, app/subscriber/src/features/search-page/SearchPage.tsx
- change grid layout to have header, sidebar, and main content 
- update theme
- new navbar
- css enhancements
=> TNO-2091/93: New nav bar and layout

app/subscriber/src/features/commentary/Commentary.tsx, app/subscriber/src/index.scss
This is just a small PR which adds the `PageSection` component to the commentary box.
=> Fix commentary box

app/subscriber/src/components/navbar/Navbar.tsx, app/subscriber/src/components/navbar/styled/Navbar.tsx, app/subscriber/src/features/my-reports/admin/styled/ReportAdmin.tsx, app/subscriber/src/features/my-reports/view/styled/ReportEdit.tsx, app/subscriber/src/index.scss
Forgot to add this to my last PR
- add key to list child to resolve error
- also missed some more scrolling errors with reports due to firefox scrolling. Tested on chrome and found some to fix up
- add hover cursor for nav expand
- add hover filter for nav bar to make more interactive
=> [Updated] Fix key error, more scrolling fixes

libs/net/dal/Services/TopicScoreRuleService.cs, libs/net/entities/TopicScoreRule.cs
- introduced an Equality operator on TopicScoreRule to check for changes
=> feat: #tno-2137 - changed Update method to only Update changed entities

app/subscriber/src/components/sidebar/advanced-search/components/sections/ContributorSection.tsx, app/subscriber/src/components/sidebar/advanced-search/components/sections/MediaTypeSection.tsx, app/subscriber/src/components/sidebar/advanced-search/components/sections/SeriesSection.tsx, app/subscriber/src/components/sidebar/advanced-search/components/sections/TagSection.tsx, app/subscriber/src/components/sidebar/advanced-search/styled/AdvancedSearch.tsx, app/subscriber/src/features/search-page/styled/SearchPage.tsx
Been fighting react-select and this advanced search scroll layout. This is really a band-aid. I think we need some UX work for the expanded states etc. 
When Bobbi is back I might book some time off with her to brainstorm.
But in the meantime at least things won't get cut off.
=> breaking off a few css fixes

app/editor/src/features/reports/av-overview/OverviewGrid.tsx
=> TNO-2060: Ad lines should list order

app/editor/src/features/reports/av-overview/AVOverviewPreview.tsx, app/editor/src/features/reports/av-overview/styled/AVOverviewPreview.tsx, app/subscriber/src/features/daily-overview/AVOverviewPreview.tsx
=> TNO-1884: Add Preview AV overview view on site link

app/subscriber/src/features/home/Home.tsx
Add the source sortOrder param when calling the home page.
=> TNO-2000 Set source sort order

app/subscriber/src/features/my-folders/ConfigureFolder.tsx, app/subscriber/src/features/my-folders/Schedule.tsx, libs/net/models/Areas/Subscriber/Models/Folder/FolderModel.cs
- stop multiple schedules being created
- changed method for updating schedule
- schedule should not need to know anything about parent folder or how many schedules there are
- filter is now being saved
- keep age limit is now being saved
=> fix: #tno-2160 - fix folder saving issues

app/editor/src/features/content/form/ContentForm.tsx, app/editor/src/features/content/form/ContentStoryForm.tsx, app/editor/src/features/content/form/MediaSummary.tsx, app/editor/src/features/content/form/components/tags/Tags.tsx
https://github.com/bcgov/tno/assets/26801490/dabf7852-a74f-45ba-918c-50d91dd06493
All the tags between brackets and separated by comma or space will be parsed and added to the tags component.
(With the changes, it will not check the middle of content, just the end, so the video is outdated)
=> Tno 2144 Parse Editor Tags

app/subscriber/src/features/my-reports/admin/components/ReportSectionContent.tsx, app/subscriber/src/features/my-reports/admin/components/ReportSectionMediaAnalytics.tsx, app/subscriber/src/features/search-page/SearchPage.tsx, app/subscriber/src/features/search-page/components/advanced-search/AdvancedSearch.tsx, app/subscriber/src/features/search-page/components/advanced-search/components/sections/MoreOptions.tsx
I have removed the search by URL parameters in the advanced search page.  It was causing too many issues.  We can figure out how to apply that in the future if needed.
This will now allow a user to click Search, and it will search...
=> TNO-2175 Removing advanced search URL parameter search

api/net/Areas/Subscriber/Controllers/ReportController.cs, app/subscriber/src/features/my-reports/view/ReportEdit.tsx
When sorting content in a report each section will maintain its own order.
=> TNO-2169 Fix report content sort

app/subscriber/src/features/search-page/components/advanced-search/AdvancedSearch.tsx, app/subscriber/src/features/search-page/components/advanced-search/components/ExpandableRow.tsx, app/subscriber/src/features/search-page/components/advanced-search/components/sections/MoreOptions.tsx, app/subscriber/src/features/search-page/components/advanced-search/constants/DefaultAdvancedSearch.ts, app/subscriber/src/features/search-page/components/advanced-search/interfaces/IAdvancedSearchFilter.ts, app/subscriber/src/features/search-page/components/advanced-search/utils/queryToState.ts, libs/net/models/Filters/ContentFilter.cs
- refactored names for consistency
=> fix: #tno-2155 - made action clearer in the UI

app/subscriber/src/components/basic-search/BasicSearch.tsx
- reset the search filter back to "basic" before submitting the search
- store the "basic" filter
=> fix: #tno-2191 - clear any advanced filter settings on basic search

app/editor/src/features/content/constants/ShowOnlyValues.ts, app/editor/src/features/content/constants/showOnlyOptions.ts, app/editor/src/features/content/list-view/components/tool-bar/filter/ShowOnlySection.tsx, app/editor/src/features/content/papers/components/AdvancedFilter.tsx
Papers page Published checkbox
List View page Published checkbox
=> TNO-2133 Published filter checkboxes

app/editor/src/features/admin/reports/constants/instanceColumns.tsx, app/subscriber/src/features/my-reports/admin/components/ReportSectionMediaAnalytics.tsx, app/subscriber/src/features/my-reports/admin/styled/ReportAdmin.tsx, app/subscriber/src/features/my-reports/view/ReportEdit.tsx, app/subscriber/src/features/my-reports/view/components/ReportEditForm.tsx, app/subscriber/src/features/my-reports/view/components/ReportSendForm.tsx, app/subscriber/src/features/search-page/components/advanced-search/components/sections/MoreOptions.tsx, app/subscriber/src/features/search-page/components/advanced-search/constants/DefaultAdvancedSearch.ts, app/subscriber/src/features/search-page/utils/filterFormat.ts
My Report form should disable editing after sending report to subscribers.
Fixed regression issue when configuring chart in report.
=> TNO-2162 Fix reports

app/subscriber/src/features/login/styled/UnauthenticatedHome.tsx
Change size to dynamically take up full screen.
=> Fix unauth page size

app/subscriber/src/components/section/Section.tsx, app/subscriber/src/components/section/styled/Section.tsx, app/subscriber/src/features/my-reports/admin/ReportSettings.tsx, app/subscriber/src/features/my-reports/admin/styled/ReportAdmin.tsx, app/subscriber/src/features/my-reports/view/styled/ReportEdit.tsx
Updated My Reports Settings tab.
=> Fix reports

app/editor/src/features/content/form/ContentForm.tsx
Simply increase the width of the `Columnist/Pundit` attribute
=> TNO-2120: Increase width of columnist on content form

api/net/Areas/Editor/Controllers/ContentController.cs, api/net/Areas/Services/Controllers/ContentController.cs
=> fix: #2200 - changed how content gets assigned a score

app/subscriber/src/components/tool-bar/ContentActionBar.tsx, app/subscriber/src/components/tool-bar/RemoveFromFolder.tsx, app/subscriber/src/components/tool-bar/index.ts, app/subscriber/src/components/tool-bar/styled/RemoveFromFolder.tsx, app/subscriber/src/components/tool-bar/styled/index.ts, app/subscriber/src/features/home/styled/Home.tsx, app/subscriber/src/features/manage-folder/ManageFolder.tsx, app/subscriber/src/features/manage-folder/styled/ManageFolder.tsx, app/subscriber/src/features/my-folders/styled/ConfigureFolder.tsx, app/subscriber/src/features/search-page/components/advanced-search/AdvancedSearch.tsx, app/subscriber/src/features/search-page/components/advanced-search/styled/AdvancedSearch.tsx, app/subscriber/src/features/search-page/components/advanced-search/utils/extractTags.ts, app/subscriber/src/index.scss
Ignore GIF quality using ffmpeg and having driver issues...
Allow users to enter tags from text area in advanced search
- fixes bug causing app to crash when `[` is entered
- can enter `[tag]` in text area to add valid tag, will automatically make uppercase if not already
Working on one more thing - leaving on draft.
Also updated manage folder and allow user to add content to report from here:
=> [Ready ✅] TNO-2141: Allow users to enter tags from text area in advanced search

api/net/Areas/Helpers/WorkOrderHelper.cs, libs/net/entities/WorkOrder.cs
- allows for service users to request transcript without exception
=> fix: # tno-2214 - remove exception on null user

app/editor/src/features/content/papers/Papers.tsx
- selectedIds was missing from FlexBoxTable config
=> fix: #tno-2232 - added missing selectedIds definition

app/subscriber/src/components/basic-search/BasicSearch.tsx, app/subscriber/src/components/basic-search/styled/BasicSearch.tsx
- better alignment for search in the header
- remove broken mobile search for now, until new approach for mobile is discussed with Bobbi
=> fix some layout issues

app/editor/src/features/content/form/ContentNavigation.tsx, app/editor/src/features/content/list-view/ContentListView.tsx, app/editor/src/features/content/papers/Papers.tsx, app/editor/src/features/content/papers/components/ReportActions.tsx, app/editor/src/features/content/papers/hooks/useColumns.tsx, app/editor/src/store/hooks/editor/index.ts, app/editor/src/store/hooks/editor/useContent.ts, app/editor/src/store/hooks/editor/usehooks-ts/index.ts, app/editor/src/store/hooks/editor/usehooks-ts/useEventCallback.ts, app/editor/src/store/hooks/editor/usehooks-ts/useEventListener.ts, app/editor/src/store/hooks/editor/usehooks-ts/useIsomorphicLayoutEffect.ts, app/editor/src/store/hooks/editor/usehooks-ts/useLocalStorage.ts, app/editor/src/store/slices/content/contentSlice.ts, app/editor/src/store/slices/content/useContentStore.ts
- in favor of localStorage plus event event emitter and subscription
=> fix: #tno-2176 - refactored aways use of shared state

app/subscriber/src/features/home/Home.tsx
Noticed another console warning while debugging the one in this ticket:
=> TNO-2185: Fix warning issue from React dev tools

app/subscriber/src/components/basic-search/styled/BasicSearch.tsx, app/subscriber/src/components/header/Header.tsx, app/subscriber/src/components/header/styled/Header.tsx, app/subscriber/src/components/navbar/styled/Navbar.tsx, app/subscriber/src/components/user-profile/styled/UserProfile.tsx, app/subscriber/src/features/landing/styled/Landing.tsx, app/subscriber/src/features/my-products/styled/MyProducts.tsx, app/subscriber/src/features/search-page/styled/SearchPage.tsx
- fixed numerous alignment and spacing issues
- content in the header is now of equal height and is vertically centered
- removed unneccsary padding from header
- changed height calculation for the left nav to avoid weird spacing issue
- removed extra svg padding from collpased navigation
- stop logout action from wrapping at narrower viewport
- removed dead css
=> fix: #tno-2236 - fix spacing issues

app/subscriber/src/components/header/styled/Header.tsx, app/subscriber/src/components/section/styled/PageSection.tsx, app/subscriber/src/features/my-products/styled/MyProducts.tsx, app/subscriber/src/features/my-reports/admin/styled/ReportAdmin.tsx, app/subscriber/src/features/my-reports/styled/MyReports.tsx, app/subscriber/src/features/my-reports/view/styled/ReportEdit.tsx
Just putting this up because I know @kylgarmor is working on some CSS as well and want to make sure we don't step on each other's toes!
- remove bottom border from headline to match new mock up
- make page section top margin consitent with all components
=> small css things

app/subscriber/src/features/press-gallery/PressGallery.tsx, app/subscriber/src/features/todays-commentary/TodaysCommentary.tsx, app/subscriber/src/features/top-stories/TopStories.tsx
=> TNO-2167 Remove header from list views

app/subscriber/src/components/tool-bar/AddToReportMenu.tsx, app/subscriber/src/features/content/view-content/FolderMenu.tsx
- just added link into existing toast to avoid adding more UI clutter
=> feat: #tno-1988 - added link to folder or report within existing toast popup

app/editor/src/features/admin/system-message/SystemMessageForm.tsx
I found a better approach to detect changes changing the Wysiwyg for it's formik counterpart.
=> TNO-2150 Change Wysiwyg component to FormikWysiwyg

app/subscriber/src/features/content/view-content/FolderMenu.tsx, app/subscriber/src/features/content/view-content/styled/FolderMenu.tsx
=> fix: #tno-2157 - disable action button to avoid empty name

api/node/src/utils/data.ts
=> Fix chart formatter logic

api/node/src/utils/data.ts, openshift/kustomize/tekton/base/tasks/git-conditions.yaml
Attempting to fix the Charts API.  It's failing to build any chart due to not handling null/undefined values.
=> Fix charts api

app/subscriber/src/features/my-minister/MyMinister.tsx
- needed to handle a list of ministers and their aliases instead of single
- also fixed issue with not using the aliases set by an admin
=> fix: #tno-2238 - changed handling of multiple ministers

app/editor/src/features/reports/av-overview/OverviewGrid.tsx, app/editor/src/features/reports/av-overview/styled/OverviewGrid.tsx
- Fixed some layout issues again
- Fixed incorrectly getting snippet time
- Picked up on another issue with clips remaining selected even if Evening Overview start time changes & clips are no longer available. Fixed:
=> TNO-2211: Fix some layout issues & snippet time on Evening Overview

app/editor/src/features/content/papers/Papers.tsx, app/editor/src/features/content/papers/components/ReportActions.tsx
- Fix iussues when trying to "Publish All" in Papers page
- Fix displayed item content is lost or overwritten
- Fix Unable to use "Publish All" functionality since moving away from common redux store for content
Before:
After:
=> TNO-2163: Fix issues with Papers page, updating content

app/editor/package.json, app/subscriber/package.json, app/subscriber/src/components/layout/styled/Layout.tsx, app/subscriber/src/components/table/styled/SubscriberTableContainer.tsx, app/subscriber/src/features/my-folders/ConfigureFolder.tsx, app/subscriber/src/features/my-folders/MyFolders.tsx, app/subscriber/src/features/my-folders/constants/columns.tsx, app/subscriber/src/features/my-folders/styled/ConfigureFolder.tsx, libs/npm/core/package.json, libs/npm/core/src/components/table/FlexboxTable.tsx, libs/npm/core/src/components/table/interfaces/ITableStyleProps.ts, libs/npm/core/src/components/table/styled/FlexboxTable.tsx
1. Fix sync issues, list view count is now updated and in sync when adding/removing from the config screen
2. Fix some styling
3. Allow filter select to be clear-able on the configure folder screen
4. Remove unused code
=> TNO-2195 Bugs

app/subscriber/src/components/layout/styled/Layout.tsx, app/subscriber/src/features/landing/styled/Landing.tsx
- commented out css left in place for a quick revert
=> fix: #tno-2250 - tweaked css to change scrollbar display

app/subscriber/src/components/date-filter/DateFilter.tsx, app/subscriber/src/components/date-filter/styled/DateFilter.tsx, app/subscriber/src/components/navbar/NavbarItems.tsx, app/subscriber/src/features/daily-overview/styled/AVOverviewPreview.tsx, app/subscriber/src/features/filter-media/FilterMedia.tsx, app/subscriber/src/features/filter-media/FilterMediaLanding.tsx, app/subscriber/src/features/filter-media/PreviousResults.tsx, app/subscriber/src/features/filter-media/constants/MediaFilterTypes.ts, app/subscriber/src/features/filter-media/constants/index.ts, app/subscriber/src/features/filter-media/index.ts, app/subscriber/src/features/filter-media/interfaces/IPreviousDate.ts, app/subscriber/src/features/filter-media/interfaces/index.ts, app/subscriber/src/features/filter-media/styled/FilterMedia.tsx, app/subscriber/src/features/filter-media/styled/FilterMediaLanding.tsx, app/subscriber/src/features/filter-media/styled/PreviousResults.tsx, app/subscriber/src/features/filter-media/styled/index.ts, app/subscriber/src/features/filter-media/utils/alphabetArray.ts, app/subscriber/src/features/filter-media/utils/index.ts, app/subscriber/src/features/home/constants/columns.tsx, app/subscriber/src/features/home/styled/Home.tsx, app/subscriber/src/features/landing/Landing.tsx, app/subscriber/src/features/press-gallery/styled/PressGallery.tsx, app/subscriber/src/features/router/AppRouter.tsx, app/subscriber/src/features/todays-commentary/styled/TodaysCommentary.tsx, app/subscriber/src/features/todays-front-pages/styled/TodaysFrontPages.tsx, app/subscriber/src/features/top-stories/styled/TopStories.tsx
** Going to make a seperate ticket to make some of this code shared as `MediaSection` and `FilterMedia` have some duplicate code in their `useEffects()` **
In this PR:
- new filter by media component
- alphabetic filter for longer lists
- hint indicator and actions when no content is returned (clickable and will take you to that filter)
- updates to date filter
- action bar added to list view
- two column layout
=> [UPDATED] TNO-2136, 2184: New filter by media 

app/editor/src/features/content/list-view/components/tool-bar/filter/DateRangeSection.tsx, app/editor/src/features/content/list-view/components/tool-bar/filter/FilterContentSection.tsx, app/editor/src/features/content/list-view/components/tool-bar/filter/styled/CreateNewSection.tsx, app/editor/src/features/content/list-view/components/tool-bar/filter/styled/DateRangeSection.tsx, app/editor/src/features/content/list-view/components/tool-bar/filter/styled/FilterContentSection.tsx, app/editor/src/features/content/list-view/components/tool-bar/filter/styled/index.ts
- switch the "clear" button to be more consistent with "clear" button on "adbacnced search
- fix spacing issue with rows lining up in "Filter Content"
- removed unnecessary width constraint on "create new content"
=> fix: #tno-2266 - fix css

app/subscriber/src/features/filter-media/FilterMediaLanding.tsx
- get rid of key error
- properly filter when clicking parent media group
- clear previously selected source when clicking parent group
- change default to all
=> filter media bugs

api/net/Areas/Admin/Controllers/AVOverviewController.cs
- if another template for STAT holiday is added, just add another value to the AVOverviewTemplateType enum
=>  feat: #2224 - subscribers will be kept in sync between weekend and weekday av overview

app/subscriber/src/features/filter-media/FilterMediaLanding.tsx, app/subscriber/src/features/filter-media/styled/FilterMediaLanding.tsx
- create proper scroll containers for both columns
- add hover interactions for options
=> Filter Media: fix scroll, add hover interactions

api/net/Areas/Helpers/ReportHelper.cs, libs/net/template/Converters/SearchAggregationHelper.cs, libs/net/template/TNO.TemplateEngine.csproj, services/net/reporting/ReportingManager.cs
- code to include aggregations on section was missing
- moved converter to shared library
=> fix: #tno-2269 - fixed reporting service

app/subscriber/src/features/filter-media/styled/FilterMediaLanding.tsx
After speaking with Kyle I have made a few adjustments to match the scrolling style of the rest of the application after the "scroll update"
=> Filter-Media: Change scroll behaviour to match rest of application

app/subscriber/src/features/my-minister/MyMinister.tsx
Quick improvement to add the full Minister Name into the query.
=> TNO-2106 Add Minister full name to query

app/subscriber/src/features/search-page/components/advanced-search/components/sections/DateSection.tsx, app/subscriber/src/features/search-page/utils/filterFormat.ts
@Fosol added a comment at ticket below, not sure if this is a bug or not
https://apps.itsm.gov.bc.ca/jira/browse/TNO-2183
=> TNO-2183: Fix advanced search date handling

api/net/Keycloak/CssHelper.cs
feels like I am on the right path here but I think there will be a last piece of the puzzle to trigger a token refresh in the UI to get updated roles maybe...?
=> fix: #tno-2262 - force Roles update in CSS if neccesary

app/subscriber/public/index.html, app/subscriber/src/components/content-list/ContentList.tsx, app/subscriber/src/components/content-list/ContentListContext.tsx, app/subscriber/src/components/content-list/ViewOptions.tsx, app/subscriber/src/components/content-list/constants/defaultValueListContext.ts, app/subscriber/src/components/content-list/constants/index.ts, app/subscriber/src/components/content-list/index.ts, app/subscriber/src/components/content-list/interfaces/IContentListContext.ts, app/subscriber/src/components/content-list/interfaces/IGroupByState.ts, app/subscriber/src/components/content-list/interfaces/IToggleStates.ts, app/subscriber/src/components/content-list/interfaces/index.ts, app/subscriber/src/components/content-list/styled/ContentList.tsx, app/subscriber/src/components/content-list/styled/ViewOptions.tsx, app/subscriber/src/components/content-list/styled/index.ts, app/subscriber/src/components/content-list/utils/determineToneIcon.tsx, app/subscriber/src/components/content-list/utils/groupContent.ts, app/subscriber/src/components/content-list/utils/index.ts, app/subscriber/src/components/content-list/utils/truncateTeaser.ts, app/subscriber/src/components/date-filter/styled/DateFilter.tsx, app/subscriber/src/css/_variables.module.scss, app/subscriber/src/css/_variables.scss, app/subscriber/src/features/home/Home.tsx, app/subscriber/src/features/home/home-filters/HomeFilters.tsx, app/subscriber/src/features/home/home-filters/styled/HomeFilters.tsx, app/subscriber/src/features/home/styled/Home.tsx, app/subscriber/src/features/landing/Landing.tsx, app/subscriber/src/features/todays-commentary/TodaysCommentary.tsx, app/subscriber/src/features/todays-commentary/styled/TodaysCommentary.tsx, app/subscriber/src/index.scss
Main changes:
- add common component `ContentList` so we can make pages more consistent
- bundle viewing options into `ViewOptions` so this can be displayed on all pages
- update styling to match mockups
=> [UPDATED] TNO-2233: Common component for content list views

app/subscriber/src/components/content-list/utils/determineToneIcon.tsx
didn't catch this one as all my test data had a tone value
=> fix dev bug when no tone value

app/subscriber/src/components/content-list/ContentList.tsx, app/subscriber/src/components/content-list/styled/ContentList.tsx
Add id check to ensure file stream only appears under corresponding item.
=> Content List - Inline Media Fix

app/subscriber/src/components/layout/DefaultLayout.tsx, app/subscriber/src/features/home/Home.tsx
not getting this locally strangely enough, but dev is throwing an error on home page. this should fix it
=> fix undefined error

app/editor/src/features/admin/event-of-the-day/EventOfTheDayList.tsx, app/editor/src/features/admin/event-of-the-day/hooks/useColumns.tsx, app/editor/src/features/admin/event-of-the-day/styled/EventOfTheDayList.tsx
- made record updates not lock the entire screen
- made topic field wider so it doesnt wrap
=> fix: #tno-2286 - performance improvements

app/subscriber/src/components/header/Header.tsx
=> TNO-2249 Revert header logo

libs/net/services/Managers/IngestManager`.cs
- added logging for failure count and retryLimit
=> feat: #tno-2264 - updated ingestmanager to allow restart after pre-set delay

app/subscriber/src/components/content-list/utils/groupContent.ts
Reverse the sort to show most recent content first.
=> TNO-2001 Reverse sort time

app/subscriber/src/store/hooks/app/useApp.ts, app/subscriber/src/store/hooks/useAjaxWrapper.ts
This fix is to handle the scenario when a request to the geolocation fails.
=> TNO-2293 Fix first time login issue

app/subscriber/src/features/search-page/styled/SearchPage.tsx
Small bug with the max-height on basic search
=> Fix max-height on basic search

api/net/Keycloak/CssHelper.cs
Fixing linting issues.
Fixing logic to extract and apply roles to an first time authenticated user.
=> TNO-2293 Fix unapproved user

app/subscriber/src/App.tsx, app/subscriber/src/components/content-list/ViewOptions.tsx, app/subscriber/src/features/landing/Landing.tsx, app/subscriber/src/features/search-page/SearchPage.tsx, app/subscriber/src/features/search-page/styled/SearchPage.tsx
This fixes a bug in regards to the inline media player on the search page as well as adds column options when you are on the Search Pages
=> Move ContentListProvider up a level

openshift/kustomize/services/content-historic/base/config-map.yaml, openshift/kustomize/services/content-historic/base/deploy.yaml, openshift/kustomize/services/content-historic/base/service.yaml, openshift/kustomize/services/content-historic/overlays/dev/kustomization.yaml, openshift/kustomize/services/content-historic/overlays/prod/kustomization.yaml, openshift/kustomize/services/content-historic/overlays/test/kustomization.yaml, openshift/kustomize/services/content/base/config-map.yaml, openshift/kustomize/services/content/base/deploy.yaml, openshift/kustomize/tekton/base/pipelines/buildah-all.yaml, openshift/kustomize/tekton/base/tasks/deploy-all.yaml, services/net/content/Config/ContentOptions.cs, services/net/content/ContentManager.cs
- updated build-all to reflect current state in openshift
- reordered params to match openshift for easier comparison in the future
=> feat: tno-2289 - split tno historic service out into own config

app/subscriber/src/features/my-reports/admin/components/ReportSectionGallery.tsx
When adding the Front Page Images section it will now show that it is using the default filter for front page images.
=> TNO-2315 Default gallery section to front page images

app/editor/package.json, app/subscriber/package.json, app/subscriber/src/features/home/Home.tsx, app/subscriber/src/features/utils/getBooleanActionValue.ts, app/subscriber/src/features/utils/index.ts, libs/npm/core/package.json, libs/npm/core/src/hooks/api/constants/Settings.ts
Was a discrepancy in my local as I had not updated my admin settings
=> Featured Content - Fix erroneous search of "Homepage" -> "Featured Story"

app/subscriber/src/components/content-list/ContentRow.tsx, app/subscriber/src/components/content-list/styled/ContentRow.tsx, app/subscriber/src/components/section/styled/PageSection.tsx
- ensure format is ok for items with long headlines
- add `Link` component in order to mark items as visited
=> TNO-2190, TNO-2196: Account for long headlines, and add visited color 

app/editor/src/features/admin/event-of-the-day/EventOfTheDayList.tsx, app/editor/src/features/admin/event-of-the-day/hooks/useColumns.tsx, app/editor/src/features/admin/event-of-the-day/styled/EventOfTheDayList.tsx
- also added display of Page & Section where set
=> fix: #tno-2291 - fix default sort to honor Source.SortOrder and PageNumber

app/subscriber/src/features/filter-media/FilterMediaLanding.tsx, app/subscriber/src/features/filter-media/styled/FilterMediaLanding.tsx
Some quick fixes for filter-media responsiveness (the below are reduced screen sizes)
=> TNO-2299: Filter media respoonsiveness

app/editor/src/features/content/utils/getSortBy.ts
- added additional sort criteria to the sort for page:section
- business only wants content sorted by source-page-section
=> feat: #tno-2300 - fix sorting on page:section

app/subscriber/src/components/basic-search/BasicSearch.tsx, app/subscriber/src/components/basic-search/styled/BasicSearch.tsx, app/subscriber/src/components/header/Header.tsx, app/subscriber/src/components/header/styled/Header.tsx, app/subscriber/src/components/navbar/Navbar.tsx
- navbar collapses automatically when mobile
- allow for search in mobile (temp styling to have it functional)
- fix various areas of responsiveness 
- removed logo text for smaller devices to fit search in header
(filter buttons need some love still)
=> TNO-2292: Mobile fixes

api/net/Areas/Admin/Controllers/TopicController.cs, app/editor/src/features/admin/event-of-the-day/EventOfTheDayList.tsx, app/editor/src/features/admin/event-of-the-day/hooks/useColumns.tsx, app/editor/src/features/admin/event-of-the-day/styled/EventOfTheDayList.tsx, app/editor/src/features/admin/topics/TopicFormSmall.tsx, app/editor/src/features/admin/topics/TopicList.tsx, app/editor/src/features/admin/topics/hooks/useColumns.tsx, app/editor/src/features/admin/topics/index.ts, app/editor/src/features/admin/topics/styled/TopicFormSmall.tsx, app/editor/src/features/admin/topics/styled/TopicList.tsx, app/editor/src/features/admin/topics/styled/index.ts
- content on the event of the day page is now sorted by topic type and then topic
- topics on the update topics page are ordered similarly
- topics in the drop down are also ordered
- new topics can be added on the update event of the day page
=> feat: #tno-2270 - address feedback from stakeholder

app/subscriber/src/components/content-list/ContentRow.tsx, app/subscriber/src/components/content-list/styled/ContentRow.tsx
=> Filter media bug fix

app/subscriber/src/features/my-reports/interfaces/IContentValidationErrors.ts, app/subscriber/src/features/my-reports/view/components/ContentEditForm.tsx, app/subscriber/src/features/my-reports/view/components/UserContentForm.tsx, app/subscriber/src/features/my-reports/view/styled/ReportEdit.tsx
Needed to implement individual validation, since there was no submit actions on the content form.
=> Tno 2278 report stories form validation

app/editor/src/features/content/papers/components/AdvancedFilter.tsx, app/editor/src/features/content/papers/components/ReportActions.tsx, app/subscriber/src/components/content-list/ContentListContext.tsx
A couple minor fixes not related to ingests.
=> Minor fixes

app/subscriber/src/features/my-reports/admin/ReportTemplate.tsx, app/subscriber/src/features/my-reports/admin/styled/ReportAdmin.tsx, app/subscriber/src/features/my-reports/view/components/ReportContentSectionRow.tsx
Splitting off some work while I figure out some other issues:
Make the subscriber icons for drag and drop consistent
=> TNO-2313: Make grab icon consistent

app/editor/src/features/content/form/ContentForm.tsx, app/editor/src/features/content/form/styled/ContentForm.tsx
=> TNO-2215 Audio video layout fix

services/net/reporting/ReportingManager.cs
Send email alerts on situations that the service was only logging errors.
=> Tno 2330 send email alerts on failure

api/net/Areas/Editor/Controllers/ContentController.cs, app/editor/src/features/content/form/ContentForm.tsx, app/editor/src/features/content/form/ContentNavigation.tsx, app/editor/src/features/content/form/components/tool-bar/form/StatusSection.tsx, app/editor/src/features/content/form/constants/defaultFormValues.ts, app/editor/src/features/content/form/hooks/useContentForm.ts, app/editor/src/features/content/form/utils/getContentPath.ts, app/editor/src/features/content/form/utils/index.ts, app/editor/src/features/content/form/utils/setTime.ts
Fixed issue where published time was not working correctly.
> Issues like this make me wonder if anyone was testing this when they were working on it :(
- Updated Editor App
- Fixed Content Form Time input
=> TNO-2326 Fix published time

services/net/indexing/IndexingManager.cs
Send email alerts on Notification fails
Ches service/options added to the service.
=> TNO-2335 send email alerts on notifications

services/net/content/ContentManager.cs
Send email alerts on Notification fails
Ches service/options added to the service.
=> TNO-2334 send email alerts on notifications

services/net/transcription/TranscriptionManager.cs
Send email alerts on Notification fails
Ches service/options added to the service.
=> TNO-2332 send email alerts on notifications

app/editor/src/features/content/form/components/upload/Upload.tsx, app/editor/src/features/content/form/hooks/useContentForm.ts
Next snippet will now remove the attached file.
- Fixed Content Form Next Snippet functionality
=> TNO-2326 Fix next snippet

app/subscriber/src/components/date-filter/DateFilter.tsx
Fix to stop infinite search loop.
=> Fix infinite search

services/net/reporting/ReportingManager.cs
Adding additional useful information when CHES notification fails.
=> Add email alert debugging info

libs/net/dal/Migrations/1.0.128/Up/PostUp/00-Filter.sql
- fix issue with Not Applicable showing up in report output
=> fix: #tno-2359 - fixed query

services/net/scheduler/SchedulerManager.cs
Send email alert on scheduler fail.
=> TNO-2337 Send email alert on failure

app/editor/src/features/content/form/ContentForm.tsx, app/editor/src/features/content/form/ContentStoryForm.tsx, app/editor/src/features/content/form/ContentTranscriptForm.tsx, app/editor/src/features/content/form/hooks/index.ts, app/editor/src/features/content/form/hooks/useExtractTags.ts
Fixed issue where tags were not being parsed from the transcription tab.
=> TNO-2326 Parse tags

app/subscriber/src/css/_variables.module.scss, app/subscriber/src/css/_variables.scss, app/subscriber/src/features/login/BrowserLogin.tsx, app/subscriber/src/features/login/Copyright.tsx, app/subscriber/src/features/login/MobileLogin.tsx, app/subscriber/src/features/login/SystemMessage.tsx, app/subscriber/src/features/login/UnauthenticatedHome.tsx, app/subscriber/src/features/login/index.ts, app/subscriber/src/features/login/styled/BrowserLogin.tsx, app/subscriber/src/features/login/styled/Copyright.tsx, app/subscriber/src/features/login/styled/MobileLogin.tsx, app/subscriber/src/features/login/styled/SystemMessage.tsx, app/subscriber/src/features/login/styled/UnauthenticatedHome.tsx, app/subscriber/src/features/login/styled/index.ts
Splitting off some work from PRs - this no longer includes the updates to mobile content list view
- adjust login pages to Bobbi's suggestions
- slight color adjustments 
- responsiveness fixes 
- remove dead code
=> TNO-2341: Updates to login page

libs/net/services/Actions/Managers/IngestActionManager`.cs, libs/net/services/Managers/IngestManager`.cs, services/net/command/CommandAction`.cs, services/net/contentmigration/ContentMigrationAction.cs, services/net/filemonitor/FilemonitorAction.cs, services/net/syndication/SyndicationAction.cs
Allow services to user their config while sending email alerts.
=> TNO-2333 Ingest Manager/services override fix

app/subscriber/src/features/login/styled/BrowserLogin.tsx, app/subscriber/src/features/login/styled/SystemMessage.tsx
Minor things I noticed while testing!
=> Login page tweaks

app/editor/src/features/admin/event-of-the-day/styled/EventOfTheDayList.tsx
- fix jankiness when hovering over row with long text
- clipboard icon now aligns with end of text inline
=> feat: #tno-2375 - add action to copy title text

libs/net/services/Managers/ServiceManager`.cs
Environment added to email subject and body.
=> TNO-2380 Add env to email alert

app/subscriber/src/components/basic-search/BasicSearch.tsx, app/subscriber/src/components/basic-search/styled/BasicSearch.tsx, app/subscriber/src/components/header/Header.tsx, app/subscriber/src/components/layout/DefaultLayout.tsx, app/subscriber/src/components/layout/styled/Layout.tsx, app/subscriber/src/components/media-type-filters/FilterOptions.tsx, app/subscriber/src/components/media-type-filters/styled/MediaTypeFilters.tsx, app/subscriber/src/components/share-menu/ShareMenu.tsx, app/subscriber/src/components/share-menu/styled/ShareMenu.tsx, app/subscriber/src/features/login/styled/BrowserLogin.tsx, app/subscriber/src/features/login/styled/SystemMessage.tsx, app/subscriber/src/features/search-page/SearchPage.tsx
- change search bar for mobile users
- conditional renders for excess info 
- better responsiveness
- conditional gird template layouts to accommodate for new search placement
=> TNO-2343: Mobile enhancements

app/subscriber/src/components/content-list/ContentRow.tsx, app/subscriber/src/features/content/view-content/ViewContent.tsx, app/subscriber/src/features/my-reports/ReportCard.tsx, app/subscriber/src/features/my-reports/utils/getLastPublishedOn.ts, app/subscriber/src/features/my-reports/view/components/ContentForm.tsx, app/subscriber/src/features/my-reports/view/components/ReportContentSectionRow.tsx, app/subscriber/src/features/my-reports/view/components/UserContentForm.tsx, app/subscriber/src/features/press-gallery/PressGallery.tsx, app/subscriber/src/features/utils/formatDate.ts, app/subscriber/src/features/utils/index.ts
- update date formatting to [gov standards](https://www2.gov.bc.ca/gov/content/governments/services-for-government/service-experience-digital-delivery/web-content-development-guides/web-style-guide/writing-guide/numbers#years-and-time)
- create util function to organize formatting in one place
=> tno-2314 consistent date

app/subscriber/src/features/my-reports/view/styled/ReportEdit.tsx
The main issue in this ticket seems to have been fixed with my previous fix in TNO-2280
=> TNO-2283: Simple styling fix for editing reports

libs/net/models/Areas/Subscriber/Models/Content/ContentModel.cs
=> fix: #tno-2384 - fix issues with seies add/search

libs/net/dal/Services/SourceService.cs
Add Search Mapping Media types while inserting and updating Sources.
=> TNO-2398 Add media types on source update and insert

app/editor/src/features/admin/reports/styled/ReportForm.tsx
=> TNO-2247: Make report preview full height instead of scrollable container

app/editor/src/features/content/form/components/tags/Tags.tsx
Removing tags in the summary/body will no longer remove tags because it was resulting in issues.
=> TNO-2373 Fix parse tags

api/net/Areas/Editor/Controllers/ContentController.cs, api/net/Areas/Helpers/TopicScoreHelper.cs, api/net/Areas/Services/Controllers/ContentController.cs
- fixed score not being assigned when calculated
=> fix: #tno-2415 - fixed incorrect property check for Source

app/subscriber/src/components/section/Section.tsx, app/subscriber/src/components/section/styled/Section.tsx, app/subscriber/src/features/my-reports/ReportCard.tsx, app/subscriber/src/features/my-reports/styled/MyReports.tsx, app/subscriber/src/features/my-reports/utils/calcNextReportSend.ts, app/subscriber/src/features/my-reports/utils/calcNextScheduleSend.ts, app/subscriber/src/features/my-reports/utils/getLastSent.ts, app/subscriber/src/features/my-reports/utils/index.ts, app/subscriber/src/features/my-reports/view/components/ReportSendForm.tsx, app/subscriber/src/features/utils/formatDate.ts
Updating My Reports page to match new design.
> The View report button is not hooked up to display the right panel preview yet
=> TNO-2349 Update my reports

openshift/kustomize/core-nlp/base/deploy.yaml, openshift/kustomize/services/extract-quotes/base/deploy.yaml, openshift/kustomize/tekton/base/tasks/git-conditions.yaml
- fix kustomize git-conditions.yaml
- replace dashes with underscores for the win
=> feat: #tno-1729 - baseline extract quotes service

app/subscriber/src/components/header/env.json, app/subscriber/src/features/daily-overview/MediaOverviewIcons.tsx, libs/net/dal/Migrations/1.0.131/Up/PostUp/00-WeekdayTemplateUpdate.sql, libs/net/dal/Migrations/1.0.131/Up/PostUp/01-WeekendTemplateUpdate.sql, libs/net/dal/Migrations/20240315213105_1.0.133.Designer.cs, libs/net/dal/Migrations/20240315213105_1.0.133.cs
Trying to test - but ran into another environment issue. On draft until I fix and test again!
In this PR:
- update icons to match mock-up
- new migration 1.0.133
- fix bug of icons not displaying on report rows (for video and transcript available)
=> TNO-2267: Fix and update icons for evening overview

api/net/Areas/Helpers/ReportHelper.cs, app/subscriber/src/features/router/AppRouter.tsx, libs/net/template/IReportEngine.cs, libs/net/template/Models/BaseTemplateModel.cs, libs/net/template/Models/Reports/ReportEngineContentModel.cs, libs/net/template/ReportEngine.cs, services/net/reporting/ReportingManager.cs
The link at the bottom of a report should go to the environment the report was generated and it should load the report or report instance.
=> TNO-2295 Report instance link in email

app/subscriber/src/components/bar/Bar.tsx, app/subscriber/src/components/section/PageSection.tsx, app/subscriber/src/features/my-reports/MyReports.tsx, app/subscriber/src/features/my-reports/ReportCard.tsx, app/subscriber/src/features/my-reports/ReportPreview.tsx, app/subscriber/src/features/my-reports/edit/styled/ReportEditForm.tsx, app/subscriber/src/features/my-reports/edit/view/ReportInstanceView.tsx, app/subscriber/src/features/my-reports/styled/MyReports.tsx, app/subscriber/src/features/my-reports/view/components/ReportEditForm.tsx
We can now view a report in the right panel.
=> TNO-2350 Update My Reports

app/subscriber/src/App.tsx, app/subscriber/src/features/search-page/SearchPage.tsx, app/subscriber/src/features/search-page/SearchPageContext.tsx, app/subscriber/src/features/search-page/components/advanced-search/AdvancedSearch.tsx, app/subscriber/src/features/search-page/components/advanced-search/styled/AdvancedSearch.tsx, app/subscriber/src/features/search-page/index.ts, app/subscriber/src/features/search-page/styled/SearchPage.tsx
- add ability to minimize advanced search
- add back to basic button
- styling changes
=> TNO-2311: Minimize advanced search

app/subscriber/src/features/my-reports/ReportPreview.tsx, app/subscriber/src/features/my-reports/styled/MyReports.tsx, app/subscriber/src/store/hooks/subscriber/useReportInstances.ts
Fixed infinite loop when fetching report info and the generating of the preview was taking too long.
Fixed issue where start next report wasn't updating redux state.
=> TNO-2350 Fix my reports

app/editor/src/features/admin/reports/ReportForm.tsx, app/editor/src/features/admin/reports/validation/ReportFormScheduleSchema.ts, app/editor/src/features/admin/reports/validation/ReportFormSchema.ts, app/subscriber/src/features/my-reports/edit/validation/ReportFormScheduleSchema.ts, app/subscriber/src/features/my-reports/edit/validation/ReportFormTemplateSchema.ts, app/subscriber/src/features/my-reports/edit/validation/index.ts
Added validation on report schedule with the following rules:
- The times fields must respect the 24 hour format
- The time fields are required when the schedule is enabled.
=> TNO-2402 Schedule validations

app/editor/src/features/content/form/ContentForm.tsx, app/editor/src/features/content/validation/ContentFormSchema.ts
Print Content will no longer require 'Byline' or 'Section'.
=> TNO-2437 Remove required field validation

api/net/Areas/Editor/Controllers/ContentController.cs, api/net/Areas/Services/Controllers/ContentController.cs
The main reason content was not being added to reports was because the `PostOn` date was not being set.  Manually testing the report did set the value and thus was working.  This should resolve the main Morning Report issues.
=> Fix Content PostedOn

api/net/Areas/Subscriber/Controllers/ReportController.cs, app/subscriber/src/features/my-reports/edit/content/ContentEditForm.tsx, app/subscriber/src/features/my-reports/edit/content/components/UserContentForm.tsx, libs/net/dal/Services/ReportService.cs, libs/net/models/Areas/Subscriber/Models/Report/ReportInstanceContentModel.cs
Fixed several issues related to  adding or creating new content for reports.
=> TNO-2425 Fix add to report

app/editor/src/features/admin/contributors/ContributorForm.tsx, app/subscriber/src/features/filter-media/FilterMediaLanding.tsx, app/subscriber/src/features/filter-media/styled/FilterMediaLanding.tsx, app/subscriber/src/features/home/Home.tsx
- all selected by default 
- can toggle select all with checkbox or row click
- fix tooltip for aliases 
- fix tooltip in toast 
- minor styling
=> TNO-2327: Add checkboxes to filter media page

app/subscriber/src/features/filter-media/FilterMediaLanding.tsx
Account for list options, some things got broken in my rebase.
=> Bug fixes for checkboxes on filter media

app/subscriber/src/features/my-reports/edit/ReportEditPage.tsx
It will now handle reports that do not exist.
=> TNO-2400 Handle no report

app/editor/src/features/content/list-view/ContentListView.tsx
Completed transcripts will no longer be included in the Content List View.
=> TNO-2376 Fix pending transcript

libs/net/dal/Services/ReportService.cs
Fixed several bugs related to reports.
- Fixed saving report with duplicate filter
- Fixed report section 'Remove Duplicate Content' functionality
=> TNO-2435 Fix Reports

app/subscriber/src/features/my-reports/edit/ReportEditContext.tsx, app/subscriber/src/features/my-reports/edit/ReportEditForm.tsx, app/subscriber/src/features/my-reports/edit/ReportEditMenu.tsx, app/subscriber/src/features/my-reports/edit/constants/ReportMainMenuOption.ts, app/subscriber/src/features/my-reports/edit/settings/ReportEditDetailsForm.tsx, app/subscriber/src/features/my-reports/edit/settings/ReportEditTemplateForm.tsx, app/subscriber/src/features/my-reports/edit/settings/index.ts, app/subscriber/src/features/my-reports/edit/settings/styled/ReportEditDetailsForm.tsx, app/subscriber/src/features/my-reports/edit/settings/styled/ReportEditPreferencesForm.tsx, app/subscriber/src/features/my-reports/edit/settings/styled/ReportEditSendForm.tsx, app/subscriber/src/features/my-reports/edit/settings/styled/index.ts, app/subscriber/src/features/my-reports/edit/styled/ReportEditForm.tsx
Updated editing my reports to include a new Info tab.
=> TNO-2473 Update report

app/subscriber/src/store/hooks/subscriber/useFilters.ts
- viewing saved search does not seem to try to save the search any more
- fixed some copy and paste errors
=> TNO-2342: small fixes

app/subscriber/src/features/filter-media/FilterMediaLanding.tsx
Fix checkbox bug on Filter Media page
=> TNO-2327 bug: Checkbox not checking

app/subscriber/src/features/filter-media/FilterMedia.tsx, app/subscriber/src/features/filter-media/FilterMediaLanding.tsx
Filter by Media Type should not default to select all items in list.
=> TNO-2478 Fix Filter by Media Type

app/editor/src/components/topic/Topic.tsx
- need to show disabled topic in list if it is associated with current content
=> fix: #tno-2419 - fix ui discrepancy between EoD List and report

services/net/extract-quotes/CoreNLP/models/NerConfidences.cs
- fixed incorrect data type mapping
=> fix: #tno-2474 - stop log file spam

app/editor/src/components/topic/Topic.tsx
- fixed issue with getting "new" value onChange
=> fix: #tno-2422 - fix for new topics

openshift/kustomize/kafka/kowl/base/deploy.yaml
- kowl:v1.5.0 already existed in our registry
=> fix: #tno-2451 - changed image reference for kustomize / kowl

app/editor/src/features/admin/filters/FilterFormPreview.tsx, app/editor/src/features/admin/reports/ReportFormPreview.tsx, app/editor/src/features/admin/reports/components/ReportSectionContent.tsx, app/subscriber/src/features/search-page/components/advanced-search/components/sections/MoreOptions.tsx
Trying to figure out why the Corpcal is not showing up in reports.
- Fixed Editor Filter admin testing page
- Fixed Editor Report admin preview page
- Rephrased search unpublished stories
=> TNO-2487 Debug corpcal issue

app/editor/src/features/content/list-view/components/tool-bar/filter/ShowOnlySection.tsx
Position changes as requested.
=> TNO-2382 Component position fix

app/editor/src/features/content/list-view/ContentListView.tsx
- if an editor creates branch new content, add it to the content list view ignoring any filters
=> fix: #tno-1891 - add new content to the content list

libs/net/dal/Services/WorkOrderService.cs
I removed a null check by accident.
Need to test this change in dev.
=> Tno 2434 id param fix

libs/net/dal/Services/WorkOrderService.cs
Null check while mapping the output.
=> Tno 2434 check null while mapping content

libs/net/dal/Migrations/20240409200843_1.0.142.Designer.cs, libs/net/dal/Migrations/20240409200843_1.0.142.cs
Fixing issue I introduced in the last PR by entering the wrong version number.
=> Fix DB Migration 1.0.142

app/editor/Dockerfile.local, app/editor/Dockerfile.nginx, app/editor/Dockerfile.rhel8, app/subscriber/Dockerfile.local, app/subscriber/Dockerfile.nginx, app/subscriber/Dockerfile.rhel8, network/nginx/Dockerfile
- also updated unprivileged image to nginxinc/nginx-unprivileged:1.24
=> fix: #tno-2509 - updated nginx to 1.25.4

app/subscriber/src/features/my-folders/ConfigureFolder.tsx
Splitting this off from the time input as I am facing a few bugs...
- add the ability in configure folder to update the name of the selected folder
- list will update in real time
=> TNO-2463: Allow user to rename folder

libs/npm/core/src/utils/array/getSourceOptions.ts
- Fix displayName function to return the short name if it exists
also need tno-core update.
=> Fix displayName function

app/editor/src/features/content/form/styled/ContentTranscriptForm.tsx
=> TNO-2397 Transcript vertical space fix

app/subscriber/src/components/tool-bar/ContentActionBar.tsx, app/subscriber/src/features/manage-folder/ManageFolder.tsx, app/subscriber/src/features/my-folders/MyFolders.tsx, app/subscriber/src/features/my-folders/utils/getTotalContentLength.ts, app/subscriber/src/features/my-folders/utils/index.ts
-- have props not display "add to folder"
-- refresh myfolders if folder contents length changed
=> Tno 2506 & 2505 remove "add to folder"

app/subscriber/src/features/my-folders/ConfigureFolder.tsx, app/subscriber/src/features/my-folders/FolderLanding.tsx, app/subscriber/src/features/my-folders/MyFolders.tsx, app/subscriber/src/features/my-folders/Schedule.tsx, app/subscriber/src/features/my-folders/styled/ConfigureFolder.tsx, app/subscriber/src/features/my-reports/edit/ReportEditMenu.tsx, app/subscriber/src/features/my-reports/edit/view/ReportInstanceView.tsx, app/subscriber/src/store/hooks/subscriber/useFolders.ts, services/net/scheduler/SchedulerManager.cs
Several bug fixes related to My Folders.
- Change 'Apply' button to 'Run Filter'
- Fix 'Run Filter' functionality
- Change Button component to the common styled one for the Subscriber site
- Fix loading state bug
- Fix sort order of folders
- Fix Formik undefined initial state bug (PLEASE USE THE DEVELEPOR WINDOW WHEN TESTING)
=> Fix My Folders

libs/npm/core/src/components/link/Link.tsx, libs/npm/core/src/components/link/styled/Link.tsx
Added a default icon to the TNO link component, adjusted the style to separate the elements slightly, and added an underline. Hoping to make it clear to users that this is a URL link.
=> Tno 2490 better toast 

app/subscriber/src/components/button/styled/Button.tsx, app/subscriber/src/components/form/timeinput/TimeInput.tsx, app/subscriber/src/features/my-folders/Schedule.tsx, app/subscriber/src/features/my-reports/edit/ReportEditActions.tsx, app/subscriber/src/features/my-reports/edit/ReportEditForm.tsx, app/subscriber/src/features/my-reports/edit/ReportEditPage.tsx, app/subscriber/src/features/my-reports/edit/content/stories/ContentActions.tsx, app/subscriber/src/features/my-reports/edit/settings/ReportEditSendForm.tsx, app/subscriber/src/features/my-reports/edit/settings/styled/ReportEditSendForm.tsx, app/subscriber/src/features/my-reports/edit/settings/template/ReportSchedule.tsx, libs/net/core/Extensions/DateTimeExtensions.cs, libs/net/dal/Services/ReportService.cs, services/net/reporting/ReportingManager.cs, services/net/scheduler/SchedulerManager.cs
This resolves an issue where the auto report would have no content in it.
Also added additional functionality to the scheduling which allows easier testing of scenarios.
- Updated Subscriber app
- Updated Scheduler Service
- Updated Reporting Service
- Provided a way to generate an auto report in the same day that one has already been sent
- Fixed empty report bug
- Fixed SignalR issue with reports
- Disabled save button when report has been submitted
=> Fix auto reports

app/subscriber/src/components/tool-bar/ContentActionBar.tsx, app/subscriber/src/store/slices/settings/settingsSlice.ts
Forgot to add this file to my last commit... was driving me nuts why it was working locally and not on dev
=> TNO-2414: Forgotten file 

services/net/folder-collection/FolderCollectionManager.cs
The Folder Collection Service filter logic was incorrect.  It should now add content to folders.
=> Fix Folder Collection Service

app/subscriber/src/components/content-list/ContentReportPin.tsx, app/subscriber/src/components/content-list/styled/ContentReportPin.tsx, app/subscriber/src/features/top-stories/styled/TopStories.tsx
Enhance the ContentReportPin component: add an underline effect on the headline and a background highlight on the report links when hovered.
Improved the user experience by providing clear visual cues for links.
=> TNO-2507 Enhance ContentReportPin component 

app/editor/src/features/admin/ingests/configurations/Newspaper.tsx, app/editor/src/features/admin/ingests/configurations/styled/IngestConfiguration.tsx, services/net/filemonitor/FilemonitorAction.cs
Created config to title case insert services.
Title case the Author name if the Configuration IS checked AND if it's All Caps.
=> TNO-2492 Title case if all caps and config is enabled

openshift/kustomize/services/notification/overlays/dev/kustomization.yaml, openshift/kustomize/services/notification/overlays/prod/kustomization.yaml, openshift/kustomize/services/notification/overlays/test/kustomization.yaml, openshift/kustomize/services/reporting/overlays/dev/kustomization.yaml, openshift/kustomize/services/reporting/overlays/prod/kustomization.yaml, openshift/kustomize/services/reporting/overlays/test/kustomization.yaml, openshift/kustomize/shared_resources/overlays/dev/kustomization.yaml, openshift/kustomize/shared_resources/overlays/prod/kustomization.yaml, openshift/kustomize/shared_resources/overlays/test/kustomization.yaml
- moved ches username and password secrets to shared_resources
=> fix: #tno-2580 - fixed config mapping

app/subscriber/src/features/login/styled/MobileLogin.tsx
fix the mobile view in subscriber login
=> TNO-2549 Fix flex-direction and padding in MobileLogin component

app/subscriber/src/features/daily-overview/styled/AVOverviewPreview.tsx
- center the page
- resize icons so they fit
=> Small AV overview changes

app/subscriber/src/features/utils/formatDate.ts
Small change to remove the 12 hour clock format from the View Content information bar
=> TNO-2556: Remove 12 hour clock format from content info bar

app/subscriber/src/features/my-reports/edit/ReportEditPage.tsx, app/subscriber/src/features/my-reports/edit/view/ReportSendForm.tsx, libs/net/ches/ChesService.cs, services/net/reporting/ReportingManager.cs, tools/scripts/variables.sh
Improving the error information when CHES fails.  
Fixed a bug in the My Reports.
Fixed bug with setup of `.env` introduced when a new version of Keycloak was added.
=> TNO-2589 Update Reporting Service

app/subscriber/src/features/search-page/components/advanced-search/AdvancedSearch.tsx
When saving search it will no longer attempt to save and will throw a toast error when:
- it is a duplicate name
- the user has not set a name yet
PS. Just having some issues with the folders area... will hopefully get that up soon
=> TNO-2528: Basic validation for saving search

app/subscriber/src/components/media-type-filters/FilterOptions.tsx
Add user preferences saving in FilterOptions.
the preference saving function will add"filterPreference" in it.
refresh page will fetch filterPreference from the server.
=> Add user preferences saving in FilterOptions component

app/editor/src/features/content/form/constants/timeLogColumns.tsx
Smaller minimum column, and a "middle" size.
=> TNO-2540 Added more granularity to time log columns modal

app/subscriber/src/features/content/view-content/ViewContent.tsx
Small PR to show the content transcript when present, not the summary by default
=> TNO-2486: Always show transcript if available 

docker-compose.yml
Doesn't need to be a `main` profile.
=> Remove coreNLP

app/subscriber/src/components/date-filter/DateFilter.tsx, app/subscriber/src/features/search-page/components/advanced-search/components/sections/DateSection.tsx, docker-compose.yml, services/docker-compose.yml
I have fixed the advanced search date logic.
=> Fix advanced search

app/subscriber/src/components/content-list/utils/groupContent.ts
The results with no source were removed due not being possible to group by source.
Just added a check to add other source when source does not exist.
=> Tno 2367 filter by media group by othersource

app/subscriber/src/features/home/Home.tsx, app/subscriber/src/features/todays-front-pages/TodaysFrontPages.tsx, app/subscriber/src/features/utils/getBooleanActionValue.ts, app/subscriber/src/store/hooks/lookup/useSettings.ts, app/subscriber/src/store/slices/settings/interfaces/ISettingsState.ts, app/subscriber/src/store/slices/settings/settingsSlice.ts, libs/net/dal/Migrations/1.0.158/Up/PostUp/00-Filters.sql
There were several logic bugs for generating search queries that used the date changing component.
=> Fix Front Page Images

app/subscriber/src/features/manage-folder/ManageFolder.tsx, app/subscriber/src/features/manage-folder/styled/ManageFolder.tsx
The close button hides the Manage Folder panel.
=> TNO-2590 Add close icon to Manage Folder

app/subscriber/src/features/my-reports/edit/content/stories/ContentForm.tsx
This is to resolve an issue when editing report content that loses data.
=> TNO-2610 Fix edit report content

app/subscriber/src/css/_variables.module.scss, app/subscriber/src/css/_variables.scss, app/subscriber/src/features/my-reports/ReportCard.tsx, app/subscriber/src/features/my-reports/components/StartNextReportInfo.tsx, app/subscriber/src/features/my-reports/edit/ReportEditActions.tsx, app/subscriber/src/features/my-reports/edit/ReportEditMenu.tsx, app/subscriber/src/features/my-reports/edit/content/stories/ReportSectionContent.tsx, app/subscriber/src/features/my-reports/edit/content/stories/ReportSectionGallery.tsx, app/subscriber/src/features/my-reports/edit/content/stories/ReportSectionMediaAnalytics.tsx, app/subscriber/src/features/my-reports/edit/styled/ReportEditForm.tsx, app/subscriber/src/features/my-reports/utils/getLastSent.ts, openshift/kustomize/services/event-handler/base/config-map.yaml
An Auto Report can now be manually started.  It displays a warning to inform the user they will lose their changes if the next scheduled send is executed.
=> TNO-2607 Start next report

app/subscriber/src/components/share-menu/ShareMenu.tsx, app/subscriber/src/components/tool-bar/ContentActionBar.tsx, app/subscriber/src/features/commentary/Commentary.tsx, app/subscriber/src/features/home/Home.tsx, app/subscriber/src/features/my-colleagues/ColleagueCard.tsx, app/subscriber/src/features/my-colleagues/ColleagueEdit.tsx, app/subscriber/src/features/my-colleagues/MyColleagues.tsx, app/subscriber/src/features/top-stories/TopStories.tsx, app/subscriber/src/store/hooks/subscriber/useColleagues.ts, app/subscriber/src/store/slices/profile/interfaces/IProfileState.ts, app/subscriber/src/store/slices/profile/profileSlice.ts, app/subscriber/src/store/slices/profile/useProfileStore.ts
Fixed several bugs and implementation issues on the Subscriber app.
- Featured Stories date filter
- Top Stories date filter
- Removed need to search for colleagues every single click
- Fixed infinite request bug for colleagues when there are none
=> Various bug fixes for subscribers

app/subscriber/src/features/todays-commentary/TodaysCommentary.tsx
Initial load was not working due to incorrect date filter.
=> Fix Today's Commentary

app/subscriber/src/features/hooks/useSubMediaGroups.ts
Remove the "All" option from media types.
=> TNO-2272 Remove "All" option

app/subscriber/src/features/my-folders/ConfigureFolder.tsx, app/subscriber/src/features/my-folders/FolderContext.tsx, app/subscriber/src/features/my-folders/FolderLanding.tsx, app/subscriber/src/features/my-folders/MyFolders.tsx, app/subscriber/src/features/my-folders/constants/columns.tsx, app/subscriber/src/features/my-folders/index.ts, libs/net/dal/Services/FolderService.cs
Was looking in all the wrong places
- moved event updates outside the conditional check for updating content 
- also now using context provider as it fixed some state issues I was experiencing when switching between folder configurations
=> Folder Schedule Bugs

app/subscriber/src/components/user-profile/UserProfile.tsx, app/subscriber/src/components/user-profile/styled/UserProfile.tsx
Add a dropdown icon and adjust the styles to create a hover effect when the mouse over it.
=> add icon and hover effect on user name TNO-2621

app/subscriber/src/components/content-list/utils/groupContent.ts
Added short name (Common Call) to group display name.
=> TNO-2272 Add Common call to group description

app/subscriber/src/components/user-profile/UserProfile.tsx
quick fix to make the icon clickable
=> TNO-2621 make the icon clickable

app/subscriber/src/features/hooks/useSubMediaGroups.ts
After a quick review with Scott, we are just displaying source's regular names.
=> TNO-2272 Display only source regular name

app/subscriber/src/components/date-filter/DateFilter.tsx, app/subscriber/src/features/search-page/SearchPage.tsx, app/subscriber/src/features/search-page/components/advanced-search/components/sections/DateSection.tsx
Fix Subscriber Advanced Search.
=> TNO-2700 Fix Advanced Search

api/net/Areas/Helpers/WorkOrderHelper.cs
When the transcription subscriber endpoint was called, was lacking configuration.
Once detected, was a simple fix.
=> TNO-2680 Add config param on request

app/subscriber/src/features/search-page/components/advanced-search/AdvancedSearch.tsx, app/subscriber/src/features/search-page/styled/SearchPage.tsx
Allow the user to save changes in the current search when modifying the settings:
When user clicks on Save Changes, the updates are saved in the same record:
When user wants to create a series of searches based on a general search, the user can modify the search and click on Save image next to the search name. For instance, the user can create an individual search for each province:
The records in the database include the search series:
Story: https://apps.itsm.gov.bc.ca/jira/browse/TNO-2671
=> TNO-2671: Saved changes in search && Create new search

app/subscriber/src/features/content/view-content/ViewContent.tsx, app/subscriber/src/features/settings/MyMinisterSettings.tsx, app/subscriber/src/store/hooks/subscriber/useMinisters.ts, app/subscriber/src/store/slices/profile/interfaces/IProfileState.ts, app/subscriber/src/store/slices/profile/profileSlice.ts, app/subscriber/src/store/slices/profile/useProfileStore.ts
The My Minister page had some serious implementation issues.
- It was making multiple updates to the user preferences
- It didn't handle invalid or deleted ministers
- It will now only save when you click 'Save'
=> Fix My Minster

app/subscriber/src/features/my-folders/ConfigureFolder.tsx, app/subscriber/src/features/my-folders/styled/ConfigureFolder.tsx, services/net/event-handler/EventHandlerManager.cs
The Event Handler Service has had a build bug since we added email error handling.
Also fixed some minor My Folder bugs and UI issues.
=> Fix Event Handler Service

app/subscriber/src/features/my-reports/edit/content/stories/ContentForm.tsx, app/subscriber/src/features/my-reports/edit/content/stories/UserContentForm.tsx, app/subscriber/src/features/my-reports/styled/MyReports.tsx
Fixing bug related to the editing content in a report.  This was a weird one and indicates a React build bug.
=> TNO-2709 Fix report edit content

app/subscriber/src/features/my-folders/ConfigureFolder.tsx
Toggle added to only display the filter select when Auto-populate is checked
- Clears the folder filters when unselected
- Checks on save if there's a selected filter and Auto-populate is checked
=> TNO-2681 Toggle filter select

libs/net/kafka/Models/Topic.cs, services/net/content/ContentManager.cs, services/net/contentmigration/migrators/ClipMigrator.cs, services/net/contentmigration/migrators/PaperMigrator.cs
The TNO Migration will now approve content with a transcript.
=> TNO-2570 Fix TNO Migration

app/subscriber/src/components/content-list/styled/ContentRow.tsx, app/subscriber/src/components/header/styled/Header.tsx, app/subscriber/src/components/section/styled/PageSection.tsx, app/subscriber/src/features/filter-media/FilterMedia.tsx, app/subscriber/src/features/filter-media/styled/FilterMediaLanding.tsx, app/subscriber/src/features/landing/styled/Landing.tsx
- switch list / filter ratio for filter by media
- change responsiveness break point 
- remove uppercase attributes (as request by Scott)
- no more rounded edges for pagesections (as requested by Bobbi)
=> CSS Feedback + Bug Fixes

app/subscriber/src/features/hooks/useSubMediaGroups.ts
Wait for `userInfo` before generating list
=> TNO-2687: Filter by Media list loads improper media types, and then refreshes to proper

app/subscriber/src/features/my-reports/edit/content/stories/ReportSectionContent.tsx, app/subscriber/src/features/my-reports/edit/content/stories/ReportSectionGallery.tsx, app/subscriber/src/features/my-reports/edit/content/stories/ReportSectionMediaAnalytics.tsx, app/subscriber/src/features/my-reports/edit/content/stories/ReportSectionTableOfContents.tsx, app/subscriber/src/features/my-reports/edit/content/stories/ReportSectionText.tsx, app/subscriber/src/features/my-reports/edit/content/summaries/ReportSectionContent.tsx, app/subscriber/src/features/my-reports/edit/content/summaries/ReportSectionGallery.tsx, app/subscriber/src/features/my-reports/edit/content/summaries/ReportSectionMediaAnalytics.tsx, app/subscriber/src/features/my-reports/edit/content/summaries/ReportSectionTableOfContents.tsx, app/subscriber/src/features/my-reports/edit/content/summaries/ReportSectionText.tsx, app/subscriber/src/features/my-reports/edit/content/summaries/styled/ReportSections.tsx, app/subscriber/src/features/my-reports/edit/settings/template/ReportSectionText.tsx, libs/npm/core/src/components/formik/wysiwyg/FormikWysiwyg.tsx
update some sections' to use FormikWysiwyg, and tweak styles.
=> Tno 2659 editor area

app/subscriber/src/components/content-list/Attributes.tsx, app/subscriber/src/components/content-list/ContentList.tsx, app/subscriber/src/components/content-list/ContentRow.tsx, app/subscriber/src/features/manage-folder/ManageFolder.tsx
- Added requested fields on folder content list component
- Made some adjustments on Attributes component to make use of them
=> TNO-2647 Add parameters and make attributes to use them

app/subscriber/public/index.html, app/subscriber/src/components/content-list/styled/ContentList.tsx, app/subscriber/src/components/content-list/styled/ContentRow.tsx, app/subscriber/src/css/_variables.module.scss, app/subscriber/src/css/_variables.scss, app/subscriber/src/features/content/view-content/styled/ViewContent.tsx, app/subscriber/src/features/search-page/components/advanced-search/AdvancedSearch.tsx, app/subscriber/src/features/search-page/components/advanced-search/components/ElasticInfo.tsx, app/subscriber/src/features/search-page/components/advanced-search/components/sections/SearchInGroup.tsx, app/subscriber/src/features/search-page/components/advanced-search/styled/AdvancedSearch.tsx, app/subscriber/src/features/search-page/styled/SearchPage.tsx, app/subscriber/src/index.scss
Had a call with Bobbi and changed a number of font weights and styles.
=> TNO-2629: Update Subscriber font

app/subscriber/src/components/content-list/ContentRow.tsx, app/subscriber/src/components/content-list/styled/ContentRow.tsx, app/subscriber/src/features/content/view-content/styled/ViewContent.tsx, app/subscriber/src/features/manage-folder/ManageFolder.tsx, app/subscriber/src/features/manage-folder/styled/ManageFolder.tsx, app/subscriber/src/features/my-folders/MyFolders.tsx, app/subscriber/src/features/my-folders/styled/FolderLanding.tsx, app/subscriber/src/features/my-folders/styled/MyFolders.tsx, app/subscriber/src/features/search-page/SearchPage.tsx, app/subscriber/src/features/search-page/styled/SearchPage.tsx
Biggest changes applied to my folders styling:
=> TNO-2726, 2727: Styling fixes to View Content, Search Page, and My Folders

libs/net/template/ReportEngine.cs
Fixed issue when there is no content.
=> TNO-2633 Fix chart config

app/subscriber/src/features/my-folders/FolderLanding.tsx, app/subscriber/src/features/router/AppRouter.tsx
It was  a lil bit trickier than I thought but, right now it /folder/:id redirects to the /folder/view/:id
=> Tno 2647 default folder route

app/subscriber/src/features/content/view-content/ViewContent.tsx
as an urgent request, update content view to work with bold search (formatSearch)
=> TNO-2656 make bold search works in content as well

app/subscriber/src/features/access-request/AccessRequest.tsx, app/subscriber/src/features/access-request/styled/AccessRequest.tsx
New screen was created with a more detailed description.
It also shows the loading spinner after 5 seconds to keep the user "entertained".
=> TNO-2655 New welcome screen

app/subscriber/src/features/my-folders/styled/FolderLanding.tsx
These are a little gimmick-y and not very smooth.
=> Remove animation from folder landing

app/editor/src/features/content/form/hooks/useContentForm.ts
I don't know if it's the best approach, but let me know if there's something to change.
=> TNO-2675 Handle alert value according to the status

libs/net/dal/Migrations/20240529201121_1.0.173.Designer.cs, libs/net/dal/Migrations/20240529201121_1.0.173.cs, libs/net/entities/UserReport.cs
Before merging/rebasing this code into your branch make sure you rollback.
`make db-rollback n=1.0.172`
Then you can merge/rebase the this code.
`make db-update`
=> Fix DB migration 1.0.173

app/subscriber/src/features/my-reports/components/ReportContentInlineText.tsx, app/subscriber/src/features/my-reports/components/index.ts, app/subscriber/src/features/my-reports/edit/content/sort/ReportContentSectionRow.tsx, app/subscriber/src/features/my-reports/edit/content/stories/ReportContentSectionRow.tsx, app/subscriber/src/features/my-reports/utils/reportInstanceContentInlineDisplay.ts
I've got confirmation, so I don't need to sort through AV content, which simplifies the issue. I just need to create a standalone display for AV content, with the format: Source - Program (Series) - Type - DateTime.
=> TNO-2651Update report instance content inline string

libs/net/template/Models/Charts/ChartDatasetModel.cs, libs/net/template/ReportEngine.cs
Fixing an issue when chart dataset values are null.
=> Fix chart auto max

app/subscriber/src/components/content-list/ContentList.tsx
Added sort function on sub group items,
=> TNO-2715 Sort sub group items

app/subscriber/src/features/my-reports/edit/ReportEditMenu.tsx, app/subscriber/src/features/my-reports/edit/settings/ReportEditDetailsForm.tsx, app/subscriber/src/features/my-reports/edit/settings/ReportEditSendForm.tsx
All required fields now on info screen:
=> TNO-2697: Move email subject line

services/net/syndication/SyndicationAction.cs
Syndication service will now us basic authentication when a username and password are provided in the ingest configuration.
=> TNO-2223 Add basic auth to syndication

services/net/syndication/SyndicationAction.cs
Needed to add basic auth to fetching the content body.
=> TNO-2223 Add basic auth to syndication service

app/subscriber/src/features/my-searches/MySearches.tsx
make a sort function in MySearches componet.
=> TNO-2684 sort myFilters alphabetically in MySearches component

openshift/scripts/stop.sh, services/net/filemonitor/FilemonitorAction.cs
Adding a logging statement to help identify when a paper name doesn't match a source.
=> TNO-2730 Log paper name

app/subscriber/src/features/search-page/components/advanced-search/components/sections/DateSection.tsx, app/subscriber/src/features/search-page/components/advanced-search/components/sections/constants/QuickPickerNames.ts, app/subscriber/src/features/search-page/components/advanced-search/styled/AdvancedSearch.tsx
Adding filters to search for 1-month, 2-months, 3-months, 6-months to advance search:
Story: https://apps.itsm.gov.bc.ca/jira/browse/TNO-2741
=> TNO-2741: Advanced Search Options

test/README.md
- fixed a typo
- added a missing key keycloak-client-id
=> Fixed test folder documents

app/editor/src/features/admin/ingests/configurations/DbMigration.tsx
Removed artificial time constraints on the UI when configuring the TNO Migration ingest.
=> TNO-2665 Fix TNO Migration

app/subscriber/src/components/tool-bar/AddToReportMenu.tsx, app/subscriber/src/components/tool-bar/styled/AddToMenu.tsx, app/subscriber/src/components/tool-bar/styled/ContentActionBar.tsx
Edit: Is ready now, was attempting to solve a problem that doesn't exist so I stopped my rewrite... 
In this PR:
- enhance add to report menu
=> TNO-2744: Update add to report menu

app/subscriber/src/features/login/UserInfo.tsx, app/subscriber/src/features/my-colleagues/MyColleagues.tsx, app/subscriber/src/features/my-products/MyProducts.tsx, app/subscriber/src/features/my-reports/MyReports.tsx, app/subscriber/src/features/my-searches/MySearches.tsx, tools/scripts/gen-env-files.sh
TNO-2734 changed modal source to components/modal instead of tno-core in subscriber for most files.
Also change in gen-env-files.sh file to remove the extra ".
=> TNO-2734 subscriber modal update styling

api/net/Areas/Services/Controllers/SettingController.cs, libs/net/models/Areas/Services/Models/Setting/SettingModel.cs, libs/net/services/Helpers/ApiService.cs, libs/net/services/Helpers/IApiService.cs, services/net/content/ContentManager.cs
We can now override which topics the Content Service is importing.
=> TNO-2665 Update Content Service

app/editor/src/features/reports/av-overview/OverviewGrid.tsx
- added time to the headline in Evening Overview clip column
=> TNO-2714 Added clip headline time

app/editor/src/features/admin/filters/hooks/useElastic.ts, app/editor/src/features/content/papers/PaperToolbar.tsx, app/editor/src/store/hooks/lookup/useSettings.ts, app/editor/src/store/rootReducer.ts, app/editor/src/store/slices/index.ts, app/editor/src/store/slices/settings/index.ts, app/editor/src/store/slices/settings/interfaces/ISettingsState.ts, app/editor/src/store/slices/settings/interfaces/index.ts, app/editor/src/store/slices/settings/settingsSlice.ts, app/editor/src/store/slices/settings/useSettingsStore.ts, libs/net/dal/Services/NotificationService.cs, openshift/kustomize/api/base/deploy.yaml, services/net/contentmigration/ContentMigrationAction.cs, services/net/notification/NotificationManager.cs
We can now send Top Story notifications throughout the day.  It will never send a duplicate alert as long as the notification has a time filter.
=> TNO-2649 Send Top Stories

api/net/Dockerfile.aspnet, api/net/Dockerfile.openshift
Openshift is having issues building the API for some reason.  Updating the dockerfile to possibly resolve it.
=> Fix api build

services/net/reporting/ReportingManager.cs
Handling unexpected errors when requests to CHES fail.
=> Fix Reporting Service

openshift/scripts/stop.sh, openshift/scripts/up.sh, services/net/content/ContentManager.cs, services/net/contentmigration/ContentMigrationAction.cs
Fixing dictionary parsing method.
=> Fix TNO Migration

services/net/reporting/ReportingManager.cs
Fixing issue where reports sent to CC and BCC wouldn't work if there were no TO addresses.
=> Fix Report Service

app/subscriber/src/components/navbar/NavbarItems.tsx, app/subscriber/src/components/user-profile/UserProfile.tsx, app/subscriber/src/features/help/Help.tsx, app/subscriber/src/features/help/index.ts, app/subscriber/src/features/help/styled/Help.tsx, app/subscriber/src/features/help/styled/index.ts, app/subscriber/src/features/router/AppRouter.tsx
=> Tno 2745 help page

app/editor/src/features/admin/notifications/NotificationFormTemplate.tsx
Fixed a race condition.
In some situations the template body was not filled correctly if the notificationTemplates came empty first.
=> TNO-2704 Fix race condition

app/subscriber/src/features/content/view-content/ViewContent.tsx
TNO-2764 changed the logic to show summary and body instead of showing summary twice.
=> TNO-2764 Change to show summary and body if they differ

app/subscriber/src/features/content/view-content/ToneValue.tsx, app/subscriber/src/features/content/view-content/ViewContent.tsx, app/subscriber/src/features/content/view-content/WorkOrderStatus.tsx, app/subscriber/src/features/content/view-content/styled/ViewContent.tsx, app/subscriber/src/features/content/view-content/utils/index.ts, services/net/contentmigration/ContentMigrationAction.cs, services/net/contentmigration/appsettings.json
Fixing issue with TNO Migration ignoring Featured Stories.
Fixing issue related to viewing the story summary and body.  I didn't debug each possible situation, but I made it show up at least.
=> Fix Featured Stories and Content View

api/net/Areas/Subscriber/Controllers/UserController.cs, app/subscriber/src/components/user-profile/UserProfile.tsx, app/subscriber/src/features/my-minister/MyMinister.tsx, app/subscriber/src/features/settings/MyMinisterSettings.tsx
In this PR:
- users who are able, may now impersonate another user and update their my minister settings
- when viewing My Ministers you will see it as the impersonated user
- same with My Minister settings, you may see their selection and update it for them
=> TNO-2720: Allow for impersonation / updating of my ministers 

app/editor/src/features/admin/av-overviews/OverviewSubscribers.tsx, app/editor/src/features/admin/notifications/NotificationSubscribersForm.tsx, app/editor/src/features/admin/products/ProductSubscribersForm.tsx, app/editor/src/features/content/list-view/ContentListView.tsx, app/editor/src/features/content/list-view/styled/ContentListView.tsx, app/editor/src/features/content/papers/Papers.tsx, app/editor/src/features/content/papers/styled/Papers.tsx, libs/npm/core/src/components/grid/styled/Grid.tsx
- Added Grid table to content
- Fixed styling issues in Papers
- Updated column width for the following components:
OverviewSubscribers.tsx: https://dev.editor.mmi.gov.bc.ca/admin/av/evening-overview
NotificationSubscribersForm.tsx: https://dev.editor.mmi.gov.bc.ca/admin/notifications/:id
ProductSubscribersForm.tsx: https://dev.editor.mmi.gov.bc.ca/admin/products/:id
=> TNO-2707 Replace flex table for Grid component in content

services/net/ffmpeg/FFmpegManager.cs
Adding additional logging to help debug.
=> TNO-2385 Fix FFmpeg Service

app/subscriber/src/features/search-page/components/advanced-search/components/sections/DateSection.tsx, app/subscriber/src/features/search-page/components/advanced-search/components/sections/SearchInGroup.tsx, app/subscriber/src/features/search-page/components/advanced-search/components/sections/constants/QuickPickerNames.ts, app/subscriber/src/features/search-page/components/advanced-search/components/sections/utils/determineActivePicker.ts, app/subscriber/src/features/search-page/components/advanced-search/styled/AdvancedSearch.tsx
Advanced search can now search all content without a date filter.
=> TNO-2794 Add all date range

api/net/Areas/Subscriber/Controllers/ProductController.cs
We can now email more than one person when someone submits a request for a product.
=> Fix subscribe request email

app/editor/src/features/admin/users/UserFilter.tsx, app/editor/src/features/admin/users/UserList.tsx, app/editor/src/features/admin/users/interfaces/IUserListFilter.ts, app/editor/src/features/admin/users/styled/UserList.tsx, app/editor/src/features/admin/users/utils/makeUserFilter.ts, app/editor/src/features/admin/work-orders/WorkOrderList.tsx, app/editor/src/features/admin/work-orders/interfaces/IWorkOrderListFilter.ts, app/editor/src/features/admin/work-orders/styled/WorkOrderList.tsx, app/editor/src/features/admin/work-orders/utils/makeWorkOrderFilter.ts, app/editor/src/features/content/list-view/ContentListView.tsx, app/editor/src/features/work-orders/transcription/TranscriptionList.tsx, app/editor/src/features/work-orders/transcription/styled/TranscriptionList.tsx, app/editor/src/store/slices/admin/adminSlice.ts, libs/npm/core/src/hooks/api/interfaces/IWorkOrderFilter.ts
-Finish WorkOrderList && UserList replacement.
- Applying pagination to Content, user list, transcriptions, work orders.
Story: https://apps.itsm.gov.bc.ca/jira/browse/TNO-2707
=> TNO-2707: Replace flex table to components using pagination

app/editor/src/features/content/list-view/components/tool-bar/filter/CreateNewSection.tsx, app/subscriber/src/components/media-type-filters/FilterOptions.tsx
TNO-2763 changes in label from Internet to Online in Subscriber Filter and Editor New Section
=> TNO-2763 Internet to Online

api/net/Areas/Services/Controllers/WorkOrderController.cs, app/editor/src/features/content/form/ContentNavigation.tsx, app/editor/src/features/content/form/components/upload/Upload.tsx, app/editor/src/features/content/form/hooks/useContentForm.ts, app/subscriber/src/features/content/view-content/ViewContent.tsx, services/net/ffmpeg/FFmpegManager.cs
Fixing issues with the process to automatically convert .mov files.  The UI should correctly display when it is being processed and update the video player when it's done.
=> TNO-2385 Fix .mov conversion

app/subscriber/src/features/search-page/SearchPage.tsx
A little refactor on the code.
Also retrieve content from the store.
The findContentWithElasticsearch stores the content, so the new useEffect additinho monitors the stored 'content' and loads in case there's no loading.
=> TNO-2755 Check content from the store

app/editor/src/features/admin/ingests/configurations/Newspaper.tsx, libs/net/models/Extensions/IngestModelExtensions.cs, services/net/content/ContentManager.cs, services/net/filemonitor/FilemonitorAction.cs, services/net/filemonitor/models/XmlNamespace.cs
Updated File Monitor Service to handle other XML feeds.  Corrected implementation issues with XPath.
This will need an update to the Ingest configuration in DEV, TEST, PROD.
=> TNO-2781 Add National Observer

app/subscriber/src/features/content/view-content/ViewContent.tsx
The file is being converted loader is displaying at the wrong time.
=> TNO-2385 Fix convert .mov

libs/net/models/Areas/Editor/Models/Contributor/ContributorModel.cs, services/net/content/ContentManager.cs
- updated content manager to find matched contributor by the ingested content Byline field
- updated Editor Contributor Model: added Aliases and added convert to Contributor method
=> TNO-2617 Automatically set Contributor based on Byline

services/net/reporting/ReportingManager.cs
Check property before sending an email
This is branched from this PR:
https://github.com/bcgov/tno/pull/1973
=> TNO-2770 Check new param on service

services/net/contentmigration/appsettings.json, services/net/reporting/ReportingManager.cs
Reduce chance of duplicate emails being used for emails.
=> TNO-2768 Fix distribution list

services/net/contentmigration/ContentMigrationAction.cs
Debugging issues with the TNO Migration Service.  It's always dies trying to connect to the Oracle database and it's difficult to determine if it's doing anything when logging level is Information.
=> Add logging to tno migration

libs/net/template/ReportExtensions.cs
There were some funky things going on in here that were causing the sentiment icons to be inconsistent, corrected logic.
=> TNO-2691: Correct Sentimet Logic for Reports

app/editor/src/features/admin/users/UserFormDistribution.tsx
Improving the distribution list management UI.
=> Manage distribution list

app/editor/src/features/login/LoginPanel.tsx, app/subscriber/src/features/login/BrowserLogin.tsx, app/subscriber/src/features/my-folders/MyFolders.tsx
Adding new authentication provider, Azure Entra ID.
Removing BCeID authentication provider.
=> Add Azure Entry ID

api/net/Program.cs, api/net/appsettings.Development.json, api/net/appsettings.Staging.json, api/net/appsettings.json, app/subscriber/src/features/my-reports/edit/view/ReportView.tsx, app/subscriber/src/features/my-reports/edit/view/ReportViewContainer.tsx, app/subscriber/src/features/my-reports/edit/view/styled/ReportView.tsx, openshift/kustomize/api-services/base/deploy.yaml, openshift/kustomize/api-services/overlays/dev/kustomization.yaml, openshift/kustomize/api-services/overlays/prod/kustomization.yaml, openshift/kustomize/api-services/overlays/test/kustomization.yaml, openshift/scripts/deploy.sh
Fixing issue with SignalR + Kafka Back Plane that is required to support separating the API.
=> TNO-2864 Separate API

openshift/scripts/deploy.sh
Fixing script to deploy the new API before waiting for the statefulset to be ready.
=> Fix DevOps deploy script

services/net/contentmigration/ContentMigrationAction.cs, services/net/contentmigration/ContentMigrationManager.cs, services/net/contentmigration/ContentMigrationService.cs
=> Improve TNO Migration

services/net/reporting/ReportingManager.cs
The Do Not Send option for reports only handle one logic path, but would not work for auto reports.
=> TNO-2879 Fix do not send report

app/subscriber/src/components/media-type-filters/FilterOptions.tsx
As the ticket request, we use the All option as the default filter when entering a list page.
=>  TNO-2821 use filter option all as page's default filter.

app/subscriber/src/features/search-page/components/advanced-search/AdvancedSearch.tsx
Check a couple of states to display the icon
=> TNO-2825 Refactor AdvancedSearch to improve display options handling

app/subscriber/src/components/media-type-filters/FilterOptions.tsx, app/subscriber/src/features/home/Home.tsx
Little fix for a the bug that doesn't apply the user's preferred filter on the content list views.
=> TNO-2690: Filter options not correctly remembering / applying when navigating back to site

app/editor/src/features/content/list-view/utils/naturalSort.ts, app/editor/src/features/content/papers/hooks/useSortContent.ts
Having back the use of `naturalSortValue` in Papers.
=> TNO-2816: Paper sort order not working

app/editor/src/features/admin/users/UserFilter.tsx, app/editor/src/features/admin/users/utils/makeUserFilter.ts, libs/net/dal/Services/UserService.cs
Fixing issue when searching for users.
=> Fix search users

app/subscriber/src/components/media-type-filters/FilterOptions.tsx
=> TNO-2690 Bug

app/editor/src/features/admin/products/ProductForm.tsx, app/editor/src/features/admin/products/ProductSubRequests.tsx, app/editor/src/features/admin/products/UserApproveDeny.tsx, app/editor/src/features/admin/products/index.ts, app/editor/src/features/admin/products/styled/ProductSubRequests.tsx, app/editor/src/features/admin/products/styled/index.ts
Splitting off some work to make PRs more manageable. 
In this PR:
- new request tab on products to approve/deny product sub change requests
Need to meet with Bobbi because I am struggling to make this look good. Leaving in draft for now. Logic should mostly stay the same, just CSS changes.
=> TNO-2785: Manage product sub requests 

app/subscriber/src/components/content-list/ContentRow.tsx
TNO-2814 added summary text for teaser snippet as well
=> TNO-2814 added summary for teaser snippet

api/net/Areas/Subscriber/Controllers/ReportInstanceController.cs, app/subscriber/src/App.tsx, app/subscriber/src/features/my-reports/ReportInstanceView.tsx, app/subscriber/src/features/my-reports/styled/ReportInstanceView.tsx, app/subscriber/src/features/my-reports/styled/index.ts, app/subscriber/src/features/router/AppRouter.tsx, app/subscriber/src/features/search-page/SearchPageContext.tsx
The link in the report email will now allow any user anonymously to view the report.  This isn't an ideal solution, but will work for us temporarily.  There isn't any PIA issues.
=> Anonymous view report page

services/net/notification/NotificationManager.cs
There was a logic bug that would result in missing notifications when there was more than one matching notification configured.
=> Fix notifications

api/net/Areas/Editor/Models/Storage/DirectoryModel.cs, api/net/Areas/Editor/Models/Storage/ItemModel.cs, api/net/TNO.API.csproj, app/editor/src/features/content/form/ContentForm.tsx, app/editor/src/features/content/form/hooks/useContentForm.ts, libs/net/ches/TNO.Ches.csproj, libs/net/core/TNO.Core.csproj, libs/net/css/TNO.CSS.csproj, libs/net/dal/TNO.DAL.csproj, libs/net/entities/TNO.Entities.csproj, libs/net/kafka/TNO.Kafka.csproj, libs/net/keycloak/TNO.Keycloak.csproj, libs/net/reports/TNO.Reports.csproj, libs/net/services/TNO.Services.csproj, libs/net/template/TNO.TemplateEngine.csproj, libs/net/tests/core/TNO.Test.Core.csproj, libs/net/tests/dal/TNO.Test.DAL.csproj, services/net/content/TNO.Services.Content.csproj, services/net/contentmigration/TNO.Services.ContentMigration.csproj, services/net/filemonitor/FilemonitorAction.cs, services/net/filemonitor/TNO.Services.FileMonitor.csproj, services/net/image/ImageAction.cs, services/net/image/TNO.Services.Image.csproj, services/net/notification/TNO.Services.Notification.csproj, services/net/reporting/TNO.Services.Reporting.csproj, tools/elastic/migration/TNO.Elastic.Migration.csproj, tools/scripts/gen-env-files.sh
Auto conversion of .mov files would incorrectly interrupt the next snippet.  This fix should resolve that issue.  Also updated .NET packages to resolve security issue.
- Update .Net packages in all projects
=> Fix auto convert

app/editor/src/features/content/form/ContentActions.tsx, app/editor/src/features/content/form/ContentForm.tsx, app/editor/src/features/content/form/components/tool-bar/ContentFormToolBar.tsx, app/editor/src/features/content/form/components/tool-bar/form/AlertSection.tsx, app/editor/src/features/content/form/interfaces/IContentForm.ts, libs/net/dal/Extensions/JsonDocumentExtensions.cs, services/net/contentmigration/sources/oracle/Entities/UserTone.cs, services/net/reporting/ReportingManager.cs
The report `PublishedOn` date was incorrectly being converted to local time when creating a filter to ensure only newly posted content was included in the next report.
I've also added the ability to pass a reference to several components.  Currently it doesn't do anything, but the goal was to limit the event handler related to the content form page.  I have also made it so that the shortcuts continue to perform their default behaviour on the page.  I did this because it was extremely annoying not being able to refresh or copy anything.
=> TNO-2885 Fix missing content in report

network/reverse-proxy/editor/Dockerfile
=> Fix Editor nginx

libs/net/core/Extensions/StringExtensions.cs
Adding space after punctuation mark in Transcripts
=> TNO-2806: Transcripts display without a space after a question mark

api/net/Areas/Services/Controllers/ContentController.cs
- when updating content, we should create new topic/tag if there is any
=> TNO-2678 Fixed Ingest Services save content issue

app/subscriber/src/components/navbar/NavbarItems.tsx, app/subscriber/src/features/my-colleagues/ColleagueEdit.tsx, app/subscriber/src/features/my-colleagues/MyColleagues.tsx, app/subscriber/src/features/my-colleagues/MyColleaguesLanding.tsx, app/subscriber/src/features/my-colleagues/constants/ColleagueActionEnum.ts, app/subscriber/src/features/my-colleagues/index.ts, app/subscriber/src/features/my-colleagues/interfaces/IMyColleaguesProps.ts, app/subscriber/src/features/my-colleagues/styled/MyColleagues.tsx, app/subscriber/src/features/router/AppRouter.tsx, app/subscriber/src/features/settings/SettingsLanding.tsx, app/subscriber/src/features/settings/constants/SettingsSessionEnum.ts, app/subscriber/src/features/settings/index.ts, app/subscriber/src/features/settings/styled/SettingsLanding.tsx, app/subscriber/src/features/settings/styled/index.ts
- Added Settings screen
- Changed My Colleagues functionality to remove Edit Route
- Added Close Functionality on Panels
Full Screen
Split Screen
=> Tno 2773 settings page

app/editor/src/features/admin/users/UserFormDistribution.tsx
- sort the distribution list by email addresses
=> TNO-2866 Report distribution list sort

api/net/Areas/Subscriber/Controllers/AVOverviewController.cs
It looks like no one tested the Evening Overview with a subscriber account.  I've updated the controller authorization.
=> Fix Evening Overview

app/subscriber/src/components/content-list/styled/ContentRow.tsx, app/subscriber/src/components/media-type-filters/styled/MediaTypeFilters.tsx, app/subscriber/src/components/tool-bar/styled/ContentActionBar.tsx, app/subscriber/src/features/content/view-content/ViewContent.tsx, app/subscriber/src/features/content/view-content/styled/ViewContent.tsx, app/subscriber/src/features/filter-media/FilterMediaLanding.tsx, app/subscriber/src/features/filter-media/styled/FilterMediaLanding.tsx, app/subscriber/src/features/home/styled/Home.tsx, app/subscriber/src/features/my-searches/styled/MySearches.tsx, app/subscriber/src/features/search-page/PreviousResults.tsx, app/subscriber/src/features/search-page/SearchPage.tsx, app/subscriber/src/features/search-page/components/advanced-search/components/ExpandableRow.tsx, app/subscriber/src/features/search-page/components/advanced-search/styled/AdvancedSearch.tsx, app/subscriber/src/features/search-page/styled/PreviousResults.tsx, app/subscriber/src/index.scss
Fixes include:
- alignment fixes to the filter media option labels
- highlight colour is now highlighter yellow
- teaser height limited for smaller screens so it stays to two lines
- reduce font size on the filter media page, and move checkbox to the left side of the label like elsewhere in the application
- fix padding on no results search screen
- on the advanced search the icon and colour for an active filter applied has been updated
=> TNO-2882: (1/2) Jonny + Bobbi U/X Session

app/editor/src/features/login/LoginPanel.tsx, app/subscriber/src/features/login/BrowserLogin.tsx, openshift/scripts/stop.sh, openshift/scripts/up.sh
We can now once again use standard IDIR through SiteMinder.
=> Add IDIR IDP

libs/net/template/ReportExtensions.cs
Reports were failing when they attempted to highlight search terms.  The code to do this won't work for us, and has issues.  I've commented it out.
=> Remove highlight terms

app/subscriber/src/components/tool-bar/ContentActionBar.tsx, app/subscriber/src/features/filter-media/FilterMedia.tsx, app/subscriber/src/features/filter-media/FilterMediaLanding.tsx, app/subscriber/src/features/home/Home.tsx, app/subscriber/src/features/todays-commentary/TodaysCommentary.tsx, app/subscriber/src/features/top-stories/TopStories.tsx
Added reset button in `ContentActionBar` to reset page to initial state of the following:
- Featured Stories
- Top Stories
- Today's Commentary
- Filter by Media
=> TNO- 2790: Home Page logo should reset page

openshift/kustomize/api-services/base/deploy.yaml, openshift/kustomize/api/base/deploy.yaml, openshift/kustomize/api/base/statefulset.yaml, openshift/kustomize/services/notification/base/deploy.yaml, openshift/kustomize/services/reporting/base/deploy.yaml, openshift/kustomize/shared_resources/base/reporting-shared-config-map.yaml, openshift/kustomize/shared_resources/overlays/dev/kustomization.yaml, openshift/kustomize/shared_resources/overlays/prod/kustomization.yaml, openshift/kustomize/shared_resources/overlays/test/kustomization.yaml
Resolving configuration issue for the transcription link in reports and alerts.
=> Fix transcribe URL

app/subscriber/src/features/home/Home.tsx, app/subscriber/src/features/todays-commentary/TodaysCommentary.tsx, app/subscriber/src/features/top-stories/TopStories.tsx
Missing to reset filters and state for previous days.
=> [FIX]TNO-2790: Home Page logo should reset page

app/subscriber/src/features/transcription-request/TranscriptionRequest.tsx, app/subscriber/src/features/transcription-request/styled/TranscriptionRequest.tsx
Adjustments for smaller cellphones.
=> TNO-1397 Logo size and container adjustment

services/net/contentmigration/migrators/ClipMigrator.cs
Events from TNO should now include their transcripts.
=> Fix Event transcripts

libs/net/dal/Services/ProductService.cs
Determine product type, update report/alert subscription. Add/remove subscription in product, also sync to relative item.
=> TNO-2807 update subscription for report and notification

app/subscriber/src/features/login/styled/MobileLogin.tsx
- added the missing IDIR image on mobile version login page
=> TNO-2857 Fixed mobile login logo issue

app/editor/src/features/admin/reports/ReportSchedule.tsx, services/net/contentmigration/ContentMigrationAction.cs, services/net/contentmigration/migrators/ClipMigrator.cs
Formatting datetime value to be easier to read/debug.
=> Update report schedule

app/subscriber/src/components/tool-bar/ContentActionBar.tsx, app/subscriber/src/components/tool-bar/ResetFilters.tsx
Adding Reset icon as action item in Content Action Bar:
=> TNO-2790: HomePage logo reset page

app/subscriber/src/css/_variables.scss, app/subscriber/src/features/my-products/MyProducts.tsx, app/subscriber/src/features/my-products/ProductCard.tsx, app/subscriber/src/features/my-products/styled/MyProducts.tsx, app/subscriber/src/features/settings/SettingsLanding.tsx, app/subscriber/src/features/settings/styled/SettingsLanding.tsx
Changes to:
- settings css (minor)
- my products css
=> CSS From Session w/ Bobbi

app/subscriber/src/features/filter-media/FilterMedia.tsx, app/subscriber/src/features/filter-media/FilterMediaLanding.tsx, app/subscriber/src/store/hooks/lookup/useSettings.ts, app/subscriber/src/store/slices/settings/interfaces/ISettingsState.ts, app/subscriber/src/store/slices/settings/settingsSlice.ts
The filter by media type will now correctly load all content by media type when a media type is selected.
=> Fix filter by media type

app/subscriber/public/index.html
TNO-924 Adding snowplow analytics initial testing code in subscriber index.html
=> TNO-924 Adding snowplow analytics initial testing code

app/subscriber/src/components/content-list/Attributes.tsx, app/subscriber/src/features/my-minister/styled/MyMinister.tsx
Last piece of the puzzle for my minister
- cleaned up DOM slightly
- ensure blank tags do not appear
- fix css naming conventions
=> Visual Bug on My Minister

app/subscriber/src/features/search-page/components/advanced-search/AdvancedSearch.tsx
We are getting slow performance in the TextArea because in every key stroke we are updating the filter. With the proposed change we are modifying the logic to update filter every 150ms using debouncing and update the state of the controlled value of the TextArea to show the refreshed input. Here we could not use `useRef` to avoid updating the state because TextArea value depends on re-render the new value to update the input. 
Previously, considering CPU throttle 20X slower and 3G Network, we were getting:
With this change, under the same throttle conditions we are improving the response:
Story: https://citz-gdx.atlassian.net/browse/TNO-2922
=> TNO: AdvancedSearchSlow

app/editor/src/features/reports/av-overview/OverviewGrid.tsx
The Following fixes were applied.
- There was no SourceIds as a Parameter. So if the Show/Program was not selected, it would bring results from ALL Sources.
- There was a limit of 20 results on the query, which would limit some content to be displayed on drop down. Probably this limit was a quick fix for an issue that was fixed on the next topic.
- Need of an end date. The previous query would only request the report date and greater then. What would work for creating "Today's" reports, but if act in a retroactive date, it would bring all the results greater than the date (and that's why I think there as that 20 limiting the results). So, as a solution, I added an end date, no matter the start date and time, I would copy the start date, and set the hour as the last available second on the …
=> TNO-2859 Query fixes

libs/net/core/Extensions/StringExtensions.cs, libs/net/template/ReportEngine.cs
The hope is this will remove any invalid characters which may be causing issues in the reports.
=> Remove invalid characters

app/subscriber/src/components/action/Action.tsx, app/subscriber/src/components/action/styled/Action.tsx, app/subscriber/src/components/section/Section.tsx, app/subscriber/src/css/_variables.module.scss, app/subscriber/src/css/_variables.scss, app/subscriber/src/features/my-minister/styled/MyMinister.tsx, app/subscriber/src/features/my-reports/MyReports.tsx, app/subscriber/src/features/my-reports/ReportCard.tsx, app/subscriber/src/features/my-reports/components/ReportKindIcon.tsx, app/subscriber/src/features/my-reports/components/styled/ReportKindIcon.tsx, app/subscriber/src/features/my-reports/styled/MyReports.tsx
Various changes to the MyReports section - more to come.
=> My Reports CSS Cleanup

services/net/reporting/Config/ReportingOptions.cs, services/net/reporting/ReportingManager.cs
Providing a way to turn off mail merge and send individual emails instead.
This is a guess on why things are failing.
=> Reporting merge issue

app/subscriber/src/features/my-reports/styled/MyReports.tsx
Small change to decrease the font size of the report titles under "My Reports"
=> Small decrease in title size

app/subscriber/src/features/my-reports/edit/content/styled/ReportEditSortForm.tsx
CSS added hover effect on rows.
=> TNO-2826 Add hover effect to ReportEditSortForm row

services/net/ffmpeg/Config/FFmpegOptions.cs, services/net/ffmpeg/FFmpegManager.cs
Adding a loop to deal with optimistic concurrency issues when updating content.
=> Fix FFmpeg

tools/additional-scripts/update_sources.py
- python script to update Editor sources in DEV/TEST
=> TNO-2932 Added script to copy sources data

app/subscriber/src/features/help/Help.tsx, openshift/kustomize/app/subscriber/base/pvc.yaml
Name convention on PVC creation.
And link path fixes.
=> TNO-2846 Naming convertions and path fixes

app/subscriber/src/features/my-reports/edit/styled/ReportEditForm.tsx
TNO-2777 added code to stick buttons to bottom on my reports
=> TNO-2777 code to stick buttons to bottom

api/net/Middleware/ErrorHandlingMiddleware.cs, app/subscriber/src/features/my-folders/MyFolders.tsx, app/subscriber/src/store/hooks/useAjaxWrapper.ts
Improve the error message related to gateway errors.
=> TNO-2897 Update gateway error

app/subscriber/src/store/hooks/app/useToastError.tsx, app/subscriber/src/store/hooks/useAjaxWrapper.ts
Minor improvements to error messages.
=> TNO-1249 Improve error messages

libs/net/core/Extensions/StringExtensions.cs, libs/net/template/Models/Reports/ChartEngineContentModel.cs, libs/net/template/ReportEngine.cs
Fixing issue where removing non ASCII characters was removing valid UTF-8 characters.
=> Fix report invalid characters

app/subscriber/src/features/login/AppLogin.tsx, app/subscriber/src/features/login/styled/AppLogin.tsx, app/subscriber/src/features/login/styled/SystemMessage.tsx
Move system message inside login-box
=> Small login changes

libs/net/elastic/Extensions/RegexSettings.cs, libs/net/elastic/Extensions/StringExtensions.cs
Updated the code to extract keywords so that they can be highlighted in a report.  This resolves compound phrases.
=> Fix highlight keywords

tools/scripts/kc-key-update.sh
mmi -> tno,
looks like it was replaced by refactor.
=> Update regex pattern to match tno directory. 

app/editor/src/features/work-orders/WorkOrderFilter.tsx, app/editor/src/features/work-orders/transcription/TranscriptionList.tsx, app/editor/src/features/work-orders/transcription/WorkOrderActions.tsx, app/editor/src/features/work-orders/transcription/WorkOrderStatus.tsx, app/editor/src/features/work-orders/transcription/styled/TranscriptionList.tsx
Add additional filters for the transcription queue.  Also provided ability to cancel a submitted request.
=> TNO-2765 Improve transcript queue

services/net/contentmigration/appsettings.json, tools/additional-scripts/update_sources.py
- added mismatched source config in content migration app settings
- minor fixes for the python import sources code
=> TNO-2923 Fixed map content from TNO 1.0

libs/net/dal/Services/AVOverviewTemplateService.cs
- Checking track status of entity before adding subscriber to Evening Overview.
- `User_av_overview` table is updating `is_subscribed` boolean field or adding a new subscriber if does not exist.
=> TNO-2800: Error when subscribing to Evening Overview

app/subscriber/src/App.tsx, app/subscriber/src/features/home/Home.tsx, app/subscriber/src/features/router/AppRouter.tsx, app/subscriber/src/features/todays-commentary/TodaysCommentary.tsx, app/subscriber/src/features/todays-front-pages/TodaysFrontPages.tsx
changes to files to call trackpageview once per page
=> TNO-924 fixed multiple calls to pageview snowplow

services/net/contentmigration/Config/MigratorOptions.cs, services/net/contentmigration/ContentMigrationAction.cs, services/net/contentmigration/appsettings.json, services/net/contentmigration/migrators/ContentMigrator.cs, services/net/contentmigration/migrators/IContentMigrator.cs
- added extra source code - media type mappings to content migration
=> TNO-2912 Added extra media type mappings

libs/net/template/ReportExtensions.cs
Temporary work around for errors in the mark keywords code.
=> Temp fix for reporting service

app/subscriber/src/components/action/Action.tsx, app/subscriber/src/features/commentary/Commentary.tsx, app/subscriber/src/features/commentary/styled/Commentary.tsx
Changes to Commentary tab refresh button.
=> TNO-2915 refresh button consistency across site

libs/net/core/Extensions/StringExtensions.cs
- fixed the extra pipe characters issues in ingest service. Since the method is also used in other places like content migrations, this fix should also fix other pipe characters issues: TNO-2942 / TNO-2938.
=> TNO-2956 Fixed the extra pipe characters issues

app/subscriber/src/features/my-reports/edit/validation/ReportFormScheduleSchema.ts
This is blocking a ton of users.
=> Remove report validation

app/subscriber/src/features/my-reports/edit/ReportEditPage.tsx
All editing content in a failed report.
=> Fix edit report

app/subscriber/src/components/content-list/ContentRow.tsx, app/subscriber/src/components/content-list/styled/ContentRow.tsx
The previous PR for this allowed for the autoplay of video, but not audio.
This PR fixes that, as well as a small styling issue with audio, it is now properly centered.
=> TNO-2905 Bug: Autoplay inline audio

libs/net/services/Actions/Managers/ServiceActionManager`.cs, libs/net/services/Managers/ServiceManager`.cs
- check if there is EmailTo config before sending emails
=> Fixed sending email errors

services/net/reporting/ReportingManager.cs
Ensures a resend request that fails doesn't get stuck in a loop and spam subscribers.
=> Fix report resend

app/editor/src/features/reports/av-overview/OverviewGrid.tsx
With this changes the content is fetched when:
- Source Id is changed
- Series Id is changed
- If there's no source the content is cleaned up
- SourceId is added as a criteria to fetch
- Racing conditions removed from the component
=> TNO-2859 More AV Overview fixes

api/net/Areas/Subscriber/Controllers/ContentController.cs, app/subscriber/src/features/my-reports/edit/content/stories/ContentForm.tsx
Fixing issues related to editing content in a report.
=> Fix edit report content

services/net/reporting/ReportingManager.cs
Fixed issue where a resent report would result in a no content message.  This appears to only have impacted the `Send a Test` email, but it is used by Scott more than realized.
=> Fix no content in resent report

app/subscriber/src/components/sentiment/Sentiment.tsx, app/subscriber/src/css/_variables.scss, app/subscriber/src/features/content/view-content/ViewContent.tsx, libs/net/template/ReportExtensions.cs
- change to lighter tone colours as per request 
- a small bug fix for scrolling to the top of `ViewContent` when navigating on mobile
=> TNO-2982: Add new tone colours

app/subscriber/src/features/my-products/MyProducts.tsx, app/subscriber/src/features/my-products/ProductCard.tsx
=> Fix Products

app/subscriber/src/features/my-reports/ReportFilter.tsx, app/subscriber/src/features/my-reports/styled/MyReports.tsx
Add clear button to the input for the filter on My Reports
=> TNO-2991: Add clear button to my reports filter

services/net/content/ContentManager.cs
Adding an extra step to strip out possible XML tags that are causing issues in formatting.  It's not clear how they are occurring however.
=> Fix Paper Service

app/editor/src/features/admin/reports/components/ReportSectionMediaAnalytics.tsx, app/editor/src/features/admin/reports/components/ReportSectionMediaAnalyticsChart.tsx, app/subscriber/src/features/my-reports/edit/settings/template/ReportSectionMediaAnalytics.tsx, app/subscriber/src/features/my-reports/edit/settings/template/charts/ChartViewer.tsx, app/subscriber/src/features/my-reports/edit/settings/template/utils/calcAutoSize.ts, app/subscriber/src/features/my-reports/edit/settings/template/utils/generateChartOptions.ts, app/subscriber/src/features/my-reports/edit/settings/template/utils/getChartData.ts, app/subscriber/src/features/my-reports/edit/settings/template/utils/index.ts, app/subscriber/src/features/my-reports/edit/settings/template/utils/shouldResizeChart.ts, libs/net/template/Models/Charts/ChartDatasetModel.cs, libs/net/template/Models/Charts/Options/ChartOptionsModel.cs, libs/net/template/ReportEngine.cs
The auto chart resize option now will dynamically resize for auto reports.
Also fixed a few bugs related to charts.
=> Add chart auto resize

api/node/src/routes.ts, app/subscriber/src/features/my-reports/edit/settings/template/charts/ChartViewer.tsx, libs/net/template/ReportEngine.cs, libs/net/template/ReportExtensions.cs, libs/npm/core/src/hooks/api/utils/mergeChartSettings.ts
Fixing various issues with resize and highlight keywords in charts.
=> Fix report charts

app/editor/src/features/admin/reports/ReportFormSections.tsx, app/subscriber/src/features/my-reports/edit/settings/ReportEditTemplateForm.tsx, app/subscriber/src/features/my-reports/edit/settings/template/utils/groupData.ts, libs/net/template/ReportEngine.cs
Resolve a few report chart bugs.
- Remove content from sections that have been deleted.
- Compare on lowercase
=> Fix report chart resize

app/subscriber/src/features/my-reports/edit/settings/template/ReportSectionMediaAnalyticsChart.tsx
Fixed issue which was causing the reports to crash the app.
=> Fix report chart

services/net/reporting/ReportingManager.cs
A report will clear folders on a retry.  This could be problematic based on timing, but is better than not clearing.
=> Fix report clear folder

docker-compose.yml, tools/objects-backup/Dockerfile, tools/objects-backup/entrypoint.sh, tools/scripts/gen-env-files.sh
setup local docker-compose service
main script is tools/objects-backup/entrypoint.sh
curl the minIO tool using it to sync files to s3 bucket incrementally.
we could add the script into the openshift cornjob later
=> TNO-2970 sync to s3

tools/mov-converter/README.md
We now have a simple way to convert files on a Mac.  This will require someone installing these for the Editors.
=> Mac auto convert

libs/net/dal/Services/ReportService.cs, libs/net/dal/Services/UserService.cs
We can now see products/reports/notifications that a user is subscribed to through distribution lists.
=> Fix user management

app/subscriber/src/features/my-reports/edit/content/ContentEditForm.tsx, app/subscriber/src/store/hooks/subscriber/useContent.ts
- Checks if there's an updated version of the content
- If that's true, update the content version, but keeps the user "versions" with the user ID.
=> TNO-2033 Merge user versions on content

libs/net/dal/Services/ProductService.cs
One concern:
- is it ok to have the URL hard coded, or do we want this to be working in dev/test
- just not sure where to access the current env from here (might be easy fix)
=> TNO-3018: Add link to request in product request email

api/net/Areas/Helpers/WorkOrderHelper.cs
If editors are manually making transcripts, we don't allow subscribers to request it and pop up a message to let them know the reason.
=> prevent override editor's work

app/subscriber/src/features/search-page/SearchPage.tsx
Will explain in comments what is going on..
=> Advanced search bugs

app/subscriber/src/features/search-page/components/advanced-search/components/sections/MediaSection.tsx
Add 'filter in use' icon to Media Source that have sourceIds selected.
=> TNO-3024: Advanced Search: Add a 'filter in use' icon to the Media Source sub-categories

app/subscriber/src/features/search-page/components/advanced-search/styled/AdvancedSearch.tsx, app/subscriber/src/features/search-page/styled/SearchPage.tsx
TNO-3034 change to advance search section heights
=> TNO-3034 change to advance search section heights

app/subscriber/src/features/access-request/AccessRequest.tsx
Changed message on access request page as per Scott's request.
=> Change unauthenticated user message

app/subscriber/src/components/content-list/utils/groupContent.ts
TNO-3030 added condition to not duplicate short name if it is same as name
=> TNO-3030 Filter by Media display option 

api/net/Areas/Editor/Controllers/StorageController.cs, openshift/kustomize/api-services/base/deploy.yaml, openshift/kustomize/api/base/statefulset.yaml
- logs show missing variables
- update s3 config in `api-services` and `statefulset`
=> Update config variables and add more logs

libs/net/dal/Services/ProductService.cs, libs/net/dal/Services/ReportService.cs, services/net/filemonitor/FilemonitorAction.cs
- should re-throw exception after logging
=> TNO-3062 minor updates to the logs

api/net/Areas/Subscriber/Controllers/ReportController.cs, api/net/Program.cs, app/subscriber/src/features/my-reports/edit/ReportEditActions.tsx, app/subscriber/src/features/my-reports/edit/ReportEditMenu.tsx, libs/net/core/Extensions/ServiceCollectionExtensions.cs, libs/net/models/Areas/Report/ContentActionModel.cs, libs/net/models/Areas/Report/ContentModel.cs, libs/net/models/Areas/Report/ContentTagModel.cs, libs/net/models/Areas/Report/ContentTonePoolModel.cs, libs/net/models/Areas/Report/ContentTopicModel.cs, libs/net/models/Areas/Report/FileReferenceModel.cs, libs/net/models/Areas/Services/Models/Report/UserModel.cs
Fixing various bugs related to the report admin pages.
- Unlock report should work correctly
- Refresh preview should work correctly
- Removing JSON serializer `Int32ToString` to determine if it is the cause of the OOM issues.
- Update API
- Update Subscriber app
- Update all services
=> Fix admin report

app/subscriber/src/features/my-reports/components/StartNextReportInfo.tsx, app/subscriber/src/features/my-reports/edit/ReportEditForm.tsx, app/subscriber/src/features/my-reports/edit/ReportEditMenu.tsx, app/subscriber/src/features/my-reports/edit/styled/ReportEditMenu.tsx, app/subscriber/src/features/my-reports/utils/getStatus.ts
Fixing issues related to reopening a report and starting the next report.
=> Fix report reopened

app/subscriber/src/features/search-page/SearchPage.tsx
TNO-3025 change to not show date picker on more than 24 hr period
=> TNO-3025 remove today's date from search result if offset greater than 1

app/editor/package.json, app/editor/yarn.lock, app/subscriber/package.json, app/subscriber/yarn.lock, libs/npm/core/package.json, libs/npm/core/src/components/form/wysiwyg/Wysiwyg.tsx
- fixed the issue that remove formatting deleting text
=> TNO-2994 Fixed removing formatting issue

docs/DEVELOPMENT.md, openshift/Makefile, openshift/kustomize/tekton/base/tasks/git-conditions.yaml, openshift/scripts/deploy.sh
Fix developer setup docs and `master` branch pipeline.
=> Fix dev setup docs

app/editor/src/features/admin/topics/TopicFormSmall.tsx, app/editor/src/features/admin/topics/styled/TopicFormSmall.tsx, app/editor/src/store/hooks/admin/useTopics.ts
This update will display a loading overlay when adding new topics to the Event of the Day form.  Regrettably, I believe the issue in PROD is a performance issue, which I cannot duplicate.  If it continues I will need to refactor the implementation to speed things up.
=> Update EoD add topic

services/net/syndication/SyndicationAction.cs, services/net/syndication/Xml/Rss/RssItem.cs
=> TNO-2980 Fixed iPolitics content issue

services/net/syndication/SyndicationAction.cs
- add null check to prevent exceptions
=> TNO-2980 Fixed syndication errors

services/net/transcription/Exceptions.cs, services/net/transcription/TranscriptionManager.cs
Summary:
Have 3 exceptions for surprise happened.
```
file missing, 
content missing,
Content did not generate,
```
config two settings in transcription Service:
```
"SendEmailOnFailure": true,
"EmailTo": "xxxx@gov.bc.ca"
```
Manager/developer will receive alert
=> TNO-2808 Alert for transcription fail

services/net/syndication/Xml/Rss/RssItem.cs
- read ipolitics author from rss xml
- updated rss item convert method to read authors' names
=> TNO-2980 Fixed the byline issue

openshift/kustomize/tekton/base/tasks/git-conditions.yaml, tools/git/DeploymentConfig.yaml, tools/git/Dockerfile, tools/git/README.md, tools/git/entrypoint.sh
Debugging and fixing issues related to the DevOps pipeline and git.  Not certain why we're now getting errors in this area as we've been running the same code for a long time.  It's either an Openshift upgrade issue, or bitnami.  At some point we should fix the bitnami version.
=> Update pipeline tooling

app/subscriber/src/components/tool-bar/AddToReportMenu.tsx
Added dropdown to search for report to Add to report modal
=> TNO-3017 auto complete search field

app/subscriber/src/components/tool-bar/AddToReportMenu.tsx
Rollback add to report changes.
=> Rollback add to report

app/subscriber/src/features/commentary/styled/Commentary.tsx, app/subscriber/src/features/landing/styled/Landing.tsx
Fixed issues with flexbox. Just made changes in max-width as per story requirement.
=> Tno 3027 commentary box headline

services/net/transcription/TranscriptionManager.cs
Attempting to figure out why transcripts are failing.
=> Update transcript logging

tools/scripts/gen-env-files.sh
update gen-env files for fileupload service, to avoid error message.
=> update Env file

api/net/Areas/Editor/Controllers/SettingController.cs, api/net/Areas/Services/Controllers/IngestController.cs, api/net/Areas/Services/Controllers/SettingController.cs, api/net/Areas/Services/Controllers/SourceController.cs, libs/net/core/Http/HttpRequestClient.cs, libs/net/core/Http/IHttpRequestClient.cs, libs/net/core/Http/OpenIdConnectRequestClient.cs, libs/net/css/CssClient.cs, libs/net/services/Helpers/ApiService.cs, libs/net/services/Helpers/IApiService.cs, services/net/content/ContentManager.cs, services/net/content/ContentService.cs
- added etag to settings and ingests, source controller
- updated content service to use etag
=> MMI-3071 Improve import data

libs/net/services/Helpers/ApiService.cs, libs/net/services/Helpers/IApiService.cs, services/net/content/ContentManager.cs
- removed redundant locks
- used concurrent dictionary to store the local etag values
- updated async methods
=> MMI-3071 Minor updates

services/net/contentmigration/Dockerfile, services/net/contentmigration/TNO.Services.ContentMigration.csproj, services/net/nlp/Dockerfile
Fixing issues with Oracle and docker image versions.
=> Fix oracle reference

app/editor/src/features/home/LogoPanel.tsx, app/subscriber/src/components/content-list/ContentReportPin.tsx, app/subscriber/src/components/content-list/ContentRow.tsx, app/subscriber/src/components/header/Header.tsx, app/subscriber/src/features/content/view-content/ViewContent.tsx, app/subscriber/src/features/help/Help.tsx, app/subscriber/src/features/my-reports/components/ReportContentInlineText.tsx, app/subscriber/src/features/my-reports/edit/content/stories/ToneSelector.tsx, libs/npm/core/src/components/form/iconbutton/IconButton.tsx, libs/npm/core/src/components/header/Header.tsx
I'm surprised I didn't catch this years ago.  The path to images cannot use a frontend environment variable because when the image is built it will have the wrong environment.
=> Fix image URL

app/subscriber/src/features/login/styled/SystemMessage.tsx
Need to add class styling to enable Quill classes.
=> Fix message alignment

api/net/Areas/Editor/Controllers/StorageController.cs
- Added additional check for fileReference.IsSyncedToS3 when file not found
- Delete file reference if file not found and not synced to S3 to clean up broken references
- update logging
=> fix: handle case when file not found and not synced to S3

api/net/Areas/Editor/Controllers/StorageController.cs
fix an mistake, we will never delete a file if the upload fails.
=> Never delete a file if the upload fails.

api/net/Areas/Editor/Controllers/ContentController.cs
update running time for each new file when uploaded
=> update running time in the endpoint

libs/net/template/ReportEngine.cs
For some reason some charts will display their data labels even when they are turned off.  I've defaulted the labels to `false` in the template and added additional logging.
=> Fix chart labels

app/editor/src/features/content/form/components/time-log/TimeLogSection.tsx
MMI-3074 changes in the modal to use component instead of body attribute to display table
=> MMI-3074 changes in the Prep Time Log modal

openshift/scripts/database-connect.sh
With the change from CrunchyDB to our own postgres this script needed to be updated.
=> Fix db-connect script

libs/net/template/ReportExtensions.cs
- fixed the sentiment analysis report exclude empty value was not working issue
=> MMI-3102 Fixed Report charts

api/node/src/utils/applyChartJsOptions.ts
I should have realized there was still a path where there was no issue.
=> Fix charts

app/subscriber/src/features/my-reports/edit/settings/template/utils/groupData.ts, libs/net/template/ReportExtensions.cs
When sorting a chart by Month and Day it was not correctly sorting.
=> Fix chart sorting date issue

app/editor/src/features/content/form/hooks/useContentForm.ts
- when the user publish the content for the first time from the edit content page, the posted on time should be updated
=> MMI-3183 Fixed the posted on time issue

openshift/kustomize/services/transcription/base/deploy.yaml, services/net/transcription/Config/TranscriptionOptions.cs, services/net/transcription/TranscriptionManager.cs
- updated transcription service to allow creating transcript for old contents
- added new config for old tno content tag name
- ignore transcript on contents that are tagged as old tno contents
=> MMI-3186 Fix transcript issues

api/net/Areas/Services/Controllers/ReportController.cs, app/subscriber/src/features/my-reports/edit/view/ReportHistoryForm.tsx, libs/net/dal/Services/ReportInstanceService.cs, libs/net/dal/Services/ReportService.cs, libs/net/services/Helpers/ApiService.cs, libs/net/services/Helpers/IApiService.cs, services/net/reporting/ReportingManager.cs
Reports that accumulate are not working correctly in all cases.  Specifically a report that has never been sent before.  This update should resolve that issue.  It's difficult to test all possible regression issues with these changes.
=> Fix accumulate reports

app/subscriber/src/features/filter-media/FilterMediaLanding.tsx
Added code to check for both lower and upper case media sources.
=> MMI-3172 change to make all options name to upper case for filtering

libs/net/dal/Services/ReportService.cs, openshift/scripts/deploy.sh, openshift/scripts/stop.sh, openshift/scripts/up.sh, services/net/ches-retry/ChesRetryManager.cs
Fixing CI/CD scripts.
Fixing query for CHES Retry Service endpoint.
Handling error when a report instance is deleted.
=> Fix Ches Retry Service

libs/net/services/Config/ServiceOptions.cs, libs/net/services/Managers/ServiceManager`.cs, libs/net/services/Runners/BaseService.cs, services/net/ches-retry/ChesRetryManager.cs, services/net/reporting/ReportingManager.cs
All services will now restart automatically if configured after a critical failure.  This doesn't solve the issue where a service goes into a Failed status.
The CHES Retry Service will now auto restart after a sequence of failures.
=> Auto restart

app/editor/package.json, app/editor/src/features/content/form/ContentForm.tsx, app/editor/src/features/content/form/components/time-log/TimeLogSection.tsx
- updated AV content prep time component:
* removed arrow icon
* automatically update Total minutes when user click on publish
=> MMI-3142 AV content prep time issue

services/net/scheduler/SchedulerManager.cs
https://citz-gdx.atlassian.net/browse/MMI-3212
First attempt to resolve issue with reports running multiple times, which stops report writers from completing their report.
=> MMI-3212 Fix Scheduler Service

app/subscriber/src/features/search-page/components/advanced-search/components/sections/DateSection.tsx, app/subscriber/src/features/search-page/components/advanced-search/components/sections/constants/QuickPickerNames.ts, app/subscriber/src/features/search-page/components/advanced-search/components/sections/utils/determineActivePicker.ts
- added 72 hours duration option
=> MMI-3211 Added Advanced Search duration option

libs/net/dal/Services/WorkOrderService.cs
Add the Media Type column information back to the Transcription Queue page.
=> MMI-3214 Fix Transcription Queue

openshift/kustomize/tekton/base/tasks/deploy-all.yaml, openshift/kustomize/tekton/base/tasks/git-conditions.yaml
The `master` pipeline should now correctly build and deploy to the configured environment.
=> Fix pipeline

app/editor/src/features/admin/ingests/configurations/Newspaper.tsx, app/editor/src/features/admin/ingests/configurations/Syndication.tsx, services/net/syndication/SyndicationAction.cs
We can now configure syndication feeds to be applied to different sources.
=> MMI-3249 Update Syndication Service

app/subscriber/src/components/content-list/ContentRow.tsx, app/subscriber/src/components/content-list/utils/highlightTerms.tsx, app/subscriber/src/features/search-page/utils/formatSearch.ts
A few improvements in highlighting the search keywords so help users identify why a story has been returned by a query.
=> MMI-3247 Enhance highlight keywords

app/subscriber/src/features/search-page/components/advanced-search/AdvancedSearch.tsx, app/subscriber/src/features/search-page/components/advanced-search/styled/AdvancedSearch.tsx
- only show the validate result for advanced search mode
- fixed editor cursor focus issue
=> MMI-2918 Updated UI

app/editor/src/features/content/form/components/tags/utils/tagParsing.ts
Click the "Add Tag" UI. We will focus on the last line only. Do not group the rest of the tags.
```
The forum also provides links to other kinds of support, including different community and faithbased spaces,
healing services, and even art-, dance- and sound-ther- apy offerings. [AND]
It's an example of Kapwa in action. [bb]
"Every culture carries with them a set of values that enable that culture to not
just survive, but to thrive and flourish," said Angeles. 
"We will come out of this stronger." dryan@postmedia. com [FIN, TRAN, FORR, HLTH, HSG, ICBC]
```
=> Optimize the tag parsing  for Tag

app/editor/src/features/admin/series/SeriesList.tsx, app/editor/src/features/admin/series/SeriesMerge.tsx
Fixing the issue where the dropdown does not include all values.  Also changing the list view to use paging so that it doesn't lock up the browser loading 5,000+ records at once.
=> MMI-3273 Fix Merge Show/Program

openshift/kustomize/services/indexing/base/config-map.yaml, openshift/kustomize/services/indexing/base/deploy.yaml, openshift/kustomize/services/indexing/overlays/cloud-test/kustomization.yaml, services/net/indexing/Config/IndexingOptions.cs, services/net/indexing/IndexingManager.cs, services/net/indexing/IndexingService.cs, services/net/indexing/appsettings.Development.json, services/net/indexing/appsettings.Staging.json, services/net/indexing/appsettings.json
Updated Indexing Service so that we can run a second cluster of them which will index content to the Elasticsearch cloud cluster.
I've deployed this to PROD so that we can test indexing Elasticsearch in the cloud.
=> MMI-3261 Elasticsearch cloud

app/subscriber/src/features/search-page/SearchPage.tsx, app/subscriber/src/features/search-page/components/advanced-search/AdvancedSearch.tsx, app/subscriber/src/features/search-page/components/advanced-search/styled/AdvancedSearch.tsx, libs/net/dal/Services/ContentService.cs
=> MMI-2918 Advanced search updates

api/net/Areas/Subscriber/Controllers/ProductController.cs, app/subscriber/src/features/my-products/MyProducts.tsx, app/subscriber/src/features/my-products/styled/MyProducts.tsx, libs/net/dal/Services/Interfaces/IReportService.cs, libs/net/dal/Services/ReportService.cs
- added email format options on the UI for report product subscription
- updated report service to add or update user report
=> MMI-3270 Updated product subscription

libs/net/dal/Services/ContentService.cs, libs/net/models/Filters/ContentFilter.cs, tools/indexer/IndexerManager.cs
The Indexer Service needs to include all the content data.
=> Fix Indexer

openshift/kustomize/tools/indexer/base/job.yaml, tools/indexer/Config/IndexerOptions.cs, tools/indexer/IndexerManager.cs
Provided a way to filter on PublishedOn date to control how much needs to be inserted.
=> Update Indexer Service

db/postgres/README.md, openshift/kustomize/postgres/standalone/base/statefulset.yaml
Updating Infrastructure as Code and adding resource limits to the Postgres DB.
=> MMI-3281 Update DB resource limits

openshift/kustomize/prod-test/api-deploy.yaml, openshift/kustomize/prod-test/api-routes.yaml, openshift/kustomize/prod-test/api-service.yaml, openshift/kustomize/prod-test/deployments/api-deploy.yaml, openshift/kustomize/prod-test/editor-deploy.yaml, openshift/kustomize/prod-test/editor-route.yaml, openshift/kustomize/prod-test/editor-service.yaml, openshift/kustomize/prod-test/subscriber-deploy.yaml, openshift/kustomize/prod-test/subscriber-route.yaml, openshift/kustomize/prod-test/subscriber-service.yaml
Creating another environment in PROD to be able to test.  
> Note that this is connected to production data and will corrupt the production data if incorrectly used.  It should only be used to test changes that will not impact data.
=> Add PROD test env
