bcgov/tno

- Makefile
- db/kafka/docker-compose.yml
- docs/DEVELOPMENT.md
- libs/java/dal/db/dal-db-migration/.dockerignore
- libs/java/dal/db/dal-db-migration/Dockerfile
- libs/java/dal/db/dal-db-migration/README.md
- libs/java/dal/db/dal-db-migration/pom.xml
- libs/java/dal/db/dal-db-migration/src/main/java/ca/bc/gov/tno/dal/db/MigrationApp.java
- libs/java/dal/db/dal-db-migration/src/main/resources/application.yml
- libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/services/ClaimService.java
- libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/services/ContentReferenceService.java
- libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/services/DataSourceService.java
- libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/services/DataSourceTypeService.java
- libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/services/LicenseService.java
- libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/services/RoleService.java
- libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/services/ScheduleService.java
- libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/services/UserService.java
- libs/java/dal/db/scripts/db-update.sh
- openshift/README.md
- openshift/templates/jobs/db/build.yaml
- openshift/templates/jobs/db/deploy.yaml
- openshift/templates/postgres/singleton/03-deploy.yaml
- tools/scripts/db-update.sh
- tools/scripts/gen-env-files.sh
To improve developer local environment setup, scripts have been updated and a `make db-update` command has been added.  Developers can now initialize their TNO database and run future migrations.
DevOps process isn't complete, but the same process can be applied within Openshift through building the `dal-db-migration` image and running it as a Job.  I will look into other CI/CD options to perform this.
There is a new `make init` command that will now perform initializing a new environment.
A number of updates were made to `.env` file locations.  The `make setup` script will generate them, however it would be best to reset your environment entirely by deleting all of your containers and images and existing `.env` files.  This makes me think I may need to start providing migration scripts …
> TNO-165 Add DB migration

- .gitignore
- libs/npm/core/.prettierrc.bak
- tools/scripts/nuke.sh
- Added "*.bak" to .gitignore. All other changes in nuke.sh
- Only proceed to nuke if there are 1 or more existing environment/config files
- Ask user if they want to delete existing backups
- Move all environment/config files using pattern \<oldname\>.\<timestamp\>.bak
> nuke.sh updated

- .gitignore
- tools/scripts/gen-maven-files.sh
- tools/scripts/nuke.sh
- tools/scripts/variables.sh
- Suppressed grep errors in `variables.sh` for files not expected to exist
- Suppressed grep errors in `gen-maven-files.sh`, and fixed bug where looking for postgress .env file in wrong location
- Now using backup file extension *.nkbak* in `nuke.sh` & `.gitignore` so as not to interfere with others
- **Note:** Run `find . -type f -name "*.bak" -delete` to remove backup files from previous version
- Cleaned up nuke.sh
> updated scripts

- Makefile
- api/editor/api-editor/src/main/resources/application.yml
- auth/keycloak/README.md
- auth/keycloak/config/realm-export.json
- db/kafka/docker-compose.yml
- docker-compose.yml
- docs/DEVELOPMENT.md
- network/nginx/config/default.conf
A number of port changes still needed to be made within Keycloak, and Nginx.
Make commands have been changed.  `kafka-up`, `core-up`, `service-up`, and `utility-up` have all been removed.  Instead an argument has been added to the `make up p={profile name}` which allows for profile selection.  By default it will use the `all` profile.
`make init` will now only start a minimum of services for the purpose of initialization, but does not run any of the features.  You will need to run subsequent `make up p={profile name}` commands to run appropriate features.  Or just run `make up` if your machine can handle running everything.
- Update make commands
- Fix Keycloak config
- Fix App config
> TNO-126 Update make commands

- libs/java/dal/db/.devcontainer/Dockerfile
- libs/java/dal/db/.devcontainer/gpg-agent.conf
- libs/java/dal/db/.devcontainer/gpg.conf
- libs/java/dal/db/Makefile
- libs/java/dal/db/scripts/close-staging-repo.sh
- libs/java/dal/db/scripts/deploy-release.sh
- libs/java/dal/db/scripts/deploy-staging.sh
- libs/java/dal/db/scripts/drop-staging-repo.sh
- libs/java/dal/db/scripts/release-staging-repo.sh
- libs/java/dal/db/scripts/setup.sh
The fix to run with `sudo` won't work with containers in Windows VM.  The default behaviour is now for Windows VM, but there is now an override that can be used through parameters.
`make setup u=sudo`
`make deploy-release u=sudo`
> Fix maven gpg signing

- app/editor/src/features/content/list-view/constants/fieldTypes.ts
Snippet List View has been updated.  The *Field Type* `Workflow Status` is now two words and works the same as all the other values.
> TNO-69 Fix dropdown values

- api/editor/api-editor/src/main/java/ca/bc/gov/tno/areas/editor/models/ContentModel.java
- libs/java/dal/db/dal-db-test/src/main/java/ca/bc/gov/tno/dal/db/ContentTest.java
- libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentAction.java
- test/TNO.postman_collection.json
We can now save `content.contentActions` with the API.
Note that the API simplifies the schema.  I have also updated the Postman tests.
> Will need to run `make refresh n=api-editor`
> TNO-208 Fix content actions

- app/editor/src/features/content/list-view/ContentListView.tsx
- app/editor/src/features/content/list-view/constants/defaultFilter.ts
- app/editor/src/features/content/list-view/constants/index.ts
- app/editor/src/store/hooks/content/useContent.ts
- app/editor/src/store/slices/content/useContentStore.ts
The content list view filter wasn't correctly displaying/updating when returning to the page.  I've provided a way to set the default filter and removed one of the `React.useEffect(...)` calls.  Seems to be working now.
> Requires an `make npm-refresh`
I've noticed a few other minor issues with the page that will need to be resolved in the future.
- Table formatting when it has rows
- Paging button styling
- Table doesn't extend to end of div properly
- Need to keep the active filter when returning to the page instead of starting over with default filter
- Need to place filter parameters into URL so it can be shared or returned to from expired session.  This will need a common hook to handle.
> Fix content list view filter

- app/editor/Dockerfile.nginx
- app/editor/Dockerfile.rhel8
When building in Openshift `yarn` runs into network issues.  Which causes the build to fail 90% of the time.  The Lab suggested to run `yarn cache clean` before building.  I'm not optimistic that this will resolve the issue.
> TNO-228 Yarn clean cache

- app/editor/src/features/content/list-view/ContentListView.tsx
When clicking a row, the wrong id was being provided. `row.original` contains the values we need.
`row.id` is the id of the row itself not the content
Ex)
Row 1 would have row.id of 0
Row 2 would have row.id of 1
> Content List View Bug Fix

- app/editor/src/features/login/LoginPanel.tsx
The URL was adding an extra slash, which caused an error when trying to login.
> Fix login URL

- app/editor/src/features/content/form/PropertiesContentForm.tsx
Previously the time log would go stale and carry over incorrectly to a new snippet/ an existing one. Tied it to a state variable so it correctly resets to it's corresponding formik values when the "page" changes
> PSP-289: Update timelog to state variable

- app/editor/src/App.tsx
When a variable is provided for the tooltip that starts out as undefined/null the tooltip will not be shown. The tooltip needs to be rebound after the variable is provided.
> TNO-214: React tooltip fix

- app/editor/src/App.tsx
- app/editor/src/features/content/form/ContentForm.tsx
- app/editor/src/features/content/list-view/ContentListView.tsx
Did some more testing, last fix was not adequate. But got some more answers.
This seems to do the trick now.
"For example, you render a generic tooltip in the root of your app, then load a list of content async. Elements in the list use the data-for={id} attribute to bind the tooltip on hover. Since the tooltip has already scanned for data-tip these new elements will not trigger.
One workaround for this is to trigger ReactTooltip.rebuild() after the data load to scan for the attribute again, to allow event wireup."
> TNO-214: React tooltip fix adjustment

- app/editor/src/features/home/styled/InfoPanelStyled.tsx
Tiny fix that caught my eye. Was previously some empty space next to the "Sign In" text on the login panel. 
**Before:**
**After:**
> Sign In Button

- app/editor/src/features/content/form/ContentForm.tsx
- app/editor/src/utils/getDataSourceOptions.ts
Updated to have abbreviation in brackets after the name
> TNO-317: Use full source name

- app/editor/src/components/upload/Upload.tsx
- app/editor/src/features/content/form/ContentForm.tsx
- libs/net/dal/Extensions/FileReferenceExtensions.cs
- libs/net/dal/Models/ContentFileReference.cs
- libs/net/dal/Services/FileReferenceService.cs
- libs/net/entities/Interfaces/IReadonlyFileReference.cs
- libs/npm/core/src/hooks/summon/useSummon.tsx
The upload/download was broken when the data source dropdown list was changed.  I've modified the design so that this won't happen, and also solved other issues I was aware of.
- Uploaded file path is now stored so that it doesn't change after first created
- Changing the data source after won't break the file
> Note that existing files already uploaded will probably not work.  I don't want to spend time moving them around at this point.
> Fix upload/download

- libs/net/services/ServiceState.cs
When sending a request to the service api to resume after too many failures it must reset the number of failures back to zero.
> We still need to update our DevOps to pause our services when doing a deploy.
> Fix Service API

- libs/net/dal/Services/ContentService.cs
When searching for content it will now include the `Content.OwnerId` when determining if if should show up for the selected user.
> Fix content search

- api/net/Areas/Services/Controllers/ContentController.cs
- libs/net/core/Http/HttpRequestClient.cs
- libs/net/dal/Services/ContentService.cs
- libs/net/dal/Services/Interfaces/IContentService.cs
- libs/net/services/Helpers/ApiService.cs
- libs/net/services/Interfaces/IApiService.cs
- libs/net/services/Runners/BaseService.cs
- openshift/kustomize/services/content/base/deploy.yaml
- openshift/kustomize/services/content/overlays/dev/kustomization.yaml
- openshift/kustomize/services/content/overlays/prod/kustomization.yaml
- openshift/kustomize/services/content/overlays/test/kustomization.yaml
- services/net/content/ContentManager.cs
- services/net/content/ContentService.cs
The Content Service was built fast to pull content to Editors.  It was creating a lot of duplicates.  This update should reduce the duplication as it asks the API if the content identified by the `source` and `uid` already exists.
I've also increased the memory limit for the Content Service because 150Mi wasn't enough.
> Content service duplicates

- app/editor/src/components/form/area/styled/Area.tsx
- app/editor/src/components/form/checkbox/styled/Checkbox.tsx
- app/editor/src/components/form/timeinput/TimeInput.tsx
- app/editor/src/components/form/timeinput/styled/TimeInput.tsx
- app/editor/src/components/formik/textarea/styled/FormikTextArea.ts
- app/editor/src/features/content/form/ContentForm.tsx
- app/editor/src/features/content/form/ContentSummaryForm.tsx
This PR includes:
- expanding content summary to full width of parent container
- fixing the margins and groupings of content actions
- adding way to manually add specific time to the content's publishedOn attribute as shown below
> TNO-331, 334, 328

- app/editor/src/components/form/checkbox/styled/CheckboxField.tsx
- app/editor/src/components/form/datepicker/styled/SelectDate.tsx
- app/editor/src/components/form/radio/styled/Radio.tsx
- app/editor/src/components/form/text/styled/TextField.tsx
- app/editor/src/components/form/textarea/styled/TextAreaField.tsx
- app/editor/src/features/content/form/ContentForm.tsx
- app/editor/src/features/content/form/ContentSummaryForm.tsx
Adding border-box to the following elements allows to assigned width to account for the element's padding which was previously causing a mismatch in size.
> TNO-341: Input sizing

- api/net/Keycloak/KeycloakHelper.cs
- auth/keycloak/config/realm-export.json
- libs/net/services/Config/ServiceOptions.cs
- openshift/kustomize/services/syndication/base/deploy.yaml
- services/net/capture/appsettings.Development.json
- services/net/capture/appsettings.Staging.json
- services/net/capture/appsettings.json
- services/net/clip/appsettings.Development.json
- services/net/clip/appsettings.Staging.json
- services/net/clip/appsettings.json
- services/net/command/appsettings.Development.json
- services/net/command/appsettings.Staging.json
- services/net/command/appsettings.json
- services/net/content/appsettings.Development.json
- services/net/content/appsettings.Staging.json
- services/net/content/appsettings.json
- services/net/nlp/appsettings.Development.json
- services/net/nlp/appsettings.Staging.json
- services/net/nlp/appsettings.json
- services/net/syndication/appsettings.Development.json
- services/net/syndication/appsettings.Staging.json
- services/net/syndication/appsettings.json
Added the audience configuration for the service account in keycloak so that validation works.
> Please note that this will require another refresh of your keycloak service and database.  `make renew`
> TNO-213 Fix Keycloak

- api/net/appsettings.Development.json
- api/net/appsettings.Staging.json
- api/net/appsettings.json
- libs/net/core/Extensions/StringExtensions.cs
- libs/net/services/Config/ServiceOptions.cs
- services/net/capture/appsettings.json
- services/net/clip/appsettings.json
- services/net/command/appsettings.json
- services/net/content/appsettings.json
- services/net/nlp/appsettings.json
- services/net/syndication/SyndicationAction.cs
- services/net/syndication/Xml/Rss/RssChannel.cs
- services/net/syndication/Xml/Rss/RssFeed.cs
- services/net/syndication/Xml/Rss/RssItem.cs
- services/net/syndication/appsettings.json
There are two date time bugs.
- Many feeds have an invalid time-zone abbreviation.  Which results in the syndication feed failing.  I've created a simple string parser to determine a possible time-zone offset for the abbreviation.
- The services compare the local system datetime to the `DataSource.LastRanOn` datetime, but it would result in an incorrect comparison.  I don't know if I've fixed this, but it now defaults to UTC.  I'll need to test the Capture and Clip services at some point.
> TNO-378 Fix syndication feed dates

- libs/net/services/Actions/IngestAction.cs
- libs/net/services/Actions/Managers/ServiceActionManager`.cs
- libs/net/services/Actions/ServiceAction.cs
- libs/net/services/Interfaces/IIngestAction`.cs
- libs/net/services/Interfaces/IServiceAction`.cs
- services/net/capture/CaptureAction.cs
- services/net/clip/ClipAction.cs
- services/net/clip/ClipDataSourceManager.cs
- services/net/command/CommandAction`.cs
- services/net/nlp/NLPAction.cs
- services/net/syndication/SyndicationAction.cs
The Clip Service would shutdown as a result of scheduled run failures.  The failure was expected (the Capture file was missing), however based on configuration the service should continue to run other schedules without erroring out.
This update wraps the schedule runs with `try+catch` and correctly handles the failures based on config.
> TNO-356 Fix Clip Service

- openshift/kustomize/cron/base/config-map.yaml
- openshift/kustomize/cron/base/cron-job.yaml
- openshift/kustomize/cron/base/kustomization.yaml
- openshift/kustomize/cron/overlays/dev/kustomization.yaml
- openshift/kustomize/cron/overlays/prod/kustomization.yaml
- openshift/kustomize/cron/overlays/test/kustomization.yaml
We now have a simple Purge Service that uses a CronJob to delete folders (based on convention) that are older than two days.
The CronJob is configured to run nightly and executes a shell script file.
> TNO-386 Add Purge Service

- services/net/command/CommandAction`.cs
- services/net/command/CommandProcess.cs
- services/net/command/ICommandProcess.cs
Ingest services using the Command Service were not cleaning up when a premature exit occurred on the process.  For example when `ffmpeg` received a 404 it would exit, however the Capture and Clip Service would keep a reference to the process that ran.  This process then would continue to be reused even when it should no longer be used.
Now an exit will remove the referenced process so that a new process can be created.
> Fix Capture Service

- libs/net/dal/Services/DataSourceService.cs
As discussed, most likely a temp fix as there will most likely be data sources that don't generate content that should be in this list.
Do we want to control this at the back end of find all, or would it be better to filter from the frontend? Wondering mainly because of the admin section as we would still want to be able to edit these I am assuming.
> TNO-374: Get rid of duplicate data sources

- app/editor/src/features/content/form/constants/timeLogColumns.tsx
`date.getMonth()` is 0 indexed so we have to add +1 for desired output
> TNO-405: Time log table displaying wrong month

- app/editor/src/components/form/formpage/FormPage.tsx
- app/editor/src/components/form/formpage/styled/FormPage.tsx
- app/editor/src/features/content/form/CondensedContentForm.tsx
Add way to bypass `min-width` on the `FormPage` component, this also returns the combined view to the proper styling
> TNO-430: Hidden expand button on combined view

- app/editor/src/features/admin/actions/ActionForm.tsx
- app/editor/src/features/admin/categories/CategoryForm.tsx
- app/editor/src/features/admin/tags/TagListFilter.tsx
- app/editor/src/features/admin/tags/TagsForm.tsx
As tags behave slightly differently than admin areas with a string id, there was some incorrect behaviour when creating a new one. 
i.e) `useEffect` loop firing when it is not supposed to because `undefined !== 0`
Can now create a new tag as expected, form will submit the name value as the id. Also fixed some copy paste errors I ran into.
> TNO-425: Fix the add a tag error

- api/net/appsettings.json
- services/net/capture/appsettings.json
- services/net/clip/appsettings.json
- services/net/content/appsettings.json
- services/net/image/appsettings.json
- services/net/indexing/appsettings.json
- services/net/nlp/appsettings.json
- services/net/syndication/appsettings.json
- services/net/transcription/appsettings.json
All of our .NET container logs had invalid characters.  It appears this may be the result of console messages that contain colour information.  I'm turning colour off and testing.
> Fix logging invalid characters

- app/editor/src/components/breadcrumb/Breadcrumb.tsx
- app/editor/src/components/breadcrumb/index.ts
- app/editor/src/components/breadcrumb/styled/Breadcrumb.tsx
- app/editor/src/components/breadcrumb/styled/index.ts
- app/editor/src/features/content/form/Breadcrumb.tsx
- app/editor/src/features/content/form/ContentClipForm.tsx
- app/editor/src/features/content/form/styled/Breadcrumb.tsx
- app/editor/src/features/content/form/styled/index.ts
Having some bugs with the query params after latest changes, removed for now as breadcrumb functionality works. Query params will update but do not control state currently. Will create ticket to capture this.
Also ended up just making our own component, seemed to fit better for our scenario.
> TNO-520: Breadcrumb trail for clips

- app/editor/src/features/content/form/ContentClipForm.tsx
- app/editor/src/features/content/form/constants/clipDirectoryColumns.tsx
- app/editor/src/features/content/form/styled/ContentClipForm.tsx
Minor styling tweaks to the clip tab on the content form. Just decided to quickly tweak them as I was working on warnings in this area. 
PR Includes:
- removal of sort icon above icons
- video centered and does not expand screen
- horizontal scroll removed 
- slight dom cleanup
Zoomed at 100% on 1920x1080:
> Minor clip styling

- app/editor/src/features/content/form/ContentForm.tsx
- app/editor/src/features/content/form/ContentLabelsForm.tsx
- app/editor/src/features/content/form/ContentTranscriptForm.tsx
- libs/net/dal/Models/ContentFileReference.cs
- libs/net/models/Areas/Editor/Models/Content/FileReferenceModel.cs
- libs/net/models/Areas/Services/Models/Content/FileReferenceModel.cs
- services/docker-compose.yml
- services/net/transcription/appsettings.json
While testing I discovered a number of bugs.
- Content Labels react key values
- Content Clip tab, attaching a file should mark it as `IsUploaded=true`
- Transcription Service should be mapped to the API volume
- Transcription Service `FilePath` should only contain the mapped volume
I also moved the Transcribe and NLP buttons to the Transcription tab.
> Fixing various bugs

- .vscode/launch.json
- .vscode/tasks.json
- api/net/Areas/Services/Controllers/DataSourceController.cs
- libs/net/dal/Services/DataSourceService.cs
- libs/net/dal/Services/Interfaces/IDataSourceService.cs
- libs/net/kafka/KafkaListener`.cs
- services/net/capture/CaptureAction.cs
I introduced a bug when I removed data source connection information from the service endpoints.  Our ingest services require the connection information to determine if they should run.  It's not ideal including the connection information in the generic endpoints as it can contain secrets.  To secure these endpoints we'll need to add claim based authorization in another PR.
I've also added the Capture and Clip Services to the root launch file so we can run them outside of a devcontainer.
> Fix data source bug

- app/editor/src/features/content/form/ContentSummaryForm.tsx
Very underwhelming fix....
Positive lookbehind `(?<= )` causing a failure to load on iOS Safari
See: https://caniuse.com/js-regexp-lookbehind
> TNO-577: Allow access from iOS

- libs/net/core/Exceptions/HttpClientRequestException.cs
- libs/net/kafka/KafkaListener`.cs
- openshift/kustomize/api/build/base/build.yaml
- openshift/kustomize/app/editor/build/base/build.yaml
- openshift/kustomize/db-migration/build/base/build.yaml
- openshift/templates/tekton/pipelines/complete.yaml
- services/net/content/ContentManager.cs
- services/net/indexing/IndexingManager.cs
- services/net/nlp/NLPManager.cs
- services/net/transcription/TranscriptionManager.cs
Fixing issue with Kafka consumer services that stop consuming messages after an unexpected failure.  Normally that failure occurs within an HTTP request to the API.  Also added additional logging information for HTTP errors.
Updated the pipeline to build one thing at a time.  When attempting to do them all at once we run out of resources and the pipeline gets stuck.  Sequential however results in build times of over 30 minutes...
- Content Service
- Transcription Service
- Indexing Service
- NLP Service
> Fix Kafka Consumer Services

- libs/net/kafka/KafkaListener`.cs
Another fix to how errors are handled with Kafka consumer services.  Currently an issue occurs when unexpected errors occur and the thread is cancelled.  The Kafka consumer library is trying to dispose before being closed.
> Fix Kafka consumer

- app/editor/src/components/form/select/Select.tsx
I had tried a handful of different libraries with the same issue, as well as trying to find a better solution for "globally" handled tooltips. Was not able to make progress there.
This is a bit of a hacky fix; however, allows us to keep our tooltips the way they are throughout the application. I believe we can also get rid of the rebuild statements if we restructure where the tooltip is being rendered; but that may be outside of this ticket.
> TNO-427: Tooltip not disappearing on dropdown

- libs/net/dal/Migrations/Initial/Up/PostUp/01-Schedule.sql
- libs/net/dal/Migrations/Initial/Up/PostUp/03-IngestSchedule.sql
The initial DB migration scripts had an issue I introduced when I changed the name of some of the schedules.
> TNO-121 Fix DB migration script

- app/editor/src/features/content/form/ContentClipForm.tsx
- `.webm` and `.ogg` added as additions for further Firefox support (warnings seemed to be FF specific)
- `src` attribute added to `<source />` tag to address compiler warnings
> TNO-519: Clip warnings

- services/net/filemonitor/FilemonitorAction.cs
- services/net/filemonitor/models/Fields.cs
To complete this task I had to:
- Add ingest records for BCNG, MELT and STAR
- Add source records for BCNG and MELT
- Add schedules for GLOBE, BCNG, MELT and STAR
- Map the ingest records to the source records
The resulting ingest records are shown below. These will likely need updating (due to missed paper names) when I have a larger data set to work with after data is being retrieved from the SFTP server. The paper names configured are gathered from:
- Information provided by Scott.
- Online research.
- Existing test data.
One small issue: The filemonitor service currently ingests media_type "Paper" (id = 5). This has a content_type of 1, which I believe maps to the product id 1 (Daily Print). Some of the publications being ingested are daily, others are weekly and others are published …
> Mapping paper names to source configuration

- app/editor/src/features/content/form/ContentForm.tsx
- app/editor/src/features/content/form/ContentSummaryForm.tsx
- app/editor/src/features/content/form/ContentTranscriptForm.tsx
- app/editor/src/features/content/list-view/ContentListView.tsx
- app/editor/src/features/content/validation/ContentFormSchema.ts
- services/net/content/ContentManager.cs
- services/net/syndication/SyndicationAction.cs
A number of bug fixes related to syndication content, the content form, and requesting transcripts and NLP.
- Syndication Ingest Service: Will now correctly update the story body
- Composite View: Will now correctly update the form based on the loaded content type
- Content Form: Summary is only visible for snippets
- Content Form: Transcription and Clips tab are only visible for snippets
- Content Form: Request Transcript button is only visible for snippets
- Content Form: Request NLP button is only visible if the story body has text
- Content Form: Request Transcript will now first save 
- Content Form: Request NLP will now first save
> Note that currently there is no way to edit the summary of a story imported by the syndication service.  Probably the summary value should just be …
> TNO-637 Fix content body bugs

- app/editor/src/features/content/form/ContentForm.tsx
- libs/net/kafka/KafkaListener`.cs
- openshift/kustomize/README.md
- openshift/kustomize/services/transcription/base/config-map.yaml
- openshift/kustomize/services/transcription/base/deploy.yaml
- services/net/capture/CaptureAction.cs
- services/net/clip/ClipAction.cs
- services/net/content/ContentManager.cs
- services/net/indexing/IndexingManager.cs
- services/net/nlp/NLPManager.cs
- services/net/transcription/TranscriptionManager.cs
The Kafka consumer services were using a `Task.Factory.StartNew(...)`, but the tasks it created would not await and continued to run to completion (even though they were still running!).  The fix creates the thread in a simpler way and appears to correctly await until the process completes before attempting to create a new thread.
Also updated the Infrastructure as Code to resolve transcription service configuration issues in Openshift.
> TNO-445 Fix Kafka consumers

- app/editor/src/features/content/form/ContentForm.tsx
- app/editor/src/features/content/list-view/ContentListView.tsx
- app/editor/src/features/content/list-view/styled/ContentListView.tsx
- Slight DOM structure change to `ContentListView` and min-height adjusted to `fit-content`
- Commentary will now only appear once (as indented) for content types other than snippet/print
> TNO-621, 611

- libs/net/kafka/KafkaListener`.cs
- services/net/content/ContentManager.cs
- services/net/indexing/IndexingManager.cs
- services/net/nlp/NLPManager.cs
- services/net/transcription/TranscriptionManager.cs
The Kafka consumers were not correctly awaiting the completion of the handle message task.  This was originally resulting in the creation of new threads any time a long async process ran.  My last fix introduced a different bug, which was it no longer ran asynchronously.  
This fix appears to correct the prior issues.
> Fix kafka consumers

- services/net/content/ContentManager.cs
- services/net/nlp/NLPManager.cs
Syndication content without a body regrettably results in the summary not being displayed because we only show the summary or the body (depending on the content type).  We never show both for syndication content.
I've updated the Content Service to check the content type and then use the summary if the body is empty.
> TNO-639 Fix syndication content without body

- services/net/clip/ClipAction.cs
For some reason on Openshift the command we were using to create a clip was resulting in a corrupt output file.  This was caused by the `-c:v copy -c:a copy` arguments.  These arguments are to speed up the process dramatically, but they result in a failure, so not much value.
> TNO-610 Fix clip service

- app/editor/src/features/admin/ingests/configurations/Audio.tsx
- app/editor/src/features/admin/ingests/configurations/AudioStream.tsx
- services/net/capture/CaptureAction.cs
- services/net/clip/ClipAction.cs
- services/net/filemonitor/FilemonitorAction.cs
- services/net/image/ImageAction.cs
- services/net/syndication/SyndicationAction.cs
Our ingest services update a `Content Reference` to reduce the possibilities of duplicates.  However, a race condition is occurring where the ingest service is posting content to Kafka and the `Content Service` has already imported it before the ingest service has even finished updating the `Content Reference`.
To resolve this ingest service `Kafka Producers` will make an additional request to the `Content Reference` to determine if it has already been imported.
Additionally I have added default "Other Arguments" for `ffmpeg` when the ingest is configured for an audio stream.
> Fix Kafka Producers

- app/editor/src/components/form/textarea/TextArea.tsx
- app/editor/src/components/form/textarea/styled/TextArea.ts
Text area now appears under label like before:
> Text area styling

- libs/net/dal/Migrations/Initial/Up/PostUp/02-Ingest.sql
- openshift/kustomize/README.md
- openshift/kustomize/elastic/overlays/test/kustomization.yaml
Minor tweak to the Initial DB migration script what configures the ingest for the radio stream.  It'll now use the mp3 endpoint instead of the m3u8 one.  This is because Openshift continues to have network issues on the m3u8 route.
Minor updates for DevOps Infrastructure as Code.
> TNO-618 Update DB Migration

- app/editor/src/components/upload/Upload.tsx
- app/editor/src/features/content/form/ContentSummaryForm.tsx
The Snippet form Upload component had issues if the user attached a file before the content was saved.  It now checks whether the file has been uploaded.
> TNO-593 Fix attach clip

- app/editor/src/features/content/form/ContentForm.tsx
- app/editor/src/features/content/form/styled/ContentForm.tsx
The Content Form layout should expand and have vertical scrolling when it is on its own page.  When it is part of the combined page it should fit the page.
> Fix content form layout

- app/editor/src/features/admin/ingests/IngestSettings.tsx
- app/editor/src/features/admin/ingests/configurations/Newspaper.tsx
- app/editor/src/features/content/form/ContentSummaryForm.tsx
- app/editor/src/features/router/AppRouter.tsx
- libs/net/core/Extensions/DateTimeExtensions.cs
- libs/net/dal/Migrations/Initial/Up/PostUp/00-Connection.sql
- libs/net/dal/Migrations/Initial/Up/PostUp/02-Ingest.sql
- libs/net/services/Actions/IngestAction.cs
- libs/net/services/Actions/Managers/IngestActionManager`.cs
- services/net/capture/CaptureAction.cs
- services/net/clip/ClipAction.cs
- services/net/command/CommandAction`.cs
- services/net/filemonitor/FilemonitorAction.cs
- services/net/image/ImageAction.cs
When a user is missing from the lookups due to either local storage not being up-to-date, or keycloak incorrectly configured it will now redirect to an error page.
Fixed time zone issues with the published on date.  The correct value will be displayed for content created by Capture and Clip Service.
Fixed configuration issues with File and Image Service.
> Will require `make db-refresh` if you want the latest ingest configuration
> TNO-646 Fix published on

- app/editor/src/features/admin/sources/constants/columns.tsx
Fixed TNO-505: [QA] lower-cased source names & numbered names display in wrong order
> Fixed TNO-505

- app/editor/src/components/form/formpage/FormPage.tsx
- app/editor/src/components/form/formpage/styled/FormPage.tsx
- app/editor/src/features/content/list-view/ContentListView.tsx
Fixed a bug that forced the combine view to have too small of a width matching that of the admin sections.
> TNO-642: Fix bug introduced on combined view

- app/editor/src/features/content/form/ContentForm.tsx
- app/editor/src/features/content/form/utils/index.ts
- app/editor/src/features/content/form/utils/triggerFormikValidate.ts
- Provide a utility function that can be used when a button that is not of type submit needs to trigger the Formik validation and present errors to the user. 
- Also ensured that this is called when content is published.
> TNO-606: Ensure validation is run on publish

- app/editor/src/features/content/form/ClipDirectoryTable.tsx
Fixed TNO-651: [enhancement] Clips Folders - current date's folder appears at top of the list by default
> Fixed TNO-651

- libs/net/dal/Migrations/Initial/Up/PostUp/00-Connection.sql
- libs/net/dal/Migrations/Initial/Up/PostUp/01-Schedule.sql
- libs/net/dal/Migrations/Initial/Up/PostUp/02-Ingest.sql
- libs/net/dal/Migrations/Initial/Up/PostUp/03-IngestSchedule.sql
- services/net/filemonitor/FilemonitorAction.cs
- services/net/filemonitor/appsettings.json
This is the gist of it. I already see a couple of issues with what I pushed, but I have to get to Openshift training. I added the `passwordAuth` property to the connection to make explicit that the Globe and Mail requires password-based authentication. I struggled a bit with how to compare bool? with bool in my error detection code. Let me know if my solution could be improved.
Sorry about the two commits, when I did `git rebase -i origin/dev` it didn't hook in to vscode...probably the same option I fixed before, but don't have time to mess with it.
> Tno 644 - Add Globe and Mail import to the filemonitor service

- app/editor/src/components/form/formpage/styled/FormPage.tsx
- app/editor/src/features/admin/work-orders/WorkOrderList.tsx
- app/editor/src/features/admin/work-orders/styled/WorkOrderList.tsx
- Tables now scroll rather than the full form page (like the content list view), also stops the page from jumping around when a pagination value is changed
- Work orders slightly adjusted to match other admin areas
- Double scroll bar no longer on content list view
> TNO-711: Double scroll bar fix

- app/editor/src/components/form/formpage/styled/FormPage.tsx
- app/editor/src/features/admin/ingests/IngestForm.tsx
- app/editor/src/features/admin/ingests/IngestStatus.tsx
- app/editor/src/features/admin/ingests/styled/IngestForm.tsx
- app/editor/src/features/admin/ingests/styled/IngestStatus.tsx
Was hoping to bundle this with the user list fix, but still fighting with it.
- Added a toggle for status information on ingest and made it take up less space - can remove if needed. Was just playing around and thought it could be handy
- Form page no longer has hidden attribute
- Tables still scroll for admin sections
> Tweaks to address issues introduced from TNO-711

- app/editor/src/features/content/form/ContentSummaryForm.tsx
Still working on the other tag related ticket.
- now checks for tags at end of summary (last line)
- still iOS friendly
- having tags above the last line will no longer delete the proper ones
I think eventually we should implement something like GitHub has for PR labels, much easier to maintain.. probably easier for the user too
> TNO-713: More smarts to tags

- app/editor/src/features/content/form/ContentSummaryForm.tsx
Set default date via `setFieldValue`, as other logic in the content form rely on the `formik` value (cannot simply set value within the date picker)
> TNO-702: Default date

- api/net/Dockerfile
- openshift/kustomize/tekton/base/tasks/build-component.yaml
- openshift/kustomize/tekton/base/tasks/buildah.yaml
- services/net/capture/appsettings.json
- services/net/clip/appsettings.json
- services/net/content/appsettings.json
- services/net/filemonitor/FilemonitorAction.cs
- services/net/filemonitor/appsettings.json
- services/net/image/ImageAction.cs
- services/net/image/appsettings.json
- services/net/indexing/appsettings.json
- services/net/nlp/appsettings.json
- services/net/syndication/appsettings.json
- services/net/transcription/appsettings.json
- File and Image ingest services had an invalid output path.
- All ingest services are now defaulted to PST instead of UTC.  This was causing issues with date comparison.  I haven't had time to test Syndication, Capture, and Clip to determine if the change has a negative impact.
- Attempting to find a way to get the API to build with Buildah.  It runs of drive space in the container.  However, if I use a PVC it then throws a permission error.
> Fix image/file ingest path

- api/net/Dockerfile
- api/net/Dockerfile.aspnet
This may not work, but will attempt to use a prebuilt image for aspnet:6.0.  This image is stored in our image registry.
I do not know if our image registry is accessible without authentication.  I'll test with my laptop shortly if the pipeline is able to complete the build.
> Change api Dockerfile image

- api/net/Dockerfile
Another attempt at resolving our build issue.  For some reason Buildah runs out of device space.
> Reduce api build image size

- app/editor/src/features/admin/ingests/configurations/FrontPage.tsx
- libs/net/dal/Migrations/Initial/Up/PostUp/02-Ingest.sql
- services/net/image/ImageAction.cs
Front pages are often delivered the evening before their published on date.  There is now a way to add a regex to parse the published on date from the file name.
> Correct Front page published on date

- api/net/Dockerfile.openshift
- openshift/kustomize/api/build/base/build.yaml
- openshift/kustomize/tekton/base/pipelines/buildah-api.yaml
- openshift/kustomize/tekton/base/pipelines/buildah-main.yaml
The change to the BuildConfig for the API regrettably required authentication to build locally.  Which complicates the ease of setting up a new developer environment.  I've created two separate Dockerfile's so that it will work locally without issues.  This of course now requires us to update both to keep them in sync, which isn't ideal.
> Fix local api build

- app/editor/src/features/admin/connections/configurations/AWSConfiguration.tsx
- app/editor/src/features/admin/connections/configurations/AzureConfiguration.tsx
- app/editor/src/features/admin/connections/configurations/FTPConfiguration.tsx
- app/editor/src/features/admin/connections/configurations/HTTPConfiguration.tsx
- app/editor/src/features/admin/connections/configurations/NASConfiguration.tsx
- app/editor/src/features/admin/connections/configurations/SFTPConfiguration.tsx
- app/editor/src/features/admin/connections/configurations/SSHConfiguration.tsx
- app/editor/src/features/admin/ingests/IngestSettings.tsx
- app/editor/src/features/admin/ingests/configurations/AudioClip.tsx
- app/editor/src/features/admin/ingests/configurations/AudioStream.tsx
- app/editor/src/features/admin/ingests/configurations/VideoClip.tsx
- app/editor/src/features/admin/ingests/configurations/VideoStream.tsx
- libs/net/core/Extensions/StringExtensions.cs
- libs/net/dal/Extensions/IngestExtensions.cs
- services/net/Makefile
- services/net/clip/ClipAction.cs
- services/net/clip/TNO.Services.Clip.csproj
- services/net/content/ContentManager.cs
- services/net/filemonitor/FilemonitorAction.cs
- services/net/image/ImageAction.cs
The Clip Service needs access to the capture files.  Which means it either needs to copy a large file across the network, or the Clip Service needs to be run in the same location as the capture files.  For performance, the best option is to run it in the same location.
- Clip service creates a temporary file if the stream is a mkv file, so that it can calculate duration.
- Fixed a bug where remote path include `~` for the current user's home directory.
- Fixed bug when saving a new Ingest configuration with a schedule.
> TNO-710 Update Clip service to run remotely

- api/net/Areas/Admin/Models/Ingest/SourceModel.cs
- api/net/Areas/Admin/Models/Source/SourceModel.cs
- app/editor/src/features/admin/sources/SourceDetails.tsx
- app/editor/src/hooks/api-editor/interfaces/ISourceModel.ts
- libs/net/dal/Migrations/Initial/Up/PostUp/01-Source.sql
- libs/net/dal/Migrations/Initial/Up/PostUp/02-Ingest.sql
- libs/net/dal/Models/SourceFilter.cs
- libs/net/models/Areas/Editor/Models/Content/SourceModel.cs
- libs/net/models/Areas/Editor/Models/Source/SourceModel.cs
- libs/net/models/Areas/Services/Models/Ingest/SourceModel.cs
- services/net/filemonitor/FilemonitorAction.cs
This should contain all the changes in the original branch TNO-709, plus the following:
1. Code to handle the situation where some downloaded newspaper import files are empty. I had to do this now, rather than opening another ticket, as I could not test the FileMonitor service without this change. Monday November 7th is the only day that empty files have been provided on the Globe and Mail FTP server.
2. As the GLOBE ingest is the only self-published ingest and it's a daily print newspaper, I added a statement in the migration to set the product_id for the ingest to "Daily Print". This is required for the correct product designation to display for Globe and Mail articles.
> Changes for TNO-709 in new branch TNO-709-2

- app/editor/src/components/form/select/Select.tsx
- app/editor/src/components/form/select/styled/Select.tsx
- app/editor/src/components/form/select/styled/SelectField.tsx
- app/editor/src/features/admin/users/UserForm.tsx
- app/editor/src/features/admin/users/styled/UserList.tsx
- app/editor/src/features/content/form/ContentForm.tsx
- app/editor/src/features/content/list-view/ContentFilter.tsx
TODO: 
- Can now click an "x" within the react-select to clear input, works for both formik and non-formik
- Also removed some dead CSS
> TNO-730: Clear button on react-select

- api/net/Areas/Admin/Controllers/WorkOrderController.cs
- api/net/Areas/Editor/Controllers/ContentController.cs
- api/net/Areas/Editor/Controllers/LookupController.cs
- api/net/Areas/Kafka/Controllers/ProducerController.cs
- api/net/Areas/Services/Controllers/ConnectionController.cs
- api/net/Areas/Services/Controllers/ContentController.cs
- api/net/Areas/Services/Controllers/ContentReferenceController.cs
- api/net/Areas/Services/Controllers/DataLocationController.cs
- api/net/Areas/Services/Controllers/IngestController.cs
- api/net/Areas/Services/Controllers/SourceController.cs
- api/net/Areas/Services/Controllers/WorkOrderController.cs
This is a temporary "fix" to get everything working with the Keycloak Gold realm integration.
Regrettably Keycloak Gold realm does not provide a way to grant roles to the service account.  All of our services use this account to communicate with our API.  Because they have no roles, they are not authorized to use our API.  
I have removed most of the security related to authorization in the API to allow everything to keep working for now.
> TNO-8 Reduce security to temporarily enable keycloak gold realm

- app/editor/src/components/form/wysiwyg/CustomToolbar.tsx
- app/editor/src/components/form/wysiwyg/Wysiwyg.tsx
When there were two instances of a WYSIWYG present (when expanding to full view) it caused issues for the styling. Had to provide a ref for each instance of the editor. 
This will unblock Cello :)
> Fix styling bug for WYSIWYG

- app/editor/src/features/content/form/WorkOrderStatus.tsx
- libs/net/kafka/KafkaListener`.cs
- services/net/content/ContentManager.cs
- tools/scripts/gen-env-files.sh
The content service was having issues restarting after going to sleep.  
The reason the content service fails regrettably is due to a known challenge with deployments.  We still need a way to tell all our services to go to sleep during a deployment of the API.
> TNO-792 Fix Content service

- api/net/Controllers/AuthController.cs
- api/net/Keycloak/CssHelper.cs
A first time user login will now perform the following steps to activate their account.
1) Check if a user with the same key exists (should only occur if they have already been activated)
2) NEW - Check if a user with the same username exists in the database
3) Check if a user with the same email exists in the database
This is to solve an issue where the preapproved user email doesn't match the username.  When the user logs in the first time, it attempts to create a new account, but the username already exists.
> TNO-815 Fix keycloak gold

- api/net/Keycloak/CssHelper.cs
- libs/net/core/Http/OpenIdConnectRequestClient.cs
Update the activate process for new users to allow them to have no email assigned from keycloak.
> Allow user to have no email

- app/editor/src/components/form/wysiwyg/Wysiwyg.tsx
Will need to confirm this in DEV once it's in. But React Quill uses <br /> and does not seem to deal well with \n tags which was coming in from ingestion. This should clear that up
> TNO-812: Paragraph spacing

- app/editor/src/components/form/wysiwyg/CustomToolbar.tsx
I initially wanted to enable react-tooltip text on the buttons in the toolbar, but the buttons use html &lt;button&gt; tags rather than the React &lt;Button&gt; component, so the functionality is not available.
The toolbar is implemented using a React Quill CustomToolbar using the `snow` theme. This theme does not support tooltips out of the box and the documentation indicates that you have to create a custom theme to add tooltips. I used the html `title` attribute on each of the toolbar buttons to achieve the desired result. It may have been better to implement these attributes in the css, but the css classes are part of the Quill component in node_modules and the use of themes is the preferred method of overriding them. As I wanted to avoid the complexity of introducing a new theme I …
> Added tooltips to wysiwyg editor toolbar

- app/editor/src/features/content/morning-report/MorningReportFilter.tsx
Morning report now only shows Print Content.
- checkbox for print content still appears; however, has bene disabled
Wondering if the option should just be removed entirely?
> TNO-840: Only show print content on morning report

- app/editor/src/store/slices/content/contentSlice.ts
Advanced search now defaults to source instead of headline.
> TNO-908: Default to Source not Headline

- .vscode/tasks.json
- app/editor/src/features/admin/ingests/IngestDetails.tsx
- libs/net/services/Managers/IngestManager`.cs
- services/net/filemonitor/FileMonitorIngestActionManager.cs
- services/net/filemonitor/FilemonitorAction.cs
- services/net/filemonitor/FilemonitorManager.cs
- services/net/syndication/SyndicationAction.cs
The File Service was not using the correct source code when add/updating the content reference.  This was causing significant error logs.
Also fixed configuration so that we can run the File Service locally.
Fixed Syndication Service to correctly handle failed requests for feeds.
> TNO-906 Fix File Service Source, Syndication Feed Request

- services/net/filemonitor/FilemonitorAction.cs
The File Service was posting duplicate content to Kafka when the published date was older.  I am not sure why but the daily papers appear to have a lot of duplicate content.
> TNO-906 Fix duplicates

- app/editor/src/components/form/toning/styled/ToningGroup.tsx
- app/editor/src/features/content/tool-bar/ContentToolBar.tsx
- app/editor/src/features/content/tool-bar/sections/filter/DateRangeSection.tsx
- app/editor/src/features/content/tool-bar/sections/filter/FilterContentSection.tsx
- app/editor/src/features/content/tool-bar/sections/filter/index.ts
- app/editor/src/features/content/tool-bar/sections/filter/styled/DateRangeSection.tsx
- app/editor/src/features/content/tool-bar/sections/filter/styled/index.ts
- moved date range to its own component for easier styling
- an x button now appears to the right of the date range component to allow the user to clear their date selection
- filter is now applied whenever date is changed or cleared
TNO-888 requests for the date to be triggered on hitting 'enter'; however, I believe the above fits in with the content tool bar better as it behaves the same as the section it is contained in. Let me know if we want it changed.
See behaviour in GIF below:
> TNO-888, 887: Date range trigger and clear

- api/net/Areas/Admin/Controllers/ContentReferenceController.cs
- app/editor/src/features/admin/ingests/ContentReferenceList.tsx
- app/editor/src/features/admin/ingests/constants/contentReferenceColumns.tsx
- app/editor/src/features/admin/ingests/constants/defaultContentReferenceFilter.ts
- app/editor/src/features/admin/ingests/interfaces/IContentReferenceListFilter.ts
- app/editor/src/hooks/api-editor/admin/useApiAdminContentReferences.ts
- app/editor/src/hooks/api-editor/interfaces/IContentReferenceFilter.ts
- app/editor/src/store/hooks/admin/useContentReferences.ts
- libs/net/dal/Models/ContentReferenceFilter.cs
- libs/net/dal/Services/ContentReferenceService.cs
- libs/net/dal/Services/Interfaces/IContentReferenceService.cs
- libs/net/entities/ContentReference.cs
The Ingest admin page has an 'Ingesting' tab to help debug.  This tab lists related content references.  I've updated this table to include all possible `source` values for the ingest.  Previously it was only filtering on the main `source`.  The papers however ingest many different sources.'
You can also now click on the row and load the content if it exists.
> TNO-906 Improve ingest admin

- app/editor/src/components/toggle-group/ToggleGroup.tsx
- app/editor/src/components/toggle-group/styled/ToggleGroup.tsx
- app/editor/src/features/content/tool-bar/sections/filter/DateRangeSection.tsx
- app/editor/src/features/content/tool-bar/sections/filter/FilterContentSection.tsx
- also clears the timeframe filter when selected
- hovering over the options will also show a not allowed while there is a start or end date selected 
- after clearing start/end date it will default the time frame back to today (is this what we want?)
> TNO-909: If using date range widget, the Today 24 HR 48 HR ALL panel should be greyed out

- app/editor/src/features/content/tool-bar/sections/filter/AdvancedSearchSection.tsx
- Fix bug where the user cannot clear source on the react-select component in the content tool bar
> TNO-1004: Can't clear source

- app/editor/src/features/content/form/ContentForm.tsx
- now select source first as it has the possibility of having a designation tied to it
- previously source overriding designation even if it was `undefined`, now only does so if it has a value
> Designation Override Bug

- libs/net/dal/Migrations/Initial/Up/PostUp/02-Ingest.sql
- services/net/clip/ClipAction.cs
The Clip Service was applying a default codecs copy which was resulting in invalid AV files.  I've removed the default value and now FFmpeg appears to be able to create valid `mp4` clips from a `webm` format.
Also fixed the default timezone configuration for the CP News syndication feed.
> TNO-874 Fix Clip service

- openshift/kustomize/postgres/crunchy/base/deploy.yaml
Due to some issue in Openshift the default images from `registry.developers.crunchydata.com` were no longer available or working.  Had to update the images in our template to `artifacts.developer.gov.bc.ca/bcgov-docker-local` and `apply` the changes.
I've updated DEV and everything appears to be stable.  I will updated TEST when our round of testing is complete.
> TNO-996 Fix CrunchyDB template

- app/editor/src/components/tool-bar/styled/ToolBarSection.tsx
- app/editor/src/features/content/form/constants/ShowOnlyValues.ts
- app/editor/src/features/content/form/constants/showOnlyOptions.ts
- app/editor/src/features/content/list-view/interfaces/IContentListFilter.ts
- app/editor/src/features/content/tool-bar/ContentFormToolBar.tsx
- app/editor/src/features/content/tool-bar/sections/filter/ShowOnlySection.tsx
- app/editor/src/features/content/tool-bar/sections/filter/utils/checkLatestShowOnlyEntry.ts
- app/editor/src/features/content/tool-bar/sections/filter/utils/getSelectedOptions.ts
- app/editor/src/features/content/tool-bar/sections/filter/utils/index.ts
- content list view filter toolbar now changes the Show Only section to a multi-select if screen real-estate is minimal. will sync up with existing values from checkboxes
- license options hidden on the content form toolbar if space is minimal 
**Sync example:**
**Resize example:**
> TNO-818: Toolbar Responsiveness

- app/editor/src/features/content/form/ContentSummaryForm.tsx
Ensure that the user inputted time is not overwritten if the date is changed. Previously changing the date after entering a time would overwrite it to the created on time.
> TNO-1015: Time overwritten bug

- api/net/Dockerfile.openshift
- libs/net/kafka/KafkaListener`.cs
- openshift/kustomize/api/build/overlays/jmf/kustomization.yaml
- openshift/kustomize/api/overlays/dev/kustomization.yaml
- openshift/kustomize/api/overlays/prod/kustomization.yaml
- openshift/kustomize/api/overlays/test/kustomization.yaml
- openshift/kustomize/services/capture/overlays/dev/kustomization.yaml
- openshift/kustomize/services/capture/overlays/prod/kustomization.yaml
- openshift/kustomize/services/capture/overlays/test/kustomization.yaml
- services/net/filecopy/FileCopyManager.cs
Surprisingly FFmpeg was never released to Openshift on the API.  I have now added it to the appropriate `Dockerfile`.
I have also updated the resource requirements for the Capture and API pods.
> TNO-736 Add FFmpeg to API

- libs/net/dal/TNO.DAL.csproj
- libs/net/services/Runners/BaseService.cs
- openshift/kustomize/tekton/base/pipeline-runs/buildah-service.yaml
- openshift/kustomize/tekton/base/tasks/build-component.yaml
- openshift/kustomize/tekton/base/tasks/buildah.yaml
- openshift/kustomize/tekton/base/triggers/template.yaml
- services/net/capture/Dockerfile
- services/net/clip/Dockerfile
- services/net/command/Dockerfile
- services/net/content/Dockerfile
- services/net/filecopy/Dockerfile
- services/net/filemonitor/Dockerfile
- services/net/image/Dockerfile
- services/net/indexing/Dockerfile
- services/net/nlp/Dockerfile
- services/net/syndication/Dockerfile
- services/net/transcription/Dockerfile
- tools/import/etl/TNO.Tools.Import.ETL.csproj
The library that loads `.env` files had a breaking change that resulted in not loading the config.
In my efforts to debug Openshift DevOps issues a change to the Dockerfiles has been rolledback.
Templates have been updated to support the latest security requirements and space limitations.
> Fix services

- app/editor/src/features/content/form/ContentSummaryForm.tsx
Prep time is only needed for TV, Talk Radio and Radio News (Audio/Visual (Snippet) form.)
> TNO-1039: Only show time log entry for snippets

- app/editor/src/features/content/form/ContentForm.tsx
- app/editor/src/features/content/form/ContentSummaryForm.tsx
Hide the NLP options for editors as they have been confusing and are not yet required
> TNO-1065: Hide NLP options for editors

- api/net/Areas/Admin/Controllers/WorkOrderController.cs
- api/net/Areas/Editor/Controllers/WorkOrderController.cs
- api/net/Areas/Services/Controllers/ContentController.cs
- api/net/Program.cs
- api/net/SignalR/WorkOrderHub.cs
- api/net/appsettings.Development.json
- api/net/appsettings.Staging.json
- api/net/appsettings.json
- libs/net/core/Extensions/IEnumerableExtensions.cs
- libs/net/kafka/Config/KafkaHubConfig.cs
- libs/net/kafka/Extensions/ServiceCollectionExtensions.cs
- libs/net/kafka/Serializers/DefaultJsonSerializer.cs
- libs/net/kafka/SignalR/HubEvent.cs
- libs/net/kafka/SignalR/HubUsernameProvider.cs
- libs/net/kafka/SignalR/KafkaHubLifetimeManager`.cs
- libs/net/kafka/SignalR/KafkaHubMessage.cs
- libs/net/kafka/SignalR/KafkaInvocationMessage.cs
- openshift/kustomize/api/base/kustomization.yaml
- openshift/kustomize/api/base/statefulset.yaml
- services/docker-compose.yml
- services/net/clip/ClipManager.cs
SignalR maintains state locally and is unaware of other instances of the API that may be running.  When running the API as a cluster (more than one pod) it requires a SignalR backpane to support broadcasting messages to every pod.  A Kafka Hub backpane has been created to support clusters.
All messages sent to the Hub will be initially published to Kafka.  The API is now a Kafka Consumer which will then receive the latest message and send it to the appropriate user now mater which pod they are connected to.
For all this to work the API will need to be reconfigured as a statefulset so that each pod will have a consistent and different Kafka Consumer Group ID.  Otherwise they would not all receive each message, or they would end generating new Group ID values that would result in receiving …
> TNO-1041 Add SignalR back-plane

- api/net/Areas/Editor/Controllers/ContentController.cs
- api/net/Areas/Editor/Controllers/MorningReportController.cs
- api/net/Areas/Services/Controllers/ContentController.cs
- api/net/Program.cs
- libs/net/dal/Services/ContentService.cs
- libs/net/dal/Services/Interfaces/IContentService.cs
- libs/net/reports/CBRAReport.cs
- openshift/kustomize/tekton/base/pipelines/buildah-main.yaml
Currently the reindex endpoint attempts to reindex everything.  However, this timeout quickly.  This update provides a way to apply query parameter filter which will allow reindexing smaller subsets.
Also adding swagger to all builds instead of just development.
> Add filter to reindex

- app/editor/src/components/form/wysiwyg/styled/Wysiwyg.tsx
> WYSIWYG font size consistency

- app/editor/src/components/form/toning/ToningGroup.tsx
- app/editor/src/features/content/validation/ContentFormSchema.ts
Revert schema back and update how toning group displays validation error. 
- will create a separate ticket to dissect how to get the Yup schema working correctly with an array
> Toning validation hotfix

- app/editor/src/features/content/form/ContentForm.tsx
- app/editor/src/store/hooks/useAjaxWrapper.ts
- services/net/indexing/IndexingManager.cs
Updated the delete content process so that the Indexing Service will no longer make a request for the content before attempting to delete it.
This does require changing the key we use in Elasticsearch.  Which means I need to delete the index and rebuild it.
> TNO-1113 Fix delete content

- app/editor/src/features/content/list-view/ContentListView.tsx
- app/editor/src/features/content/list-view/constants/columns.tsx
- new icon on content list view rows to open snippets in new tabs (header as hover tooltip to save space/ as per discussion with Bobbi)
- now when clicking a row on the content list view it will scroll the content form into view (see GIF below)
> TNO-1058: Content scrolling

- app/editor/src/features/content/list-view/ContentListView.tsx
- app/editor/src/hooks/useCombinedView.ts
Previously at the beginning of a user's session the page would not scroll as the element was not yet in existence. Have moved the logic to the `useCombinedView` hook to listen for changes in the pathname.
> Content Scroll - Bug Fix

- app/editor/src/components/form/toning/ToningGroup.tsx
- app/editor/src/features/content/form/ContentForm.tsx
- app/editor/src/features/content/form/constants/defaultFormValues.ts
- app/editor/src/features/content/form/interfaces/IContentForm.ts
- app/editor/src/features/content/form/utils/toForm.ts
- app/editor/src/features/content/validation/ContentFormSchema.ts
Cleaned up toning validation, we had some unnecessary placeholder fields for tone. Now the component will directly change `toningPools` instead of going through various variables.  
Also added some print content validation, as well as the conditional validation of `otherSource/source` as it was a quick add.
> TNO-1122: Validation

- Makefile
- api/net/Areas/Editor/Controllers/ContentController.cs
- api/net/Areas/Editor/Controllers/LookupController.cs
- api/net/Areas/Kafka/Controllers/ProducerController.cs
- api/net/Areas/Services/Controllers/ConnectionController.cs
- api/net/Areas/Services/Controllers/ContentController.cs
- api/net/Areas/Services/Controllers/ContentReferenceController.cs
- api/net/Areas/Services/Controllers/DataLocationController.cs
- api/net/Areas/Services/Controllers/IngestController.cs
- api/net/Areas/Services/Controllers/SourceController.cs
- api/net/Areas/Services/Controllers/WorkOrderController.cs
- auth/keycloak/config/realm-export.json
- services/net/filemonitor/FilemonitorAction.cs
- tools/scripts/refresh-keycloak.sh
Keycloak Gold realm CSS tool now support roles for service accounts.
This allows us to secure our endpoints so that both service accounts and users follow the same permission processes.
You will need to run `make renew` to update Keycloak with the appropriate service account roles.
Won't know if it all works until it's deployed to DEV.  Locally it appears to work correctly.
> TNO-804 Add service account authorization

- app/editor/src/components/form/tags/DraggableTagList.tsx
- app/editor/src/features/content/form/MediaSummary.tsx
Fixed the warning by following [this](https://github.com/react-grid-layout/react-draggable/blob/v4.4.2/lib/DraggableCore.js#L159-L171).
"If running in React Strict mode, ReactDOM.findDOMNode() is deprecated. Unfortunately, in order for <Draggable> to work properly, we need raw access to the underlying DOM node. If you want to avoid the warning, pass a `nodeRef`..."
> Fix console warning for draggable component

- app/editor/src/features/content/list-view/ContentListView.tsx
- app/editor/src/features/content/morning-report/AdvancedMorningReport.tsx
- app/editor/src/features/content/tool-bar/ContentToolBar.tsx
- app/editor/src/features/content/tool-bar/sections/filter/FilterContentSection.tsx
Content List filter was getting reset when navigating to different pages.  It will now maintain state.
Note that there is a new issue introduced with the latest Morning Report page filter changes.  Specifically with the Advanced Search, the source value is displayed even though this shared component no longer should display it.
> TNO-1140 Fix content filter state

- app/editor/src/features/content/tool-bar/sections/filter/AdvancedSearchSection.tsx
Previously there was a bug that would occur when the user hits the "search" button in the Advanced Search Section of the toolbar.  The filter state used in the advanced search section would be out of sync with the Redux store causing it to revert the toggle group's state.
> TNO-1186: Hitting search wipes toggle group state

- app/editor/src/features/content/tool-bar/sections/filter/InputOption.tsx
- app/editor/src/features/content/tool-bar/sections/filter/styled/SelectLabel.tsx
- app/editor/src/features/content/tool-bar/sections/filter/styled/index.ts
- can now click anywhere in row to toggle the checkbox state
- when removing tags the checkbox will now correctly uncheck
- row highlights when item is selected for easier identification (can remove if we want)
> Product filter bugs

- app/editor/src/features/content/list-view/constants/fieldTypes.ts
- app/editor/src/features/content/morning-reports/components/AdvancedFilter.tsx
- app/editor/src/features/content/tool-bar/sections/filter/AdvancedSearchSection.tsx
This fixes a bug I introduced in the advanced search when selecting a source.
> Fix advanced source filter

- app/editor/src/features/content/tool-bar/sections/filter/FilterContentSection.tsx
Removes the `Any` product as it no longer works.  The product filter is an OR statement, so we would need to update the elasticsearch query to handle this if it's required.
> Fix product filter

- app/editor/src/features/admin/topic-score-rules/validation/TopicScoreRuleSchema.ts
- app/editor/src/features/content/form/utils/calcTopicScore.ts
- app/editor/src/store/slices/content/contentSlice.ts
- libs/net/dal/Configuration/TopicScoreRuleConfiguration.cs
- libs/net/dal/Migrations/20230403180045_1.0.10.Designer.cs
- libs/net/dal/Migrations/20230403180045_1.0.10.cs
- libs/net/entities/TopicScoreRule.cs
- libs/net/models/Areas/Admin/TopicScoreRule/TopicScoreRuleModel.cs
- libs/net/models/Areas/Editor/Models/TopicScoreRule/TopicScoreRuleModel.cs
Fixing topic score rules admin page validation.  Also defaulting advanced filter to source.
Add DB migration 1.0.10.
> Fix topic score rules

- app/editor/src/features/content/form/components/wysiwyg/styled/Wysiwyg.tsx
TNO-1075: WYSIWYG expand button doesn't work
> Fix TNO-1075 (a minor css update)

- app/editor/src/features/content/form/components/topic/Topic.tsx
TNO-1190: cannot search in topic drop down
> Fix TNO-1190

- services/net/filemonitor/FilemonitorAction.cs
TNO-1198: Paper Ingest keeps failing for Blacks Newsgroup
> Fix TNO-1198

- app/subscriber/src/components/sidebar/styled/CustomSidebar.tsx
Unfortunately, we have to override the ugly way to get the hover colour working.
> Hover color

- app/editor/src/features/content/form/ContentActions.tsx
Weekdays the commentary expiry value will default to 3 hours and weekends will be 5 hours.
> I still need to integrate with Canada's free API for holidays so that it will default to 5 hours on holidays.
> TNO-1221 Add Commentary Default Expiry Value

- api/net/Areas/Admin/Controllers/WorkOrderController.cs
- app/editor/src/features/admin/topics/styled/TopicList.tsx
- app/editor/src/features/admin/work-orders/WorkOrderForm.tsx
- app/editor/src/features/admin/work-orders/WorkOrderList.tsx
- app/editor/src/features/admin/work-orders/constants/columns.tsx
- app/editor/src/features/admin/work-orders/constants/defaultWorkOrder.ts
- libs/net/dal/Services/TopicService.cs
Work orders admin page now uses the new FlexTable component and correctly pages.
Fix topic admin table to sort proactive topics first.
> TNO-1078 Replace work order table

- app/editor/src/features/admin/work-orders/WorkOrderForm.tsx
- app/editor/src/features/admin/work-orders/WorkOrderList.tsx
- app/editor/src/features/admin/work-orders/constants/columns.tsx
- app/editor/src/features/admin/work-orders/styled/WorkOrderList.tsx
- app/editor/src/features/content/form/utils/getDefaultCommentaryExpiryValue.ts
- libs/net/dal/Services/WorkOrderService.cs
- libs/net/entities/WorkOrder.cs
All future work orders for transcripts or NLP will include the headline so that it can be displayed without making an additional query.
You can now click on the headline and it will load the content.
> Existing work orders will not have the value regrettably.
> TNO-1077 Add headline to work order

- app/editor/src/features/admin/work-orders/styled/WorkOrderList.tsx
Updated style so that the column would not overflow.
> Fix workorder table column

- app/editor/src/features/home/InfoText.tsx
- app/editor/src/features/home/styled/InfoPanel.tsx
Added scroll box for alert message on the editor side, everything behaves as expected on subscriber side (enough room for large messages)
> Fix alert message

- app/editor/src/features/content/form/components/wysiwyg/Wysiwyg.tsx
- libs/net/core/Extensions/StringExtensions.cs
TNO-1270: [QA] Create rule so B.C. and other acronyms do not display with a paragraph break
> Fix TNO-1270

- services/net/content/ContentManager.cs
Temporary fix to get the Content Service running again.  This is to resolve the issue with bad data being sent to Kafka from the Syndication Service.
> Fix Content Service

- api/net/Areas/Admin/Controllers/NotificationController.cs
- api/net/Areas/Admin/Controllers/ReportController.cs
- services/net/content/ContentManager.cs
The Razor engine is setup to cache the templates after they are compiled and rendered for the first time.  Without caching it would be slow to recompile each time it ran.  To overwrite cache I've added a flag to control this behaviour.
> TNO-474 Update report cache

- services/net/notification/NotificationManager.cs
- services/net/reporting/ReportingManager.cs
- services/net/reporting/ReportingService.cs
Now when we update a report/notification template it will generate a new cached parsing template.
> Please note that this design has a memory leak due to RazorLight being poorly designed.  I've created a story to resolve this issue.  I have also reviewed Fluid templating engine.  However that engine doesn't support grouping (I couldn't figure out how to get it to work).
> TNO-474 Fix Report/Notification Template

- app/editor/src/features/content/form/ContentForm.tsx
- app/editor/src/features/content/form/ContentStoryForm.tsx
- app/editor/src/features/content/form/components/time-log/TimeLogSection.tsx
- app/editor/src/features/content/form/components/upload/styled/Upload.tsx
- app/editor/src/features/content/form/styled/ContentForm.tsx
- app/editor/src/features/content/form/styled/MediaSummary.tsx
- app/editor/src/features/content/hooks/index.ts
- app/editor/src/features/content/hooks/useTab.tsx
- app/editor/src/features/content/index.ts
- app/editor/src/features/content/list-view/ContentListView.tsx
- app/editor/src/features/content/list-view/components/tool-bar/filter/CreateNewSection.tsx
- app/editor/src/features/content/list-view/constants/columns.tsx
The Content List View will now default to opening another tab to load content.  We can come up with a way to make this responsive or based on user preferences later.
- Content Form navigation buttons update the active row on the Content List View
- Creating a new content item will open the form in the other tab
- Modified the layout of the Content Form a little to squeeze the bottom up a little.  Still needs work though.
> TNO-1299 Publish will reset form

- app/subscriber/src/features/commentary/utils/DetermineContentIcon.tsx
Simple change to have a more universal symbol for A/V content as there is presently no trivial way to differentiate the two.
(have confirmed with Bobbi that this one is ok)
- These changes will be reflected in the commentary box of the subscriber site
> TNO-1295: New icon for A/V content

- app/editor/src/features/content/validation/ContentFormSchema.ts
TNO-1302: Summary is not a required field when content is tagged as News Radio or Events product
> TNO-1302 updates

- app/subscriber/src/features/login/styled/UnauthenticatedHome.tsx
Scrolling now works as expected for mobile users on the login screen.
<hr />
> TNO-1297: Can now scroll unauthenticated home on mobile

- app/subscriber/src/features/content/view-content/ViewContent.tsx
- app/subscriber/src/features/content/view-content/utils/formatTime.ts
- app/subscriber/src/features/content/view-content/utils/index.ts
Time while viewing content will now display in a 2 digit format as requested.
> TNO-1286: Format time w/ 2 digits

- app/subscriber/src/features/content/view-content/ViewContent.tsx
Previous logic no longer accurate as CP News contains a body and not a summary. New logic will check if summary or body contains data rather than determining off content type.
> TNO-1317: CP News content not appearing

- libs/net/dal/Services/ContentService.cs
The bug was caused from the front-end which is fixed now, and the original implementation of the elastic query was correct.
> Tweak for my-minister

- app/subscriber/src/features/content/view-content/ViewContent.tsx
- app/subscriber/src/features/my-minister/MyMinister.tsx
- app/subscriber/src/features/router/AppRouter.tsx
This PR includes functionality that bolds the user's selected minister in the body or summary of a piece of content. See GIF below for reference (**hard to see from thumbnail - click image for clearer view**).
- only functions when user views content from their my minster list
- currently set up just for one minister at a time
> TNO-1380: Bold minister's name on returned content

- app/subscriber/src/features/content/view-content/ViewContent.tsx
Only return summary if there is no body present. Body contains the full content the user is looking for when present.
> TNO-1380: Bold minister's name on returned content - Adjustment

- app/subscriber/src/features/content/view-content/ViewContent.tsx
Summary would somehow override body with previous logic (in certain scenarios), using ternary instead of the Show component now.
Unable to recreate locally so hopefully this will work as it is on my local machine.
> [Bug] Content summary displaying instead of body: Updating logic

- app/subscriber/src/features/content/view-content/ViewContent.tsx
Let me know if this looks ok, having issues with the previous logic in DEV. Using the same logic now as we do on the editor. 
- if the content is of type snippet or image -> display summary
- if the content is of type story or print content -> display body
> [Bug] Change of logic for displaying body or summary

- app/subscriber/src/features/content/view-content/ViewContent.tsx
🤦 This explains why it was working locally for body - added summary and body to a piece of content and found out why it was being overwritten.
> [Bug] Summary overwriting body

- app/editor/src/features/content/form/components/tags/Tags.tsx
- app/editor/src/features/content/form/components/time-log/styled/TimeLogSection.tsx
- app/editor/src/features/content/form/styled/TimeLogTable.tsx
Tags select opens from the top instead of the bottom.  Also fixed layout of time log.
Time Log Modal
> TNO-1406 Editor Fixes

- app/subscriber/src/features/home/constants/columns.tsx
Simple fix to reduce the width of the tone column to free up some space, additionally reducing width of headline column to help with the responsiveness when collapsing.
> TNO-1379: Reduce width of tone column

- libs/net/dal/Services/ContentService.cs
For some reason, this is 10 on my local; however, showing a `productId `of 11 on DEV.
> Frontpage bug

- app/subscriber/src/features/content/view-content/ViewContent.tsx
PR to ensure button is disabled when work order has previously been completed.
> Subscriber View Content: Ensure work orders fetched on load

- app/subscriber/src/features/content/view-content/ViewContent.tsx
Simple fix to add page number on the content view page.
> TNO-1411: Add page number to content view

- app/editor/src/features/content/papers/Papers.tsx
- app/editor/src/features/content/papers/components/ReportActions.tsx
Made it easier to remove content from the selected/published list on the Papers page.
- If a filter is applied (top stories, commentary, or homepage) it will display buttons to remove content from those
- A 'Publish All' button is displayed when one of the filters is applied so that all items on the page will be published
> TNO-1394 Enhance Editor Papers

- app/subscriber/src/features/content/view-content/ViewContent.tsx
- app/subscriber/src/features/my-minister/MyMinister.tsx
- app/subscriber/src/features/settings/MyMinisterSettings.tsx
In this PR:
- another console warning bug fix
- multiple ministers can now be selected
- when none are selected it will now return no content rather than all
- bold all ministers that are selected as they appear when viewing content
Little bit tricky with highlighting multiple ministers, let me know if anything needs clarification. Have it working as seen below:
> TNO-1378: Multiple ministers can now be selected

- app/subscriber/src/features/home/Home.tsx
- app/subscriber/src/features/home/utils/makeFilter.ts
- libs/net/dal/Services/ContentService.cs
In this PR:
- papers on the home page will now display based off the papers defined sort order 
- these can be updated at any time through the editor -> admin -> sources -> sort order
> TNO-1288: Adjust order of display of papers

- openshift/kustomize/cron/base/cron-job.yaml
- openshift/kustomize/postgres/crunchy/base/deploy.yaml
1) Feat(Crunchy PG backup jobs deletion): Added jobs: ttlSecondsAfterFinished will be applied to both full & incremental backups schedules and will delete jobs after success or failed state after 100 seconds. This will free up occupied resource capacity.
2) feat(cron job deletion): Delete as above.
> Jobs automatic deletion

- app/subscriber/src/features/search-page/SearchPage.tsx
In this PR:
- the search page will now bold the words searched
- works for single or multi-word searches
- headline, and summary/body will both bold found instances of keywords
See example below for the query text of `just eby`
> TNO-1434: Bold results on search page

- app/subscriber/src/features/content/view-content/ViewContent.tsx
- app/subscriber/src/features/content/view-content/styled/ViewContent.tsx
Include source name on content with the content type of Internet, other types already include this.
> TNO-1439: Include source on internet types

- app/subscriber/src/features/content/view-content/ViewContent.tsx
Added `More...` link to content when a source url is present. Clicking said link will open a new tab redirecting the user to the source url to "read more".
> TNO-1448: Link to source url when present

- app/subscriber/src/features/search-page/SearchPage.tsx
This fixes the following current issue in dev: 
When there are multiple matched instances of a queried word, it will repeat itself. This PR will only bold and replace it with the proper word/capitalization.
Got a tiny bit tricky to maintain the capitalization of each word, could not simply replace it with a bolded version of the query text as that would result in things like `Eby` being replaced with `<b>eby</b>` (lowecase)
> Search page bug

- libs/net/kafka/Models/ContentBase.cs
- libs/net/kafka/Models/SourceContent.cs
- libs/net/services/Actions/IngestAction.cs
- libs/net/services/Managers/IngestManager`.cs
- openshift/kustomize/api/base/deploy.yaml
- openshift/kustomize/api/base/statefulset.yaml
- services/net/image/ImageAction.cs
- services/net/syndication/SyndicationAction.cs
- services/net/syndication/Xml/Rss/RssItem.cs
There were a number of regression issues introduced with the latest changes to support the Content Migration Service.  This should resolve the identified issues.
- Front page images should now be imported
- Front page images should not result in mass duplication
- Front page image files should now be imported
- Syndication feeds that require a separate request for content should now work again (CPNews)
- All Ingest Services should always fetch the ingest configurations even when they go error out
> Fix Image/Syndication/Content Services

- services/net/syndication/SyndicationAction.cs
when translating the Categories to Labels, swapped the Name and Label so that the 'Key' and 'Value' are set correctly for Syndication sources
> fix: #tno-1538 - switch Label and Name

- app/editor/src/features/admin/ingests/configurations/DbMigration.tsx
- services/net/contentmigration/ContentMigrationAction.cs
- we can now add a delay on how "up to date" a migration can be kept
- use as a buffer between updates in TNO and migrations into MMIA
> feat: #1562 - add configurable delay for migration

- services/net/contentmigration/migrators/ContentMigrator.cs
- after discussion with stakeholder (Scott) we can ignore the alert attribute
- it's enough that an Editor can trigger a new alert manually if they choose
> feat: #tno-1489 - no re-alerting on migration

- app/subscriber/src/features/commentary/styled/Commentary.tsx
- app/subscriber/src/features/front-pages/styled/FrontPages.tsx
- app/subscriber/src/features/landing/styled/Landing.tsx
- cleaned up column layout
- tightnened up spacing to be more consistent around edges of main and right
- .right-panel has max-width in % rather than absolute
- .right-panel uses the real estate that main-panel leaves
- fixed bottom margin on main-panel instead of on the button
- front-pages should not fit content, should be 100% of its parent
> feat: #tno-1533 - change layout of subscriber page

- api/net/Areas/Services/Controllers/ContentController.cs
- libs/net/dal/Services/ContentService.cs
- libs/net/dal/Services/Interfaces/IContentService.cs
- libs/net/services/Helpers/ApiService.cs
- libs/net/services/Interfaces/IApiService.cs
- services/net/indexing/IndexingManager.cs
Update the API endpoint and Content Service to only update the `Content.Status` to eliminate data corruption or concurrency issues.
> fix: #tno-1524 - only update content status

- libs/net/core/Extensions/JsonElementExtensions.cs
I introduced a regression issue when I updated the extension methods for JsonDocument and JsonElement.  It would be wonderful if we could find time to add unit-tests for these things.
This bug was causing all elastic migrations to fail.
> Fix JsonDocument extension method and elastic migration tool

- app/subscriber/src/App.tsx
- app/subscriber/src/components/sidebar/advanced-search/AdvancedSearch.tsx
- app/subscriber/src/components/sidebar/advanced-search/constants/DefaultAdvancedSearch.ts
- app/subscriber/src/components/sidebar/advanced-search/constants/ToggleOptions.ts
- app/subscriber/src/components/sidebar/advanced-search/constants/index.ts
- app/subscriber/src/components/sidebar/advanced-search/styled/AdvancedSearch.tsx
- app/subscriber/src/components/sidebar/advanced-search/utils/queryToState.ts
Simple PR to add a reset button to the advanced search on the subscriber site
> Add reset button to advanced search

- app/editor/src/features/admin/ingests/configurations/FrontPage.tsx
- libs/net/dal/Migrations/Initial/Up/PostUp/02-Ingest.sql
- services/net/image/ImageAction.cs
With the latest changes to support Globe & Mail frontpage images, it broke the other newspaper front page images.  This update will fix this.
Requires manually updating the front page image ingest configuration values.
> TNO-1177 Fix Image Service

- services/net/contentmigration/migrators/PaperMigrator.cs
TNO has pre-replace all paragraph markers with a pipe '|' character.  This fix, undoes this on the way into MMIA
> fix: #tno-1662 - replace pipe with p tags

- app/editor/src/features/content/form/components/upload/Upload.tsx
Browsers have a client side feature that allows us to control the default keyframe loaded in a video file.  It appears that in the case of the default MOV file created by editors they are perhaps incorrectly creating the first frame, or they are not including a default image.  With controlling the keyframe it is essentially moving the head forward a little with the hope that an image can be displayed.  I have tested the example MOV file in Chrome and it works.
> TNO-1408 Fix MOV keyframe

- app/editor/src/features/admin/av-overviews/OverviewGrid.tsx
- app/editor/src/features/admin/av-overviews/styled/OverviewGrid.tsx
- app/editor/src/features/reports/av-overview/OverviewGrid.tsx
- app/editor/src/features/reports/av-overview/styled/OverviewGrid.tsx
Simple PR to add Grip Lines to each AV Overview item to make the drag and drop more intuitive.
- Included in the admin and editor areas of the application
> TNO-1622: Add grip bars to av overview

- api/net/Areas/Editor/Controllers/AVOverviewController.cs
- api/net/Areas/Editor/Controllers/ContentController.cs
- api/net/Areas/Editor/Controllers/IngestController.cs
- api/net/Areas/Editor/Controllers/ReportController.cs
- api/net/Areas/Editor/Controllers/StorageController.cs
- api/net/Areas/Editor/Controllers/SystemMessageController.cs
- api/net/Areas/Editor/Controllers/UserController.cs
- api/net/Areas/Editor/Controllers/WorkOrderController.cs
- api/net/Middleware/ErrorHandlingMiddleware.cs
- app/editor/src/features/admin/filters/utils/generateTermsForArrayField.ts
- app/editor/src/store/hooks/useAjaxWrapper.ts
- app/subscriber/src/store/hooks/useAjaxWrapper.ts
- libs/net/core/Exceptions/NoContentException.cs
- libs/net/dal/Services/ActionService.cs
- libs/net/dal/Services/ContentReferenceService.cs
- libs/net/dal/Services/ContentService.cs
- libs/net/dal/Services/IngestService.cs
- libs/net/dal/Services/NotificationService.cs
- libs/net/dal/Services/ReportService.cs
- libs/net/dal/Services/ReportTemplateService.cs
- libs/net/dal/Services/SourceService.cs
- libs/net/dal/Services/UserService.cs
Updated most of the `NotImplemtedException` uses that were related to not finding content to a new exception `NoContentException`.  This allows us to manage which error messages are returned to the UI.
Update Editor and Subscriber app to handle different types of error message responses.
Also fixed a bug related to report filters.
> TNO-1681 Friendly error messages

- libs/net/elastic/ITNOElasticClient.cs
- libs/net/elastic/TNOElasticClient.cs
TNO-1618: All Elasticsearch queries should be sorted by date
> TNO-1618 updates

- app/subscriber/public/constants.json
- app/subscriber/src/components/sidebar/advanced-search/AdvancedSearch.tsx
- app/subscriber/src/components/sidebar/advanced-search/components/MoreOptions.tsx
- app/subscriber/src/components/sidebar/advanced-search/constants/DefaultAdvancedSearch.ts
- app/subscriber/src/components/sidebar/advanced-search/constants/constants.json
- app/subscriber/src/components/sidebar/advanced-search/interfaces/IAdvancedSearchFilter.ts
- app/subscriber/src/components/sidebar/advanced-search/utils/queryToState.ts
- app/subscriber/src/features/content/list-view/interfaces/IContentListFilter.ts
- app/subscriber/src/features/home/utils/makeFilter.ts
- app/subscriber/src/features/search-page/SearchPage.tsx
This ticket ended up expanding a bit more as I have been running into issues, I have it down to 1 now.
My current issue as you will see in the GIF below is that when searching for content with files attached I get an "all shards failed" message. 
Interestingly enough this only started to happen once I had content with a file attached, before it was correctly returning no items without an error (previously when no content with a file existed).
This PR includes the functionality for filtering by
- top story
- front page
- if a file includes an image
- disable/enable bolding
> TNO-1705: Advanced search bugs

- app/editor/public/links.json
- app/editor/src/features/content/form/components/tool-bar/ContentFormToolBar.tsx
- app/editor/src/features/content/form/components/tool-bar/form/PublishedSection.tsx
- app/editor/src/features/content/form/components/tool-bar/form/index.ts
- app/editor/src/features/content/form/components/tool-bar/form/styled/PublishedSection.tsx
- app/editor/src/features/content/form/components/tool-bar/form/styled/index.ts
In this PR:
- allow editors to view published content on the subscriber site
- only shows if content is published
- link changes depending on environment
I am curious what is the best way to store these external subscriber links and if a JSON is the best approach.
> TNO-1707: Link to subscriber

- api/net/Areas/Editor/Controllers/ReportController.cs
- api/net/Areas/Editor/Controllers/ReportInstanceController.cs
- api/net/Areas/Subscriber/Controllers/ReportController.cs
- app/editor/src/features/admin/reports/ReportForm.tsx
- openshift/kustomize/services/capture/base/kustomization.yaml
- openshift/kustomize/services/clip/base/kustomization.yaml
- openshift/kustomize/tekton/base/pipelines/buildah-all.yaml
- openshift/kustomize/tekton/base/triggers/dev/binding.yaml
- openshift/kustomize/tekton/base/triggers/template.yaml
- openshift/kustomize/tekton/base/triggers/test/binding.yaml
- services/net/scheduler/SchedulerManager.cs
A user who is subscribed to a report can now preview it even though the report is private and the user does not own the report.  This provides a way for users to share their private reports with other users.
By default a report scheduled event will be assigned to the owner of the report.  This will make that user the owner of the instance when the report is run in the Reporting Service.
Fixed DevOps issues to be able to deploy Capture and Clip Service to the TEST environment.
> TNO-1723 Enable report preview

- app/editor/src/features/content/form/components/tool-bar/ContentFormToolBar.tsx
This should solve the bug Carolynn found with the link disappearing. 
But also I have a question, should we not bother showing the link for `Publish` and only show for `Published`? It seems to work as expected for `Publish` (until the status is changed of course).
> Fix bug for published link

- app/editor/src/features/reports/av-overview/OverviewGrid.tsx
Was some rollback in a rebase at some point making the date only filter based on the current time which would result in no clips showing up.
Previously it had only filtered based on today's date; however, now it will also check the start time of the section and search the published time based off of that.
If for some reason the start time is not present it will look at all clips from that series from today's date.
> AV Overview - Date filter bugs

- app/editor/src/features/content/list-view/constants/columns.tsx
- app/editor/src/features/content/papers/constants/columns.tsx
Performance is current abysmal with react-tooltip, looking at reimplementing and making sure we are up to par with their most recent documentation. In the meantime since it is taking a little bit, I have removed the tooltips from the list view (maybe can reintroduce later if need be and performance is fixed). 
This bit of work will be two parts.
> Remove tooltip from list view

- app/subscriber/src/components/folder-sub-menu/FolderSubMenu.tsx
- app/subscriber/src/components/folder-sub-menu/index.ts
- app/subscriber/src/components/folder-sub-menu/styled/FolderSubMenu.tsx
- app/subscriber/src/components/folder-sub-menu/styled/index.ts
- app/subscriber/src/features/content/view-content/ViewContentToolbar.tsx
- app/subscriber/src/features/home/Home.tsx
- app/subscriber/src/features/home/styled/Home.tsx
- app/subscriber/src/features/my-minister/MyMinister.tsx
- app/subscriber/src/features/todays-commentary/TodaysCommentary.tsx
- app/subscriber/src/features/top-stories/TopStories.tsx
- app/subscriber/src/features/top-stories/styled/TopStories.tsx
In this PR:
- made a reusable component as the button that renders the folder submenu and functionality is used in a couple of places
- simplified code
- added functionality to add selected content to folder to todays commentary, top stories, and my ministers
- behave the same as #1069
> TNO-1744, 1745, 1746: Add content to folder from Today's Commentary, Top Stories, and My Ministers 

- app/subscriber/src/features/content/view-content/FolderMenu.tsx
Realized I had not disabled the button when no content is selected; however, this is a unique case as it is using a tooltip (for the popout menu) that is given a `clickable` prop handled through the library. Essentially saying show on click instead of hover. 
Trying to come up with a clean way of disabling. But adding this in the meantime to advise users no content is selected
> Toast error when no content selected

- app/editor/src/features/admin/reports/ReportFormDetails.tsx
- app/subscriber/src/features/my-reports/admin/ReportAdminSettings.tsx
- app/subscriber/src/features/my-reports/hooks/useColumns.tsx
- app/subscriber/src/features/my-reports/styled/MyReports.tsx
Using an icon to indicate if the report contains media analytics (charts).  It's a basic check if the report has a section where the settings has `showCharts=true`.  This can be a false positive, but for now I think it'll be okay.
> TNO-1724 Update My Reports

- app/editor/src/features/content/form/ContentForm.tsx
- app/editor/src/features/content/form/ContentStoryForm.tsx
- app/editor/src/features/content/form/MediaSummary.tsx
- app/editor/src/features/content/form/components/time-log/TimeLogSection.tsx
- app/editor/src/features/content/form/styled/ContentForm.tsx
- libs/npm/core/src/components/form/area/Area.tsx
When creating new content with a new file the form will now default to staying on the same form after publishing.  There is a checkbox that can be used to override this behavior "Create new after publish".
- Click 'Enter' in the prep time input to auto add to total minutes
- If content has a new file it will default the "Create new after publish" checkbox to `false`, otherwise it will default to `true`.
> TNO-1788 Change Publish Flow

- services/net/transcription/appsettings.json
Added `m4a` format to auto convert to `mp3` before sending to Azure Cognitive Services.
> TNO-1785 Fix m4a transcription

- app/editor/src/features/admin/reports/ReportFormSections.tsx
- app/editor/src/features/admin/reports/styled/ReportSections.tsx
- added some more details to the sections grid header
- tweaked css
> feat: #tno-1837 - updated reports sections display

- libs/net/core/Http/OpenIdConnectRequestClient.cs
- services/net/syndication/SyndicationAction.cs
Ingest service error alerts highlighted two issues.
- Attempting to add a second authorization header
- Processing DTD in XML
> TNO-1823 Fix ingest services

- api/net/Areas/Subscriber/Controllers/ContributorController.cs
- libs/net/dal/Models/ContentFileReference.cs
- services/net/capture/CaptureAction.cs
- services/net/transcription/TranscriptionManager.cs
Currently files are uploaded to a directly that named by the `Source.Code`.  If the code has a space it causes issues.  Code has been updated to replace a space with an underscore.
> TNO-1739 Fix file paths

- app/subscriber/src/features/content/view-content/ViewContent.tsx
Suppress transcript warning messages on subscriber app.
Other status errors were hardcoded to ensure that the app would "eat" the warning messages.
> TNO-1794 Suppress transcript warning messages

- app/editor/src/features/reports/av-overview/OverviewGrid.tsx
Not sure exactly what time it did this; however, the timezone was wrong so it would jump forward a day on the content filter resulting in no options when doing the evening report. If you tested it before 5ish it would work but not otherwise.
> TNO-1835: Fix evening overview clip options

- app/editor/src/features/content/form/components/tool-bar/form/StatusSection.tsx
Added Id on editor's content form (when there is an ID).
Screenshot bellow:
> TNO-1838 Display id on content form

- app/subscriber/src/components/sidebar/styled/CustomSidebar.tsx
Since our menu has been growing vertically it was causing some funky behaviour with scroll bars. The sidebar height is now more dynamic depending on the users device.
> Subscriber site double scrollbar fix

- app/editor/src/features/admin/filters/FilterForm.tsx
- app/editor/src/features/admin/filters/FilterFormImportExport.tsx
- app/editor/src/features/admin/filters/FilterFormQuery.tsx
- app/subscriber/src/features/content/list-view/interfaces/IContentListFilter.ts
- app/subscriber/src/features/my-searches/FilterFormDetails.tsx
- app/subscriber/src/features/search-page/SearchPage.tsx
- app/subscriber/src/features/search-page/utils/filterFormat.ts
- openshift/kustomize/tekton/base/tasks/deploy-all.yaml
The dates saved by the Subscriber app searches were invalid when they were empty strings.  This "used" to work because we were using the `any` type and ignoring bad data.  Now we have strong types to reduce this type of issue.
I've also fixed the DatePicker component implementation for the Filter forms.  We can now clear the value and it properly formats.
> TNO-1531 Fix invalid fitler date settings

- app/editor/src/features/content/form/ContentStoryForm.tsx
Problem source:
When the mask was not fully filled (still had the _) the validation would fail and the state was not set. So when there was a change anywhere else, the state would go back to the previous state.
Solution:
When leaving the field (onBlur) I checked for _ characters and replaced with zeros, so it would be ok to convert 12:00:__ to 12:00:00 or even 12:__:__ to 12:00:00, and then set the state with a valid field.
> TNO-1839 Mask and state fix

- app/subscriber/src/features/search-page/utils/filterFormat.ts
The startDate empty string will no longer be passed through when saving a search.
> TNO-1889: Invalid start date on save (when left blank)

- app/editor/src/features/content/form/components/tool-bar/form/ActionSection.tsx
- app/subscriber/src/features/home/Home.tsx
- app/subscriber/src/features/home/constants/HomeFilterType.ts
- app/subscriber/src/features/home/home-filters/HomeFilters.tsx
Cleanup the component, and fix state errors so the filter is persisted when navigating back to the list view.
Added ALL toggle:
> TNO-1848: State bug with home filters

- app/subscriber/src/features/press-gallery/PressGallery.tsx
- app/subscriber/src/features/press-gallery/interfaces/IDateOptions.tsx
- app/subscriber/src/features/press-gallery/interfaces/IPressMember.tsx
- app/subscriber/src/features/press-gallery/interfaces/index.ts
- app/subscriber/src/features/press-gallery/styled/PressGallery.tsx
- app/subscriber/src/features/press-gallery/utils/generateDates.ts
- app/subscriber/src/features/press-gallery/utils/index.ts
Based off of Scott's comments - I need to look at this again in a little bit with fresh eyes
- user can filter by either press member OR date 
- user can see preview of how many pieces of content are associated with query by looking at the numeric value following the label
- one input will automatically clear when selecting the other 
I will be posting the comment below for clarity, I think that this may need to be broken up into more tickets as it is rather complex.
**Criteria:**
```
Please add a toggle option so clients can sort by Date or Member.
If sorted by Member all Press Gallery reporters should be listed in alphabetic order by their first name, followed by a number indicating the number or returned items for the last two weeks.
Keith Baldrey (8)
Mike Smyth (9)
Vaughn Palmer (10) …
```
> TNO-1866: Change search filters for Press Gallery 

- app/editor/src/features/content/form/components/upload/Upload.tsx
- services/net/ffmpeg/FFmpegManager.cs
- services/net/ffmpeg/TNO.Services.FFmpeg.csproj
Updated the FFmpeg Service to also update the `ContentType` mime information.
The hope is this will fix the Safari browser issue.
> TNO-1873 Fix FFmpeg Service

- libs/net/models/Areas/Services/Models/ContentReference/ContentReferenceModel.cs
- services/net/contentmigration/migrators/ContentMigrator.cs
add an extra piece of metadata to content that came in via the content migration service
> feat: #tno-1932 - add metadata for migrated content

- app/subscriber/src/components/date-filter/DateFilter.tsx
- app/subscriber/src/features/home/Home.tsx
- app/subscriber/src/features/home/constants/HomeFilterType.ts
- app/subscriber/src/features/home/home-filters/HomeFilters.tsx
In this PR:
- persist date so when the user views a piece of content and navigates back, the date filter is on the appropriate date
- add events filter to the home screen to show contents tagged with the events product id
- rework home page to use elastic queries like the rest of the application
> [Now Review Ready ✅] TNO-1904: Add events filter

- app/editor/src/features/content/papers/constants/defaultPaperFilter.ts
The Papers page will no longer include the front page images.
> TNO-1943 Update Papers filter

- api/net/Areas/Subscriber/Controllers/ReportInstanceController.cs
- libs/net/kafka/KafkaListener`.cs
Introduced a regression issue on the subscriber site when I changed the route for view a report instance from `preview` to `view`.
> Fix view report instance

- app/editor/src/features/content/form/ContentForm.tsx
Due the refactor the hour field needed to be set individually, and the SetForm method was deleting all the content.
The set method was transferred to the form props scope, and the setHours function, was changed to be an auxiliary function (getHours) to format/validate the hour input.
> TNO-1840 Change the scope to hour validation

- services/net/filemonitor/FilemonitorAction.cs
When Blacks Press sends us corrupted XML files the File Monitor Service fails to be able to ingest all the stories in the file.  This update should fix the most common issue that occurs.
> TNO-1965 Fix Blacks Ingest

- app/editor/src/features/admin/ingests/configurations/Newspaper.tsx
- services/net/filemonitor/FilemonitorAction.cs
- services/net/filemonitor/models/Fields.cs
Fixing issue introduced when fixing the Blacks Newsgroup XML.  Resulted in breaking Globe & Mail XML.
Will now use a configuration option to turn it on or off.
> TNO-1965 Fix File Monitor Service

- app/subscriber/src/components/sidebar/advanced-search/AdvancedSearch.tsx
- app/subscriber/src/components/sidebar/advanced-search/styled/AdvancedSearch.tsx
Small PR - needed to take a break from the rewiring of redux and rewiring everything to only use `IFilterContentSettings`.
Not removing Tags component incase needed back. Also removed the max height of the select dropdowns.
> TNO-2081: Remove search tags and height of selects

- app/subscriber/src/features/my-searches/utils/settingsToFilter.ts
- app/subscriber/src/features/search-page/SearchPage.tsx
- app/subscriber/src/features/search-page/styled/SearchPage.tsx
- Pin currently viewed filter to top so it is still visible while scrolling
- Make sure container doesn't overflow
> Style Enhancements 

- app/editor/src/features/admin/products/ProductDetailsForm.tsx
- app/editor/src/features/admin/products/ProductSubscribersForm.tsx
- app/subscriber/src/components/section/Section.tsx
- app/subscriber/src/components/section/styled/Section.tsx
- removed pointer cursor from section when not clickable
- added report owner name to list of products in drop down to assist user when trying to find a report owned by a specific user
> feat: #tno-1937 - small fix for usability

- app/subscriber/src/components/table/styled/SubscriberTableContainer.tsx
- app/subscriber/src/features/my-folders/MyFolders.tsx
- app/subscriber/src/features/my-folders/constants/columns.tsx
- app/subscriber/src/features/my-folders/styled/MyFolders.tsx
- app/subscriber/src/features/utils/handleEnterPressed.ts
- app/subscriber/src/features/utils/index.ts
In this PR:
- strip repetitive css and use existing component made
- fix bug where you cannot rename folder
- apply common table theme to my folders
- allow user to hit enter when renaming a folder to confirm save
- change icons
- made a simple util for `handleEnterPress()` to be used with inputs throughout the app on their `onKeyDown` prop
> Folder fixes and style enhancements 

- api/net/Areas/Editor/Models/Storage/ItemModel.cs
- api/net/Areas/Subscriber/Models/Storage/ItemModel.cs
- api/net/TNO.API.csproj
- libs/net/dal/TNO.DAL.csproj
- libs/net/models/Filters/ContentFileReference.cs
- libs/net/models/TNO.Models.csproj
- libs/net/services/Helpers/ApiService.cs
- libs/net/services/TNO.Services.csproj
- services/net/contentmigration/ContentMigrationAction.cs
- services/net/ffmpeg/FFmpegManager.cs
- services/net/ffmpeg/TNO.Services.FFmpeg.csproj
- tools/css-api/TNO.CSS.API.csproj
- apparently the library we used to determine contentype type is wrong
- an m4a file should map to audio/mp4 NOT audio/m4a
- switched to new library
- updated all references
- removed unused references
- small fix for content migrator to fix issue with null settings
> fix: #tno-2090 - radio content content type broken

- app/subscriber/src/features/my-folders/ConfigureFolder.tsx
- app/subscriber/src/features/my-folders/MyFolders.tsx
- app/subscriber/src/features/my-folders/Schedule.tsx
- app/subscriber/src/features/my-folders/constants/daysOfWeek.ts
- app/subscriber/src/features/my-folders/constants/defaultSchedule.ts
- app/subscriber/src/features/my-folders/constants/filterOptions.ts
- app/subscriber/src/features/my-folders/constants/index.ts
- app/subscriber/src/features/my-folders/index.ts
- app/subscriber/src/features/my-folders/styled/ConfigureFolder.tsx
- app/subscriber/src/features/my-folders/styled/index.ts
- app/subscriber/src/features/my-folders/utils/createSchedule.ts
- app/subscriber/src/features/my-folders/utils/index.ts
- app/subscriber/src/features/router/AppRouter.tsx
In this PR:
- the ability to run a filter against a folder to populate is now available
- you may also set up the schedule to determine when to empty the folder
I also have a bug fix that I will add for the editor side when picking the `runOn` date.
_Note that this ticket has not had UX yet_
> TNO-1997/98: Ability to run filter on Folder, and schedule when to empty it 

- app/subscriber/src/components/layout/constants/SidebarMenuItems.tsx
- app/subscriber/src/components/sidebar/advanced-search/styled/AdvancedSearch.tsx
- app/subscriber/src/features/search-page/SearchPage.tsx
- app/subscriber/src/features/search-page/styled/SearchPage.tsx
- date filter in advanced search will now center itself instead of piling on the right (short term fix discussed with Bobbi)
- add source and series if present to the search results 
- renamed home page to featured stories
> TNO-2080, 2098, 2086: Little one pointers - styling, add source and series to search page, rename home -> featured stories

- app/subscriber/src/components/share-menu/ShareMenu.tsx
something changed the alignment of the content action bar recently, just lining it up again
CURRENTLY:
AFTER:
> fix alignment

- app/subscriber/src/features/home/constants/columns.tsx
In case of content that have no body text, the teaser box looks out of place. So I added this extra check.
> TNO-2102 Empty body check

- app/subscriber/src/components/sidebar/advanced-search/components/sections/MoreOptions.tsx
Taking a break from some tag stories to get some quick ones in.
Checkbox was just missing the name attribute which allows the label to use the `for` attribute correctly
> TNO-2125: bugfix for clicking checkbox label

- libs/net/core/Extensions/StringExtensions.cs
- any carriage returns and line feeds that are embedded inside markup will be removed
> fix: #tno-2112 - added format fix for content coming in from TNO

- app/editor/src/features/reports/av-overview/OverviewGrid.tsx
When clips have too many options, and appear at the bottom of the screen it would cause a layout issue with options being cut off. This will restrict the menu size to 120px maximum.
> TNO-2130: Clips being cut off of Evening Overview

- app/subscriber/src/components/basic-search/BasicSearch.tsx
- app/subscriber/src/features/my-searches/MySearches.tsx
- app/subscriber/src/features/my-searches/hooks/useElastic.ts
- app/subscriber/src/features/router/AppRouter.tsx
- app/subscriber/src/features/search-page/SearchPage.tsx
- app/subscriber/src/features/search-page/components/advanced-search/AdvancedSearch.tsx
- app/subscriber/src/features/search-page/utils/formatSearch.ts
- app/subscriber/src/features/search-page/utils/index.ts
- app/subscriber/src/features/utils/index.ts
- app/subscriber/src/features/utils/isNumber.ts
- app/subscriber/src/store/slices/lookup/interfaces/ILookupState.ts
- app/subscriber/src/store/slices/lookup/lookupSlice.ts
- app/subscriber/src/store/slices/lookup/useLookupStore.ts
- libs/npm/core/src/utils/convertTo.ts
Resolved regression bug introduced into the basic search.
My Saves Searches will now load the full page results instead of the Advanced Search.  Clicking the GO ADVANCED will load the component to edit the search.  I've added the gear icon back which will go directly to the advanced search.
> Fix basic search

- app/subscriber/src/components/tool-bar/styled/ContentActionBar.tsx
- app/subscriber/src/features/search-page/SearchPage.tsx
- app/subscriber/src/features/search-page/components/advanced-search/AdvancedSearch.tsx
- app/subscriber/src/features/search-page/components/advanced-search/components/ExpandableRow.tsx
- app/subscriber/src/features/search-page/components/advanced-search/components/sections/SearchInGroup.tsx
- app/subscriber/src/features/search-page/components/advanced-search/constants/DefaultAdvancedSearch.ts
- app/subscriber/src/features/search-page/components/advanced-search/styled/AdvancedSearch.tsx
- app/subscriber/src/features/search-page/styled/SearchPage.tsx
- added visual hint for advanced search settings when section is collapsed
- added tooltips to icons in collapsible section
- fixed check box labels to be clickable for "search in"
- altered layout for advanced search to remove excess margins
- removed a bunch of uneccesary css
- In the screen grab below, Sentiment and Media Types both have search criteria set, as hinted at by the indicator (which has a tooltip)
> fix: #tno-2151 - fixed reset settings

- api/net/Areas/Helpers/ReportHelper.cs
- app/subscriber/src/features/my-reports/admin/ReportSubscribers.tsx
- app/subscriber/src/features/my-reports/admin/styled/ReportAdmin.tsx
- app/subscriber/src/features/my-reports/interfaces/IReportResultForm.ts
- app/subscriber/src/features/my-reports/interfaces/index.ts
- app/subscriber/src/features/my-reports/view/components/ReportContentSectionRow.tsx
- app/subscriber/src/features/my-reports/view/components/ReportInstanceView.tsx
- app/subscriber/src/features/my-reports/view/components/ReportSections.tsx
- app/subscriber/src/store/slices/profile/interfaces/IProfileState.ts
- app/subscriber/src/store/slices/profile/profileSlice.ts
- app/subscriber/src/store/slices/profile/useProfileStore.ts
- libs/net/models/Areas/Subscriber/Models/Report/UserModel.cs
- libs/net/models/Areas/Subscriber/Models/Report/UserReportModel.cs
- services/net/reporting/ReportingManager.cs
A number of fixes for reports.
- Resolving preview issues
- Resolving view instance issues
- Adding list of subscribers to a report (view only)
- Disabling form fields (hiding some) when report instance has been sent
> TNO-2162 Fix reports

- tools/scripts/create-styled-component.sh
This is a simple shell script to create a `styled-component` with our standard practices.
When creating a `styled-component` it can be quite tedious making a `/styled` directory followed by the component and an `index.ts` file in both the styled directory, and working directory.
With the following script a user may run `create-styled-component.sh <component-name>`.
The above command will do the following
1. create styled folder in working directory if none exists already
2. add `<component-name>.tsx` and export statement to `/styled/index.ts` (will create `index.ts`  if none exists, or append)
3. create <component-name>.tsx and add basic imports to use styled component
4. add export statement to working directory `index.ts` if it exists
Running `create-styled-component.sh Component` on an …
> Dev Tool: Create styled-component 

- app/editor/src/index.scss
Tested on various size screens:
> TNO-1992: Fix expanding Story WYSIWYG editor to full size

- app/editor/src/features/content/form/ImageSection.tsx
Image content can now select from all enabled sources
> TNO-2138: Display all enabled sources for images

- app/editor/src/features/content/form/ContentForm.tsx
As per discussion with Bobbi, I added the following:
> TNO-2177: Add content next/prev btns beside publish/save btn

- app/editor/src/features/content/list-view/components/tool-bar/filter/InputOption.tsx
> TNO-1948: Fix select checkbox issue

- app/subscriber/src/features/search-page/SearchPage.tsx
Still keeping the behavior on clicking the whole line to navigate to content, but allowing the click on the check box.
> TNO-2096 Fix to allow check box selection

- app/editor/src/features/content/form/components/tags/Tags.tsx
I needed to set the tags in the component as manual once it's loaded (because they are already persisted).
Once it's done, then the behavior will be the same, and persisted tags that are not in the text, will not be wiped.
> TNO-2212 Persist manual tags state "onLoad"

- app/subscriber/src/components/navbar/styled/Navbar.tsx
Removing bold from the sidebar options as it looked out of place, and didn't match the mock up.
> remove bold from sidebar

- app/editor/src/features/content/constants/ShowOnlyValues.ts
- app/editor/src/features/content/constants/showOnlyOptions.ts
- app/editor/src/features/content/interfaces/IContentListFilter.ts
- app/editor/src/features/content/list-view/ContentListView.tsx
- app/editor/src/features/content/list-view/components/tool-bar/filter/ShowOnlySection.tsx
- app/editor/src/features/content/list-view/hooks/useColumns.tsx
- app/editor/src/store/slices/content/interfaces/IContentSearchResult.ts
- When the list is already rendered, a call is made to retrieve the work orders on the last two days.
- New Column added to display transcript status
- If there are work orders, the new column is filled
- Added option at Show Only to display the pending transcripts
- When the Option is checked, a frontend "filter" function is called to display that status.
> Tno 2139 filter content by transcription

- app/subscriber/src/components/basic-search/BasicSearch.tsx
- app/subscriber/src/components/basic-search/styled/BasicSearch.tsx
- app/subscriber/src/components/header/Header.tsx
- app/subscriber/src/components/layout/styled/Layout.tsx
- app/subscriber/src/features/landing/Landing.tsx
- app/subscriber/src/index.scss
**In this PR:**
- basic search will appear in the header when not viewing a search page
- small styling changes to accommodate this
**Things to consider:**
- need to talk to Bobbi on how this will work on mobile, as the horizontal screen real estate is not the same in the header. spent a good chunk of time trying to figure out a "nice" solution but was not happy with it
- may need some new designs to accompany this and or use the old search bar on mobile (will reach out to her) and create another ticket
> TNO-2149: Move basic search to header

- app/subscriber/src/components/basic-search/BasicSearch.tsx
Erroneously removed search button when removing broken mobile inputs. Now back to match mock-up
> Fix button on header search

- app/subscriber/src/features/my-reports/view/components/ContentForm.tsx
- libs/net/template/ReportEngine.cs
Reports will no longer show the Editor Summary but instead will show the Subscriber Summary (if they enter one).
The Subscriber Summary will be included in the report template output.
> TNO-2245 Change report summary

- app/subscriber/src/components/tool-bar/AddToReportMenu.tsx
> TNO-2199: Fix Add to Report menu, show only media story type

- app/subscriber/src/css/_variables.module.scss
- app/subscriber/src/css/_variables.scss
- app/subscriber/src/features/my-minister/MyMinister.tsx
- app/subscriber/src/features/my-minister/constants/columns.tsx
- app/subscriber/src/features/my-minister/constants/index.ts
- app/subscriber/src/features/my-minister/styled/MyMinister.tsx
- app/subscriber/src/features/utils/interfaces/IContentSearchResult.ts
- app/subscriber/src/store/hooks/subscriber/interfaces/IMinisterModel.ts
Overall functionality:
- Filter the Ministers base on user setting
- Iterates this list and make a call for each Minister using the Minister name, Minister aliases and date as parameters
- Get the results and check mentions to each other Minister and populate the Object, also add a count to that minister content.
UI Functionalities:
- Checkboxes are displayed with the minister name and content count
- It can be clicked to hide/show a certain Minister content
- A tag to is displayed to show the mentions to other ministers on that content
> TNO 2106 - My Minister screen

- app/subscriber/src/features/filter-media/FilterMedia.tsx
- app/subscriber/src/features/manage-folder/ManageFolder.tsx
Noticed this also wasn't working on Filter Media Type page, fixed on both pages:
> TNO-2210: Fix select all on Manage Folder and on Filter Media Type pages

- app/subscriber/src/features/my-reports/view/components/ReportSectionContent.tsx
- app/subscriber/src/features/my-reports/view/components/ReportSectionGallery.tsx
- app/subscriber/src/features/my-reports/view/components/ReportSections.tsx
We can now drag+drop to an empty section, and to a gallery.
> TNO-2204 Fix reports drag+drop

- app/subscriber/src/components/date-filter/DateFilter.tsx
- app/subscriber/src/components/date-filter/styled/DateFilter.tsx
- app/subscriber/src/css/_variables.module.scss
- app/subscriber/src/css/_variables.scss
- app/subscriber/src/features/my-folders/Schedule.tsx
- app/subscriber/src/features/my-folders/styled/ConfigureFolder.tsx
- app/subscriber/src/features/search-page/SearchPage.tsx
- app/subscriber/src/features/search-page/components/advanced-search/components/sections/DateSection.tsx
- app/subscriber/src/features/search-page/components/advanced-search/styled/AdvancedSearch.tsx
- app/subscriber/src/features/search-page/utils/filterFormat.ts
- Fix buggy behaviour with start dates before end date and end dates after start date
- CSS, colour updates from Bobbi
- Fix query filter for start but no end date, and end but no start date
- Fixed folder schedule date picker, no months or year nav before
- Only allow scheduling dates from today on
- Only allow filtering for dates on or before today's date
Folder date picker:
Before:
After:
Bugs with advanced search date picker:
Before:
After:
> TNO-2123: Fix date picker colours and UI/UX

- app/subscriber/src/components/content-list/utils/groupContent.ts
- app/subscriber/src/features/home/Home.tsx
Moved the sort functionality from Home component to the groupContent function.
> Tno 2001 order by time

- app/subscriber/src/components/content-list/ContentList.tsx
- app/subscriber/src/components/content-list/styled/ContentList.tsx
- app/subscriber/src/features/search-page/SearchPage.tsx
- app/subscriber/src/features/search-page/styled/SearchPage.tsx
- icon instead of text for opening in new window
- add content list to search page
- remove old code
> [READY] Search Page - Add new list view

- app/subscriber/src/features/my-reports/admin/components/ReportSectionGallery.tsx
Gallery sections for Front Page Images can now be overridden to pull content from any filter or folder.  It will default to the front page images filter.
> TNO-2285 Enhance Gallery Section

- app/subscriber/src/features/my-reports/admin/styled/ReportAdmin.tsx
- app/subscriber/src/features/my-reports/view/components/ContentForm.tsx
- app/subscriber/src/features/my-reports/view/components/ReportSectionContent.tsx
- app/subscriber/src/features/my-reports/view/components/ReportSectionGallery.tsx
- app/subscriber/src/features/my-reports/view/components/ReportSectionMediaAnalytics.tsx
- app/subscriber/src/features/my-reports/view/components/ReportSections.tsx
- app/subscriber/src/features/my-reports/view/styled/ReportEdit.tsx
Updated My Reports forms and fixed an edit content bug.  Form inputs are smaller so that more content can be displayed on the screen.  Also enabled editing gallery content.
> Update My Reports

- app/subscriber/src/components/content-list/ContentList.tsx
- app/subscriber/src/components/content-list/styled/ContentList.tsx
- app/subscriber/src/features/search-page/SearchPage.tsx
add prop that allows user to control whether `ContentList` should be a scroll container on the y-axis. Fixes current bug on search page
> fix scroll issues on search page

- app/subscriber/src/components/section/styled/PageSection.tsx
- app/subscriber/src/features/home/Home.tsx
- app/subscriber/src/features/top-stories/TopStories.tsx
- filter was firing before `homePage` action was determined, now uses `isReady` flag before firing
- top stories now correctly showing content
- also fix misalignment i saw during demo
(before)
> Bug Fixes - Only show Homepage items & Top Stories fix

- app/editor/src/features/admin/reports/utils/createReportSection.ts
- app/subscriber/src/features/my-reports/admin/components/ReportSectionContent.tsx
Removed the ability to add a Table of Content within a report section in the Subscriber app.  This feature is still available to the Editor app.
> TNO-2306 Remove section ToC

- services/net/content/ContentManager.cs
- we should probably apply some sort of exponential backoff here or at least sniff the thrown exception to see if it is transient and then determine whether to retry or perma-fail
> bug: #tno-2302 - add resume after sleep

- app/editor/src/features/content/form/ContentNavigation.tsx
- app/editor/src/features/content/list-view/ContentListView.tsx
- app/editor/src/features/content/papers/Papers.tsx
- if the user navigates in a content tab/window the currently highlited row will be selected
> fix: #tno-2301 - nav under content in paper is in sync

- app/subscriber/src/features/search-page/SearchPage.tsx
Needed a break from the css cleanup - turning out to be a bit of a nightmare fixing all the broken colours.
In this PR:
- clicking go advanced from the basic search bar will no longer trigger query on initial load. user has to hit `search` first
> TNO-2208: Should not fetch when user initialy clicks "Go Advanced"

- api/net/Areas/Editor/Controllers/ContentController.cs
- app/editor/src/features/admin/event-of-the-day/EventOfTheDayList.tsx
- need to check current status of content when updating it
- if content is in a state of Publish | Published, it gets re-published, else it just gets re-indexed
- if the users sets the Topic to "Not Applicable" send an empty list of topics instead of thgat "magic" topic
> fix: #tno-2328 - fixed issue in indexing and updating

- app/subscriber/src/components/content-list/ContentRow.tsx
- app/subscriber/src/features/press-gallery/PressGallery.tsx
- app/subscriber/src/features/press-gallery/interfaces/IGroupedDates.ts
- app/subscriber/src/features/press-gallery/interfaces/index.ts
- app/subscriber/src/features/press-gallery/styled/PressGallery.tsx
- app/subscriber/src/features/press-gallery/utils/index.ts
- app/subscriber/src/features/press-gallery/utils/seperateAlias.ts
- fixed issued filter was broken when searching for a comma separated alias
- small styling changes 
- remove additional requests for total hits on press gallery, it also interferes too much now that the OR is no longer required. Hits are constantly changing
> [UPDATED] TNO-2138, TNO-2139: Press gallery enhancements

- libs/net/services/Actions/Managers/IngestActionManager`.cs
- services/net/contentmigration/ContentMigrationAction.cs
- adopted a "fail fast" method when verifying ingest schedules
- log reason why ingest is not being run
- reset failures AFTER initial checks have taken place
> fix: #tno-2352 - added logging and tweaked logic

- app/editor/src/store/hooks/admin/useTopics.ts
- app/editor/src/store/hooks/lookup/useLookup.ts
- do not make a call to refresh ALL lookups just because we added a new topic
- when adding a new topic, just update Topics in redux and localstorage
- may be a new pattern here to increase responsiveness in lists?
> fix: #tno-2354 - sped up response time from adding a topic

- app/subscriber/src/components/content-list/styled/ContentRow.tsx
- app/subscriber/src/features/my-reports/admin/styled/ReportAdmin.tsx
Small PR, stuck on some mobile responsiveness issues - splitting this off it for now.
Cursor when hovering a row that is drag-gable is now the following:
> TNO-2166: Update draggable row cursor

- app/subscriber/src/components/date-filter/DateFilter.tsx
- app/subscriber/src/features/filter-media/FilterMedia.tsx
- app/subscriber/src/features/filter-media/FilterMediaLanding.tsx
- app/subscriber/src/features/filter-media/PreviousResults.tsx
Reduced # of calls from ~10 to 1 on Filter Media page, by reducing redundant queries, and combining 5 separate queries for 5 days, into 1.
Before: 
After:
> TNO-2290: Fix filter media type query bugs

- libs/net/services/Managers/IngestManager`.cs
- libs/net/services/Managers/ServiceManager`.cs
- services/net/capture/CaptureManager.cs
- services/net/clip/ClipManager.cs
- services/net/command/CommandManager.cs
- services/net/content/ContentManager.cs
- services/net/contentmigration/ContentMigrationManager.cs
- services/net/filecopy/FileCopyManager.cs
- services/net/filemonitor/FilemonitorManager.cs
- services/net/folder-collection/FolderCollectionManager.cs
- services/net/image/ImageManager.cs
- services/net/indexing/IndexingManager.cs
- services/net/nlp/NLPManager.cs
- services/net/notification/NotificationManager.cs
- services/net/reporting/ReportingManager.cs
- services/net/scheduler/SchedulerManager.cs
- services/net/syndication/SyndicationManager.cs
- services/net/transcription/TranscriptionManager.cs
The method SendEmailAsync was moved to the ServiceManager class as @kylgarmor suggested.
Some refactor were necessary since other services relied on Service Manager, but it avoided some duplicated code, and if we need to send emails from other services we are ready for that.
I was able to make some local tests, and they went great.
When @Fosol get an email from dev, please forward it to me to make sure we have a good format for sending it. (And if we need to fix it, is going to be in only one place.
> Tno 2365 move email alerts to service manager

- api/net/Areas/Admin/Controllers/SeriesController.cs
- app/editor/src/features/content/form/components/upload/Upload.tsx
- services/docker-compose.yml
- services/net/capture/Dockerfile
- services/net/ffmpeg/Dockerfile
- services/net/ffmpeg/FFmpegManager.cs
- services/net/ffmpeg/TNO.Services.FFmpeg.csproj
Fixing the FFmpeg Service we use to process QuickTime 10 `.mov` files.  This provides Editors a simple way to convert QuickTime files that do not play in browsers to `.mp3` and `.mp4`.
The Processing button provides a way to apply the configured conversion for the selected media type.
> TNO-2324 Fix FFmpeg Service

- app/subscriber/src/features/search-page/components/advanced-search/AdvancedSearch.tsx
- app/subscriber/src/features/search-page/components/advanced-search/components/sections/ContributorSection.tsx
- app/subscriber/src/features/search-page/components/advanced-search/components/sections/SeriesSection.tsx
- libs/net/models/Areas/Services/Models/Content/ContentModel.cs
- libs/net/models/Areas/Subscriber/Models/Series/SeriesModel.cs
- migrated content that comes in with a new Series value will be added as `isOther`
- these items are now hidden in the Subscriber Advanced Search page
- all Series that are isOther OR isDisabled
- all Media Sources that are set to isDisabled
- all Contributors that are set to isDisabled
> fix: #tno-2384 - fix issues with series add/search

- app/subscriber/src/components/content-list/ContentRow.tsx
- app/subscriber/src/components/content-list/styled/ContentRow.tsx
Quick break from Evening Overview ticket..
Small ticket to display source when grouped by time. Previously source was only displayed as the group header which caused issues when organizing by time.
> TNO-2381: Add source name when grouped by time

- app/subscriber/src/components/tool-bar/AddToReportMenu.tsx
Was making this more complicated than it needed to be - forget we already had this implemented!
Also DB Migration PR coming, just reverting and getting things cleaned up...
In this PR:
- when clicking add to report, no longer does it request for the content to be included
> TNO-2322: Performance fix

- tools/scripts/kc-key-update.sh
Since we changed the setup process and switched to a new Keycloak image, some Keycloak account secrets need to be manually changed. This script can automatically locate the tno directory from its address, so you can execute it from anywhere and the result will be the same. It helps you update secrets in 
```
/api/net/.env, 
/tools/css-api/.env, 
/services/net/**/.env.
```
You can find secrets from `tno-service-account` in keycloak admin.
e.q.
`./tools/scripts/kc-key-update.sh xxxxxxx{secret}
`
> Add script for updating secret keys

- app/editor/src/features/admin/contributors/ContributorForm.tsx
- app/subscriber/src/components/basic-search/styled/BasicSearch.tsx
- app/subscriber/src/features/press-gallery/utils/seperateAlias.ts
In this PR:
- Add tooltip so user knows how to create aliases
- Fix responsiveness of search bar in header
- Remove white space separation and only separate alias values on `,` followed by any amount of white space
> TNO-2322: Press Gallery serach inaccuracy 

- api/net/Areas/Admin/Controllers/ReportInstanceController.cs
- api/net/Areas/Subscriber/Controllers/ReportInstanceController.cs
- app/editor/src/features/admin/reports/ReportFormInstances.tsx
- app/editor/src/features/admin/reports/components/ReportSectionContent.tsx
- libs/net/dal/Services/Interfaces/IReportInstanceService.cs
- libs/net/dal/Services/ReportInstanceService.cs
- openshift/kustomize/api/base/deploy.yaml
- openshift/kustomize/api/base/statefulset.yaml
- openshift/kustomize/api/overlays/dev/kustomization.yaml
- openshift/kustomize/api/overlays/prod/kustomization.yaml
- openshift/kustomize/api/overlays/test/kustomization.yaml
- openshift/kustomize/services/build/base/reporting.yaml
- services/net/reporting/ReportingManager.cs
Fixing issue that was resulting in report instances not saving their content.  
> Note reports that don't include content from their prior report will be empty until new content is received.  We need a better way to inform the user of this, as it just looks broken otherwise.
- Fixed Reporting Service
> TNO-1944 Fix Editor report admin

- api/net/Areas/Admin/Controllers/ReportController.cs
- api/net/Areas/Services/Controllers/ReportInstanceController.cs
- api/net/Areas/Subscriber/Controllers/ReportController.cs
- api/net/Areas/Subscriber/Controllers/ReportInstanceController.cs
- app/editor/src/features/admin/reports/ReportFormDetails.tsx
- app/editor/src/features/content/papers/PaperToolbar.tsx
- app/editor/src/store/hooks/editor/useReportInstances.ts
- app/subscriber/src/features/my-reports/ReportPreview.tsx
- libs/net/dal/Extensions/JsonDocumentExtensions.cs
- libs/net/dal/Services/Interfaces/IReportInstanceService.cs
- libs/net/dal/Services/ReportInstanceService.cs
- libs/net/dal/Services/ReportService.cs
- libs/net/models/Areas/Admin/Report/ReportSectionModel.cs
Several bug fixes related to reports.  Administrators can now reassign ownership of a report and all its filters and folders to a new user.  Subscribers will now only be presented with the 'Strat next report' button when the current report has already been sent out.
- Updated Subscriber app
- Updated API
- Updated Reporting Service
> TNO-1944 Fix reporting service

- services/net/indexing/IndexingManager.cs
Fixing Indexing Service so that it deletes content from the published index when the content has been unpublished.  Not sure why this was working before and not now?
> Fix Indexing Service

- services/net/filemonitor/FilemonitorAction.cs
The InnerText property was striping the HTML tags.
The InnerXml returns a string without stripping the tags.
> TNO-2406 Keep HTML tags retrieving data

- app/editor/src/features/admin/reports/ReportFormDetails.tsx
To prevent confusion in the owner dropdown results, we search for users across multiple fields related to the user's name.
> findUsers by keyword instead of Username. #TNO-2401

- app/subscriber/src/features/my-folders/ConfigureFolder.tsx
The apply button appears to be working; however, there was still an issue with `react-select` showing old state if the value was null. This fix allows the value to appropriately display null. 
- fun fact: setting `react-select` to `null` clears it but `undefined` does not
> TNO-2431: Fix filter value

- app/editor/src/features/admin/sources/SourceDetails.tsx
- app/editor/src/features/admin/sources/SourceList.tsx
- app/editor/src/features/admin/sources/constants/columns.tsx
- app/editor/src/features/content/papers/Papers.tsx
- app/editor/src/features/content/papers/components/ContentFilter.tsx
- app/editor/src/features/content/papers/constants/defaultPaperFilter.ts
- app/editor/src/features/content/papers/constants/defaultSources.ts
- app/editor/src/features/content/papers/constants/index.ts
- app/editor/src/features/content/papers/hooks/index.ts
- app/editor/src/features/content/papers/hooks/usePaperSources.ts
- libs/net/models/Areas/Admin/Source/SourceModel.cs
Admins can now configure which sources are used in the default Papers filter.
> TNO-2479 Admin paper sources

- app/subscriber/src/features/my-reports/styled/MyReports.tsx
This page inherited min-width: fit-content from the template, set it to min-content, and fixed the issue.
> Tno 2440 fix subscriber report panel width issue

- app/editor/src/features/content/constants/AdvancedSearchKeys.ts
- app/editor/src/features/content/constants/advancedSearchOptions.ts
This ticket was to add Transcript, Byline, and Summary. All three were already present; however, Transcript was pointed to `story` instead of `body`
> TNO-2420: Add Transcript to Advanced section (Editor)

- app/editor/src/features/admin/reports/ReportFormPreview.tsx
- app/editor/src/features/admin/reports/ReportTemplateContext.tsx
- app/editor/src/features/admin/reports/utils/openPreviewInNewTab.ts
In editor | admin | report
To create a new tab after clicking "generate preview" to display the report without any parent styles.
> TNO 2248 new tab for reports preview

- app/editor/src/features/content/papers/Papers.tsx
- app/editor/src/features/content/papers/constants/defaultPaperFilter.ts
- app/editor/src/features/content/papers/constants/defaultSort.ts
- app/editor/src/features/content/papers/constants/index.ts
- app/editor/src/features/content/papers/hooks/index.ts
- app/editor/src/features/content/papers/hooks/useSortContent.ts
- app/editor/src/features/content/papers/utils/calcTotals.ts
- app/editor/src/features/content/papers/utils/index.ts
- app/editor/src/features/content/papers/utils/sortContent.ts
- app/editor/src/store/slices/content/contentSlice.ts
The default sort for the Editor Papers should be the `source.sortOrder` then the `page`.  Additionally, if an Editor changes the `source.sortOrder` it will resort the content in the UI to handle this scenario.
Ideally we would reindex the Source in Elasticsearch to resolve this issue, but I've created a separate story for this.
> TNO-2404 Fix papers sort

- app/subscriber/src/features/search-page/components/advanced-search/AdvancedSearch.tsx
Fix state sync issue for advanced search - will now display search terms always (previously would be overridden on refresh/ state change)
> TNO-2445: Search terms not always appearing on saved searches

- api/net/Areas/Services/Controllers/ContentController.cs
- app/editor/src/features/content/form/ContentForm.tsx
- app/editor/src/features/content/form/hooks/useContentForm.ts
- fixed the SignalR message to be 'quotes' instead of 'file'
- updated onContentUpdated to disply quotes if SignalR message comes through with quotes
- updated Quotes tab to show count of quotes
> fix: #tno-2502 - show quotes without refresh

- libs/net/dal/Services/WorkOrderService.cs
There's no need to check the contentId into configuration, since we have it on joined content.
It fixes the error when the contentId param is passed.
> TNO-2434 Remove contentId check from configuration

- api/net/Areas/Subscriber/Controllers/ReportController.cs
- app/subscriber/src/components/tool-bar/AddToReportMenu.tsx
- app/subscriber/src/features/my-reports/ReportPreview.tsx
- app/subscriber/src/store/hooks/subscriber/useReports.ts
Now when adding content to a report it will ensure that it generates a new instance if it is required, and it will update local state so that the user can go view the report and see the content has been added.
> Fix add to report

- app/editor/src/features/content/form/hooks/useContentForm.ts
The issue was triggered because of two factors.
Every time a content is Unpublished, the indexing service acts on it, so we have two versions increases when:
- The form is updated
- When indexing service updates.
So we have a two step version increase on each update.
What happens is, when you unpublish (or publish unpublished content), the indexing service needs to handle this status change, but most of the times, when the service changes and sends SignalR the message to fetch the data, the for is still submitting, so is always one version earlier then the version handled by the indexing service.
Removing the !isSubmitting check, guarantees that, the version of the content will always be up to date when performing a second action (Unpublishing or Re-Publishing) without refreshing the …
> TNO-2227 Allow signalR to update content while submitting

- app/subscriber/src/components/form/timeinput/TimeInput.tsx
- app/subscriber/src/components/form/timeinput/index.ts
- app/subscriber/src/components/form/timeinput/styled/TimeInput.tsx
- app/subscriber/src/components/form/timeinput/styled/index.ts
- app/subscriber/src/features/my-folders/Schedule.tsx
- app/subscriber/src/features/my-folders/styled/ConfigureFolder.tsx
This is currently not in tno-core, I could update our shared `TimeInput`, but am unsure of whether this is valid for our other use cases. For now it is isolated to the subscriber app. The shared input uses an external library called `MaskedInput`, this one is from scratch.
Features:
- user may click the clock face to reveal hour/minute/time options and click the desired inputs
- user may also type hh:mm:ss - this will automatically append the : when required 
- the menu will stay in sync with what the user inputs, for example if I type 11:11:11, clicking the clockface will show the 11 11 11 options selected
- clicking anywhere off the menu will close it
- only valid hh:mm:ss will be accepted, enforced by regex
> TNO-2464: New time input for folder schedules

- app/subscriber/src/features/search-page/components/advanced-search/styled/AdvancedSearch.tsx
get bigger font size in adv search options
> Increase font sizeTNO-2504

- app/subscriber/src/components/content-list/ContentList.tsx
- app/subscriber/src/components/tool-bar/AddToFolderMenu.tsx
- app/subscriber/src/components/tool-bar/AddToReportMenu.tsx
- app/subscriber/src/components/tool-bar/ContentActionBar.tsx
- app/subscriber/src/features/content/view-content/FolderMenu.tsx
- app/subscriber/src/features/home/Home.tsx
Now when checking an item in the content list view:
- it will stay checked until an action is performed (Add to folder, Add to report)
- we store these values in cache and ensure that it is synchronized with the current state 
- currently this does not clear when closing the app (if this is desired behaviour we could use session storage instead)
> TNO-1986: Persist checked items until action is performed

- app/subscriber/src/features/manage-folder/ManageFolder.tsx
Fixed issue where a folder contained unpublished content and as a result would not display the stories.
> TNO-1847 Fix my folders results

- libs/net/dal/Migrations/1.0.146/Up/PostUp/00-Filters-EventOfTheDay.sql
- instead of using just count of articles, the report uses the value of the Topic.Score to define percentages
- fixed size parameter in query - the pie chart uses the content, whereas the bullet list below it uses the aggregate - confusing...
> feat: #tno-2517 - switch Event of the day report to use Topic Scores

- app/subscriber/src/components/section/Section.tsx
- app/subscriber/src/features/my-reports/ReportCard.tsx
- app/subscriber/src/features/my-reports/edit/settings/ReportEditSendForm.tsx
- app/subscriber/src/features/my-reports/styled/MyReports.tsx
- app/subscriber/src/features/my-reports/utils/calcNextScheduleSend.ts
- db/kafka/docker-compose.yml
- docker-compose.override.yml
- docker-compose.yml
- libs/npm/core/src/components/show/Show.tsx
- services/docker-compose.yml
Fix report card schedule to display the next schedule run date and time.
- Fixed bug in report type display (Auto Send)
- Updated Section component to only render when needed
- removed warning in docker-compose.yaml files
> TNO-2541 Enable Draft Reports/Fix Schedule Display

- app/subscriber/src/features/my-reports/edit/content/stories/ReportSectionMediaAnalytics.tsx
- libs/net/models/Areas/Admin/Report/ReportModel.cs
- libs/net/models/Areas/Editor/Models/ReportInstance/ReportSectionModel.cs
Fixing issue when saving a report with a Media Analytic section that pulls data from another report.
> TNO-2535 Fix save media analytics

- app/editor/src/features/content/form/ContentActions.tsx
When creating print content it will no longer default to alert.
> TNO-2421 Fix print content

- app/subscriber/src/features/filter-media/FilterMediaLanding.tsx
- show all should now correctly check with the appropriate list option
- if all are no longer selected the show all checkbox will uncheck itself
- if all items are checked and you deselect show all, the remainder items will uncheck
- some polishing still needs to be done with the alphabet filter, have some more bug fixes in another PR. wanted to get this up
> TNO-2483: Show all issues

- app/subscriber/src/features/my-reports/styled/MyReports.tsx
Fixed issue related to the Report Preview extending past the edge of the page.
> TNO-2519 Fix preview report

- app/subscriber/src/features/filter-media/FilterMediaLanding.tsx
- app/subscriber/src/features/filter-media/styled/FilterMediaLanding.tsx
- can now click the label of select all
- select all now works with the alphabet filter
- fix warning for uncontrolled to controlled input
One more issue with the alphabet filter (very weird edge case) - may leave for now as it is not common, and the filter maybe changing next sprint. Creating a ticket to capture this work. Spent too long on it.
> TNO-2510: More filter by media fixes

- app/subscriber/src/features/my-reports/edit/styled/ReportEditForm.tsx
- app/subscriber/src/features/my-reports/styled/MyReports.tsx
I've noticed that the preview in the subscriber edit view uses a different file, and I've discovered a bug where very high-resolution files can push the top toolbar to the side. so make large images with the same maximum width as their parent.  In GIF changing the screen width will adjust the size of the image, and the toolbar will move accordingly. Additionally, in some cases where the content width is too large, you can scroll horizontally with the scrollbar to locate the toolbar.
> TNO-2219 Fix image overflow  update

- services/net/filemonitor/FilemonitorAction.cs
Some corner cases were detected and handled.
**By PAN PYLAS**
Since we have on the file By the "y" char is lowercase then the All Caps check does not work.
So before checking we replace the substring "By" with "BY". Then we can keep checking if the rest of the string is uppercase.
**By JOHN CHIDLEY-HILL
By STEVEN CHASE, ROBERT FIFE**
Since we have special chars on these strings, the All Caps check also does not work. So just for the All Caps check, we remove the special chars.
> TNO-2492 Fix corner cases

- app/subscriber/src/components/content-list/ContentRow.tsx
In the particular case of the bug, the content had a PDF file attached.
Since the previous check was just verifying if there was not an image file, the pdf file was displaying the play button.
Just narrowed the logic to display the button if the type contains audio OR video.
> TNO-2597 Verify just audio and video files

- app/subscriber/src/components/action/Action.tsx
- app/subscriber/src/components/action/styled/Action.tsx
- app/subscriber/src/features/my-reports/edit/ReportEditForm.tsx
- app/subscriber/src/features/my-reports/edit/ReportEditPage.tsx
- app/subscriber/src/features/my-reports/edit/content/ContentEditForm.tsx
- app/subscriber/src/features/my-reports/edit/content/ReportEditContentForm.tsx
- app/subscriber/src/features/my-reports/edit/content/ReportEditSortForm.tsx
- app/subscriber/src/features/my-reports/edit/content/stories/ContentActions.tsx
- app/subscriber/src/features/my-reports/edit/content/stories/styled/ContentActions.tsx
Enhanced the Action component to have predefined variants.
Added an Undo button on the report content edit form.  This button will revert back to the original story values.
I was unable to duplicate the issues I was seeing in TEST when editing content.
> TNO-2610 Update Edit Report Content

- app/subscriber/src/features/hooks/useSubMediaGroups.ts
- app/subscriber/src/features/search-page/components/advanced-search/components/sections/MediaSection.tsx
That was an annoying one to debug.
Bug fix for:
- previously when you clicked "Media source" in the advanced search you could not select more than one option without the menu collapsing
- state was being reset as it was not being maintained properly in a hook
- moved state to the component as it should be
> TNO-2558: Selecting more than one option minimizes menu

- api/net/Models/Auth/LocationModel.cs
Error occurs when city, postal and state fields are null, getting `400 - Bad Request` error:
The location is obtained from `https://geolocation-db.com/json/` with null values for the mentioned fields.
The endpoint `auth/userinfo` is defining the location as optional. However, if the location object exists, all fields are required. With this change we are modifying the fields with null value as optional.
> Fix- Userinfo Bad Request

- app/editor/src/components/tab-control/hooks/useTab.tsx
In the old code, 
```
const url = `${path}/${id}${values?.showNav ? `?showNav=${values.showNav}` : ''}`;
```
Because we pass a `false` value to `showNav`, it's best not to rely on concise conditional statements, otherwise, the subsequent logic will never execute as we want, to prevent it, let's use a function in its place.
> TNO-2578  Add createUrl function for generating URLs with query param

- app/editor/src/features/content/form/ContentForm.tsx
- app/editor/src/features/content/form/styled/ContentForm.tsx
check available next to byline, default is turn on, and able to input all uppercase value.
> Add option to toggle title case for byline in ContentForm

- app/subscriber/src/components/header/Header.tsx
Throwing up a small one as I am fighting some state bugs on folders
Small bug that was removing the basic search from the `/mysearches` page.
> TNO-2575: Add serach bar to /mysearches

- app/editor/src/features/admin/filters/constants/filterColumns.tsx
- app/editor/src/features/admin/filters/styled/FilterList.tsx
- app/editor/src/features/admin/filters/utils/handleCopyKeyWords.ts
- app/editor/src/features/admin/filters/utils/truncateString.ts
- app/subscriber/src/features/my-searches/MySearches.tsx
- app/subscriber/src/features/my-searches/styled/MySearches.tsx
added keywords fields in editor/admin/filter and subscriber/my saved searches
we are also able to use the hover icon button to copy text from the table cell
> Tno 2561 add keywords

- app/subscriber/src/features/my-minister/MyMinister.tsx
My minister fist call was suppressing the date parameter.
Added default date "today" when there's no date stored on filter.
> TNO-2584 Set default initial date when filter is empty

- app/subscriber/src/components/content-list/ContentList.tsx
- app/subscriber/src/components/content-list/ContentRow.tsx
- app/subscriber/src/features/search-page/SearchPage.tsx
Before we only had this semi applied to the search results, but as this is desired across the site, I have removed the prop and made it the default.
In settings the admin may define what pieces of content will have this pop out option.
> New popout on same page for A/V content

- app/subscriber/src/store/hooks/subscriber/useFilters.ts
- libs/net/dal/Services/FilterService.cs
Sorting in backend used when loading `MySearches` subscriber for the first time.
Sorting in `useFilters` to sort the filters by name after saving a new search.
> TNO-2658: Sort Saved Searches in Alphanumeric Order

- libs/npm/core/src/components/form/wysiwyg/Wysiwyg.tsx
This is a known [bug](https://github.com/zenoamaro/react-quill/issues/935), and although the official documentation says that this setting has been REMOVED, apparently It helps us in v2.0.2
https://quilljs.com/docs/upgrading-to-2-0#configuration
Test like this: in the editor, select one of the contents to go to the rich text editor,  click the pop-out button, and select a row that is not the first row, then click the bullet-list button. On the dev server, the editor will keep creating new lines. If you pack tno-core locally, this should be avoided.
> TNO-2571 setting to prevet ininite loop of creating new lines 

- app/subscriber/src/features/my-folders/ConfigureFolder.tsx
Two issues were tackled on this PR.
- The run filter button is no correctly enabled when editing. (Before we needed to switch the filter select to enable the button)
- I found a concurrency error when running a filter, then updating the config, so this is fixed now.
> TNO-2681 Folder config fixes

- app/subscriber/src/components/date-filter/styled/DateFilter.tsx
> TNO-2620 Update width fix the year text cut in firefox

- api/net/Areas/Helpers/WorkOrderHelper.cs
- libs/net/entities/WorkOrder.cs
When a transcript is requested and there is a line break on headline, the Json parser throws an exception while generating the work order configuration field.
So just to generate the configuration, all line breaks are stripped from the headline.
> TNO-2673 Remove headline line breaks to generate configuration

- app/subscriber/src/components/content-list/ContentList.tsx
- app/subscriber/src/components/section/styled/PageSection.tsx
When user clicks the search results are missing 1rem padding in Page Content:
https://github.com/bcgov/tno/assets/10526131/29c35911-c825-4d61-80d0-e2cb6ad61011
Applied padding for all children:
https://github.com/bcgov/tno/assets/10526131/757b033a-25f3-424d-aed8-eca49983814c
Story: https://apps.itsm.gov.bc.ca/jira/browse/TNO-2664
> TNO-2666: Search results move when clicking search

- app/subscriber/src/features/my-folders/ConfigureFolder.tsx
- libs/net/dal/Services/FolderService.cs
At the initial load, events and schedule were not loaded.
Which implied on toggle without saving, that the events were not displayed on screen, leading the user to think that was not being saved at all.
This guarantees that no matter on how it's loaded/saved/added, the UI is always accurate to the data.
> TNO-2652 Retrieve events and schedule on load folders

- app/subscriber/src/features/search-page/SearchPage.tsx
- app/subscriber/src/features/search-page/components/advanced-search/AdvancedSearch.tsx
**Issue**
After saving a new record, subscriber is showing the previous content. However, the URL is correct (including the new id).
**Fix**
When saving a new record, the navigation goes to `/search/advanced/${data.id}` which finds an existing route which redirects to `SearchPage` component.  Because the `SearchPage` is already mounted React is not mounting again, so it is not updating the `id` param obtained by react-router-dom. As a result, the user is redirected to `/subscriber/filters/${id}` using `useApiSubscriberFilters` in order to obtain the last well-known value for _id_  embedded in the URL and because it is not updated then it is replacing the new content with the old one.
This change is to update the id before comparing its value.
> TNO-2671 [Fix]:  Saved changes in search && Create new search

- app/subscriber/src/components/content-list/ContentList.tsx
Had trouble reproducing this one but hopped on a call with Bobbi as she was able to.
The issue was:
- selected items were stored in cache even when closing the browser, if it was not visible on the page when the user next loads they will have no idea that other options are selected
Temporary solution: 
- clear cached items on refresh or session end
Eventually Bobbi suggested that we could have a selected items box, so we could keep items selected if the user navigates away but it would be apparent that there are previously selected items.
The `beforeunload` event will get called when the user refreshes or closes the app.
> TNO-2623: Wrong number of items being added to reports

- app/subscriber/src/components/media-type-filters/FilterOptions.tsx
- app/subscriber/src/features/home/Home.tsx
- app/subscriber/src/features/todays-commentary/TodaysCommentary.tsx
- app/subscriber/src/features/top-stories/TopStories.tsx
We were properly applying the `activeFilter` that controlled the active buttons, but not actually applying it to the filter. This would only be noticeable on refreshing the page.
This is now fixed, also ensured not to fetch the data until `userInfo` is present in order to avoid the screen briefly having the wrong results before being overridden.
> TNO-2623: Selected filter and results are not correlated when refreshing  

- app/subscriber/src/features/content/view-content/ViewContent.tsx
Previously we would display identical text twice when a transcription was present.
Added simple logic to check if there is a transcription available, and if there is, skip the default summary section.
See issue below.
Now:
> TNO-2361: Transcription / Body Duplication Fix

- api/net/Areas/Helpers/TopicScoreHelper.cs
- api/net/Config/ApiOptions.cs
- api/net/appsettings.json
- services/net/folder-collection/FolderCollectionManager.cs
- services/net/notification/Validation/NotificationValidator.cs
Updated date comparison code to use the same `ToTimeZone(...)` extension function in all services.  This should resolve the date filter issues on notifications.
> Fix Notification Service

- app/subscriber/src/components/content-list/ContentList.tsx
- app/subscriber/src/components/content-list/utils/groupContent.ts
- app/subscriber/src/components/media-type-filters/FilterOptions.tsx
- app/subscriber/src/components/media-type-filters/FilterOptionsContextProvider.tsx
- app/subscriber/src/components/media-type-filters/index.ts
- app/subscriber/src/features/home/Home.tsx
- app/subscriber/src/features/landing/Landing.tsx
- app/subscriber/src/features/search-page/styled/SearchPage.tsx
- app/subscriber/src/features/todays-commentary/TodaysCommentary.tsx
- app/subscriber/src/features/top-stories/TopStories.tsx
Small changes to update the grouped by date display, and additionally fix a bug that causes the api to fetch before the user's filter preference is grabbed. 
I added the active filter to a context provider for the landing page to use, this way it will not fetch until the active filter is set based on the userPrefs, which should eliminate the race condition that was present when using `userInfo` as the ready state.
Also some padding fixes for the search page.
> TNO-2667,2690: Update grouped by date display, and fix filter option sync issue

- app/subscriber/src/components/content-list/Attributes.tsx
- app/subscriber/src/components/content-list/styled/ContentRow.tsx
- app/subscriber/src/features/home/Home.tsx
- app/subscriber/src/features/search-page/SearchPage.tsx
- app/subscriber/src/features/todays-commentary/TodaysCommentary.tsx
- app/subscriber/src/features/top-stories/TopStories.tsx
Noticed some issues with the content attributes, the dividers had been removed. Re implemented the logic on how they are applied using  `.attr:not(:last-child)::after` so it works everywhere. 
**Before:**
**After:**
> Styling regression fixes

- app/subscriber/src/features/content/view-content/ViewContent.tsx
- app/subscriber/src/features/content/view-content/styled/ViewContent.tsx
Noticed there were some dividers next to the attributes being placed incorrectly, this should fix that up. 
(example before it could be like `Vancouver Sun| (nothing) +2`)
> View Content Header Small Fixes

- app/subscriber/src/features/my-folders/ConfigureFolder.tsx
Super easy fix, this will close the configuration when a folder is deleted preventing users from performing actions on a non-existent folder.
> TNO-2729: Close right side when deleting folder

- app/subscriber/src/features/search-page/components/advanced-search/styled/AdvancedSearch.tsx
Change margin instead of z-index as z-index posed another of other UI issues.
> TNO-2735: Fix calendar being cut off

- app/subscriber/src/App.tsx
- app/subscriber/src/features/content/view-content/styled/ViewContentToolbar.tsx
- app/subscriber/src/features/utils/fixTooltipResizeObserver.ts
- app/subscriber/src/features/utils/index.ts
This is a workaround to fix the ResizeObserver infinite loop bug introduced by react-tooltip and content on the page.
> Fix ResizeObserver loop bug

- app/editor/src/App.tsx
- app/editor/src/utils/fixTooltipResizeObserver.ts
- app/editor/src/utils/index.ts
Fixing same issue in the Editor app.  For some reason the script doesn't work if it's within tno-core.  Which requires duplicating the file in each app.
> TNO-2746 Fix tooltip resize error

- app/subscriber/src/features/content/view-content/ViewContent.tsx
Summary stores the transcription for Content Type Audio/Video and sometimes summary is different to body. We need to show the summary and body when they are different.
- Remove HTML tags, square brackets and brake lines before comparison
- Check if the difference in length is greater than 10%
- If summary and body are different then show both of them:
Story: https://apps.itsm.gov.bc.ca/jira/browse/TNO-2728
> TNO-2728=MMI-Advanced Search Problems

- app/subscriber/src/components/content-list/ContentRow.tsx
- app/subscriber/src/features/content/view-content/ViewContent.tsx
- app/subscriber/src/features/search-page/utils/formatSearch.ts
Search query `(are +once) | city +mus* -in`
bold: `City`  `are` `once`,  and prex `mus`
exclude: `in`
- Change formatSearch to support complex search expression when bolding keywords. 
Include keywords by `+`  `|` `()` `""` `''` 
Include prefix by end with `*`
Exclude keywords by`-` `~`
- Improve performance by usememo
> TNO-2656 fix bold search

- app/subscriber/src/components/tool-bar/AddToReportMenu.tsx
- app/subscriber/src/components/tool-bar/styled/AddToMenu.tsx
- added a loading indicator to the appropriate section to give the user some feedback when the request is in process 
- removed unnecessary dom clutter
- slight styling changes
- active report selected will now have icon next to it even when not hovering
> TNO-2744: Small enhancements again

- app/editor/src/features/admin/ingests/configurations/DbMigration.tsx
- libs/net/services/Actions/Managers/IngestActionManager`.cs
- openshift/scripts/deploy.sh
- services/net/content/ContentManager.cs
- services/net/contentmigration/.gitignore
- services/net/contentmigration/ContentMigrationAction.cs
Adding a way to slow down the import of historical content.
Changing the Content Service to be able to continue importing content even when the ingest has been disabled.
> TNO-2665 Fix TNO Migration

- openshift/kustomize/services/content-current/base/config-map.yaml
- openshift/kustomize/services/content-current/base/deploy.yaml
- openshift/kustomize/services/content-current/base/kustomization.yaml
- openshift/kustomize/services/content-current/base/service.yaml
- openshift/kustomize/services/content-current/overlays/dev/kustomization.yaml
- openshift/kustomize/services/content-current/overlays/prod/kustomization.yaml
- openshift/kustomize/services/content-current/overlays/test/kustomization.yaml
- openshift/scripts/deploy.sh
- services/net/content/ContentManager.cs
Need to handle the empty string in the Content Service configuration.
Added new deployment dedicated to the TNO topic.  This should ensure all other content is coming in, no matter how much is migrated.
> TNO-2665 Fix Content Service

- libs/net/dal/Services/ReportInstanceService.cs
- services/net/reporting/ReportingManager.cs
The Reporting Service will not regenerate a report instance that has already been sent out.  This will resolve the bug related to the EoD aggregation results.
> Fix Reporting Service

- app/editor/src/features/content/form/components/upload/Upload.tsx
- app/editor/src/features/content/form/components/upload/styled/Upload.tsx
In this PR:
- this was a ticket to get images showing properly on the editor site / subscriber site; however, that seems to have been fixed by someone else
- instead i did some css fixes that make the media appear a little cleaner on the editor site
- images are confirmed working on both editor and subscriber
> TNO-2696: Image layout fixes

- libs/net/template/ReportExtensions.cs
When the user clicks on the option to turn off the display of the source, the extension looks for the otherSource, which is basically the same code as the source.code. This can be confusing.
> TNO-2710 No reason to display otherSource at this point. confuses the client.

- services/net/ffmpeg/appsettings.json
Changing the FFmpeg Service to start at the end of the Kafka queue instead of the beginning.
> TNO-2385 Fix FFmpge Service

- app/subscriber/src/features/settings/MyMinisterSettings.tsx
- app/subscriber/src/store/hooks/subscriber/useUsers.ts
`updateUsers` had a `storeMyProfile` which was overwriting the `profile.preferences.impersonate`, this will fix that allowing the conditionals to be correct in a `useEffect` after updating a user. 
I am not sure why it was working locally before this change...
Key changes:
- update user now takes an optional prop to check if it is being used in an impersonation or not so the user's profile will not get overwritten by the wrong information
> TNO-2720: Impersonation for my minster fix

- app/subscriber/src/App.tsx
- app/subscriber/src/components/folder-sub-menu/FolderSubMenu.tsx
- app/subscriber/src/components/share-menu/ShareMenu.tsx
- app/subscriber/src/components/user-profile/UserProfile.tsx
- app/subscriber/src/features/settings/MyMinisterSettings.tsx
- app/subscriber/src/store/hooks/subscriber/useUsers.ts
There are still a few more console warnings that are package dependent, they are listed below
- https://github.com/zenoamaro/react-quill/issues/981
- https://github.com/atlassian/react-beautiful-dnd/issues/2563
The latter of these is likely to be fixed in an update, but `react-quill` has not been that actively maintained.
This PR covers some small `react-tooltip` warnings that were appearing in the subscriber application.
> TNO-2749: Console warnings

- app/subscriber/src/features/search-page/SearchPage.tsx
The search was working correctly, but since there was a frontend filter to determine if it's an old or a current record, the boundaries were set to the current time (also subject to UTC issues).
But a simple fix is to set the initial date to a 00:00:00 time, and the final date to a 23:59:59 time, so the frontend filter wont hide results, and there's also no Time zone concerns, since it's only a frontend filter and the time zone is handled by the query itself.
> TNO-2759 Fix day filter

- libs/net/dal/Services/UserService.cs
The save user wasn't handling the new account type when editing an existing user.
> TNO-2768 Fix manage user

- app/subscriber/src/features/press-gallery/PressGallery.tsx
Splitting this off as the other PR had some unneeded code. This will ensure Press Gallery list behaves the same as the rest of the application
> Fix missing attributes in Press Gallery

- app/subscriber/src/features/filter-media/FilterMediaLanding.tsx
Was doing 2x `storeFilter` calls that were leading to several issues, now consolidated into one as it should have been.
> Filter by Media: Filter bug

- libs/net/entities/Content.cs
Ingest services are failing when submitting content with an empty headline.
> Fix content headline

- api/net/Config/SIgnalROptions.cs
- api/net/Program.cs
- libs/net/kafka/Extensions/ServiceCollectionExtensions.cs
- openshift/kustomize/api-services/base/deploy.yaml
- openshift/kustomize/api-services/base/kustomization.yaml
- openshift/kustomize/api-services/base/service.yaml
- openshift/kustomize/api-services/overlays/dev/kustomization.yaml
- openshift/kustomize/api-services/overlays/prod/kustomization.yaml
- openshift/kustomize/api-services/overlays/test/kustomization.yaml
- openshift/kustomize/api/base/route-editor.yaml
- openshift/kustomize/api/base/route-subscriber.yaml
- openshift/kustomize/api/overlays/prod/kustomization.yaml
- openshift/kustomize/api/overlays/test/kustomization.yaml
- openshift/kustomize/shared_resources/base/services-config-map.yaml
Standing up separate API for the backend services.  This will allow us to dedicate the standard API for the frontend Editor and Subscriber applications.  This will also allow us to turn on debug logging to help us narrow down the network issues we're seeing.
> TNO-2864 Separate API

- network/reverse-proxy/editor/Dockerfile
- network/reverse-proxy/editor/config/default.conf
- network/reverse-proxy/subscriber/Dockerfile
- network/reverse-proxy/subscriber/config/default.conf
- openshift/kustomize/nginx-reverse-proxy/base/deploy.yaml
- openshift/kustomize/nginx-reverse-proxy/base/kustomization.yaml
- openshift/kustomize/nginx-reverse-proxy/base/service.yaml
- openshift/kustomize/nginx-reverse-proxy/build/base/build.yaml
- openshift/kustomize/nginx-reverse-proxy/build/base/kustomization.yaml
- openshift/kustomize/nginx-reverse-proxy/build/overlays/dev/kustomization.yaml
- openshift/kustomize/nginx-reverse-proxy/overlays/dev/kustomization.yaml
- openshift/kustomize/nginx-reverse-proxy/overlays/prod/kustomization.yaml
- openshift/kustomize/nginx-reverse-proxy/overlays/test/kustomization.yaml
Provide an Nginx reverse-proxy for the Editor, Subscriber applications and the API.  This will allow us to remove the Openshift path router which appears to not be working reliably.  This may still not resolve various issues we're seeing, but the hope is it will be enough for us to keep using Openshift for our release.
I've created two Nginx services as it will take longer to figure out the configuration to support a single Nginx service for everything.
> TNO-2865 Add reverse-proxy

- app/subscriber/src/features/my-reports/edit/ReportEditActions.tsx
- app/subscriber/src/features/my-reports/edit/ReportEditContext.tsx
- app/subscriber/src/features/my-reports/edit/view/ReportView.tsx
Summary:
1. Hide some buttons in bottom action bar for 'Preview&Send' and 'History'
2. Init Preview Report and always display the Preview Report in the right panel..
3. Considering report updateOn, tracking this data value with hook, so the behavior is regenerate report only when report got update. This could reduce times of request from user, save server resources
> Report preview fix

- app/editor/src/features/content/list-view/ContentListView.tsx
- app/editor/src/features/content/papers/Papers.tsx
Fixing the issue to keep focused the correct row in the papers/content table when clicking on forward/backward button:
> TNO-2817: Editor page sync not working

- services/net/contentmigration/ContentMigrationManager.cs
The TNO Migration will now correctly filter out ingest configurations before performing the action.  This will reduce logging noise.
> Fixing TNO Migration

- app/subscriber/src/features/search-page/SearchPage.tsx
Very small change to add a toast when no results come back, similar to when there are too many.
> TNO-2772: More user feedback for no results

- app/subscriber/src/components/content-list/utils/highlightTerms.tsx
`highlightTerms` function splits the body into chunks based on the press members names, so they can be bold, then the function returns an array.
Need to ensure body is string before applying split function. Otherwise, return an array with the body immediately without parsing body.
> TNO-2784: [Fix] Stories on Press Gallery landing page are not written by Press Gallery members 

- app/subscriber/src/features/my-reports/ReportInstanceView.tsx
- app/subscriber/src/features/my-reports/ReportView.tsx
- app/subscriber/src/features/router/AppRouter.tsx
Fixed issue when viewing a report instance from an email link.  It should now correctly view the instance and not attempt to regenerate the report.
> TNO-2893 Fix view report instance

- app/subscriber/src/components/content-list/ContentRow.tsx
Small bug that Bobbi pointed out, a classname that contained the styling  just got removed in a previous PR.
> Teaser bug fix

- app/subscriber/src/features/filter-media/FilterMedia.tsx
- app/subscriber/src/features/manage-folder/ManageFolder.tsx
- app/subscriber/src/features/my-minister/MyMinister.tsx
- app/subscriber/src/features/press-gallery/PressGallery.tsx
- app/subscriber/src/features/search-page/SearchPage.tsx
- app/subscriber/src/features/todays-commentary/TodaysCommentary.tsx
- app/subscriber/src/features/top-stories/TopStories.tsx
Pretty simple bug, the `onClear` was not being passed down to the problematic pages. Home page worked as expected because it had it.
> TNO-2801: Adding content to folder/reports does not uncheck them

- services/net/contentmigration/migrators/ClipMigrator.cs
Keep transcript content in body field during execution of contentmigration service.
> TNO-2811: TNO Migration missing Event transcripts

- app/subscriber/src/features/my-reports/edit/view/ReportViewForm.tsx
The "Send to subscribers" button was incorrectly only showing up for administrators.
> Fix send report

- app/subscriber/src/components/content-list/ContentRow.tsx
- app/subscriber/src/components/layout/DefaultLayout.tsx
- app/subscriber/src/components/layout/styled/Layout.tsx
- app/subscriber/src/components/tool-bar/styled/ContentActionBar.tsx
- app/subscriber/src/features/content/view-content/ViewContent.tsx
- app/subscriber/src/features/content/view-content/styled/ViewContent.tsx
- app/subscriber/src/features/landing/Landing.tsx
- app/subscriber/src/features/router/AppRouter.tsx
When clicking the pop out button on the content list view, we now have a new simplified screen to show the a/v content.
New styling for A/V popout:
> [READY] TNO-2880: New popout for A/V

- app/subscriber/src/components/tool-bar/ContentActionBar.tsx
- looks like some logic got moved around to incorrect locations likely during a rebase
- dropped unnecessary editor check to display the back button 
- added check for admin or editor before showing Edit Story button
> Fix logic for "Edit Story" button on ViewContent

- app/subscriber/src/components/media-type-filters/styled/MediaTypeFilters.tsx
Bobbi and I had noticed these buttons got misaligned, fixed again:
> CSS small fix

- api/net/Areas/Editor/Controllers/ReportController.cs
- api/net/Areas/Services/Controllers/ReportController.cs
- app/editor/src/features/content/papers/PaperToolbar.tsx
- app/subscriber/src/components/action/styled/Action.tsx
- app/subscriber/src/features/my-reports/edit/view/ReportView.tsx
- libs/net/dal/Services/ReportInstanceService.cs
- libs/net/dal/Services/ReportService.cs
- libs/net/models/Settings/ReportSettingsModel.cs
- services/net/reporting/ReportingManager.cs
Several minor changes and fixes for reports.
- `ReportInstance.SentOn` will be set even if there is a failure
- Viewing a sent report will no longer require regenerating
- Fixed Action component hover cursor
- Several SQL query changes to test if they are quicker with split queries
- Reports will not keep trying to update the report instance until successful.  This should have a limit added at some point.
> Fix reports

- app/subscriber/src/components/header/Header.tsx
Added `window.location.reload()` to force remounting the component for the related page.
Note: There is another [PR already merged](https://github.com/bcgov/tno/pull/2063) that filters the selections of the user using the refresh icon placed on the `ContentActionBar` working on the same fashion as Advanced Search.  This PR reloads the page to enforce remounting the components associated the page.
Story: https://citz-gdx.atlassian.net/browse/TNO-2790
> TNO-2790: HomePage logo reset page

- api/net/Areas/Admin/Controllers/ReportController.cs
- libs/net/core/Extensions/StreamExtensions.cs
- libs/net/core/Http/HttpRequestClient.cs
- libs/net/kafka/KafkaListener`.cs
- libs/net/kafka/Models/ReportRequestModel.cs
- libs/net/services/Config/ServiceOptions.cs
- libs/net/services/Managers/IngestManager`.cs
- libs/net/services/ServiceState.cs
- libs/net/services/ServiceStatus.cs
- libs/net/tests/services/ServiceStateTest.cs
- services/net/content/ContentManager.cs
- services/net/contentmigration/migrators/ClipMigrator.cs
- services/net/event-handler/EventHandlerManager.cs
- services/net/ffmpeg/FFmpegManager.cs
- services/net/filecopy/FileCopyManager.cs
- services/net/folder-collection/FolderCollectionManager.cs
- services/net/indexing/IndexingManager.cs
- services/net/nlp/NLPManager.cs
- services/net/notification/NotificationManager.cs
- services/net/reporting/ReportingErrors.cs
- services/net/reporting/ReportingException.cs
- services/net/reporting/ReportingManager.cs
- services/net/scheduler/SchedulerManager.cs
- services/net/transcription/TranscriptionManager.cs
- tools/elastic/migration/TNOMigration.cs
Failed reports will now keep trying over and over by sending a message to Kafka.  I will need to put a limiter on this at some point, but want to test before doing this.
A failed report which is partially successful will pick up where it left off, by publishing a message to Kafka for the report instance instead.
I also discovered that the prior implementation to restart services after failures was not implemented correctly, as such only a few services actually do this.  The new code added for the reports will need to be applied to other services later.
> Fix reporting

- app/subscriber/src/features/search-page/components/advanced-search/AdvancedSearch.tsx
Not showing saved filter when user is in Advanced Search:
The fix is adding search filter as default value if it exists, else the value is empty:
> [Fix] TNO-2922: Advanced Search Very Slow

- app/subscriber/src/features/search-page/utils/formatSearch.ts
In  the modified version of `formatSearch`, we are discarding `[-~]` to be bold, they are added to excludePatterns list. However, jut includePatterns is providing bolding.
This change just remove `-` from excludePatterns to be handled in includePatterns list to be bold.
Story: https://citz-gdx.atlassian.net/browse/TNO-2921
> TNO-2921: Advanced Search Using Escape Characters Breaking Bolding.

- app/subscriber/src/features/press-gallery/utils/generateDates.ts
The issue was that the logic relied on the label of the select option as a key, when we changed the way a date was formatted in one place it broke the other. 
Here is the area the label broke:
> TNO-2911: Fix count on Press Gallery date options

- app/subscriber/src/features/search-page/components/advanced-search/components/ElasticQueryHelp.tsx
When first loading the page, you would have to click Simple Query to have the simple query info text appear, even though this is the default.
It will now load this cheat sheet by default, and update appropriately when clicking Advanced Query.
> Elastic Info: default to simple-query

- app/subscriber/src/features/press-gallery/PressGallery.tsx
- app/subscriber/src/features/press-gallery/utils/generateDates.ts
Gave it one more go, but ended up removing the count on the drop down labels, it was often inaccurate and stale.  Becomes overly complex with state/grouping.
> TNO-2911: Remove count from date dropdown in Press Gallery

- app/subscriber/src/features/search-page/SearchPage.tsx
- app/subscriber/src/features/search-page/components/advanced-search/AdvancedSearch.tsx
AdvancedSearch includes a TextInput area which is showing the search term in the UI. This textInput component requires to update the state imediately to show updated text to the user, Considering this, we just need to use this search-term state which is of type `string` and it is just local to AdvancedSearch component.  This allows us to isolate search term from other components and passed to the general state just when the user clicks on Search. 
**Performance Measurements**
Current Change
Previous Change
Original
> TNO-2922: AdvancedSearch - Very slow when typing

- app/subscriber/src/features/landing/Landing.tsx
- app/subscriber/src/features/landing/styled/Landing.tsx
Show Commentary and Top Domains only on requested pages:
- Featured Stories
- Top Stories
- Today’s front pages
- Story detail page
And handle screen size on landing in case there's no extra windows.
> TNO-2895 Configure landing and screen size

- app/subscriber/src/features/my-reports/styled/ReportInstanceView.tsx
Update styles with flexbox for report instance preview, especially for mobile browser users, and handle large IMG display as well. 
This is because after the user receives the email and clicks to view it on the website, we will redirect them to the report instance view. On that page, we are missing some Flex-related feature.
Result:
> flex display for report instance view in subscriber

- app/subscriber/src/features/search-page/SearchPage.tsx
- app/subscriber/src/features/search-page/components/advanced-search/AdvancedSearch.tsx
- On key stroke just update just searchTerms. On update of searchTerms update the filter for existing searches. Otherwise, update filter for new searches clicking on Search button.
- Back logic to show `Saved` label when saving changes using `Save changes` label.
> TNO-2922: AdvancedSearch very slow when typing

- app/subscriber/src/features/login/IDPOptions.tsx
- app/subscriber/src/features/login/styled/AppLogin.tsx
- app/subscriber/src/features/login/styled/UnauthenticatedHome.tsx
You can now scroll the below page when a viewing device is too small to support all the content. This is the iPhone 5, which to my knowledge is one of the smallest screen sizes (in terms of iPhones at least) and the login page is quite functional.
> [Ready] Fix scroll bug, better spacing, move alert

- app/subscriber/src/features/my-minister/MyMinister.tsx
- app/subscriber/src/features/my-minister/styled/MyMinister.tsx
This PR fixes:
TNO-2940
- Remove duplicates from results (having more than 1 minister mentioned).
- Add mentions properly, since we don't have an "owner", all ministers should be mentioned if found in content.
- Change the hide show feature to accommodate the new logic of adding mentions.
TNO-2941
- Remove the click on the label  allowing proper toggle.
> TNO-2940 Group, mentions and filter settings

- app/subscriber/src/features/commentary/styled/Commentary.tsx
When headlines were too long they would wrap and look out of place. This PR ensure that they are cut off with an ellipsis and do not wrap.
> Visual fix for Commentary Box

- app/subscriber/src/features/my-reports/components/ReportContentInlineText.tsx
- app/subscriber/src/features/my-reports/edit/content/ContentEditForm.tsx
- app/subscriber/src/features/my-reports/edit/content/sort/ReportContentSectionRow.tsx
- app/subscriber/src/features/my-reports/edit/content/stories/ContentForm.tsx
- app/subscriber/src/features/my-reports/edit/content/stories/ReportContentSectionRow.tsx
- Ability to edit byline in the subscriber story version:
In Subscriber, under Content > Quick Sort:
Change byline _Yuri Kageyama_ for _Yuri Wong_ and clicked Save Story:
The version is updated for Subscriber:
The byline is updated in the version of the content in database. Then, the editor keeps the original byline:
> TNO-2965: Missing byline field 

- app/subscriber/src/components/layout/styled/Layout.tsx
- app/subscriber/src/components/navbar/styled/Navbar.tsx
- app/subscriber/src/features/landing/styled/Landing.tsx
Finding quite a few little responsive things that need tweaking, have some more in an upcoming PR just need to finish polishing. For now I am splitting off one of the tickets.
This sidebar will also scroll for smaller devices like the iPhone 5:
> TNO-2969: Navigation bar being cut off on smaller devices

- app/subscriber/src/components/tool-bar/ContentActionBar.tsx
- app/subscriber/src/components/tool-bar/styled/ContentActionBar.tsx
- app/subscriber/src/features/landing/styled/Landing.tsx
- app/subscriber/src/features/press-gallery/PressGallery.tsx
Simply change the size of the select input on the Press Gallery page, as well as some additional CSS cleanup.
> TNO-2971: Press gallery input too small 

- libs/net/dal/Services/AVOverviewInstanceService.cs
Looks like this is a long time bug, and was causing a lot of confusion.
The find by date method was never returning data, since the date comparison was wrong never bringing the actual AV Overview, every time it was only loaded with the template data.
Since the template was loaded, the search methods were never called, bringing invalid data from previous states, showing wrong data to the user when switching between dates.
Once this is merged, I'll make some final tests in dev, but I believe, data wise it's the definitive fix.
> TNO-2859 Fix find by date method

- app/subscriber/src/features/content/view-content/ViewContent.tsx
- app/subscriber/src/features/landing/Landing.tsx
- app/subscriber/src/store/hooks/app/index.ts
- app/subscriber/src/store/hooks/app/useMobile.tsx
Previously, if you had scrolled down the page and clicked a navigation item it would save your screen position when entering the new page.
This lead to confusion for users finding content.
These changes scroll to the top after navigating on a mobile device so nothing is hidden.
> TNO-2966: Scroll to top of page when navigating on mobile device

- app/subscriber/src/features/my-reports/edit/settings/template/ReportSchedule.tsx
- app/subscriber/src/features/my-reports/edit/styled/ReportEditForm.tsx
- app/subscriber/src/features/my-reports/edit/validation/ReportFormScheduleSchema.ts
Just adding some validation for reports.
Previously, you could enable a schedule, set a start time and save. Now you must select at least one day before saving.
> TNO-2945: When  a schedule is enabled, at least one day must be selected for running

- app/subscriber/src/features/my-reports/edit/settings/template/ReportSchedule.tsx
- app/subscriber/src/features/my-reports/edit/validation/ReportFormScheduleSchema.ts
Previously `notOneOf` fell outside of the `isEnabled` block, which in turn caused manual reports to be blocked.
> TNO-2945: Fix validation blocker for manual reports

- app/editor/src/features/content/form/ContentActions.tsx
- app/editor/src/features/content/form/constants/actionsEnum.ts
- app/editor/src/features/content/form/styled/ContentActions.tsx
- app/editor/src/features/content/form/styled/index.ts
- app/editor/src/features/content/papers/Papers.tsx
- app/editor/src/features/content/papers/components/ReportActions.tsx
- app/editor/src/features/content/papers/styled/Papers.tsx
The following shortcut keys have been updated to avoid overriding common actions performed by the operating system or web browsers:
- **Featured Stories**: `Ctrl + U`  
_(Overridden)_ Previously used by web browsers to view the source code of the current webpage.
- **Top Stories**: `Ctrl + I`
- **Commentary**: `Ctrl + M`
- **Published**: `Ctrl + B`
- **Non Qualified Subject**: `Ctrl + L`  
_(Overridden)_ Previously used by web browsers to move to the address bar.
Included bolding and underline to the letter associated with the shortcut key.
**Papers page:**
**Contents page:**
> TNO-2830: Common shortcut keys no longer work on the Content Form

- app/subscriber/src/components/content-list/ContentRow.tsx
Taking a break from my other ticket...
Now when the user clicks the "play inline" button, the video will start playing automatically and with sound. 
Note that I used a workaround to get the sound to work, if it is too much of a work around, we can go back to just adding the `autoplay` attribute with the tradeoff of losing audio until the user un-mutes.
> TNO-2905: Autoplay inline video

- app/subscriber/src/components/media-type-filters/FilterOptions.tsx
- app/subscriber/src/components/media-type-filters/utils/determineStore.ts
- app/subscriber/src/features/search-page/SearchPage.tsx
- app/subscriber/src/features/search-page/styled/SearchPage.tsx
- app/subscriber/src/store/hooks/subscriber/useContent.ts
- app/subscriber/src/store/slices/content/constants/initialContentState.ts
- app/subscriber/src/store/slices/content/contentSlice.ts
- app/subscriber/src/store/slices/content/interfaces/IContentState.ts
- app/subscriber/src/store/slices/content/useContentStore.ts
Implemented the FilterOptions bar, as a secondary filter, and merge into the main filter before run the query, without persisting into the main filter.
> TNO-2967 Filter options implementation

- app/subscriber/src/features/my-reports/edit/ReportEditPage.tsx
Allow users to edit a failed or cancelled report.  I'm not certain this won't cause any other issues.
> Enable edit failed report

- app/editor/src/features/reports/av-overview/OverviewGrid.tsx
There was an issue preventing the search for clips when toggle between dates.
When the start time between sessions are identical (very common on AV Overview), the was no trigger to search for new clips.
I changed a little bit the logic checking also the ID change and then validating the start time.
So with this changes, it keeps working when completing the session start time, but also loads the correct clips when toggling between existing AV Overviews.
> TNO-2859 Triggers clip search when the AV ID is changed

- app/subscriber/src/components/tool-bar/styled/AddToMenu.tsx
Found this small styling bug when working on a report ticket. Not sure when this occurred but assuming it was some sort of css regression. 
Before: 
After:
> Margin fixes for add to report menu

- app/subscriber/src/features/search-page/SearchPage.tsx
Since we 7 days in advance and then group by the current date range (not considering the full search), the warning of more than 500 rows show be based on the current date range, not the total hits from the elastic search.
Although is not a severe issue it may cause confusion to the users.
> TNO-2967 Check current date length

- app/subscriber/src/features/search-page/SearchPage.tsx
- app/subscriber/src/features/search-page/components/advanced-search/AdvancedSearch.tsx
**Issue: Multiple Unnecessary Re-renders of ContentList on Search Execution**
When the user clicks the Search button in AdvancedSearch component, the `executeSearch` function is triggered, which subsequently calls `fetchResults` function within the SearchPage component. This action causes the SearchPage component to re-render, leading to multiple unnecessary re-renders of the ContentList component. Since ContentList is responsible for handling the bolding of search terms, these repeated re-renders can cause freezing the browser.
**Solution**
To enhance performance and prevent browser freezing, we need to optimize the rendering process so that ContentList re-renders only once after the search results are fetched.
**Additional Issue: Search Terms Not Saved on New Search Creation**
During …
> Advanced Search locking up browser

- app/editor/src/features/reports/av-overview/OverviewGrid.tsx
Only trigger the search event when there's a change on AV Id or Start time.
It prevents extra calls to the search method.
> TNO-2859 Change the search event trigger

- app/editor/src/features/admin/reports/ReportForm.tsx
- app/subscriber/src/features/my-reports/ReportPreview.tsx
- app/subscriber/src/features/my-reports/edit/view/ReportViewForm.tsx
- services/net/reporting/ReportingManager.cs
disable sending button in editor and subscriber 
prevent any sending with no subscribers in reporting service, and set status to failed.
> TNO-2949 Prevent sending report with no subscribers 

- app/subscriber/src/features/landing/Landing.tsx
Previously if there was overflow this would not behave as expected as `window.scrollTo(0, 0)` could still be at position 0,0 and be displaying the middle of the page.
Using the `<main>` element, we avoid this problem entirely.
> Reset view when changing feature bug fix

- app/subscriber/src/features/home/Home.tsx
- app/subscriber/src/features/todays-commentary/TodaysCommentary.tsx
- app/subscriber/src/features/top-stories/TopStories.tsx
When 500+ results were returned it would truncate - meaning that the currently selected date may not have the results present on the page even if there were some (as the previous 5 days could be taking those spots).
> Fix bug 500+ return bug

- app/subscriber/src/features/my-reports/edit/ReportEditContext.tsx
- app/subscriber/src/features/my-reports/edit/settings/template/ReportSectionMediaAnalyticsChart.tsx
- app/subscriber/src/features/my-reports/edit/settings/template/charts/ChartViewer.tsx
When adding charts to reports, this will allow multiple charts to be displayed at the same time.
> Fix multiple charts

- app/editor/src/features/admin/reports/ReportFormInstances.tsx
- app/subscriber/src/features/my-reports/MyReports.tsx
- app/subscriber/src/features/my-reports/ReportCard.tsx
- app/subscriber/src/features/my-reports/ReportPreview.tsx
- app/subscriber/src/features/my-reports/ReportStatus.tsx
- app/subscriber/src/features/my-reports/edit/ReportEditActions.tsx
- app/subscriber/src/features/my-reports/edit/ReportEditForm.tsx
- app/subscriber/src/features/my-reports/edit/view/ReportViewForm.tsx
- app/subscriber/src/features/my-reports/edit/view/styled/ReportViewForm.tsx
- app/subscriber/src/features/my-reports/index.ts
- app/subscriber/src/features/my-reports/styled/ReportStatus.tsx
- app/subscriber/src/features/my-reports/styled/index.ts
- services/net/reporting/ReportingManager.cs
A failed report status is more visible.  We also now have a way to retry sending a failed report (both Editor and Subscriber apps).  This will only attempt to resend to users who have not yet received it.
The Reporting Service will now retry X times to send an email.  Each time it will wait X milliseconds before the next attempt.  A failure to send to any subscriber will place the report back in the queue to retry automatically X times.
- Updated Subscriber app
- Updated Reporting Service
- Fixed a few UI bugs
> Enhance Reporting Service

- app/subscriber/src/features/my-searches/MySearches.tsx
- app/subscriber/src/features/my-searches/styled/MySearches.tsx
Small fix for more keywords to be displayed and to utilize the white space more efficiently
New:
- hovering any of the keywords will display a tooltip saying copy to clipboard
- can click anywhere on keywords (previously a button) to copy keywords to clipboard
> TNO-2993: Fix My Searches Layout 

- app/subscriber/src/features/search-page/components/advanced-search/AdvancedSearch.tsx
- app/subscriber/src/features/search-page/components/advanced-search/styled/AdvancedSearch.tsx
- date range now collapsible in advanced search
- fixed cursor for the rows so the user can  easily see it is clickable
> TNO-2989: Make date section collapsable in Advanced Search

- libs/net/dal/Services/ReportService.cs
There are two fixes:
On line 830 there's a check on the section setting OverrideExcludeHistorical, when there's nothing to do with the exclude report content. So the feature is controlled only by the content setting ExcludeReports.
This fixes the reports using folders as data source.
On the line 854, there was a check that I believe was include by mistake on sectionSettings.RemoveDuplicates, that should be sectionSettings.OverrideExcludeHistorical (since the array is called excludeAboveAndHistorical), and also another problem that the on false was returning an empty array, and was overwriting the content that should be excluded by the excludeOnlyTheseContentIds.
This fixes the reports using filters as data source.
Report used to test content to be excluded.
Option to exclude report empty …
> TNO-3016 Fix exclude content filters

- app/subscriber/src/features/search-page/components/advanced-search/components/ElasticQueryHelp.tsx
Had the exit button as a child of the `<Show>` for Simple Query, the exit button would not show for an Advanced Query. This fixes that.
> Elastic Info - Small Bug

- api/net/Areas/Subscriber/Controllers/ReportController.cs
- app/subscriber/src/components/modal/Modal.tsx
- app/subscriber/src/features/my-reports/edit/content/ReportEditContentForm.tsx
- app/subscriber/src/features/my-reports/edit/settings/template/ReportSectionMediaAnalyticsChart.tsx
- app/subscriber/src/features/my-reports/edit/settings/template/utils/convertToChart.ts
- libs/net/dal/Services/Interfaces/IReportService.cs
- libs/net/dal/Services/ReportService.cs
Fixed issue with charts that should only display the content in their own section.
Fixed issue with regenerate report and charts.
Fixed modal disable confirm button.
> Fix report charts

- libs/net/dal/Services/ReportService.cs
While testing the override on the folder portion of the code, was removed by mistake.
It is slightly different from the filter implementation, that's why the confusion.
Tested with/without override and looks good.
> TNO-3016 Add Override back

- app/subscriber/src/features/my-reports/ReportFilter.tsx
- app/subscriber/src/features/search-page/styled/PreviousResults.tsx
Just small things:
- adding some padding to the previous results on the search page so it no longer goes right up against the edge
- after chatting with Bobbi - the clear button on the filter for my reports now also clears the filter (not just the text)
> Small tweaks

- app/subscriber/src/components/section/PageSection.tsx
- app/subscriber/src/components/section/styled/PageSection.tsx
- app/subscriber/src/components/tool-bar/ContentActionBar.tsx
- app/subscriber/src/components/tool-bar/styled/ContentActionBar.tsx
- app/subscriber/src/features/content/view-content/ViewContent.tsx
- app/subscriber/src/features/content/view-content/styled/ViewContent.tsx
- app/subscriber/src/features/landing/Landing.tsx
Cleaned up the header of `ViewContent` to match Bobbi's mockup.
> [READY] TNO-2987: Rearragne View Content Header

- api/net/Areas/Subscriber/Controllers/ReportController.cs
- app/subscriber/src/features/my-reports/edit/ReportEditContext.tsx
- app/subscriber/src/features/my-reports/edit/settings/template/ReportSectionMediaAnalytics.tsx
- app/subscriber/src/features/my-reports/edit/settings/template/ReportSectionMediaAnalyticsChart.tsx
Report charts that use a linked report for data, can now fetch that data in the UI.
> Fix linked reports

- app/editor/package.json
- app/subscriber/package.json
- libs/npm/core/package.json
- libs/npm/core/src/components/form/wysiwyg/Wysiwyg.tsx
- libs/npm/core/src/components/form/wysiwyg/styled/Wysiwyg.tsx
- hide expand button when expanded (regression issue of some sort)
- take up 100% of expanded modal
> style fixes for wysiwyg

- services/net/indexing/IndexingManager.cs
- services/net/indexing/IndexingService.cs
In 5 seconds not send a same notification.
Test that it works according to the logic that was designed.
some logs:
```
2024-09-04 00:11:48 dbug: TNO.Core.Http.OpenIdConnectRequestClient[0]
2024-09-04 00:11:48       HTTP request made: POST:http://host.docker.internal:40010/api/kafka/producers/notification (User-Agent: TNO)
2024-09-04 00:11:48 info: TNO.Services.Indexing.IndexingManager[0]
2024-09-04 00:11:48       Notification for Content 1061 was sent, added to cache.
.....
2024-09-04 00:11:52 info: TNO.Services.Indexing.IndexingManager[0]
2024-09-04 00:11:52       Notification for Content 1061 was recently sent, skipping this notification request.
2024-09-04 00:11:52 dbug: TNO.Services.Indexing.IndexingManager[0]
```
> Prevent multiple notification in indexing service.

- app/subscriber/src/features/my-reports/edit/settings/data-sources/ReportSectionGallery.tsx
- app/subscriber/src/features/my-reports/edit/settings/data-sources/ReportSectionMediaAnalytics.tsx
- app/subscriber/src/features/my-reports/edit/settings/template/ReportSectionContent.tsx
- app/subscriber/src/features/my-reports/edit/settings/template/ReportSectionGallery.tsx
- app/subscriber/src/features/my-reports/edit/settings/template/ReportSectionMediaAnalytics.tsx
- libs/net/dal/Services/ReportService.cs
Reports will not include duplicate content, and they will also exclude linked report content when configured to do so.
> Fix duplicate report content

- app/editor/src/features/admin/products/ProductSubRequests.tsx
- app/subscriber/src/features/my-products/MyProducts.tsx
- app/subscriber/src/features/my-products/ProductCard.tsx
- libs/net/dal/Services/ProductService.cs
- libs/net/models/Areas/Subscriber/Models/Product/UserProductModel.cs
Fixing various issues related to subscriptions through a distribution list.
> Fix subscriptions

- app/subscriber/src/features/commentary/utils/filterCommentaryResults.ts
Commentary is showing old content because of the TNO Migration.  We filter commentary based on the `content.postedOn` date, which gets set to the date and time we add content to MMI.
This will eliminate content being imported for the time being.
> Fix commentary

- app/editor/src/features/content/form/ContentForm.tsx
- app/editor/src/features/content/form/hooks/useContentForm.ts
- app/subscriber/src/components/content-list/ContentList.tsx
- app/subscriber/src/components/content-list/ContentListContext.tsx
- app/subscriber/src/components/content-list/ContentRow.tsx
- app/subscriber/src/components/content-list/constants/defaultValueListContext.ts
- app/subscriber/src/components/content-list/interfaces/IContentListContext.ts
- app/subscriber/src/features/content/view-content/ViewContent.tsx
- app/subscriber/src/store/hooks/subscriber/useContent.ts
- app/subscriber/src/store/hooks/useAjaxWrapper.ts
Fixed issue where far too many requests were being made to the API.
Subscriber site will now present a friendlier error message.
Editor site will only display one error message if the file is missing.
> TNO-2944 Missing files

- libs/net/dal/Services/UserService.cs
There was a miss call when retrieving the subscriber users from a product.
The list was being filtered based on the Subscribers of the associated report, which shouldn't be always equal.
Once the products have their subscribers the query should link with the ProductSubscriptionsManyToMany not the ReportSubscriptionsManyToMany, NotificationSubscriptionsManyToMany or AVOverviewSubscriptionsManyToMany.
> TNO-3043 Fix retrieve subscribers list

- app/subscriber/src/features/my-reports/edit/content/ContentEditForm.tsx
- app/subscriber/src/features/my-reports/edit/content/stories/ContentForm.tsx
- libs/net/dal/Extensions/ContentExtensions.cs
Temporarily remove user tone pools as it's breaking production..
> Remove tonepools

- libs/net/services/Helpers/ApiService.cs
- libs/net/services/Helpers/IApiService.cs
- services/net/event-handler/EventHandlerManager.cs
- services/net/reporting/ReportingManager.cs
- services/net/scheduler/SchedulerManager.cs
A common error is related to updated the schedule event.  It will often throw an optimistic concurrency error due to various race conditions.  This new code will attempt to resolve that type of issue by fetch the latest, reapplying changes and then saving.
- Updated Scheduler Service
- Updated Event Handler Service (for clearing folders)
- Updated Reporting Service
> Fix schedule concurrency errors

- api/net/Areas/Editor/Controllers/StorageController.cs
- libs/net/dal/Services/FileReferenceService.cs
- libs/net/dal/Services/Interfaces/IFileReferenceService.cs
- libs/net/dal/TNO.DAL.csproj
- openshift/kustomize/api/base/deploy.yaml
summary:
- install AWSSDK.S3 
- has a api endpoint to upload to s3, in local we need 
```
S3_ACCESS_KEY
S3_SECRET_KEY
S3_BUCKET_NAME
S3_SERVICE_URL
```
I have the same variables in openshift
- call api you may want to set the limit numbers of files and updatedBefore of for filter
> API Endpoint upload files to s3

- libs/net/dal/Extensions/JsonDocumentExtensions.cs
- fixed the ES search query for the top stories: the "should" (OR) query should be inside of the "must" (AND)
> TNO-2973 Fixed ES search query

- app/editor/src/features/admin/report-templates/templates/body/CustomReport.cshtml
- app/subscriber/src/features/my-reports/edit/settings/template/ReportSectionContent.tsx
- app/subscriber/src/features/my-reports/edit/settings/template/ReportSectionGallery.tsx
- app/subscriber/src/features/my-reports/edit/settings/template/ReportSectionMediaAnalytics.tsx
- app/subscriber/src/features/my-reports/edit/settings/template/ReportSectionText.tsx
When a report section was disabled in the Editor Admin it hid the section when generating the report.  However, the section still was visible in the Table of Contents, and also there was no way to edit that property in the Subscriber app.
- Updated Subscriber app
- Provided way for users to hide/show report sections
- When section is hidden it will also not show up in the table of contents
> Fix report section

- api/net/Areas/Admin/Controllers/UserController.cs
- api/net/Keycloak/KeycloakHelper.cs
- libs/net/keycloak/Partials/KeycloakServiceUsers.cs
Presently if a user account was originally created in the shared Keycloak realm it will have an invalid `key`.  The first time a user logs in that should automatically be resolved.  However, there are accounts that have not logged in since we migrated to the custom Keycloak realm.
When editing users in this state, it results in an error because their `key` is not a GUID.  The temporary fix is to simply not update keycloak when updating the user record.  When the user does login finally, it should sync correctly.
One new issue that doesn't makes sense is the user account `MMINDP1` with the email  `mmindp1@gov.bc.ca` doesn't exist in our custom Keycloak realm, yet Scott has said he has successfully logged in today...  I don't know how that can be, as there are no errors in the logs …
> Fix keycloak sync issue

- api/net/Areas/Editor/Controllers/ContentController.cs
- api/net/Areas/Editor/Controllers/StorageController.cs
- api/net/Areas/Subscriber/Controllers/ContentController.cs
- api/net/Program.cs
- api/net/appsettings.json
- libs/net/dal/Config/S3Options.cs
- libs/net/dal/Extensions/ServiceCollectionExtensions.cs
- libs/net/dal/Migrations/20240913020858_1.3.3.Designer.cs
- libs/net/dal/Migrations/20240913020858_1.3.3.cs
- libs/net/dal/Services/FileReferenceService.cs
- libs/net/dal/Services/Interfaces/IFileReferenceService.cs
- libs/net/dal/TNO.DAL.csproj
- libs/net/entities/FileReference.cs
-  add new fields `IsSyncedToS3`  `last_synced_to_s3_on`  `S3Path ` to `FileReference`
-  add `force`  param to `GetFiles` method , and `upload-files-to-s3` endpoint
-  Update Editor/Subscriber/Content and Storage Controller to support priority use of S3 files. 
-  add `delete-old-local-files` api
To make this PR small, I make another PR to refactor transcription service.
> Tweak API support S3 bucket stream

- api/net/Areas/Editor/Controllers/ContentController.cs
- app/editor/src/features/content/form/hooks/useContentForm.ts
- libs/net/dal/Services/FileReferenceService.cs
- libs/net/dal/Services/Interfaces/IFileReferenceService.cs
The Editors continuously creates junk files, sometimes uploading 8-10 GB in a week. Currently, my s3 moving system cannot track these files because their fileReference has already been deleted. If we don't control it, disk space will still be consumed and the purge program will be triggered. 
They will be like this
Here’s an explanation of my modifications and the root cause of the issue:
When uploading a new file and clicking "publish", in ContentService we delete the previous fileReference during this process, 
oFileReferences.Except(updated.FileReferences).ForEach(a =>
{
context.Entry(a).State = EntityState.Deleted;
});
we’re unable to remove the associated attachments. However, at this point, we haven’t yet uploaded the new file, so there’s no new fileReference either.
Afterward, in …
> MMI-3095 cleanup junk upload files and prevent stream old file in editor

- network/reverse-proxy/editor/Dockerfile
- network/reverse-proxy/editor/config/default.conf
- network/reverse-proxy/editor/nginx.conf
- network/reverse-proxy/subscriber/Dockerfile
- network/reverse-proxy/subscriber/config/default.conf
- network/reverse-proxy/subscriber/nginx.conf
- openshift/kustomize/api/base/route-editor.yaml
- openshift/kustomize/api/base/route-subscriber.yaml
- openshift/kustomize/app/editor/base/route.yaml
- openshift/kustomize/app/subscriber/base/route.yaml
Openshift routes will do their best to keep sticky sessions.  Nginx will also maintain sticky sessions.
There are some downsides that everyone should be aware of.
- If a pod dies there is nothing to handle the transition, so the client will throw an error
- I was unable to see the cookie to maintain the session, which could indicate another proxy layer involved
- I have limited ability to test and confirm all scenarios
- Nginx is hardcoded configuration to communicate with api-0 and api-1.  Which means we would need to update the config if we want to have more pods available.
The good that comes from this.
- We can have more than one api pod.  If the pod dies everything will automatically switch to the other pod.
- SignalR is getting a reliable connection as long as the api pods don't die
> Config sticky sessions

- app/subscriber/src/features/search-page/SearchPage.tsx
Fixed the advanced search so that it correctly displays results.
> Fix advanced search

- app/editor/src/features/content/form/ContentNavigation.tsx
- app/editor/src/features/content/list-view/ContentListView.tsx
- app/editor/src/features/content/papers/Papers.tsx
- app/editor/src/store/hooks/editor/usehooks-ts/useLocalStorage.ts
- app/subscriber/src/features/search-page/SearchPage.tsx
- tools/mov-converter/README.md
The implementation to store search results in local storage resulted in errors on the page once local storage filled up.  Once local storage fills up there are additional errors that occur related to authentication.
- Only store content IDs in local storage for search results
- Update documentation to install OSX file converter
This will also fix the Editor navigation bug.
> Fix tab navigation

- api/net/Areas/Editor/Controllers/StorageController.cs
Cleanup missing fileReference speed up API call. 
If we choose to move files to s3 because there are missing files in June, these references won't be cleared, they will be in the query results (like filter files before sept ), causing  a long delay as the system checks and tries to move them one by one  in every API call.
> MMI-3091 cleanup missing files' FileReference

- app/subscriber/src/components/date-filter/DateFilter.tsx
- app/subscriber/src/features/daily-overview/AVOverviewPreview.tsx
- app/subscriber/src/features/event-of-the-day/EventOfTheDayPreview.tsx
- app/subscriber/src/features/filter-media/FilterMedia.tsx
- app/subscriber/src/features/home/Home.tsx
- app/subscriber/src/features/my-minister/MyMinister.tsx
- app/subscriber/src/features/router/AppRouter.tsx
- app/subscriber/src/features/search-page/SearchPage.tsx
- app/subscriber/src/features/todays-commentary/TodaysCommentary.tsx
- app/subscriber/src/features/todays-front-pages/TodaysFrontPages.tsx
- app/subscriber/src/features/top-stories/TopStories.tsx
The date navigation component is now displayed on all search result pages.  This date picker does not mutate the current filter.  This however, does currently mean that when returning to the page it may not return to the original date on some pages.
I have also cleaned up the implementation to make the date navigation component more generic.  I have resolved implementation issues that resulted in multiple search requests when they were not needed.  
Basic testing appears positive, but there are a lot of pages that have been touched by this change.
> Add date navigation

- openshift/kustomize/cron/restart/base/cron-job.yaml
- openshift/kustomize/cron/restart/base/kustomization.yaml
- openshift/kustomize/cron/restart/overlays/dev/kustomization.yaml
- openshift/kustomize/cron/restart/overlays/prod/kustomization.yaml
- openshift/kustomize/cron/restart/overlays/test/kustomization.yaml
- openshift/kustomize/services/reporting/base/config-map.yaml
- openshift/kustomize/services/reporting/base/deploy.yaml
This CRON job will restart the api-services and reporting-services at 2 AM every night.  This is to reduce the chance of the Out of Memory leak we have.
The restart is a rolling release, so there should be no down time.
> Add CRON job to restart pods

- services/net/contentmigration/Dockerfile
- services/net/contentmigration/NuGet.Config
- services/net/nlp/Dockerfile
- services/net/nlp/NuGet.Config
The docker images that require local nuget packages need a few teaks so that they work.
> Add local nuget to docker

- app/subscriber/src/components/content-list/ContentList.tsx
- openshift/kustomize/api/base/statefulset.yaml
The page would crash when selecting a lot of content.  This would occur because the implementation would store all the content information into local storage.
This update only stores the content Id values.  However, this does request adding a way to fetch content that was selected but is not currently in memory.
> Fix select content

- api/net/Areas/Kafka/Controllers/ProducerController.cs
- api/net/Config/KafkaOptions.cs
- api/net/appsettings.json
- libs/net/services/Helpers/ApiService.cs
- libs/net/services/Helpers/IApiService.cs
- openshift/kustomize/services/folder-collection/base/config-map.yaml
- services/net/folder-collection/FolderCollectionManager.cs
- services/net/folder-collection/appsettings.json
- services/net/indexing/IndexingManager.cs
Currently there is a race condition between the Indexing Service and the Folder Collection Service.  Any folder with a filter that relies on an Elasticsearch query can result in missing content the first time it is indexed.
This new workflow will publish the indexing request to a new `folder` topic when the content has successfully been indexed.  The Folder Collection Service will now consume the `folder` topic instead of the `index` topic.
> Update indexing process

- app/editor/src/features/admin/reports/components/ReportContentOptions.tsx
- app/subscriber/src/features/my-reports/edit/settings/ReportEditPreferencesForm.tsx
- libs/net/dal/Extensions/JsonDocumentExtensions.cs
- libs/net/dal/Services/ReportService.cs
- libs/net/models/Settings/ReportContentSettingsModel.cs
- libs/net/models/Settings/ReportSettingsModel.cs
Add a ES search filter to excludes `BC updates` (headline) and `BC colander` (Body)
> MMI 1815 option omit BCupdates

- openshift/kustomize/tekton/base/tasks/deploy-all.yaml
- openshift/scripts/deploy.sh
I saw this from pipeline. 
I think scale filecopy cause this erorr.
```
step-deploy
Stopping extract-quotes
Warning: apps.openshift.io/v1 DeploymentConfig is deprecated in v4.14+, unavailable in v4.10000+
Warning: extensions/v1beta1 Scale is deprecated in v1.2+, unavailable in v1.16+
deploymentconfig.apps.openshift.io/extract-quotes-service scaled
Stopping filecopy
Warning: apps.openshift.io/v1 DeploymentConfig is deprecated in v4.14+, unavailable in v4.10000+
error: no objects passed to scale
```
> File copy didn't exist. Fix broken pipeline.

- services/net/indexing/TNO.Services.Indexing.csproj
Elasticsearch has a bug that doesn't allow deleting from an index.
> Downgrade elastic lib

- libs/net/elastic/Extensions/StringExtensions.cs
For some reason some report content when the Highlight Keywords option is enabled it results in adding <mark></mark> elements incorrectly.  This code should eliminate when no matches are found.
> Fix highlight keywords

- app/editor/src/features/content/form/ContentForm.tsx
We need to temporarily remove the new checkbox so that we don't cause confusion to Editors.  This was merged by me into PROD prematurely due to a bug fix with export report.
> Hide CBRA unqualified

- api/net/Areas/Editor/Controllers/StorageController.cs
- libs/net/core/Storage/IS3StorageService.cs
- libs/net/core/Storage/S3StorageService.cs
- libs/net/dal/Helpers/FfmpegHelper.cs
I have update duration (running time) to all s3 AV files.
Now, We have an API to update running to File Reference running time 
1. if file from s3 we will get it from meta data field
2. other than that we will process from local
This could solve most of the case to get running time. don't need to download and process for each file, most of the files should should be located in s3.
> MMI-3118 updated running time

- .vscode/settings.json
- api/net/Areas/Reports/Controllers/CBRAController.cs
- libs/net/dal/Migrations/1.3.12/Up/PostUp/00-CbraReportFunctions.sql
- libs/net/dal/Migrations/1.3.13/Down/PostDown/00-CbraReportFunctions.sql
- libs/net/dal/Migrations/1.3.13/Up/PostUp/00-CbraReportFunctions.sql
- libs/net/dal/Migrations/20241220200117_1.3.13.Designer.cs
- libs/net/dal/Migrations/20241220200117_1.3.13.cs
- libs/net/dal/Services/TimeTrackingService.cs
- libs/net/dal/TNOContext.cs
- libs/net/entities/CBRAReportStaffSummary.cs
- libs/net/entities/CBRAReportTotalEntries.cs
- libs/net/entities/CBRAReportTotalExcerpts.cs
- libs/net/entities/CBRAReportTotalsByBroadcaster.cs
- libs/net/entities/CBRAReportTotalsByProgram.cs
- libs/net/reports/CBRAReport.cs
Added new DB migration 1.1.13.
> MMI-244 Fixed cbra report issues

- libs/net/template/Models/Charts/Options/ChartOptionsModel.cs
- libs/net/template/Models/Charts/Options/ChartOptionsPluginModel.cs
For some reason `maintainAspectRatio` was failing to deserialize boolean values.  However, this has not occurred in the past.  I'm not confident this will work either 100%.
> Fix chart options

- db/postgres/docker/Dockerfile.prod
- openshift/kustomize/api-services/base/deploy.yaml
- openshift/kustomize/api/base/deploy.yaml
- openshift/kustomize/api/base/statefulset.yaml
- openshift/kustomize/elastic/base/statefulset.yaml
- openshift/kustomize/kafka/broker/base/statefulset.yaml
- openshift/kustomize/postgres/crunchy/README.md
- openshift/kustomize/postgres/crunchy/base/deploy.yaml
- openshift/kustomize/postgres/crunchy/base/upgrade.yaml
- openshift/kustomize/postgres/crunchy/overlays/prod/kustomization.yaml
- openshift/kustomize/postgres/standalone/README.md
- openshift/kustomize/postgres/standalone/base/kustomization.yaml
- openshift/kustomize/postgres/standalone/base/service.yaml
- openshift/kustomize/postgres/standalone/base/statefulset.yaml
- openshift/kustomize/postgres/standalone/overlays/dev/kustomization.yaml
- openshift/kustomize/postgres/standalone/overlays/prod/kustomization.yaml
- openshift/kustomize/postgres/standalone/overlays/test/kustomization.yaml
- openshift/kustomize/services/content-historic/base/deploy.yaml
- openshift/kustomize/services/content/base/deploy.yaml
- openshift/kustomize/services/indexing/base/deploy.yaml
- openshift/kustomize/services/notification/base/deploy.yaml
- openshift/kustomize/services/reporting/base/deploy.yaml
- openshift/kustomize/services/transcription/base/deploy.yaml
- openshift/kustomize/shared_resources/overlays/dev/kustomization.yaml
- openshift/kustomize/shared_resources/overlays/prod/kustomization.yaml
- openshift/kustomize/shared_resources/overlays/test/kustomization.yaml
Due to the performance issue of the CrunchyDB v15 in Openshift, I had to migrate to a single Postgres database in Openshift.  I've updated our Infrastructure as Code to reflect this change.  This solution is temporary and puts us at risk due to the single database does not have HA or backups.
> Replace CrunchyDB

- services/net/filemonitor/FilemonitorAction.cs
The Paper Ingest Service would fail if someone entered a duplicate source mapping.  It will now ignore the a bad configuration and log an error.
> Fix Paper Ingest Service

- openshift/kustomize/postgres/standalone/base/statefulset.yaml
Forgot to update this template previously.  We no longer have CrunchyDB objects installed.
> Update DB template

- api/node/src/utils/applyChartJsOptions.ts
- app/subscriber/src/features/my-reports/edit/ReportEditForm.tsx
- app/subscriber/src/features/my-reports/edit/settings/template/utils/getDatasets.ts
- app/subscriber/src/features/my-reports/edit/settings/template/utils/groupData.ts
Some charts would throw errors if certain boolean values were `undefined`.  They will now default to false in the chart api.
When unlocking a report it will now remove the saved `report.instance.body` value so that changes can be detected and a new body can be generated.
> Fix report issues

- libs/net/template/ReportExtensions.cs
After change, summary in ToC can be displayed with private = true and the sourceId is empty. 
For non-private content, the behavior remains unchanged. They have two types of summaries: one in the content summary field and another in the value found in the versions field. A previous modification caused all content to display summaries in the Table of Contents while versions is empty. 
I just had Scott review the changes on the Test Server by modifying the template (using the same logic).
The method should work the same after the update. I’ll test it later.
> MMI-3111 fix Enhance Summary method 

- app/subscriber/src/features/commentary/utils/filterCommentaryResults.ts
- updated content commentary timeout filter that it is now based on the commentary action created on time, which is the time when the user set the content commentary action
> MMI-3103 Updated content commentary timeout filter

- app/editor/src/features/content/form/ContentForm.tsx
Add unique key and default value for media type select in ContentForm.
fix missing mediaTypeId after click "x" button in this field , and causes error message in the form valiadtion.
> MMI-3105 Add unique key and default value for media type select in ContentForm

- api/net/Middleware/ErrorHandlingMiddleware.cs
- app/editor/src/store/hooks/app/useToastError.tsx
- libs/net/core/Exceptions/ContentConflictException.cs
- libs/net/core/Extensions/ExceptionExtensions.cs
- libs/net/dal/Services/ContentService.cs
In the past, it was monitored that there were some concurrency errors in the API during content editing. After a long period of comparison, I found that most of it was actually harmless. 
Some of it was caused by the request for a transcript. I tried automatic merging, but it turned out to be unsafe, as there were too many factors to consider. 
So, I changed it to display the modified fields on the frontend, giving users a prompt, and logging some detailed content on the backend for debugging purposes.
> MMI-3063 better UX for concurrency errors

- libs/net/dal/Configuration/ReportSectionConfiguration.cs
- libs/net/dal/Migrations/20250217170030_1.3.21.Designer.cs
- libs/net/dal/Migrations/20250217170030_1.3.21.cs
Updating the database so that the Executive Summaries in reports can have unlimited text.
- Add DB migration 1.3.21
> Enhance Executive Summary

- services/net/filemonitor/FilemonitorAction.cs
- services/net/filemonitor/TNO.Services.FileMonitor.csproj
In the Wysiwyg editor or web interface, certain Canadian French characters (such as é, è, ç) are displayed as question marks (?). This issue persists even though the HTML header is set to UTF-8 encoding. The problem is from character encoding handling during data ingestion through the filemonitor service.
```
using var sr = new System.IO.StreamReader(filePath);
```
StreamReader first lookup Byte Order Mark (BOM) from files, if news site doesn't put it in the file, StreamReader use UTF8 as default. For content with French word, it may be using Windows-1252, ISO-8859-1, encoding standard, but StreamReader will consider the file use UTF8, normally will see '\uFFFD' in the content, because we could not find those characters.
Solution steps:
- Call the ·ReadFileContents· function to begin …
> MMI-3042 Fix text

- libs/net/services/Runners/BaseService.cs
- services/net/syndication/SyndicationAction.cs
It appears the HttpClient doesn't follow redirects by default.  However, the issue with iPolitics is they redirect from HTTPS to HTTP.  Which isn't allowed.  We would need to manually handle the redirect.  I think having this config is still useful.
This is difficult to test because our IP is whitelisted.
> Allow redirects

- api/net/Areas/Services/Controllers/EventScheduleController.cs
- app/subscriber/src/components/layout/DefaultLayout.tsx
- app/subscriber/src/features/my-reports/MyReports.tsx
- app/subscriber/src/features/my-reports/edit/ReportEditPage.tsx
- app/subscriber/src/store/hooks/subscriber/useReportSync.ts
- libs/net/dal/Services/ContentService.cs
- libs/net/reports/TNO.Reports.csproj
It appears that the root issue with the Scheduler Service was that if the user had a stale version of the report and was editing it when an event fired, they would override the last run time of the report.  Which then would cause the Scheduler Service to request the report to regenerate again.  This fix should update the local copy of the report so that the next save does not overwrite the last run time.
> MMI-3212 Fix Scheduler Service Issue

- api/net/Areas/Editor/Controllers/WorkOrderController.cs
- libs/net/dal/Services/Interfaces/IWorkOrderService.cs
- libs/net/dal/Services/WorkOrderService.cs
- libs/net/models/Areas/Services/Models/Ingest/IngestModel.cs
Three changes made in this PR.
1. Default the retry timeout for all Ingest Services.  In theory they should pick backup where they left off after their timeout.
2. Apply proper dependency injection into the transcript workorder endpoint.
3. Rewrote LINQ statement to correct issues with generated SQL.
> MMI-3213 Fix Ingest Services & Transcript Work Queue

- api/net/Areas/Services/Controllers/EventScheduleController.cs
- api/net/Areas/Services/Controllers/ReportInstanceController.cs
- app/subscriber/src/features/my-reports/MyReports.tsx
- app/subscriber/src/features/my-reports/edit/ReportEditPage.tsx
- app/subscriber/src/store/hooks/subscriber/useReportSync.ts
The Scheduler Service will send a message to the Reporting Service to generate a report based on a schedule.  If the user has already loaded a version of the report when these events occur it will result in a concurrency error when the user saves their report.
This update should apply the latest version details to their report.  There is still a possible situation where the user will overwrite changes made by the automated process, but we prefer this possibility over the error message currently received.
> Fix report concurrency error

- app/editor/src/features/content/papers/Papers.tsx
Update Papers component to adjust column sizes and add Byline field
Because the byline field is not keywords type in Elasticsearch. I don't turn the sortable on.
> MMI-3174 add Byline field in the paper content table

- app/editor/package.json
- app/editor/src/features/content/form/ContentForm.tsx
- app/editor/src/features/content/form/ImageSection.tsx
- app/subscriber/package.json
As the ticket required, I added two fields  `page number` and `sentiment `in the image page, and added coverage test command.
> MMI-3045 add fields to image form 

- app/editor/src/features/content/form/hooks/useContentForm.ts
Changes to Published On date to show current date on clicking next snippet button.
> MMI-3185 Published on behaviour

- app/editor/src/features/content/form/ContentForm.tsx
- app/editor/src/features/content/form/ContentStoryForm.tsx
- app/editor/src/features/content/form/components/tags/Tags.tsx
- app/editor/src/features/content/form/components/tags/TagsContext.tsx
- app/editor/src/features/content/form/components/tags/hooks/useTagManagement.ts
- app/editor/src/features/content/form/components/tags/index.ts
- app/editor/src/features/content/form/components/tags/types.ts
- app/editor/src/features/content/form/components/tags/utils/tagParsing.ts
- app/editor/src/features/content/form/utils/getTargetField.ts
- app/editor/src/features/content/form/utils/index.ts
1. Refactored Tags component using Context API for state management, 
2. let editor add/remove Text Tag list in the editor UI.
3. Add custom hooks 
4. Added type definitions.
```mermaid
graph LR
subgraph Old Structure
A[Tags component] --> B[state management]
A --> C[logic]
A --> D[UI render]
end
subgraph New structure
E[Tags component] --> F[TagsContext]
F --> G[state management]
F --> H[useTagManagement]
H --> I[Parse Tag]
H --> J[Tag update]
E --> K[UI render]
end
```
```mermaid
sequenceDiagram
participant UI as  UI
participant Context as TagsContext
participant Hook as useTagManagement
UI->>Context: User selecet (addTags)
Context->>Hook:  call processTagSelectionChanges
alt new tags
Hook->>Hook: handleTagAddition
else remove tags
Hook->>Hook: handleTagRemoval
end
Hook->>Context: get …
```
> MMI 3200 UI 

- app/subscriber/src/features/my-reports/edit/view/ReportHistoryForm.tsx
Fixed the issue where report history was no longer displayed.  This was caused by an update to the CHES Retry Service.  Previously reports would get stuck in the Accepted status, but now they will get automatically updated to the Completed status.  The report history page needs to display completed reports.
> MMI-3246 Fix report history

- services/net/syndication/SyndicationAction.cs
Adding an additional XmlReaderSetting so that it parses Dtd attributes.  It won't solve the face we're be IP blocked however.
> MMI-3265 Fix Syndication service

- api/net/Areas/Editor/Controllers/StorageController.cs
- api/net/Areas/Subscriber/Controllers/ContentController.cs
- api/net/appsettings.json
- app/editor/src/features/admin/notifications/constants/defaultRazorTemplate.ts
- libs/net/core/Extensions/StringExtensions.cs
- libs/net/dal/Config/StorageOptions.cs
- libs/net/template/Models/BaseTemplateModel.cs
- openshift/kustomize/services/notification/base/deploy.yaml
- services/docker-compose.yml
- services/net/notification/Config/NotificationOptions.cs
- services/net/notification/NotificationManager.cs
- services/net/notification/appsettings.json
- tools/scripts/gen-env-files.sh
This update provides a way to display uploaded image files in notifications.
- Updated notification template (separate PR for the DB migration)
- Updated API, added new endpoint for downloading files
> MMI-3276 Allow images in Notifications

- libs/net/elastic/Extensions/StringExtensions.cs
clients use outlook email doesn't support `<mark>` , this new way can highlight with style and `<span>` tag
> MMI-3274 Enhance MarkKeywords 

- libs/net/template/ReportExtensions.cs
This fixes an issue where the media analytics chart would display no data if the grouping was Published On.
> MMI-3356 Fix media analytics
